### ISSUE TITLE
[Quicklinks] Add image preview

### ISSUE THREAD

**Issue by RobertBolender** [raycast/extensions#10001]
### Description

I submitted a small extension for saving links that included an image preview feature, but it was suggested that the extension was very close to the existing Quicklinks functionality. So I'm submitting two feature requests, this is request 1 of 2.

This was the PR for the extension:
- https://github.com/raycast/extensions/pull/9614

### Who will benefit from this feature?

Anyone who enjoys sharing memes or other images

**Comment by mathieudutour** [comment]
Seems like this issue is about a specific extension, not the API. Would you mind opening a new issue using the [correct template](https://github.com/raycast/extensions/issues/new?assignees=&labels=extension%2Cbug&projects=&template=extension_bug_report.yml&title=%5BExtension+Name%5D+...) so that the authors of the extension are properly aware of it?
