### ISSUE TITLE
[GitHub Repository Search]  "cookies must be enabled for github"

### ISSUE THREAD

**Issue by BrennerSpear** [raycast/extensions#10070]
### Extension

https://www.raycast.com/thomas/github-repository-search

### Description

doesn't work, I get "cookies must be enabled for github"

### Steps To Reproduce

Add personal access token
add github base url

search for anything

you'll get "cookies must be enabled for github"

**Comment by mheidinger** [comment]
Hi @BrennerSpear, 
I haven't encountered this issue yet but according to e.g. the following StackOverflow answer it seems like your API endpoint is not correct: https://stackoverflow.com/questions/22275080/solving-cookies-must-be-enabled-to-use-github-using-gae-webapp2-urllib2-python
It is hitting the GitHub website instead of the API endpoints.

Have you set up a custom base URL for an enterprise server? If yes does it also contain the suffix `/api/v3`?
If you want to use the public GitHub, just omit the base URL config option entirely.
