### ISSUE TITLE
[zipcodebase] pass state as parameter

### ISSUE THREAD

**Issue by dataders** [raycast/extensions#10129]
### Extension

https://www.raycast.com/xmok/zipcodebase

### Description

zipcodebase's [Postal codes by city](https://app.zipcodebase.com/documentation#city) API allows for a `state_name` parameter
https://app.zipcodebase.com/documentation#city

### Who will benefit from this feature?

anyone who wants to limit the result set when searching for US city zipcodes

**Comment by xmok** [comment]
Hey **dataders** the problem is that we can have a maximum of 3 arguments for a command and we could swap out the "limit" argument for "state_name" but then the lack of a limit could eat into a user's API credits.

Do you think it would be effective if we remove all limit arguments and replace them with a "default_limit" in the Extension Preferences, instead? Then we can add in the missing arguments like "state_name".

Interested to hear your thoughts!

**Comment by dataders** [comment]
> Do you think it would be effective if we remove all limit arguments and replace them with a "default_limit" in the Extension Preferences, instead? Then we can add in the missing arguments like "state_name".

@xmok yeah that's be great, honestly!

**Comment by xmok** [comment]
@raycastbot reopen this issue
