### ISSUE TITLE
[Todoist] Fails with JS heap out of memory error

### ISSUE THREAD

**Issue by gh0stdotexe** [raycast/extensions#10127]
### Extension

https://www.raycast.com/doist/todoist

#### Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:406:5
[kOnExit]:worker:313:26
Worker.<computed>.onexit:worker:229:20
```

### Steps To Reproduce

trying to run the todoist menu bar extension in raycast, but it refuses to work. 

- activated menu bar in todoist settings (disabled desktop dock option)
- open raycast
- refresh / attempt to run todoist extension "menu bar activate"
- fails / even after multiple refreshes, cache clear, raycast app quit + restart, todoist app quit + restart, reinstalled todoist even.

**Comment by lucymhdavies** [comment]
Looks like my issue is a duplicate: https://github.com/raycast/extensions/issues/10789

So copying over my latest comment from that issue:

The issue has been happening every few days since I initially reported it. Same error logs.

On days where the issue occurs (such as today), reloading the extension will work for a few seconds at best, and then crash again.

Given the error is related to an out-of-memory issue, my theory is that it occurs on days where there are many tasks in my todo list, and doesn't happen on days when there are fewer. But I've not yet been able to validate this theory.

Is there any way to get more detailed logs to see what's going on?

**Comment by gh0stdotexe** [comment]
> Looks like my issue is a duplicate: #10789
> 
> So copying over my latest comment from that issue:
> 
> The issue has been happening every few days since I initially reported it. Same error logs.
> 
> On days where the issue occurs (such as today), reloading the extension will work for a few seconds at best, and then crash again.
> 
> Given the error is related to an out-of-memory issue, my theory is that it occurs on days where there are many tasks in my todo list, and doesn't happen on days when there are fewer. But I've not yet been able to validate this theory.
> 
> Is there any way to get more detailed logs to see what's going on?

I believe you might be onto something. I have experimented with the task text display limit, which currently is set to 35, but I have also tried settings ranging from 20 to over 40. Additionally, I've tested filtering techniques to display fewer tasks from my typically full to-do list.

Just like you, I haven't been able to fully validate this theory. However, I suspect that the solution to the issue lies in this direction.

**Comment by lucymhdavies** [comment]
I've added a bunch of "test" tasks to my Today list, to see if I can force a crash.
(I was able to clear the crash in my case by reducing the number of tasks in my Today, and clearing the extension's cache)

So far, 110 tasks works fine (with most of those being "test"). But I suspect it's less to do with the number of tasks, and more to do with the amount of memory each task takes up. e.g. a recurring task that has been repeated for several months would take up more memory than a similar task which has never been completed.


I wouldn't expect the task text display limit would affect this bug, as the extension would still need to load the entire task into memory. But I'm not gonna rule that out either. For now, I've set mine to 100 characters, and it's not yet causing any issues.

I'm sure with enough dedication (or automation) I'd be able to force a crash, but so far with these small "test" tasks I've not been able to do so yet.

**Comment by lucymhdavies** [comment]
turns out i can duplicate a whole bunch of tasks in one go.

so with 206 "test" tasks (in addition to the real tasks in my list), I'm able to force a crash.
(This is waaaaay more tasks than I'd normally have. Normally I see the issue at around 50 tasks. but those tasks have more data in them than these simple "test" tasks)

So now that I have a reasonably reliable way to force a crash... if we knew of a good way to get more error logs, then we'd be closer to figuring out how to resolve the issue.

**Comment by lucymhdavies** [comment]
This is still an issue.

I've not developed extensions for Raycast myself, but I do wonder if this is even something that can be solved by the extension, or if it would need a change to Raycast core.

**Comment by lucymhdavies** [comment]
Yeah, from investigation, there's a few other similar issues with different extensions:
* https://github.com/raycast/extensions/issues/11741
* https://github.com/raycast/extensions/issues/11710
* https://github.com/raycast/extensions/issues/11648
* https://github.com/raycast/extensions/issues/11445
* https://github.com/raycast/extensions/issues/11311
* https://github.com/raycast/extensions/issues/11241
* https://github.com/raycast/extensions/issues/11226
* https://github.com/raycast/extensions/issues/10381
* https://github.com/raycast/extensions/issues/10381
* https://github.com/raycast/extensions/issues/6810

Many with the exact same error trace (some it's the same, but different line numbers which I expect is due to different versions)

**Comment by lucymhdavies** [comment]
@raycastbot reopen this issue

**Comment by gh0stdotexe** [comment]
Yep, i'm still experiencing this too. I've basically opted to disabling it until resolved. 

If further logs are needed lmk, will provide.

Thanks @lucymhdavies for bumping!

**Comment by lucymhdavies** [comment]
In my case, it only seems to be a problem if there are a lot of results for the view.
(which is usually the start of my day, when I haven't prioritised my todo list, and pushed most of it to tomorrow)

A quick cache reset of the extension resolves it for me.

I've also had some discussions in the slack, which has given me a bit more context I can use to investigate this issue a little further. I might fork the extension and spend some time debugging to see what I can find :)

<details>
<summary>Discussion from Slack</summary>

https://raycastcommunity.slack.com/archives/C02HEMAF2SJ/p1715342564936389


Lucy Davinhart
  5 hours ago
Hey folks :slightly_smiling_face:
Something I've noticed with one of the extensions I use is occasional JS heap out of memory issues
https://github.com/raycast/extensions/issues/10127
Did a bit of digging just now (the bot auto-closed the issue for inactivity, which reminded me)... and it looks like there's a few similar issues for various different extensions. So I'm wondering... is there a wider Raycast core issue going on? :thinking_face:
(On a related note, if somebody could re-open the Issue, that would be helpful please) 


Sorin
:raycast:  [5 hours ago](https://raycastcommunity.slack.com/archives/C02HEMAF2SJ/p1715342920179449?thread_ts=1715342564.936389&cid=C02HEMAF2SJ)
It's only a Raycast core issue insofar as Raycast only affords extensions a certain amount of memory, and if they exceed that number, they crash with a "JS heap out of memory" error. :sweat_smile:
https://developers.raycast.com/information/security#runtime-model
An extension runs in its own v8 isolate (worker thread) and gets its own event loop, JavaScript engine and Node instance, and limited heap memory. That way, we ensure isolation between extensions when future Raycast versions may support background executions of multiple extensions running concurrently.


Lucy Davinhart
  5 hours ago
ahhhh! gotcha. That makes a lot of sense.
So if an extension does need more memory, there's currently no way for an extension to request that.
Extensions would need to be able to manage their own memory usage efficiently (which for some extensions may be possible, but for others may be much harder)
:thinking_face:


Sorin
:raycast:  [4 hours ago](https://raycastcommunity.slack.com/archives/C02HEMAF2SJ/p1715345099741749?thread_ts=1715342564.936389&cid=C02HEMAF2SJ)
yeah, extensions cannot currently request more memory. We provide some tools to help manage memory usage (e.g. [useStreamJson](https://developers.raycast.com/utilities/react-hooks/usestreamjson)) to help with that but…it's a tricky problem :grimacing:


Lucy Davinhart
  [3 hours ago](https://raycastcommunity.slack.com/archives/C02HEMAF2SJ/p1715349779009489?thread_ts=1715342564.936389&cid=C02HEMAF2SJ)
Yeah, I can imagine it's not an easy thing


Lucy Davinhart
  2 hours ago
out of interest, how much memory does each extension get?
Like I say, I've not done any extension development (yet), but that would give me an idea as to whether the issues I'm seeing with this extension are due to poor memory management by the extension, or if it's due to the extension getting a lot of data back from the APIs it's calling.
(i.e. if it's a problem solvable by the extension, or not)


Sorin
:raycast:  [2 hours ago](https://raycastcommunity.slack.com/archives/C02HEMAF2SJ/p1715350616774019?thread_ts=1715342564.936389&cid=C02HEMAF2SJ)
100MB currently


Sorin
:raycast:  2 hours ago
you should be able to see them in your extension by checking
import { resourceLimits } from "node:worker_threads";




Lucy Davinhart
  2 hours ago
ahhhh. right.
Yeah, that's quite a lot. so definitely feels like a poor memory management issue (and therefore, hopefully, a solvable issue).
this gives me an excuse to fork the extension and experiment with it :slightly_smiling_face:
https://github.com/raycast/extensions/tree/main/extensions/todoist



Lucy Davinhart
  2 minutes ago
in the meantime, do you think you could re-open that ticket? I've got enough info here that I might be able to do some further investigation myself, if the original extension developers don't have the time :slightly_smiling_face:
</details>

**Comment by lucymhdavies** [comment]
In my case, I'm now working around this by using a Filter.

Not all filters that you can do in the Todoist app work, thanks to an issue with the Todoist API (see https://github.com/raycast/extensions/issues/13209), but in my case this filter shows me enough tasks to be vaguely useful, without hitting the memory issue:

```
today & !no time
```

**Comment by gjsduarte** [comment]
Having the same issue. But my Default view is only showing 16 tasks before it errors out with the same error message:
`Error: Worker terminated due to reaching memory limit: JS heap out of memory`

Pretty sure something must be wrong here.

**Comment by RCheesley** [comment]
Same issue here, for me it works again if I clear the local cache and reload, but then it stops working pretty soon afterwards. Guess I should do more tasks! 🤦🏻

**Comment by lucymhdavies** [comment]
I think it's clear that at this point that there's nothing we can really do on the extension point to improve this.

The Todoist API does now support time-based queries, from https://github.com/raycast/extensions/issues/13209, which does help with this issue somewhat. But even then, if you have more than a handful of tasks within the time window, the API returns too much data for the extension to process within its fixed memory limit.

Do we know if there's a way to track the root issue with Raycast itself?
