### ISSUE TITLE
[Schoology] ...

### ISSUE THREAD

**Issue by GiantSquidGamer** [raycast/extensions#10209]
### Extension

https://www.raycast.com/Vaibhav-Satishkumar/schoology

### Description

Add time as a variable in the graphs so that we can see for how long a grade was at a specific time. Make it so that people can see the previous weeks grades in detal, and can chose to expand the graphs in a arc mini browser to see the whole semester progress. Allow what if grades and allow for people to archive courses on the raycast preview so they dont have to see old courses they dont want to see. Make it visually apealling and when people click on the dots they should become empty and a window should apear above stating the grades. They could also just drag over the line to see the grades like bessy. 

### Who will benefit from this feature?

Students who want effecidency in their school enviornment

### Anything else?

Do it or else you are bad. hehehe >:)

**Comment by Visual-Studio-Coder** [comment]
-   [ ] Add time as a variable in the graphs so that we can see for how long a grade was at a specific time.
-   [ ] Provide detailed views of previous week's grades.
-   [ ] Enable the option to expand graphs in a mini browser to view the entire semester progress.
-   [ ] Allow for "what if" grades to be calculated.
-   [ ] Implement the ability to archive courses in the Raycast preview to hide old courses.
-   [ ] Create a visually appealing design.
-   [ ] Enable a feature where clicking on dots in the graphs makes them empty and a window appears displaying the grades.
-   [ ] Implement the ability to drag over the line to see the grades, similar to Bessy.

**Comment by GiantSquidGamer** [comment]
It appears that the what-if grades have not yet been added to the system. To ensure that all the necessary information is available, please add the what-if grades as soon as possible. This will allow for an accurate representation of the overall performance and grades of the students. Thank you for your attention to this matter.
