### ISSUE TITLE
[Apple Reminders] Smart Lists do not appear in the list filter dropdown

### ISSUE THREAD

**Issue by third774** [raycast/extensions#10282]
### Description

Any chance Smart Lists could be included in the list of filters?

### Who will benefit from this feature?

Power users of Apple Reminders

**Comment by mathieudutour** [comment]
Seems like this issue is about a specific extension, not the API. Would you mind opening a new issue using the [correct template](https://github.com/raycast/extensions/issues/new?assignees=&labels=extension%2Cbug&projects=&template=extension_bug_report.yml&title=%5BExtension+Name%5D+...) so that the authors of the extension are properly aware of it?
