### ISSUE TITLE
[Coffee] caffeinate status menu bar doesn't deactivate itself a.k.a. it's always in the menu bar 

### ISSUE THREAD

**Issue by ConstantineSad** [raycast/extensions#10301]
### Extension

https://www.raycast.com/mooxl/coffee

### Description

caffeinate status menu bar doesn't deactivate itself a.k.a. it's always in the menu bar 

### Steps To Reproduce

-

### Current Behaviour

No matter how often chose in the menu "caffeinate status menu bar" it's always displayed in the menu bar 

### Expected Behaviour

it disappears from the menu bar

**Comment by pernielsentikaer** [comment]
I'm a bit confused about this error. Can you provide more details in the title and error description?

What is actually happening?

You can also upload a video or screenshot to help explain it 🙂

**Comment by sxn** [comment]
hi @ConstantineSad 👋

Pressing ↵ in the root search doesn't make the item go away, because once a menu bar command is "activated", the primary action is `Refresh`

<img width="862" alt="image" src="https://github.com/raycast/extensions/assets/1155589/dd25aa75-684b-429f-a947-166ded3194a2">

If you want to make a menu bar item go away, you can use either the `Deactivate Command` action

<img width="862" alt="image" src="https://github.com/raycast/extensions/assets/1155589/40947e14-c2df-4175-9ce9-95f65ff5b86c">

or you can hold down ⌘ and drag the item out of the menu bar.

Hope this helps! 😸
