### ISSUE TITLE
[Apple Reminders] Open Reminders app from the menu bar

### ISSUE THREAD

**Issue by ovanbiervliet** [raycast/extensions#10327]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

It would be handy to have a link in the menu bar dropdown that opens the Reminders app.

### Who will benefit from this feature?

Everyone that wants to manage some reminders in the app itself, for example to drag/move between lists etc.

### Anything else?

![Ø-230125-eREGmbEL@2x](https://github.com/raycast/extensions/assets/3488544/04e8cac5-4345-45dc-881b-93e0993856b8)

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the Slack community if you need further help.

Note that opening up a PR and having it merged will earn you some credits as we want to reward contributions. You’ll then soon be able to exchange them in our swag store.

**Comment by irangarcia** [comment]
Hey @thomaslombart! 
I would like to work on it if the OP is not interested

**Comment by ovanbiervliet** [comment]
Yes, feel free to pick it up as I currently can't do this 👍

**Comment by irangarcia** [comment]
Just opened it #10348
