### ISSUE TITLE
[Search npm Packages] Include popularity, stars etc. in search results

### ISSUE THREAD

**Issue by MKaciuba** [raycast/extensions#1033]
# Extension – [Search npm Packages](https://github.com/raycast/extensions/tree/de047f2e9ad02d2c79a526f2291f64f74aca05b6/extensions/search-npm/)
Author: @mrmartineau

First of all, I absolutely love the extension!

I think one useful addition would be to include info such as popularity, GitHub star count, last publish date etc. I usually base my decision about using a particular package on this info.

**Comment by mrmartineau** [comment]
@MKaciuba hi mate, thanks for the feedback. I would also like to add more info to the output, but there isn't much space for it in the Raycast UI. 3rd party extensions have a `title`, `description` (second line), image and the right-hand bit where we put the version, to put information. That doesn't leave much space for the new things that you've suggested. Have a look at the Raycast extensions API docs and see if you can figure out where that information could go.

Actually, we could put that info in the action panel, would that be acceptable?

**Comment by MKaciuba** [comment]
What do you think about giving a configurable option to choose one of those data points to appear next to the version simply by concatenation, like this: `1.2.3 | ⭐456`? Then you could have more detailed info in the action panel as you propose.

**Comment by mrmartineau** [comment]
They could also work. If I get some time, I will add this stuff.

**Comment by mrmartineau** [comment]
@MKaciuba FWIW a typical response from the npms.io suggestions API (that the extension uses) looks like this:

```json
{
  "package": {
    "name": "react",
    "scope": "unscoped",
    "version": "18.0.0",
    "description": "React is a JavaScript library for building user interfaces.",
    "keywords": [
      "react"
    ],
    "date": "2022-03-29T16:00:04.223Z",
    "links": {
      "npm": "https://www.npmjs.com/package/react",
      "homepage": "https://reactjs.org/",
      "repository": "https://github.com/facebook/react",
      "bugs": "https://github.com/facebook/react/issues"
    },
    "publisher": {
      "username": "acdlite",
      "email": "npm@andrewclark.io"
    },
    "maintainers": [
      {
        "username": "gaearon",
        "email": "dan.abramov@gmail.com"
      },
      {
        "username": "acdlite",
        "email": "npm@andrewclark.io"
      },
      {
        "username": "fb",
        "email": "opensource+npm@fb.com"
      },
      {
        "username": "trueadm",
        "email": "dg@domgan.com"
      },
      {
        "username": "sophiebits",
        "email": "npm@sophiebits.com"
      },
      {
        "username": "lunaruan",
        "email": "lunaris.ruan@gmail.com"
      }
    ]
  },
  "score": {
    "final": 0.9197584952933029,
    "detail": {
      "quality": 0.8629706748020751,
      "popularity": 0.9194826852725915,
      "maintenance": 0.9687095800207814
    }
  },
  "searchScore": 1010.62555,
  "highlight": "<em>react</em>"
}
```

There are some score values which might be useful, but as you can see there are no GitHub star counts. I don't think it's a good idea to call another API to fetch this info for every result item. So unless you can find a free suggestions API that also returns GitHub stars, I think we'll have to leave it as is.

Having said that, here's what it could look like with scores information added: 

<img width="793" alt="image" src="https://user-images.githubusercontent.com/64883/165408814-1cd94f51-0e96-4fe1-81b3-56431d934c1d.png">

..which also isn't ideal because Raycast doesn't offer an `Action` for simply displaying information like we want in the `ActionsPanel`. I am using `Action.CopyToClipboard` in the screenshot above which isn't great. See more options [here](https://developers.raycast.com/api-reference/user-interface/actions#api-reference)

**Comment by mrmartineau** [comment]
@mathieudutour I wasn't aware of the `Detail` view. So I could use markdown and render something like this (but better):

<img width="793" alt="image" src="https://user-images.githubusercontent.com/64883/165626525-72c9d990-7109-4483-a2db-8f2dd0e3e748.png">

I'm still not sure if it is worth the changes to be honest. Am happy to take suggestions though.

**Comment by mrmartineau** [comment]
FYI I have a just opened PR with some updates to this extension: https://github.com/raycast/extensions/pull/1585
