### ISSUE TITLE
[Arc] Shortcut configuraion

### ISSUE THREAD

**Issue by shoppingjaws** [raycast/extensions#10358]
### Extension

https://www.raycast.com/the-browser-company/arc

### Description

Hey, thanks a bunch for the awesome Ext!

In my usage, I prefer assigning the shortcut "Search with Google" to command + enter.
Is it possible to add shortcut key configuration?

If you agree, I will attempt to implement it.

### Who will benefit from this feature?

Improved customizability in multiple environments.

**Comment by thomaslombart** [comment]
Hey @shoppingjaws, that's not possible since ⌘ + ⏎ is already reserved for another action. It's possible to configure it but this would bloat the extension preferences. If it turns out to be a popular feature, we can look at it.

![arc 2024-01-30 at 12 04 35](https://github.com/raycast/extensions/assets/16003285/727ae41d-e7ad-4f82-b0da-3092d7c17d9d)
