### ISSUE TITLE
[ray.so] Request ability to use custom fonts 

### ISSUE THREAD

**Issue by samducker** [raycast/extensions#10364]
### Extension

https://www.raycast.com/garrett/ray-so

### Description

Would be great to be able to use my custom fonts with ray.so

### Who will benefit from this feature?

Users wanting to add personality to there generated images

**Comment by dgrzedzielski** [comment]
Hey, I'm not the creator of this extension, but I think what you are requesting is a rather new feature in ray.so. So, we cannot add that feature inside the Raycast extension unless it is implemented in ray.so.

**Comment by RSO** [comment]
Hey, @samducker, this repository is for the ray.so extension in Raycast, not for ray.so itself.

That being said, since I used to maintain ray.so I can respond and say that ray.so by design does not allow for too many customizations, as we'd like to keep things simple. What we want, is to give users some customization options while making sure that every image comes out looking great. This is why you won't see an option to remove the dots, change the border radius, or customize the paddings of the window. While we'll likely offer other fonts in the near future as part of theme-sets, I don't think we'll offer the ability to load custom fonts.

That being said, @peduarte is going to be taking over, and I know that he has a bunch of ideas on things he'd like to improve, so maybe he disagrees with me 😄.
