### ISSUE TITLE
[Messages] Fails with heap memory errors

### ISSUE THREAD

**Issue by chrismessina** [raycast/extensions#10381]
### Extension

https://www.raycast.com/thomaslombart/messages

### Description

Attempting to compose a message by searching for a recipient crashes the extension.

### Steps To Reproduce

1. Install Messages extension.
2. Launch extension.
3. Select the Contact dropdown.
4. Type `jo`
5. Type a space.

### Current Behaviour

Once I type a space, the extension crashes and an error appears:

![2024-01-26 (15 24 37) Arc@2x](https://github.com/raycast/extensions/assets/22610/6eb3811d-dafb-4ef7-bb45-8526fcda4ba2)

### Expected Behaviour

I expect to be able to search for a contact recipient and send a message.

**Comment by thomaslombart** [comment]
Thanks for reporting the issue. Do you consistently get this error? Are there any other searches that cause the error to trigger?

**Comment by thomaslombart** [comment]
Otherwise, could you help debugging the issue by following the steps described over here: [Getting logs via terminal](https://manual.raycast.com/troubleshooting/getting-logs-via-consoleapp)? Thanks a lot!

**Comment by chrismessina** [comment]
The error is consistent. It appears that `JavaScript heap out of memory`. 

I'm attaching two logs, one where I'm just executing the extension (already installed), and a second log starting from when I install the extension and invoke it the first time (e.g. I can see the interface), and then I get the error. 

I'm guessing I have too many contacts (21,479), although Raycast's [native Contacts search](raycast://extensions/raycast/contacts/search-contacts) works fine. 

[logs.zip](https://github.com/raycast/extensions/files/14103347/logs.zip)

**Comment by thomaslombart** [comment]
Thanks for the details. The `JavaScript heap out of memory` error is a common one amongst Raycast extensions since we don't have proper support for pagination yet. In the meantime, we can look into adding support for pagination in a custom way.

**Comment by chrismessina** [comment]
Bumping this in case we get proper pagination.

**Comment by thomaslombart** [comment]
I have just released an update to the extension that modifies the `Send Message` feature. It now retrieves your latest chats instead of all your contacts. Here's a brief explanation:

Unfortunately, it's not possible to determine whether to send an SMS or an iMessage when accessing contacts through the [Contacts framework](https://developer.apple.com/documentation/contacts) (see issue #10899). However, this information is available in a table that contains all your message chats. The downside is that you won't be able to send a message to someone you haven't chatted with yet. Sending messages to people you've already chatted with is more common than messaging someone new, which is why this change was made.

**Comment by chrismessina** [comment]
> I have just released an update to the extension that modifies the `Send Message` feature. It now retrieves your latest chats instead of all your contacts. 

This means I can use this extension now, so that works for me! :)
