### ISSUE TITLE
Can't search my hashtags, I.e. #content?

### ISSUE THREAD

**Issue by m0rg5** [raycast/extensions#10406]
### Description

Searching any hashtag returns no results. 
I.e. #content 
![image](https://github.com/raycast/extensions/assets/8669538/1e9b8d4c-b546-42b0-b384-bbaf34069706)

To my mind searching tags is more fundamental than text search.

### Current Behaviour

No search results

### Expected Behaviour

Displays all searched tags in order modified.

**Comment by iamyeizi** [comment]
Hi @m0rg5! you have to put in the title of the issue the name of the corresponding extension. For example in your case it is the extension https://www.raycast.com/lardissone/raindrop-io and in the title:
`[Raindrop.io] Can't search my hashtags, I.e. #content?`
otherwise the tags will always be wrong.

**Comment by mathieudutour** [comment]
Seems like this issue is about a specific extension, not the API. Would you mind opening a new issue using the [correct template](https://github.com/raycast/extensions/issues/new?assignees=&labels=extension%2Cbug&projects=&template=extension_bug_report.yml&title=%5BExtension+Name%5D+...) so that the authors of the extension are properly aware of it?
