### ISSUE TITLE
[Notion] Unable to leave a `status` property field empty

### ISSUE THREAD

**Issue by bkeys818** [raycast/extensions#10458]
### Extension

https://www.raycast.com/notion/notion

### Description

The "Create Database Page" command doesn't allow the value of a `status` property field to be empty. By default, a `status` property has a default value that will be used when empty. However, if a `mutliselect` property is converted into a `status` property, it can be left empty.``

### Steps To Reproduce

1. Create a database with a `mutliselect` property.
2. Convert the property type from `mutliselect` to `status`.
3. Run the "Create Database Page."
4. Select the new database.
5. Try and set the `status` to empty.

### Current Behaviour

There is no way to leave a `status` property field empty.

### Expected Behaviour

A `status` property field can be empty **ONLY** when there is no default value.

**Comment by thomaslombart** [comment]
Thanks for flagging this issue. Would you like to work on it?

**Comment by bkeys818** [comment]
@thomaslombart, I'm going to finish up my work on the Toggl Track extension first, but then I can.

**Comment by dariuszpaluch** [comment]
@bkeys818  
- It will be difficult because status property doesn't have a unique value compared to status converted from multiselect, so there is the problem to detect which one should have the require value
- If you want to have status without a default value, why not just use a select field?

The only solution for that is to add the ability to manually mark which one should be treated as multiselect->statuc property.

**Comment by bkeys818** [comment]
@dariuszpaluch, that's an excellent point. I was thinking about adding "No Selection" as an option for all status properties, but I'm not sure if that's the best solution. It might not be best for users, and I'm not sure how the API would respond. When I can find the time, I'll reach out to the Notion team and ask them about the purpose of allowing things to work this way.
