### ISSUE TITLE
Google Chrome Beta

### ISSUE THREAD

**Issue by commandcontrolit** [raycast/extensions#10539]
### Extension

https://www.raycast.com/raycast/browser-bookmarks

### Description

Add support for Google Chrome Beta

### Who will benefit from this feature?

Anyone using Google Chrome Beta

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the Slack community if you need further help.

Note that opening up a PR and having it merged will earn you some credits as we want to reward contributions. You’ll then soon be able to exchange them in our swag store.

**Comment by commandcontrolit** [comment]
Hi Thomas! I would love to help, but I am far from capable of helping with this as I'm not a developer or coder and I hack things out to get them to work. lol .. Sorry!

**Comment by leotuil-ast** [comment]
Hey @thomaslombart @commandcontrolit , i will take a look.

**Comment by tleo19** [comment]
Hey @thomaslombart @commandcontrolit, I will take a look. 😃
