### ISSUE TITLE
[Github] Changing repo while creating issue clears all fields

### ISSUE THREAD

**Issue by MartinBernstorff** [raycast/extensions#10542]
### Extension

https://www.raycast.com/raycast/github

### Description

I would strongly prefer to type the issue title before selecting a repository. This gets the most important information out of my head first, so I don't have to keep it in short-term memory. This makes me much less likely to forget. 

However, if I select a repository after entering the title, the title is cleared.

Thanks a lot for your work!

### Steps To Reproduce

1. Start creating a new github issue
2. Enter title
3. Select repository

**Comment by thomaslombart** [comment]
Thanks for flagging this issue. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the Slack community if you need further help.

Note that opening up a PR and having it merged will earn you some credits as we want to reward contributions. You’ll then soon be able to exchange them in our swag store.
