### ISSUE TITLE
[Todoist] Postpone the task or Reschedule

### ISSUE THREAD

**Issue by weeebdev** [raycast/extensions#10569]
### Extension

https://www.raycast.com/doist/todoist

### Description

Rescheduling the overdue task drops recurrence property.

### Steps To Reproduce

Try to reschedule the overdue recurring task. 

### Current Behaviour

It drops the recurrence.

### Expected Behaviour

It should not.

**Comment by Princeyadav05** [comment]
@thomaslombart i was able to reproduce the bug.

The issue here seems that we are just getting the iso date even though I'm putting a valid to-doist recurrence string. Hence it drops the recurrence property.

![image](https://github.com/raycast/extensions/assets/22894003/c673bd4e-e631-407e-bb5c-b92d3d74c6ef)

![image](https://github.com/raycast/extensions/assets/22894003/3a6fbe10-ccee-4fff-9263-2e983e882142)

And the same happens when I try to create a new task. 
Does raycast todoist extension not support recurring tasks or date strings?

I also checked the todoist API for recurring tasks. it does support recurring strings.
![image](https://github.com/raycast/extensions/assets/22894003/58eec40e-4802-4e51-a815-51181540d12e)

**Comment by thomaslombart** [comment]
It's probably happening because of this [line](https://github.com/raycast/extensions/blob/129f3677172fb3e0747a65489fcbc53958ddf89d/extensions/todoist/src/components/TaskActions.tsx#L263). It may be worth adding the `is_recurring` boolean to it if the task is recurring. Do you want to look at it @Princeyadav05?

**Comment by Princeyadav05** [comment]
Yes @thomaslombart :)

**Comment by Princeyadav05** [comment]
Hi, @thomaslombart @pernielsentikaer 

Getting the following error after updating my fork from the lastest main.

![image](https://github.com/raycast/extensions/assets/22894003/d739e3f6-9dd3-401d-abc1-9a9a74addf12)

![image](https://github.com/raycast/extensions/assets/22894003/f6099843-f4ab-42df-a2af-45aaffcf27a4)

Any suggestions here?

**Comment by thomaslombart** [comment]
The goal here is that if someone reschedules the task, there's a new due date, but it'll stay recurring. For example, if I have a task called "Clean the house" every Sunday, and I reschedule it to Tuesday, it'll still be recurring on Sunday. So, I'd say using the original string though I'm not entirely sure.

**Comment by weeebdev** [comment]
@Princeyadav05 @thomaslombart 
any updates on this?
