### ISSUE TITLE
[GitHub] Add Projects Support

### ISSUE THREAD

**Issue by p0fi** [raycast/extensions#10586]
### Extension

https://www.raycast.com/raycast/github

### Description

Just like the current support for features such as 
* Repositories (Search Repositories, My Latest Repositories)
* Issues (Search, Create, Open Issues)
* Pull Requests (My, Create, Search Pull Requests)

it would be fantastic if the extension also included support for [GitHub Projects](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects). It would be really neat to have the ability to easily list and navigate to my projects and my organization's projects from raycast.

### Who will benefit from this feature?

Everyone who is using GitHub Projects to track their work.

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the Slack community if you need further help.

Note that opening up a PR and having it merged will earn you some credits as we want to reward contributions. You’ll then soon be able to exchange them in our swag store.

**Comment by p0fi** [comment]
Sounds actually interesting! I'm definitely up for giving it a try!
