### ISSUE TITLE
Raycast Focus Anchor Extension - Broken

### ISSUE THREAD

**Issue by BritAngeles** [raycast/extensions#10614]
### Extension

https://www.raycast.com/ashleyhindle/focus-anchor

### Description

Love Focus Anchor. The Raycast Extension does not appear to work. Whatever I type in the box in Raycast does not appear in Focus Anchor.

When loading extension for the first time it says something about 'Pop To Root'. I;m not technical and have no idea what this means. Please tell me if I;m doing something wrong or setting up wrong. Have tried deleting and reinstalling, but alas.

Cheers

### Steps To Reproduce

Install Focus Anchor recast Extension:

https://www.raycast.com/ashleyhindle/focus-anchor#

Try using the Raycast Command

### Current Behaviour

Typing in the Raycast Command textbox and pressing return, just closes Raycast with no effect

### Expected Behaviour

Typing in the Raycast Command textbox and pressing return, should enter the text into the Focus Anchor box

**Comment by ashleyhindle** [comment]
Hey @BritAngeles,

Glad you're enjoying Focus Anchor 😍 

It looks like the popup message you're getting after installation is expected, if it's this:
![Xnapper-2024-02-06-18 14 48-E6492CCC-483A-4E09-AB1F-2A02631D3C42](https://github.com/raycast/extensions/assets/454975/894caedc-34c9-4612-82da-8701e1be5c64)


This happens because the Focus Anchor Raycast extension requires a commitment/focus to be passed.

You can use the extension by activating raycast, typing 'anchor', then hitting the `tab` key then typing your commitment:
![image](https://github.com/raycast/extensions/assets/454975/5690d737-5e21-44cd-ab24-e67b3a4429d5)

**Comment by BritAngeles** [comment]
Thank you for responding so fast.

Unfortunately it's not working for me. I type in the commitment in the box and nothing happens when I press enter. Raycast just closes, and the Focus Anchor box remains unchanged (whether blank or containing an anchor).

The workaround I've found. If I quit Focus Anchor and close the app completely. Then the Raycast Command works. If Focus Anchor is open, the Raycast command doesn't work.

Appreciate your app anyway. Great work. Cheers
