### ISSUE TITLE
[Easy New File] File name as parameter for 'New file here'

### ISSUE THREAD

**Issue by lllopo** [raycast/extensions#10621]
### Extension

https://www.raycast.com/koinzhang/easy-new-file

### Description

Currently the process of new file creation is cumbersome, mildly said. It would be much easier and quicker if the 'New file here' takes a parameter which is the desired target file name. I don't know how much of this is technically possible, but I think it should work as follows :

1. Ask for a parameter on 'New file here' 
2. If the parameter is a fully qualified file name **with** extension - autodetect the template from the extension and create the file directly.
3. If the template can not be detected -> popup the template selection.
4. If the parameter has no extension -> again - popup the template selection.

This is a much faster way of creating a file with the desired name.  Currently the default behaviour doesn't even ask for a file name, which is hardly usable at all. The user have to go through Command-N which is like third step deep which not handy at all.

### Who will benefit from this feature?

Everyone, I believe :-).

**Comment by koinzhang** [comment]
keep active

**Comment by koinzhang** [comment]
keep active

**Comment by koinzhang** [comment]
@lllopo I'm sorry I didn't update this extension until now, I've had very little energy and time to maintain extensions since I've been working.
Thank you very much for your suggestion, it inspired me a lot, so I've made a small refactoring of the Easy New File extension (#12442) based on your suggestion, feel free to keep your suggestions coming!

- You can now quickly create new files directly with the New File Now (previously New File With Text) command in the main window.
- Update the name of the New File Here command to New File With Template to make it clearer
- Other detail optimisation and bug fixes

![easy-new-file-1](https://github.com/raycast/extensions/assets/36128970/09f2efa5-a82b-443d-a4d3-fee40adedca8)

**Comment by koinzhang** [comment]
@raycastbot close this issue
