### ISSUE TITLE
[SSH Connection Manager] Missing terminal Alacritty

### ISSUE THREAD

**Issue by maxheyer** [raycast/extensions#10630]
### Extension

https://www.raycast.com/dimagrossman/ssh-manager

### Description

The ssh-manager extension allows the user to specify a terminal to open new ssh connections.

The ssh-manager does not allow the use of the Alacritty terminal (51k GitHub stars)

### Steps To Reproduce

1. Install the extension
2. Install Alacritty
3. You are not able to choose Alacritty as terminal.

### Current Behaviour

The user is not able to choose Alacritty as the terminal.

### Expected Behaviour

The user is should be able to choose Alacritty as the terminal.

**Comment by emiara** [comment]
I'm currently working on a PR for this.
The existing code for opening iTerm2, Warp, and Terminal utilizes AppleScript. Implementing this for Alacritty poses challenges because it lacks an AppleScript dictionary for direct interaction and lacks useful items in the Apple Menu Bar (which is how Warp is scriptable, despite lacking an AppleScript dictionary).

I have managed to get it to work by using the child_process Node.js API. I also attempted to do it in AppleScript for consistency, but it doesn’t seem easily achievable in an elegant manner."

Anyways, Would be nice to be able to use Alacritty with this wonderful extension.
