### ISSUE TITLE
Scale method on resizing images with TinyPNG doesn't work

### ISSUE THREAD

**Issue by jojo-baker** [raycast/extensions#10728]
### Description

Hi,
I've been trying to use the TinyPNG extension to resize images. The scale method doesn't seem to work. The image it outputs that should be resized is unreadable.

### Steps To Reproduce

I open up raycast and click on the resizing images item. I add "scale" to the method and set a width. The image file that it saves can't be opened so is corrupt. The other methods seem to work fine.

![Screenshot 2024-02-13 at 11 32 35 am](https://github.com/raycast/extensions/assets/53515798/e6fb882a-6cb1-4f4d-ae65-7ae9a1241e05)

### Current Behaviour

It saves a file that can't be opened. 
![Screenshot 2024-02-13 at 11 34 49 am](https://github.com/raycast/extensions/assets/53515798/dd6b0e71-a2d4-4106-a150-4a68df27dd95)
![Screenshot 2024-02-13 at 11 35 09 am](https://github.com/raycast/extensions/assets/53515798/915c934a-b51b-4c79-ba89-f7ada64af4b5)

### Expected Behaviour

It's supposed to save an image that has been scaled to the inputted width or height.

**Comment by mathieudutour** [comment]
Seems like this issue is about a specific extension, not the API. Would you mind opening a new issue using the [correct template](https://github.com/raycast/extensions/issues/new?assignees=&labels=extension%2Cbug&projects=&template=extension_bug_report.yml&title=%5BExtension+Name%5D+...) so that the authors of the extension are properly aware of it?
