### ISSUE TITLE
[Things] ... Show Today's List opens Things

### ISSUE THREAD

**Issue by alwinsamson** [raycast/extensions#10766]
### Extension

https://www.raycast.com/loris/things

### Description

`Show Today's List` opens Things application in the background while Raycast loads, Raycast still shows the list from Today, not sure if that's expected behavior. 

### Steps To Reproduce

Restarted the application multiple times, if the application is opened in the background Raycast load the list faster, otherwise it opens the application.

**Comment by loris** [comment]
Hi @alwinsamson let me know if I understood your issue right, but this is working as expected indeed: Things exposes its data using an Apple Script API, which requires the Things app to be opened in background.
The fact that you already see some data while the Things app is still loading is because the extension cache previously loaded data for providing a more responsive experience

**Comment by loris** [comment]
@alwinsamson That's a subjective question, but I personally (and I believe many Raycast users) find it more efficient and productive to control some (running) apps within Raycast and avoid context switching: Things, Spotify, Safari, etc

**Comment by alwinsamson** [comment]
@loris I appreciate your explanation; Previously, I had assumed there might be an alternative method or that the background opening of Things was unintended behavior. Thank you for providing clarity.
