### ISSUE TITLE
[Obsidian] Append to Daily Note

### ISSUE THREAD

**Issue by 49470v** [raycast/extensions#10802]
### Extension

https://www.raycast.com/KevinBatdorf/obsidian

### Description

Silent mode doesn't work. The checkbox in the settings has no effect on the fact that obsidian still opens when creating a daily note

### Steps To Reproduce

1. Open Raycast
2. Сreate daily note
3. Obsidian will open in any case (regardless of the settings)

**Comment by KevinBatdorf** [comment]
The way the extension was built it requires Obsidian to be open and focus it. The "silent" part just means it wont focus that note inside Obsidian.

I realize it's a bit clunky but it's a limitation of the advanced uri plugin that powers this extension, which is similar to pasting a URL in the browser and it opening Obsidian

**Comment by conatus** [comment]
@KevinBatdorf

Thanks so much for your work on this extension, it is really appreciated.

While the extension works really nicely, it would be cool if Obsidian was not foregrounded, at least as an option. 

Is there way we could work out how we might do this?

**Comment by KevinBatdorf** [comment]
I think the entire plugin would need to be rewritten using the [obsidian plugin api](https://docs.obsidian.md/Plugins/Getting+started/Build+a+plugin) (may or may not work) or otherwise write out the functionality in node explicitly. I think it will require a lot of work. If someone has the time I'm willing to help and audit the code. Otherwise I'll just need to find the time myself eventually since I agree it's an ux failure as it functions now.
