### ISSUE TITLE
[Google Workspace] Configure which browser to open Google Drive files in

### ISSUE THREAD

**Issue by laurensnl** [raycast/extensions#10810]
### Extension

https://www.raycast.com/raycast/google-workspace

### Description

It would be very helpful if the extension could be configured to open Google Drive documents in another browser than your default browser (like Quicklinks) 

### Who will benefit from this feature?

People who use different browsers for different purposes (like Safari for personal browsing and Chrome for work).

### Anything else?

<img width="477" alt="Screenshot 2024-02-18 at 12 51 03" src="https://github.com/raycast/extensions/assets/4354382/29516125-772b-4ee0-8a91-db2404e7e6ed">

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the Slack community if you need further help.

Note that opening up a PR and having it merged will earn you some credits as we want to reward contributions. You’ll then soon be able to exchange them in our swag store.

**Comment by thomaslombart** [comment]
Someone from our team will take care of it 🙂
