### ISSUE TITLE
[Timers] ... Possibility stop alerting sound when time is over

### ISSUE THREAD

**Issue by GitDmytro** [raycast/extensions#10878]
### Extension

https://www.raycast.com/ThatNerd/timers

### Description

Please add possibility to stop ringing of timer (when time is over) from notification window. Now there only on button "Show", that try to open file when I click it.

### Who will benefit from this feature?

Users of Timer extension

**Comment by ThatNerdSquared** [comment]
Hi @GitDmytro, thanks for using Timers :)

I'll look into it; the reason this hasn't already been implemented is because I send that notification using applescript, which doesn't allow us to configure specific buttons on the banner. Implementing custom buttons would require a rewrite of the notification system to hit the system APIs directly.

The use-case is useful so I'll look to implement this eventually, but the technical challenges mean that it might take a while. In the meantime, consider using the "Dismiss Ringing Timer" command, or stopping the timer in the "Manage Timers" command.

**Comment by ThatNerdSquared** [comment]
(Commenting to keep the issue open — I'm currently busy but will be investigating/implementing this and other improvements after Apr. 22nd.)

**Comment by ThatNerdSquared** [comment]
This is implemented, but awaiting review to make it into the Raycast Store:

https://github.com/raycast/extensions/pull/12551

**Comment by ThatNerdSquared** [comment]
Unfortunately, due to restrictions with macOS system APIs and also on the Raycast store, this is not currently technically possible to implement :((

The Raycast team has informed me they'll open up methods to do this in the future, but for now I am closing this issue as I won't be able to address it, despite my best efforts. Sorry about that.

**Comment by ThatNerdSquared** [comment]
@raycastbot close this issue
