### ISSUE TITLE
Fully controlled form components behave as stateful

### ISSUE THREAD

**Issue by FezVrasta** [raycast/extensions#1093]
Raycast version:

## Description

Controlled form components don't act as fully controlled. They act as hybrid.

## Steps To Reproduce

1. Create a Form.TextField and add a `value` and `onChange` properties
2. Make sure the `onChange` handler doesn't update the value
3. Type into the text field

```
const [value, setValue] = useState("Hello, World!");
const noop = console.log;

return <Form.TextField value={value} onChange={noop} />
```

## The current behavior

You can see the text field update with your typed text

## The expected behavior

Since the `value` property is not being updated as I type I don't expect the text field content to update. This behavior should be limited only to text fields using the "defaultValue" property.

**Comment by mattisssa** [comment]
Hey! Thanks for the report. I'm going to duplicate the response from slack to keep some info for this issue.

If the `value` is actually `undefined`, we assume that the form item is not controlled since for now we cannot determine is the field is even defined or not. For now, in the Raycast the `<Form.SomeItem value={undefined} />` is the same as `<Form.SomeItem/>`

At this point, we proposed to use an empty string as a **workaround**, since with `""` we can actually determine that the value is defined and the form item is controlled.

**Comment by FezVrasta** [comment]
The problem I'm describing happens with a defined `value` property.

**Comment by sxn** [comment]
hey @FezVrasta, thanks for reporting this. You're right, the input should always display whatever `value` is set to. In your example `value` is not changed, so the input should behave effectively as read-only. We'll look into fixing this behaviour.
