### ISSUE TITLE
Query Numi CLI doesn't work

### ISSUE THREAD

**Issue by alexbet** [raycast/extensions#10970]
### Description

When I check the "Use numi-cli" checkbox, quering Numi doesn't work. It says that numi-cli is not installed, when in fact it is. It is installed with Homebrew as suggested on the Numi Github page, and the path to the numi file (a symbolic link) is correct. The symbolic link is at 

/opt/homebrew/bin/numi-cli

Here are a couple of screenshots of the setting and the result. 

<img width="1068" alt="Screenshot 2024-02-26 at 6 17 38 PM" src="https://github.com/raycast/extensions/assets/3966760/071f882a-9fd5-403a-b5fe-561c5c59dc31">

<img width="862" alt="Screenshot 2024-02-26 at 6 18 10 PM" src="https://github.com/raycast/extensions/assets/3966760/e3c81cc6-8b42-453d-b2cf-117f3c88aeb0">

I tried uninstalling/installing the extension and the numi-cli, but nothing changed. 

### Steps To Reproduce

1. Check the "use numi-cli" option in the extension
2. Try to query Numi

### Current Behaviour

It says that numi-cli is not installed, which is not correct. If I query the numi-cli directly in Terminal, it works fine. 

### Expected Behaviour

It should work with the numi-cli.

**Comment by mathieudutour** [comment]
Seems like this issue is about a specific extension, not the API. Would you mind opening a new issue using the [correct template](https://github.com/raycast/extensions/issues/new?assignees=&labels=extension%2Cbug&projects=&template=extension_bug_report.yml&title=%5BExtension+Name%5D+...) so that the authors of the extension are properly aware of it?
