### ISSUE TITLE
[Adb]Add ability to get current activity

### ISSUE THREAD

**Issue by lidary-byte** [raycast/extensions#10974]
### Description

Add ability to get current activity

**Comment by mathieudutour** [comment]
Seems like this issue is about a specific extension, not the API. Would you mind opening a new issue using the [correct template](https://github.com/raycast/extensions/issues/new?assignees=&labels=extension%2Cbug&projects=&template=extension_bug_report.yml&title=%5BExtension+Name%5D+...) so that the authors of the extension are properly aware of it?
