### ISSUE TITLE
Chrome Extension Search and Bring Up Found Chrome App Window

### ISSUE THREAD

**Issue by RobertHana** [raycast/extensions#11134]
### Description

I like creating Chrome window'd Shortcuts, which are really Chrome Apps ... I like Raycast's Chrome Extension to search tabs and windows ... I think it does find and list a matching window of Chrome App, but it does not bring up the specific window

### Who will benefit from this feature?

People who make Chrome Apps to separate their sites into Apps

**Comment by mathieudutour** [comment]
Seems like this issue is about a specific extension, not the API. Would you mind opening a new issue using the [correct template](https://github.com/raycast/extensions/issues/new?assignees=&labels=extension%2Cbug&projects=&template=extension_bug_report.yml&title=%5BExtension+Name%5D+...) so that the authors of the extension are properly aware of it?
