### ISSUE TITLE
[raycast-ollama] "Explain code step by step" not working with terminal editors

### ISSUE THREAD

**Issue by comatory** [raycast/extensions#11158]
### Extension

https://www.raycast.com/massimiliano_pasquini/raycast-ollama

### Description

I'm trying to use command "Explain code step by step" with Neovim running in tmux but the command seems not able to pick up the selected text via visual mode.

### Steps To Reproduce

1. Open any terminal
2. Run tmux (optional)
3. Open source code with neovim
4. Jump on top of the file (`gg`), switch to visual mode (`shift + v`), jump to end of file (`shift + g`)

### Current Behaviour

The command says "No text selected"

### Expected Behaviour

Start processing my selected text.

**Comment by MassimilianoPasquini97** [comment]
Hi @comatory,
nvim selection is not shared with macOS system. A workaround is to set nvim to share yanked buffer with system clipboard adding the following line on `~/.config/nvim/init.vim`.
```vim
set clipboard=unnamedplus   	" using system clipboard
```
Set the raycast extentions to use clipboard as a fallback and yank text instead of selecting it.
![image](https://github.com/raycast/extensions/assets/62497822/2353e5da-4d96-4045-862f-477b0b290039)

**Comment by comatory** [comment]
@MassimilianoPasquini97 Thanks. Works like a charm!

Took me a while to find the checkbox, it's under the extension settings.
