### ISSUE TITLE
[Visual Studio Code - Project Manager] php project read wrong version if opened from this

### ISSUE THREAD

**Issue by thou9787** [raycast/extensions#11221]
### Extension

https://www.raycast.com/MarkusLanger/vscode-project-manager

### Description

Sometimes I find that the PHP IntelliSense does not detect the correct version. As a result, I've tried several different methods to open a project:

Opening it from the project manager works fine.
Opening it from the terminal works fine.
Opening it from VSCode also works fine.
Therefore, I suspect the problem might lie here. Could you please take a look at this?

Thank you.

### Steps To Reproduce

1. open raycast
2. type my shortcut to open this extension
3. type my project name
4. enter

### Current Behaviour

detect wrong php version 

### Expected Behaviour

detect correct php version

**Comment by theherk** [comment]
I don't see how that would work. Maybe you could share some code that would act as a project where we can re-create this issue. Since all this does is use the project manager to open a project, I really don't see what that would have to do with intellisense. Also, your description suggests it works when opened from vscode, when opened from raycast and when opened from the terminal, so it isn't clear to me how the issue occurs.

**Comment by thou9787** [comment]
Sorry, I tried to use gpt to support my bad English, but It seemed to describe something wrong

The problem is not about the intellisense
I used this extension to open my php project, but it cannot read my local php version, I tried to set the version to vscode user setting json, but it still not works

> your description suggests it works when opened from vscode, when opened from raycast and when opened from the terminal
Vscode will read the correct php version when I opened from vscode open button, terminal(code .), and vscode project manager(in vscode windown, click the extension icon, and press my folder)
But when I tried to open it from this extension(visual-studio-code-project-manager) from raycast, It will read the wrong version 

Hope the information is clear this time, Thank you

**Comment by theherk** [comment]
@thou9787, it is a bit more clear. The only way I can see this extension being involved is if by chance it is using a different instance of VSCode than you have otherwise configured. I'd check the extension configuration in Raycast, and verify that the `Build` selected matches the one you are opening and otherwise having success. Otherwise, you may have to hunt this down yourself and contribute the fix, because I can't picture another potential culprit.
