### ISSUE TITLE
[Bitwarden Vault] ...

### ISSUE THREAD

**Issue by aaronjz** [raycast/extensions#11240]
### Extension

https://www.raycast.com/jomifepe/bitwarden

#### Error:
```
CLINotFoundError: Bitwarden CLI not found at /opt/homebrew/bin/bw, please make sure you installed it correctly. More information in the extension's description.


```

### Steps To Reproduce

Try searching vault with the "Search Vault" command. See error report.

### Current Behaviour

Was working before, not sure why it's not working at the moment.

### Expected Behaviour

That this extension would search the vault.

**Comment by jomifepe** [comment]
Hello, sorry to pull the rug but due to several issues, I disabled the CLI download for arm64/M1 macs, so the extension is back to how it previously was, and you need to install the CLI on your machine.

It's pretty straightforward to install, see how in the [extension's description](https://www.raycast.com/jomifepe/bitwarden).

If you have any issue feel free to comment here.

**Comment by jomifepe** [comment]
I just released a new version, which should make your extension work again.

**Comment by julienxaop** [comment]
Hello, 
I downloaded the extension today and I just had the same error. => 
`CLINotFoundError: Bitwarden CLI not found at /opt/homebrew/bin/bw, please make sure you installed it correctly. More information in the extension's description.`

But I followed the 'option2' using npm to install the CLI. And the error message says that it can't find the binary in the homebrew folder. 
I then uninstalled the npm package and re-installed it via homebrew (your 'option1') this time. 
And now that works fine.

I then think that you should either: 
- Remove the "'option2' using npm" step from the installation guide.
- or update the code so that it also search for the npm package.

Thank you and have a nice day ;-)

**Comment by jomifepe** [comment]
Good to hear that it's working now, I updated the npm installation suggestion in the README.

@raycastbot close this issue
