### ISSUE TITLE
[GitHub] Repo Invite notification results in API error

### ISSUE THREAD

**Issue by antonengelhardt** [raycast/extensions#11249]
### Extension

https://www.raycast.com/raycast/github

### Description

When i receive an invitation to a repository, and click the notification, an error is shown

### Steps To Reproduce

1. Have someone invite you to a private repo
2. Wait for the notification
3. Click the notification

![Screenshot-CleanShot-006144@2x](https://github.com/raycast/extensions/assets/106314688/4fb97466-a83a-49a6-836f-2bf16dec2e27)

### Current Behaviour

An API error is shown

![Screenshot-Arc-006146@2x](https://github.com/raycast/extensions/assets/106314688/3f2699d9-6874-47e2-8a7d-e4cf5608874a)

### Expected Behaviour

The same behavior as if i had clicked the button in the email notifying me about the invite.

**Comment by antonengelhardt** [comment]
The button in the email points to: https://github.com/repo-owner/repo/invitations . So maybe it is a good idea, to construct the url based on these details instead of "following the thread"...

**Comment by antonengelhardt** [comment]
Forgot to capture the Toast that also appears when clicking the invite: 

![Screenshot-Arc-006148@2x](https://github.com/raycast/extensions/assets/106314688/ae6543c4-a069-434a-bc07-e8c61b052b41)

**Comment by thomaslombart** [comment]
Thanks for flagging this issue. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the Slack community if you need further help.

Note that opening up a PR and having it merged will earn you some credits as we want to reward contributions. You’ll then soon be able to exchange them in our swag store.

**Comment by antonengelhardt** [comment]
Sure, i messaged you
