### ISSUE TITLE
[Gitlab] My Merge Requests : Ability to copy branch name

### ISSUE THREAD

**Issue by DiyarDigiplace** [raycast/extensions#11344]
### Description

Hello,

We developers often switch branches between merge requests, I think it would be useful to be able to copy the branch name of a merge request. Also, being able to put on top **open** merge requests would be nice too.
![CleanShot 2024-03-18 at 03 35 28@2x](https://github.com/raycast/extensions/assets/160529800/aabe933d-aef8-41f8-915e-8efd96452143)

Thank you for reading.

### Who will benefit from this feature?

Developers

**Comment by mathieudutour** [comment]
Seems like this issue is about a specific extension, not the API. Would you mind opening a new issue using the [correct template](https://github.com/raycast/extensions/issues/new?assignees=&labels=extension%2Cbug&projects=&template=extension_bug_report.yml&title=%5BExtension+Name%5D+...) so that the authors of the extension are properly aware of it?
