### ISSUE TITLE
[Linear] View subscriptions show up as unknown notifications

### ISSUE THREAD

**Issue by gtsiolis** [raycast/extensions#11377]
### Extension

https://www.raycast.com/linear/linear

### Description

[View subscriptions](https://linear.app/changelog/2023-10-12-triage-responsibility#view-subscriptions) show up as unknown notifications. This affects how notifications show up in command and menu bar.

<img width="658" alt="Frame 2161" src="https://github.com/raycast/extensions/assets/120486/442704a6-afe5-4707-9efe-eb97d76dfcb9">

### Steps To Reproduce

Subscribe for notifications in a view for when issues are added to the view.

**Comment by thomaslombart** [comment]
Thanks for flagging this issue. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the Slack community if you need further help.

Note that opening up a PR and having it merged will earn you some credits as we want to reward contributions. You’ll then soon be able to exchange them in our swag store.

**Comment by gtsiolis** [comment]
Thanks for the nudge, @thomaslombart. Tried this quickly in https://github.com/raycast/extensions/pull/11572, but I've probably missed something. Hints are welcome!

**Comment by thomaslombart** [comment]
https://github.com/raycast/extensions/pull/12118

**Comment by gtsiolis** [comment]
Thanks for cross-linking #12118, @thomaslombart — the issue around _View_ notifications is probably still relevant, the linked PR seems to only add _Project_ and _Document_ notifications. Cc @jordanamblin
