### ISSUE TITLE
[Todoist] Quick add is returning 400

### ISSUE THREAD

**Issue by grevory** [raycast/extensions#11388]
### Extension

https://www.raycast.com/doist/todoist

### Description

I am able to Create Task using the plugin so the integration is working as expected. But when I try to use Quick Add I get a 400 error.

<img width="751" alt="Screenshot 2024-03-19 at 2 05 55 PM" src="https://github.com/raycast/extensions/assets/1222666/f106d466-4323-4c3e-9d13-4e5a5818af86">

### Steps To Reproduce

1. Open RayCast
2. Choose the Todoist Quick Add command
3. Enter a date/time, like "Today"
4. Enter a description like "Test"
5. Press Command + Enter, or just Enter
6. Look at the status bar at the bottom of the RayCast prompt

### Current Behaviour

Returns a 400 error when you attempt to add a Quick Task

### Expected Behaviour

The task entered in the prompt appears in the Todoist Inbox.

**Comment by thomaslombart** [comment]
This is happening because Todoist uses NLP to parse your text. Since `Today` will be recognized as a date, it means your main text is empty so it can't add an empty to-do. It's the same experience on their website:

![CleanShot 2024-03-21 at 09 34 12@2x](https://github.com/raycast/extensions/assets/16003285/4364c1ab-d40e-41b7-8226-9466c6c2fcf1)

Unfortunately, Todoist's API doesn't send back a more descriptive error, so we can't really improve that part. On the other hand, we can't replicate the same NLP experience as the one on Todoist due to technical limitations. Therefore, I'll mark this one as "Not Planned" 🙂

**Comment by grevory** [comment]
Ok, yes I knew that "Today" was going to be processed as a date. I think the issue here is I was reading the "Text" prompt as what was required for the date and Description as the task. Could the prompt be improved maybe? Maybe it shouldn't be changed since this is how Todoist handles Quick Add too.

<img width="738" alt="Screenshot 2024-03-21 at 2 28 18 PM" src="https://github.com/raycast/extensions/assets/1222666/ba5afb70-0740-4793-a801-e05fc274eb19">

**Comment by thomaslombart** [comment]
It could be improved, yes. What would you suggest?
