### ISSUE TITLE
[Can I Use] Doesn't find some entries

### ISSUE THREAD

**Issue by DaniGuardiola** [raycast/extensions#11401]
### Extension

https://www.raycast.com/thomaslombart/can-i-use

### Description

Some items can't be found (e.g. https://caniuse.com/css-cascade-scope)

### Steps To Reproduce

Try searching for "@scope" and compare Raycast (no results) to the actual webpage: https://caniuse.com/?search=%40scope

**Comment by thomaslombart** [comment]
Thanks for flagging this issue. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the Slack community if you need further help.

Note that opening up a PR and having it merged will earn you some credits as we want to reward contributions. You’ll then soon be able to exchange them in our swag store.
