### ISSUE TITLE
[Browser Bookmarks] Safari/Bookmarks.plist access error

### ISSUE THREAD

**Issue by alex-mextner** [raycast/extensions#11481]
### Extension

https://raycast.com/raycast/browser-bookmarks

#### Error:
```
Error: EPERM: operation not permitted, open '/Users/a.mekhonoshin/Library/Safari/Bookmarks.plist'
```

### Steps To Reproduce

1. install Browser Bookmarks ext
2. allow Safari in its settings
3. try to search bookmarks

### Current Behaviour

error and no result

### Expected Behaviour

search safari bookmarks

**Comment by alex-mextner** [comment]
after several retries Raycast shown Disk Access request and now it's okay.

So issue is why it had not shown immediately when I just installed an the ext and pressed show commands at complete installation screen

**Comment by thomaslombart** [comment]
Thanks for flagging this issue. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the Slack community if you need further help.

Note that opening up a PR and having it merged will earn you some credits as we want to reward contributions. You’ll then soon be able to exchange them in our swag store.
