### ISSUE TITLE
[Apple Reminders] Properly handle nested lists

### ISSUE THREAD

**Issue by jenningsb2** [raycast/extensions#11493]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

Here is what the tasks look like in Apple Reminders:

![CleanShot - Reminders - Reminders - 2024-03-25 165223@2x](https://github.com/raycast/extensions/assets/29644050/f18bd8f1-8768-4caa-9665-37848a80ff03)

When tasks are nested, they appear disconnected to the 'parent' task:

![CleanShot - Brave Browser - New Issue · raycastextensions - 2024-03-25 165316@2x](https://github.com/raycast/extensions/assets/29644050/b32c36bb-02de-4da0-9e48-d3cbf9dd6a1b)

 
![CleanShot - Brave Browser - New Issue · raycastextensions - 2024-03-25 165307@2x](https://github.com/raycast/extensions/assets/29644050/432b02a9-f979-46bb-a1f6-42874cc485da)

### Who will benefit from this feature?

People who like to break down bigger tasks into smaller tasks.

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the Slack community if you need further help.

Note that opening up a PR and having it merged will earn you some credits as we want to reward contributions. You’ll then soon be able to exchange them in our swag store.

**Comment by thomaslombart** [comment]
Hey, so I took a look at that, and unfortunately, there's no way from an API point of view to know if a reminder has a parent reminder. So, I'll mark this one as "Not planned." Feel free to reopen it if you have new information about that.
