### ISSUE TITLE
I can see only my profile repos and not my organization repos

### ISSUE THREAD

**Issue by DanSega1** [raycast/extensions#11502]
### Description

MY personal user connected to my work GitHub organization and I can see only my personal repositories and nothing on my organization.

### Current Behaviour

See only my personal repositories

### Expected Behaviour

See all the repositories that connect to my account

**Comment by mathieudutour** [comment]
Seems like this issue is about a specific extension, not the API. Would you mind opening a new issue using the [correct template](https://github.com/raycast/extensions/issues/new?assignees=&labels=extension%2Cbug&projects=&template=extension_bug_report.yml&title=%5BExtension+Name%5D+...) so that the authors of the extension are properly aware of it?

**Comment by frytg** [comment]
btw, seems related to https://github.com/raycast/extensions/issues/10586
