### ISSUE TITLE
[Zoom] would love to use predefined rooms via extentions

### ISSUE THREAD

**Issue by yosefy-pipl** [raycast/extensions#11611]
### Extension

https://www.raycast.com/raycast/zoom

### Description

i would love to connect to predefined zoom rooms
i have may be 5 of them and use all the time
so not to type the numbers every time

### Who will benefit from this feature?

everybody who uses constant zoom rooms

### Anything else?

command i have found to do it is:
```
open -a zoom.us 'https://us02web.zoom.us/j/4325619999?pwd=Y3VTRGViM215Ny9aMVJPY0phdummy09'
```

<https://devforum.zoom.us/t/ability-to-launch-zoom-meeting-from-command-line/28528/3>

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the Slack community if you need further help.

Note that opening up a PR and having it merged will earn you some credits as we want to reward contributions. You’ll then soon be able to exchange them in our swag store.
