### ISSUE TITLE
[Shell] is not working

### ISSUE THREAD

**Issue by NdagiStanley** [raycast/extensions#11615]
### Extension

https://www.raycast.com/asubbotin/shell

#### Error:

```
TypeError: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined

Mn:index.tsx:272:41

---
269: };
270: 
271: export default function Command(props: { arguments?: ShellArguments }) {
272:   const [cmd, setCmd] = useState<string>("");
273:   const [history, setHistory] = useState<string[]>();
274:   const [recentlyUsed, setRecentlyUsed] = usePersistentState<string[]>("recently-used", []);
275:   const iTermInstalled = fs.existsSync("/Applications/iTerm.app");
---

Or:index.js:11:2490
    at ray-navigation-stack
Ro:index.js:11:2088

```

### Steps To Reproduce

1. Install Raycast
2. Install extension
3. Type "shell" and enter OR Type "shell" then tab then enter the intended command
4. You get a message "Something went wrong"

### Current Behaviour

Please find attached screenshots

<img width="862" alt="Screenshot 2024-04-03 at 19 24 23" src="https://github.com/raycast/extensions/assets/15629602/b220a72e-e2b6-4fae-90e5-52874ff2ecdc">

<img width="862" alt="Screenshot 2024-04-03 at 19 24 43" src="https://github.com/raycast/extensions/assets/15629602/dfbc157a-c5a8-46b0-b67b-71a9e2f1c84a">

### Expected Behaviour

I'm expecting the shell script or alias in my terminal to run.

**Comment by NdagiStanley** [comment]
Looking forward to the fix

**Comment by MohamedK1** [comment]
Hello 👋 ,

I tried to look into the issue. However, I am not able to reproduce it.

I followed the steps mentioned in `Steps to reproduce` section and still this is not possible to be reproduced. Could you please make sure that the extension is updated and try again? maybe if you could provide a video with the steps too that might be helpful.

I also looked into running aliases/functions defined using the extension, for this it's working when you are enabling in the setting the `use terminal` option since the shell will be expanding/using the aliases with the interactive/bootstrapping of the terminal. As for the normal exec path without `use terminal` flag, it uses nodeJS child process exec which will not preload the aliases.

https://github.com/nodejs/node/issues/3916

**Comment by thomasjo** [comment]
I can confirm I'm having the exact same problem. Everything was working fine when I initially setup Raycast a couple of weeks ago, but then something broke.

Does Raycast bundle its own Node runtime? My only explanation for why things suddenly broke for me, and why it's not broken for everyone, is that something in my environment is triggering the issue.

I'll see if I get time later today to clone this repo and properly debug the exception. It doesn't make sense to me for the error to caused by the line that's being reported, so I'm guessing there's minification or something similar that's causing the _"red herring"_.

**Comment by MohamedK1** [comment]
@NdagiStanley I tried the exact same flow as the video but I didn't face the issue. Was there any recent change you did to your environment that you think it might be the reason causing this? Also for the copy Error action what information do you get is it only these ones that you have put in the issue description?

@thomasjo yeah that's true I think it might be so. it should be related to the environment or something that's enviroment depends. I looked into the extension code and it seems there is no major change their since 2 years. Was wondering if reinstalling raycast and/or the extension affect the issue?

**Comment by MohamedK1** [comment]
Solving the issue of not being able to run alias in general in the extension in this PR https://github.com/raycast/extensions/pull/12065.

The main problem of this current issue is not in the PR. Still needing more details to be able to reproduce the issue.
