### ISSUE TITLE
[Browser Bookmarks] open in different profiles

### ISSUE THREAD

**Issue by jstensland** [raycast/extensions#11662]
### Extension

https://www.raycast.com/raycast/browser-bookmarks

### Description

It's great that I can search bookmarks from different profiles (I use chrome), but I would like the option to then open that bookmark in that profile, rather than the last selected window being used. This is similar to the "Open Bookmark's Browser" option, but for the browser profile.

### Who will benefit from this feature?

Anyone that keeps a work and personal profile in their browser and wants to search for a bookmark to open in one or the other would benefit.

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the Slack community if you need further help.

Note that opening up a PR and having it merged will earn you some credits as we want to reward contributions. You’ll then soon be able to exchange them in our swag store.
