### ISSUE TITLE
[Dashlane Vault] Empty Vault

### ISSUE THREAD

**Issue by FoxSupp** [raycast/extensions#11715]
### Extension

https://www.raycast.com/tm.wrnr/dashlane-vault

### Description

The Extension I properly installed and also my Path is updated in the extension itself to the Path where the dcli is stored. But still I get none of my Password inside of the Extension. I just get "Vault Empty" and when I sync I get "Sync with Dashlane succeeded".  I CAN however access my Notes those are synced Properly but I cannot access any of the Passwords inside of the Vault.

### Steps To Reproduce

1. Install Homebrew
2. Install the DCLI
3. Login with the DCLI and Sync
4. Install the Raycast Extension
5. Change the Path to the DCLI in the Extension
6. Don't get any Password inside of the Vault

### Current Behaviour

No Passwords shown inside of the Vault

### Expected Behaviour

All my Saved passwords inside of my Vault

**Comment by tmwrnr** [comment]
Hi @FoxSupp,

Thanks for using the extension. Sorry to hear that you could not use the extension because it is currently not working. 

This is because of a bug inside of the Dashlane CLI with the [latest release](https://github.com/Dashlane/dashlane-cli/releases/tag/v6.2415.0). I already opened an [issue](https://github.com/Dashlane/dashlane-cli/issues/235).

You could install the previous version [v6.2412.0](https://github.com/Dashlane/dashlane-cli/releases/tag/v6.2412.0), which should work again with the extension.

**Comment by Mikescops** [comment]
Is there a way to have some version control on Raycast to ensure people get the information through the app itself that they have to use a specific version of the CLI?

**Comment by tmwrnr** [comment]
You can not control the version of the CLI directly with Raycast as far as I know. But I will improve the error handling to show, that this specific version is not useable with the extension.

**Comment by Mikescops** [comment]
Hello @FoxSupp, it should work with v6.2416.0 of the CLI. Let me know.

**Comment by tmwrnr** [comment]
Hi @FoxSupp, I tried it and with new the version the extension works again. 

I also opened a pull request (#11950) where a user is shown an error message if the buggy version is currently installed.

I will close this issue, because the error is not within the extension itself.

**Comment by tmwrnr** [comment]
@raycastbot close this issue
