### ISSUE TITLE
[GIF Search] Tenor gif search returns irrelevant results

### ISSUE THREAD

**Issue by amarckal** [raycast/extensions#11718]
### Extension

https://www.raycast.com/josephschmitt/gif-search

### Description

Searching for gifs in Tenor seems to be broken. For example searching for the classic "Point to Head" meme returns these results:
<img width="740" alt="image" src="https://github.com/raycast/extensions/assets/100710908/28ff3033-4bac-489f-a483-005242b868f9">

Entering the same text in the search bar returns different results every time as well

Doing the search on Tenor directly works without issues, see:
<img width="740" alt="image" src="https://github.com/raycast/extensions/assets/100710908/26b0c4e8-2af6-4fbe-adbd-46fe095f3e82">

### Steps To Reproduce

1. Run the ray cast gif search and search for gifs in Tenor.
2. Delete a single character or more and wait for it to trigger another search, after that enter back the original text and notice how the search results are now completely different

**Comment by j3lte** [comment]
Unfortunately that's not an easy fix, this needs a bit of a rewrite of the Tenor API implementation in the extension. Currently it is using V1 of the API, while Tenor has gone to V2 (with a different API key, url and url parameters). This migration is documented [here](https://developers.google.com/tenor/guides/migrate-from-v1).

The original author (@josephschmitt) provides API keys for these services, but this is a key for V1. Meaning that in order to update the extension in the first place, we will need an extra key coming from [https://cdn.joe.sh/gif-search/config.json](https://cdn.joe.sh/gif-search/config.json) (something like `tenor_v2`). Only then could we migrate the Tenor code of the extension to V2.

**Comment by thomaslombart** [comment]
I'll take a look at it.
