### ISSUE TITLE
[YouTube Music] Not working for Arc browser

### ISSUE THREAD

**Issue by ferminrp** [raycast/extensions#11849]
### Extension

https://www.raycast.com/danieldbird/youtube-music

### Description

I'm testing all commands and nothing works

### Steps To Reproduce

Install the extension
Pick arc as the browser
Try to pause music or move to next track

**Comment by gnosticdev** [comment]
I use arc and it works great. Can you share more details like your arc settings?

**Comment by sashaaldrick** [comment]
I'm getting the same issue, it worked fine, but all of a sudden across both my macs, I get the same issue. What arc settings could specifically affect this?

**Comment by gnosticdev** [comment]
Hi there,since yours did work at some point then my assumption is a conflict elsewhere on your system. Make sure Arc has AppleScript enabled by going to View > Developer > Allow JavaScript from Apple EventsJesse Greer(410)953-9525On Jun 20, 2024, at 10:44 AM, Sasha ***@***.***> wrote:﻿
I'm getting the same issue, it worked fine, but all of a sudden across both my macs, I get the same issue. What arc settings could specifically affect this?

**Comment by gnosticdev** [comment]
i would also make sure your settings are allowing Raycast to control Arc. You should find these in 

Settings > Privacy & Security > Automation > Raycast

make sure Arc is switched on.  


Jesse Greer

**Comment by H8njo** [comment]
I think I've figured out why the bug occured.
it's because youtube music command controls youtube.

you can check the bug out if you play youtube music and youtube at the same time. and then execute the command.
It would work on the wrong tab which is on youtube video is playing.

**Comment by Asharax** [comment]
Mine doesn't work with Javascript & automation enabled and it's the only Youtube tab, nothing happens when I click next track with Arc. I added logs and it gets timed out when it should be running the JS command to next track. I'm not sure why.

**Comment by haroldao** [comment]
same
