### ISSUE TITLE
[Image Modification] Webp conversion degrades quality by default

### ISSUE THREAD

**Issue by JUSTIVE** [raycast/extensions#11864]
### Description

currently Image Modification (or sips)'s webp conversion uses cwebp, as shown as [here](https://github.com/raycast/extensions/blob/c2177d79799f6af2128b02a437a2b0713166ff01/extensions/sips/src/operations/convertOperation.ts#L60).
but the cwebp's quality parameter is [75 by default](https://developers.google.com/speed/webp/docs/cwebp#:~:text=and%20100.-,The%20default%20is%2075.,-In%20case%20of), causes degraded quality.

maybe an option for quality would be nice, or just add -lossless flag should fix this.

### Steps To Reproduce

convert any image to .webp with image modification extension 

### Current Behaviour

output file show s degraded quality compare to original file

### Expected Behaviour

output file's quality should not degraded by default

**Comment by JUSTIVE** [comment]
oh, it's an extension bug, I selected wrong label..

**Comment by mathieudutour** [comment]
Seems like this issue is about a specific extension, not the API. Would you mind opening a new issue using the [correct template](https://github.com/raycast/extensions/issues/new?assignees=&labels=extension%2Cbug&projects=&template=extension_bug_report.yml&title=%5BExtension+Name%5D+...) so that the authors of the extension are properly aware of it?

**Comment by JUSTIVE** [comment]
thx for let me know!
