### ISSUE TITLE
[Toothpick] Disconnecting a Device not working properly

### ISSUE THREAD

**Issue by maltemichels** [raycast/extensions#12233]
### Extension

https://www.raycast.com/VladCuciureanu/toothpick

### Description

When I try to disconnect an already connected devices, I get the message that it’s disconnected successfully although the devices still stays connected. Please let me know which additional info could be helpful, to fix this issue.

### Steps To Reproduce

1. Open **Manage Bluetooth Connections**
2. Select an already connected device
3. Press Enter
4. Getting the feedback **Device disconnected successfully**
5. Device is still connected

**Comment by VladCuciureanu** [comment]
This is a semi-known issue caused by the flakiness introduced by using MacOS's private AppleScript API. I can only suggest to switch over to the experimental blueutils BlueTooth backend as shown [here](https://github.com/VladCuciureanu/Toothpick#enabling-blueutil-backend).

Let me know if that helps.

**Comment by maltemichels** [comment]
Ah, okay – with blueutil it works fine. Thanks for the hint!

**Comment by VladCuciureanu** [comment]
Np!

@raycastbot close this issue.
