### ISSUE TITLE
[Apple Reminders] Does not recognize Tags and recurring tasks

### ISSUE THREAD

**Issue by binaryblitz10** [raycast/extensions#12279]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

1. It does not recognize “#” to add a tag
2. It does not recognize recurring tasks when using “yearly, monthly and so on”

https://github.com/raycast/extensions/assets/169087053/29456136-54af-4711-90c9-f4a873edadf2

### Steps To Reproduce

1. Open quick add for Apple Reminder
2. Type the task in natural language with "#" and "yearly" / "monthly"

**Comment by thomaslombart** [comment]
Tags are not supported as we're technically limited by Apple's APIs. For the recurring task thingy, it seems you're not using the AI. If you have Raycast Pro, you just have to untick the checkbox. Otherwise, you won't be able to add recurring tasks from the `Quick Add Reminder` command.


![CleanShot 2024-05-14 at 12 36 52@2x](https://github.com/raycast/extensions/assets/16003285/28f106ed-93ba-4029-8a42-9f53089745aa)

**Comment by WangX0111** [comment]
I wrote a shortcut that maps # in note to tag. https://www.icloud.com/shortcuts/710fac8f7e0c424e907def63c06b0a6c
