### ISSUE TITLE
[Brew] continue installation even when closing Raycast window

### ISSUE THREAD

**Issue by ivribalko** [raycast/extensions#12311]
### Extension

https://www.raycast.com/nhojb/brew

### Description

Thank you for the great extension! 

It appears that closing the Raycast window while the extension is installing currently interrupts the installation process. Would it be possible to continue the installation even if the Raycast window is closed? The extension's upgrade command seems to support this, as closing and reopening Raycast displays the ongoing installation at the bottom as long as the upgrade command is running:

<img width="388" alt="image" src="https://github.com/raycast/extensions/assets/20713003/310b82aa-817c-4733-b76f-50ccd2f0e007">

### Who will benefit from this feature?

The installation process will benefit all users by not requiring the Raycast window to remain open throughout the entire installation. This is especially helpful for installing larger casks that may be several gigabytes in download size.

**Comment by nhojb** [comment]
Thanks for reporting this.

Unfortunately this behaviour is due to the way Raycast manages extension processes. Extension lifetime is currently tied directly to the view. When the view is closed and Raycast pops to root, then the extension is unloaded - which is the behaviour you have observed.

We do have an internal issue to track this. I'll raise it again and see if we can find time to address it. Probably will require adding support for extending extension lifetime our API.
