### ISSUE TITLE
[Apple Notes] ...Failed to view a note in Raycast window with larger images

### ISSUE THREAD

**Issue by jasonshanks** [raycast/extensions#12347]
### Extension

https://www.raycast.com/raycast/apple-notes

### Raycast Version

1.73.3

### macOS Version

14.4.1

### Description

After updating to the latest version. I was able to successfully view several of my text only notes, as well as one with multiple images (each under 1MB).

It failed to display one note that included 2 images (10MB and 9MB respectively) So may have to do with file size? Other than that, just a paragraph of text.

Error:
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:406:5
[kOnExit]:worker:313:26
Worker.<computed>.onexit:worker:229:20

### Steps To Reproduce

Try to open an existing Apple Note that includes images of varying sizes.

### Current Behaviour

Fails to display the note with the 'View Note' action.

**Comment by jasonshanks** [comment]
Yes, sure enough. I compressed and replaces those same two images. Now: 5.3MB and 4.3MB. Note loaded fine with 'View Note'

**Comment by thomaslombart** [comment]
Yeah, the problem seems to come from the [`runAppleScript`](https://github.com/raycast/extensions/blob/ba73d7b9535b01672be8ad3220528d7a771a1e57/extensions/apple-notes/src/api.ts#L49) function as images are returned under the Base64 format. Not sure if it's possible to set a different format in the AppleScript function.
