### ISSUE TITLE
[Jira] Provide option to see my active issues in current sprint by default

### ISSUE THREAD

**Issue by ChillarAnand** [raycast/extensions#12360]
### Description

Most of the time, I will be looking at my tickets in the current sprint.

At the moment it is not possible to assign a simple shortcut which can show my active tickets in the current sprint.

**Comment by ChillarAnand** [comment]
Any update on this?

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it?

If yes, here's our [guide on extension contributions](https://developers.raycast.com/basics/contribute-to-an-extension) so that you can open up a pull request. Feel free to contact me here or in the [Slack community](https://raycast.com/community) if you need further help.
