### ISSUE TITLE
[Apple Notes] ...

### ISSUE THREAD

**Issue by Curicae** [raycast/extensions#12484]
### Extension

https://www.raycast.com/raycast/apple-notes

### Raycast Version

1.74.1

### macOS Version

14.5

### Description

I can't create a new note, but I can do everything else. 

### Steps To Reproduce

1. Clicking new note command
2. Error " Could not create a new note."

**Comment by thomaslombart** [comment]
Could you share a recording? It'll make it easier to see what's happening.

**Comment by thomaslombart** [comment]
Maybe there are missing permissions? Could you check that out in the macOS's settings in `Privacy & Security > Automation `?

Otherwise, could you follow that guide:
1. [Fork the extension](https://developers.raycast.com/basics/contribute-to-an-extension)
2. In `new.ts`, comment the `closeMainWindow()` line
3. Re-run the command and you should get a toast within the Raycast window
4. Open that toast by clicking or it or pressing ⌘ + T, then copy the logs and paste them here 🙂

**Comment by Curicae** [comment]
closeMainWindow() line
let text = "";
  try {
    text = await getSelectedText();
  } catch {
    // fails silently
  }

  if (props.fallbackText) {
    text = props.fallbackText;
  }

  if (props.arguments.text) {
    text = props.arguments.text;
  }

  try {
    await createNote(text.trim());
  } catch (error) {
    showFailureToast(error, { title: "Could not create a new note." });
  }
  But I can't find logs because I don't know what toast is

**Comment by thomaslombart** [comment]
![CleanShot 2024-05-21 at 12 48 13@2x](https://github.com/raycast/extensions/assets/16003285/e823660e-c1f5-4734-bb45-8c838b277776)

**Comment by Curicae** [comment]
#### Error:
```
Error: Command failed with exit code 1: osascript
66:97: execution error: Notes bir hatayla karşılaştı: folder "Notes" alınamıyor. (-1728)
    at F9 (/Users/curicae/.config/raycast/extensions/8c7187e0-f64c-4dba-ba77-b1cb543256d6/new.js:32:3080)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.L9 (/Users/curicae/.config/raycast/extensions/8c7187e0-f64c-4dba-ba77-b1cb543256d6/new.js:42:185)
```
The first few times I tried, it didn't come out for some reason.

**Comment by thomaslombart** [comment]
I see what's happening. I'll probably fix it this week.
