### ISSUE TITLE
Gemini wont produce any results

### ISSUE THREAD

**Issue by Bradleeey** [raycast/extensions#12527]
### Description

I have tried everything, followed the steps to set up the API key, and all I get when I try any command is the following...

Could not access Gemini.
This may be because Gemini has decided that your prompt did not comply with its regulations. Please try another prompt, and if it still does not work, create an issue on GitHub.

### Current Behaviour

nothing happens

### Expected Behaviour

something to happen

**Comment by mathieudutour** [comment]
Seems like this issue is about a specific extension, not the API. Would you mind opening a new issue using the [correct template](https://github.com/raycast/extensions/issues/new?assignees=&labels=extension%2Cbug&projects=&template=extension_bug_report.yml&title=%5BExtension+Name%5D+...) so that the authors of the extension are properly aware of it?
