### ISSUE TITLE
Add ability to search all icon sets in Iconify

### ISSUE THREAD

**Issue by rjhewitt3** [raycast/extensions#1265]
#1176 – [Iconify](https://github.com/raycast/extensions/tree/6c27faad5f848a8d8c2821ca0873d6db50f20ccb/extensions/iconify)

Author: @Destiner 

This extension is extremely valuable, but I'm not necessarily using it for specific icon sets. As a result, I'd love to be able to search all of the icon libraries at the same time. In other words, adding an "All" option for the Icon Set dropdown would be extremely helpful for quick inspiration or placeholder icons.

Secondarily, it would be equally helpful (but much harder to develop) to be able to search a variety of terms for icons. For example, Feather uses "cart" but ideally, you would be able to access those icons by typing "basket" or "commerce". This would take quite a bit of cataloging, but some of the icon sets might already have that sort of tagging.

**Comment by Destiner** [comment]
Thanks for feedback @rjhewitt3.

I actually wanted to provide a way to search across all icons, but wasn't sure it's helpful, since I mostly use a single icon set. Gonna add that in a week.

As for the second request, I think that's helpful too, but I'm not yet sure how to accomplish that. Unfortunately, all icons come with a single term in Iconify, so I'll have to source that data elsewhere. I'm not sure whether I'll be able to do it, but at least we can brainstorm here.

**Comment by rjhewitt3** [comment]
@Destiner Was it not possible to add an "All" option to the icon set dropdown? Other extensions use this area for the "All" option and this seems to work really well.

**Comment by Destiner** [comment]
@rjhewitt3 that’s possible, but wouldn’t work well, since the implementation is completely different. You can disable the commands that you don’t use in Raycast preferences.

**Comment by rjhewitt3** [comment]
Not sure why this would need to be disabled though, but you could expose your own setting for that if you really wanted it optional. But if anything should be optional here, it would be choosing which libraries are available and which aren't. (At least in my opinion.)
