### ISSUE TITLE
[iMessage 2FA] ...

### ISSUE THREAD

**Issue by bcometa** [raycast/extensions#12671]
### Extension

https://www.raycast.com/yuercl/imessage-2fa

### Description

Would love the option to "mark as read" or even "delete" text after using/pasting with 2FA. 

### Who will benefit from this feature?

Everyone

**Comment by hitolaus** [comment]
I would also love this feature, but the problem is that iMessage-2FA reads the OTP using the local SQLite copy of your messages (~/Library/Messages/chat.db). Modifying this database to set the read state is highly discouraged, as it may corrupt the database and cause issues in the iCloud synchronization process.

**Comment by bcometa** [comment]
Ah, bummer!
