### ISSUE TITLE
[svgl] Multi-path svg not displaying correctly in search

### ISSUE THREAD

**Issue by TheCommieAxolotl** [raycast/extensions#12687]
### Extension

https://www.raycast.com/1weiho/svgl

### Raycast Version

1.75.2

### macOS Version

14.3

### Description

The [RelaGit logo](https://svgl.app/library/relagit-icon-light.svg) does not display both its elements inside of raycast. The icon displays correctly on the site. 

<img height="100" alt="SCR-20240531-razz" src="https://github.com/raycast/extensions/assets/87679354/5c86d334-f0e0-4ee0-afd6-a48c2e755d4f">
<img height="100" alt="SCR-20240531-rbdn" src="https://github.com/raycast/extensions/assets/87679354/73fb0737-eae8-45c2-a905-966b6daa9d50">

The icon shown in svgl.app vs. raycast

### Steps To Reproduce

1. Open the "Search SVG Logos" command
2. Search for RelaGit
3. Observe the incorrect display.

### Current Behaviour

The image does not display both parts.

<img height="140" alt="SCR-20240531-rbdn" src="https://github.com/raycast/extensions/assets/87679354/73fb0737-eae8-45c2-a905-966b6daa9d50">

### Expected Behaviour

The image displays as on the site.

<img height="140" alt="SCR-20240531-razz" src="https://github.com/raycast/extensions/assets/87679354/5c86d334-f0e0-4ee0-afd6-a48c2e755d4f">

**Comment by TheCommieAxolotl** [comment]
Possibly related: 

The instatus, linux, bitcoin, eth, dogecoin, xrp, bnb, alogrand, firebase, angular, next.js, vk, and dev student club icons do not appear to render at all.
<img width="133" alt="SCR-20240531-rcpy" src="https://github.com/raycast/extensions/assets/87679354/8dd8df83-1bd1-4bb3-a620-08708a56c9f4">

**Comment by 1weiho** [comment]
Thanks for reporting this issue. 

This issue was discovered when I first developed it. 
I tried not to use the svgl API, directly downloading these svgs and creating a brand new Raycast Extension project, reading my local svg files through basic file path methods. 

However, it still cannot be displayed normally. 
I'm not sure if this is related to the issue of rendering svg images in Raycast. 
I'll try to troubleshoot the issue again.
