### ISSUE TITLE
[Home Assistant] Entity/Entities Menus - Show Last Refresh Date/Time and Change Icon

### ISSUE THREAD

**Issue by JonLaliberte** [raycast/extensions#12701]
### Extension

https://www.raycast.com/tonka3000/homeassistant

### Description

1. In the settings for the menu it shows the last refresh date/time, it would be nice if that were in the menu.
2. It would be nice if we could set the icon for the menu.
3. This is a great extension, thanks for your efforts already!

### Who will benefit from this feature?

Anyone that uses the Entities/Entity menus

**Comment by tonka3000** [comment]
@JonLaliberte 

> It would be nice if we could set the icon for the menu

Can you explain that in more detail

**Comment by tonka3000** [comment]
@raycastbot assign me

**Comment by JonLaliberte** [comment]
> @JonLaliberte
> 
> > It would be nice if we could set the icon for the menu
> 
> Can you explain that in more detail

The icon that is shown in the menu doesn't match the icon in Home Assistant:
For example:
<img width="496" alt="Screenshot 2024-07-24 at 4 32 41 PM" src="https://github.com/user-attachments/assets/a58f3137-0fb5-4359-98f4-e642e211b7af">
No way to set those icons.

Honestly, not the biggest deal, so unless others want the feature I wouldn't worry about it :)

**Comment by tonka3000** [comment]
> The icon that is shown in the menu doesn't match the icon in Home Assistant

Ah, now I got you.

Icon management in the Home Assistant API is not really easy because there is no direct way to get the icon of the API beside the alias. So I add most of the icons manually in the extension. Would also love to have the same icons automatically but currently I found no way to do it.

But I can add yours maybe. Can you check what `device_class` your sensors are. Also send a screenshot of the icon which you see in the HA dashboard.
