### ISSUE TITLE
[Open Folders] Folders show as some kind of template code instead of by name

### ISSUE THREAD

**Issue by jace** [raycast/extensions#12778]
### Extension

https://www.raycast.com/timothy_boye/open-folders

### Raycast Version

1.75.2

### macOS Version

14.5

### Description

My folders show up like this. I can only see the actual folder name in the status bar at bottom right. However, the folder icons are correct.
<img width="862" alt="Screenshot 2024-06-05 at 10 32 04 AM" src="https://github.com/raycast/extensions/assets/26695/914bff23-a6b4-4191-adb3-8227d475606b">

### Steps To Reproduce

I just installed the extension and added folders to the speed dial.

### Current Behaviour

Folder names appear to be template code instead of a rendered template.

### Expected Behaviour

Actual folder names.

**Comment by gfazioli** [comment]
@jace @timothyBoye I created I PR https://github.com/raycast/extensions/pull/13196
But I'm not sure if everything is going well, because I can see
<img width="993" alt="image" src="https://github.com/raycast/extensions/assets/432181/336c20a2-0fd7-4576-96d7-7d5d73a974a7">

Maybe someone could help with that?

**Comment by gfazioli** [comment]
@jace @timothyBoye ok, I was able to fix the issue on the PR #13196 - waiting for approval

**Comment by timothyBoye** [comment]
@raycastbot close this issue

Thanks for the fix, sorry I was not available to fix this.
