### ISSUE TITLE
Drag-and-drop missing files?

### ISSUE THREAD

**Issue by bladnman** [raycast/extensions#12795]
### Extension

https://www.raycast.com/timothy_boye/open-folders

### Raycast Version

1.75.2

### Description

When I "list" my download files and then drag a file from that raycast list and drop it on a browser page it does not work. The browser recognizes the drag but once dropped the event.dataTransfer.files list is empty. 

I tried the same by searching for the file using default raycast file search and dargging-and-dropping that file in the same place and it works.

### Steps To Reproduce

- "list downloads" 
- drag a file onto browser that accepts files

### Current Behaviour

nothing happens

### Expected Behaviour

file should be uploaded

**Comment by timothyBoye** [comment]
@bladnman can I ask why you want to drag a downloaded file to your web browser? Not really a bug per say, I can’t say that feature even occured to me to implement is all. Essentially the feature was envisioned as a quick way to open a downloaded file in its default app, rather than move them or drag them to an app. If I have time I can look into it.
