### ISSUE TITLE
[Raycast Wallpaper] update wallpaper on every Desktop

### ISSUE THREAD

**Issue by rares2002** [raycast/extensions#12831]
### Description

It would be nice that the extension updates the wallpaper on every desktop, not just on the current one.

**Comment by mathieudutour** [comment]
Seems like this issue is about a specific extension, not the API. Would you mind opening a new issue using the [correct template](https://github.com/raycast/extensions/issues/new?assignees=&labels=extension%2Cbug&projects=&template=extension_bug_report.yml&title=%5BExtension+Name%5D+...) so that the authors of the extension are properly aware of it?
