### ISSUE TITLE
Simple Youtube streaming: ffplay / ffmpeg

### ISSUE THREAD

**Issue by Viranchee** [raycast/extensions#12845]
### Description

For the Youtube Download extension, if the whole CLI `ffmpeg` is replaced by `ffplay`, it will allow to stream the youtube videos.

eg. This is my Youtube streaming CLI script:
``` bash
yt-dlp $(pbpaste) -o - 2> /dev/null | ffplay -af atempo=1.0 -autoexit -i - &>/dev/null
```

### Who will benefit from this feature?

Everyone, even the author

### Anything else?

Just add a checkbox option to allow streaming on the Youtube Download extension UI

**Comment by mathieudutour** [comment]
Seems like this issue is about a specific extension, not the API. Would you mind opening a new issue using the [correct template](https://github.com/raycast/extensions/issues/new?assignees=&labels=extension%2Cbug&projects=&template=extension_bug_report.yml&title=%5BExtension+Name%5D+...) so that the authors of the extension are properly aware of it?
