### ISSUE TITLE
[Linear] ... Some notifications appearing as unknown

### ISSUE THREAD

**Issue by quinn-linear** [raycast/extensions#12890]
### Extension

https://www.raycast.com/linear/linear

### Raycast Version

1.76.0

### macOS Version

14.4.1

### Description

some, not all notifications are appearing as unknown types 
![CleanShot 2024-06-11 at 16 02 07](https://github.com/raycast/extensions/assets/97164745/ab4a73f9-316b-424a-8ebc-ab434a530bac)

### Steps To Reproduce

SLA breached notification type is one of them. 
![CleanShot 2024-06-11 at 16 02 07](https://github.com/raycast/extensions/assets/97164745/aecbfd2d-bf00-43fe-9a8f-75a5969c4bfc)

### Current Behaviour

Some notification names are unknown

### Expected Behaviour

 Display name of notification types in all cases

**Comment by ramsaysewell** [comment]
I haven't been able to reproduce this issue myself as I do not have SLAs enabled due to being on a non-enterpise level plan on Linear. For anyone interested in debugging this issue in the code, though and does have access to SLAs, a new notification type and icon would need to be added into `src/helpers/notifications.ts`. 

Hope this helps someone, apologies on hitting a brick wall myself on this one!
