### ISSUE TITLE
[Menubar Weather] ... Location not updating?

### ISSUE THREAD

**Issue by bcometa** [raycast/extensions#12911]
### Extension

https://www.raycast.com/koinzhang/menubar-weather

### Raycast Version

1.76.0

### macOS Version

14.5

### Description

Shows New York, but I typed in Burbank, CA. When using longitude/latitude, it's still not the correct weather. 

### Steps To Reproduce

Type Burbank, CA as location. Type longitude/latitude of "The latitude of North Hollywood, Los Angeles, CA, USA is 34.187042, and the longitude is -118.381256."

### Current Behaviour

Shows incorrect weather forecast. With typed city name, it still shows New York. With log/lat, still wrong (but different). 

### Expected Behaviour

Shows weather for correct city or location. 
![Raycast (Settings)  06-12-2024 @ 12 19 40 PM](https://github.com/raycast/extensions/assets/27237458/99f01fc0-60d4-44e2-aa67-666d3e3442fd)

**Comment by koinzhang** [comment]
Hi @bcometa 1. For **City**, only the name Burbank is currently supported, so if you enter Burbank, CA, you will not be able to get the location information correctly.
2. for **Latitude and Longitude**, you only need to input the number.
You can refer to the following figure for the correct way to input
<img width="317" alt="image" src="https://github.com/raycast/extensions/assets/36128970/be9acf67-96e2-46a2-b914-1169efed2cb5">

You can judge whether the weather information is based on City or Latitude/Longitude by the content shown below.

Based on City
<img width="302" alt="image" src="https://github.com/raycast/extensions/assets/36128970/951fcd4e-d1fa-4122-b820-1dd9c03aa311">

Based on Latitude/Longitude
<img width="278" alt="image" src="https://github.com/raycast/extensions/assets/36128970/7a20623d-608a-49a3-8749-eb30e81c6e89">

If you can't get the weather information correctly, it may be caused by the network, you can switch the network to try.

**Comment by bcometa** [comment]
Thanks! Just city without state is working! Still can't get long/lat to work, but no need now. Much appreciated!

**Comment by koinzhang** [comment]
Hi @bcometa. I submitted a PR #13445 to update the Menubar Weather extension, now you can enter more precise location information, hope this helps.

- Get latitude and longitude based on Swift API, support more fine-grained address, for example, you can input address like this: **Pennsylvania Avenue NW, Washington, DC, USA**

**Comment by bcometa** [comment]
Awesome, thank you!

**Comment by koinzhang** [comment]
@bcometa Can this issue be closed?

**Comment by bcometa** [comment]
I'm new to github and didn't know I had the power to close it :).
