### ISSUE TITLE
[Amazon AWS] The application can’t be opened. -50

### ISSUE THREAD

**Issue by ivan-dl** [raycast/extensions#13032]
### Extension

https://www.raycast.com/Falcon/aws

### Raycast Version

1.76.1

### macOS Version

14.5

### Description

I can't open any console service url, there's error message showed "The application can’t be opened. -50" 
Event though I click on the "copy link" button, the url is wrong like "undefined/console?account_id=undefined&role_name=undefined&destination=https://console.aws.amazon.com/cloudwatch/home" 

### Steps To Reproduce

in raycast, type console, and choose a service, press enter

### Current Behaviour

an error message appear "The application can’t be opened. -50"

### Expected Behaviour

open a new browser page and access to the corresponding AWS service page

**Comment by b0lle** [comment]
Hi Ivan, have you already configured your AWS credentials?
Can you show your ~/.aws/config file? (Please mask sensitive data)

**Comment by jfkisafk** [comment]
Reproduced the issue and working on the fix.

**Comment by jfkisafk** [comment]
@raycastbot assign me

**Comment by jfkisafk** [comment]
The issue is that when an `undefined` is set to `process.env.AWS_...`, instead of setting `undefined`, it gets set as the string `"undefined"`. So the checks over [here](https://github.com/raycast/extensions/blob/23f3dc9845049b6baf0bd1fb674b756211f37bd5/extensions/amazon-aws/src/console.tsx#L28-L30) are rendered worthless. cc: @b0lle
