### ISSUE TITLE
[Linear] Search Documents Commdand

### ISSUE THREAD

**Issue by neobarthold** [raycast/extensions#13030]
### Extension

https://www.raycast.com/linear/linear

### Description

We are using more and more the document feature in linear. It would be great to have a command to quickly search and open (with ⌘+⏎) any document.

### Who will benefit from this feature?

Every Linear user, but especially those who are using the documents extensively.

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. There seems to be a [GraphQL query](https://studio.apollographql.com/public/Linear-API/variant/current/schema/reference?query=documents) for that.
