### ISSUE TITLE
[Brew] Wrong version of brew detected

### ISSUE THREAD

**Issue by an-intake** [raycast/extensions#13049]
### Extension

https://www.raycast.com/nhojb/brew

### Raycast Version

1.77

### macOS Version

sonoma 14.5

### Description

Hi, i don't think this is strictly a bug but i'm having issues with the application that i would like to resolve since i find it very useful. I have both versions of brew installed (x86 - arm ) since i need both but the x86 version is somehow used as default in the terminal command given by the application. This made a mess since i just recently found out that 3/4 of the stuff i downloaded were running trough rosetta.  Yes the brew path is correct and the default in the terminal is arm. I uninstalled and reinstalled while also wiping the x86 brew but i still face the same issue. Is there a way to change the command issued by the application? What may have i done incorrectly? ( maybe having briefly x86 as default when first installing?)

### Steps To Reproduce

not sure what to put here

**Comment by nhojb** [comment]
Yeah, we check for `brew` in the PATH first, then fallback to checking the current architecture and choosing `/opt/homebrew` or `/usr/local` as appropriate. I'm not sure if we should change it now since some users may be relying on their PATH environment 🤔 

Two things you can do:

1. Set a "Custom Brew Executable Path" in Settings -> Extensions -> Brew (see screenshot).
2. Or you can add `/opt/homebrew/bin` as the first item in `/etc/paths`. Raycast will load `/etc/paths` at startup and add each item to the app's PATH environment.

<img width="1112" alt="Screenshot 2024-06-21 at 10 25 10" src="https://github.com/raycast/extensions/assets/312540/ca5f02c1-09d4-4023-b9fa-3654c05ed712">

**Comment by an-intake** [comment]
Thank you for the explanation but i actually tried both methods and i still got the same issue. I'm no technician but i'm pretty sure i followed the PATH fix correctly and it did not change. Regarding the custom path i simply changed it to the default brew arm location correct? Definetly not sure of my raycast skills. 
Sorry for the delayed answer

**Comment by nhojb** [comment]
> I'm no technician but i'm pretty sure i followed the PATH fix correctly and it did not change. 

You need to quit and re-open Raycast to ensure that any change to `/etc/paths` is picked up by Raycast.

> Regarding the custom path i simply changed it to the default brew arm location correct?

It should be the full path to the brew executable e.g. `/opt/homebrew/bin/brew`

**Comment by an-intake** [comment]
Yea i put the wrong path in the homebrew custom executable but now it works! I'm still not sure why but the paths fix seems to not work for me even trying multiple reinstalls and resets. Anyway than you very much for the help.

**Comment by an-intake** [comment]
Yea i put the wrong path in the homebrew custom executable but now it works! I'm still not sure why but the paths fix seems to not work for me even trying multiple reinstalls and resets. Anyway than you very much for the help.
