### ISSUE TITLE
[SF Symbols Search] ...

### ISSUE THREAD

**Issue by connorwforsyth** [raycast/extensions#13057]
### Extension

https://www.raycast.com/peteschaffner/sf-symbols-search

### Description

Hey there. Awesome extension! 

It would be awesome to have an action that enables the user to copy the SF Symbol to the clipboard as SVG. Similar to other icon library Raycast extensions.

### Who will benefit from this feature?

For quickly grabbing icons for presentations / illustrations. Particularly in software that doesn't support SF Symbols as an input.

**Comment by peteschaffner** [comment]
@connorwforsyth This extension was a real pain to maintain back when I created it because all symbols had to be rasterized so they'd render in the grid view, and thus were shipped with the extension (which made it huge). I still would love to bring this extension back to life and maybe there have been some changes/new APIs that would make that more feasible.

I'm pretty busy these days, but will take a look at some point, and yes, I will also look into providing SVG copying support!

**Comment by connorwforsyth** [comment]
Hey thanks for the reply and putting in the work @peteschaffner ! I might fork this and give it a go at some point. 🫡
