### ISSUE TITLE
[Amazon AWS] it was working, but broke a couple of days ago.

### ISSUE THREAD

**Issue by arabshapt** [raycast/extensions#13088]
### Extension

https://www.raycast.com/Falcon/aws

### Raycast Version

1.77.1

### Description

TypeError: Cannot read properties of undefined (reading 'pipelineExecutionId')

sx:codepipeline.tsx:12:66

---
 9: import { StopExecutionAction } from "./components/codepipeline/stop-execution-action";
10: 
11: export default function CodePipeline() {
12:   const { pipelines, error, isLoading, revalidate, pagination } = usePipelines();
13: 
14:   return (
15:     <List
---

Fr:index.js:8:2490
    at ray-navigation-stack
No:index.js:8:2088

### Steps To Reproduce

No idea, I used it with sso and it worked until now

**Comment by jfkisafk** [comment]
@raycastbot assign me

**Comment by jfkisafk** [comment]
I couldn't fully reproduce this issue, but my best guess is that you have a pipeline w/o any executions. When this pipeline is getting rendered, aws-sdk is making `executions -> undefined` instead of `executions -> []`. The place it might be erroring out is https://github.com/raycast/extensions/blob/main/extensions/amazon-aws/src/codepipeline.tsx#L68. Made this list rendering much safer in the PR.

**Comment by arabshapt** [comment]
Thank you! I am not sure why this is happening, because I have different profiles and there is no error why i use a profile without pipelines as you see in the screenshot. Only when I switch to the one with pipeline does it break... 
![image](https://github.com/raycast/extensions/assets/26434809/f1e7afa7-ce58-46a3-95f7-518dd20f5b16)
on INT there are no pipelines

**Comment by pernielsentikaer** [comment]
This is now merged 🙂
