### ISSUE TITLE
Authy - Twillo : I got corrupted OTP for ALL of my records

### ISSUE THREAD

**Issue by allanim** [raycast/extensions#13159]
### Description

I have reset my Authy backup password.
Then, I cannot use the search token.
All records show 'corrupted'.

My password is correct, but I cannot see it.

### Steps To Reproduce

1. I have used Authy(Search token) well for a long time.
2. One day, I changed the backup password on Authy.
3. I updated the backup password on Raycast Settings.
4. All records show 'corrupted'

### Current Behaviour

Continues I updated the backup password on Raycast settings. 

### Expected Behaviour

Show secret tokens.

**Comment by mathieudutour** [comment]
Seems like this issue is about a specific extension, not the API. Would you mind opening a new issue using the [correct template](https://github.com/raycast/extensions/issues/new?assignees=&labels=extension%2Cbug&projects=&template=extension_bug_report.yml&title=%5BExtension+Name%5D+...) so that the authors of the extension are properly aware of it?
