### ISSUE TITLE
[Spotify Player] Getting 400 errors

### ISSUE THREAD

**Issue by juliabeach** [raycast/extensions#13167]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Raycast Version

1.77.1

### macOS Version

14.5

#### Error:
```
Error: Error while refreshing tokens: 400 (Bad Request)
{"error":"invalid_grant","error_description":"Refresh token revoked"}

    at withAccessToken()
    at D0
Fr:index.js:8:2490
    at ray-navigation-stack
```

### Steps To Reproduce

its been showing red triangle error for several weeks even after reboots

**Comment by moisesrodriguez** [comment]
Same issue

**Comment by thomaslombart** [comment]
FYI, I'm investigating this issue but I can't reproduce it yet, making it hard to pinpoint where the issue comes from.

To start debugging, could you let me know if:
- You revoked the authorization for the Spotify extension somehow?
- You changed your password or anything related to authentication in Spotify?

**Comment by thomaslombart** [comment]
I [shipped an update](https://github.com/raycast/extensions/pull/13427) that should automatically prompt you to re-authenticate if something goes wrong. It's not going to solve the underlying issue but at least you don't have to manually log out now.
