### ISSUE TITLE
[Shell History] Multiline commands represented as one command per line

### ISSUE THREAD

**Issue by luarmr** [raycast/extensions#13206]
### Extension

https://www.raycast.com/koinzhang/shell-history

### Raycast Version

1.77.3

### macOS Version

14.5

### Description

Multiline commands are represented as 1 commad per line

I use multiline commands very often.

this is a random example:
```
curl --request GET \
  --url 'https://blabla.atlassian.net/rest/api/3/search\?****' \
  --user '******:'$JIRA_API_TOKEN
```

This command will be represented in the extension as 3 separate command

<img width="770" alt="Screenshot 2024-06-28 at 2 01 55 PM" src="https://github.com/raycast/extensions/assets/817416/d5c41591-f0a6-4a23-beb9-9e388d0160fa">

### Steps To Reproduce

Go to you command line a execute:
```
curl --request GET \
  --url 'https://blabla.atlassian.net/rest/api/3/search\?****' \
  --user '******:'$JIRA_API_TOKEN
 ```
 
 Open the extension 

### Current Behaviour

Each line is represented as one command.

### Expected Behaviour

Show the command as a single line. I'm not sure if it's best to just add `...` at the end.
 Personally, I suggest replace the current `accessories` with one labeled multiline. The accessories for my personal use are not relevant since I only use zsh. But I understand that I am only one use case.
 
 ---
 
 **PS: I really like the extension, especially the ability to add commands to the snippets. The history in the `execute shell command` extension didn't meet my needs. I was working on something similar, so as soon as I saw it in the marketplace, I installed it!**

**Comment by koinzhang** [comment]
Thank you for your feedback. Your help is needed to improve this issue, feel free to contact me in slack, or if that's not convenient, reply directly in Github.
Now I need to know what kind of multi-line commands are stored in your zsh_history file?
In my zsh_history, the multi-line commands are represented as follows (I have onmyzsh installed, so there will be dates).
<img width="649" alt="image" src="https://github.com/raycast/extensions/assets/36128970/4fc5133a-395f-4036-a819-935062c91a22">
But I'm not sure what form others are stored in, and I need to determine the storage form in order to make improvements.

Run `open ~/.zsh_history` in you terminal and open zsh_history file, you can see the zsh history

**Comment by luarmr** [comment]
No problem, they show exactly the same than yours:

```
: 1719576015:0;curl --request GET \\
  --url 'https://blabla.atlassian.net/rest/api/3/search\?****' \\
  --user '******:'$JIRA_API_TOKEN
: 1719590931:0;open ~/.zsh_history
```

**Comment by koinzhang** [comment]
Thanks for the info, it looks like zsh's command history comes with its own time, now I know how to fix this.

**Comment by koinzhang** [comment]
Hi @luarmr. I've submitted a PR#13224 to fix this and added a feature to show the contents of the Shell Hitory

![shell-history-3](https://github.com/raycast/extensions/assets/36128970/35925873-1be0-468f-83ec-63657f84ab0b)

**Comment by luarmr** [comment]
awesome, thanks!

**Comment by koinzhang** [comment]
Hi @luarmr, the pr had been merged, i will close this issue. if you have other issue, feel free to give feedback.
@raycastbot close this issue
