### ISSUE TITLE
[Notion] When adding text to a page, can you add a feature to save the text to a new page of the page selected?

### ISSUE THREAD

**Issue by CobbPalahniuk** [raycast/extensions#13208]
### Extension

https://www.raycast.com/notion/notion

### Description

In the previous extension I was using called simply "Memo" ([https://www.raycast.com/mt40/memo](https://www.raycast.com/mt40/memo)) this feature was available, but I want to use this extension because it is overall better.

Can this feature be added?

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the [Slack community](https://raycast.com/community) if you need further help.

Note that opening up a PR and having it merged will earn you some credits as we want to reward contributions. You’ll then soon be able to exchange them in our swag store.

**Comment by CobbPalahniuk** [comment]
Thanks for the reply. I contacted you on Slack.
