### ISSUE TITLE
[Cal.com - Share Meeting Links] 

### ISSUE THREAD

**Issue by NormCopeland** [raycast/extensions#13215]
### Extension

https://www.raycast.com/cal/cal-com-share-meeting-links

### Description

I would like to be able to copy the _private_ link for an event type from the Raycast extension. For one of my events I have enabled the `Enable Private URL` option, however copying the meeting link from the Raycast extensions only gives me the regular link. 

### Who will benefit from this feature?

Anyone who is using the private URL feature.

**Comment by jfkisafk** [comment]
I don't think it is possible at the moment. Both the `GET /event-types` and `GET /event-types/{id}` API(s) ([source](https://cal.com/docs/enterprise-features/api/api-reference/event-types#find-all-event-types)) do not return the hashedLink generated on the website when enabling [private urls](https://cal.com/docs/core-features/event-types/single-use-private-links). 

In ideal case scenario, Cal.com's backend should return private url in the event's `link` string rather than regular link. Trying to see if we can open feature request.

**Comment by AlexIsMaking** [comment]
I had a look at this earlier too and it doesn't look like there's an endpoint that'll generate a private URL either unfortunately.

**Comment by jfkisafk** [comment]
Closing this issue in favor of the issue on Cal.com side (please +1 that for traction). This is not a problem with the extension and cal.com need to provide this extensibility as part of their API response. 

PS: If they just start providing private link as part of the `link` response for the API then no further changes are required in the extension.

**Comment by jfkisafk** [comment]
@raycastbot close this issue

**Comment by NormCopeland** [comment]
Thanks @jfkisafk and @AlexIsMaking for taking a look at this.

**Comment by arealestate** [comment]
Looks like the cal.com folks fix the API so this can be reopened

**Comment by Josh-ML** [comment]
Would it be possible to take another look at this issue, I believe the API should now be providing the hashed link, but it's not the default link provided. 

In the API response, the eventTypes array contains:

```
"eventTypes": [
  "hashedLink": [
      {
          "id": ######,
          "link": "som3ha5hher3",
          "eventTypeId": ######
      }
  ],
]
```

It would be great if we could get a Raycast shortcut to copy the private link instead of the public link :)
