### ISSUE TITLE
[ChatGPT] Latex / Formula Support

### ISSUE THREAD

**Issue by SiKreuz** [raycast/extensions#13211]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Description

I often have questions about technical and mathematical things. The response then contains text similar to what can be seen in the screenshot. This is basically Latex syntax and is obviously hard to read for humans. 

<img width="442" alt="image" src="https://github.com/raycast/extensions/assets/48913164/39f471d3-9268-4ab2-9b6f-716871ac2069">

### Who will benefit from this feature?

Everyone that has more technical and mathematical conversations with ChatGPT.

**Comment by ionescu77** [comment]
## Description
First of all thank you to the contributors for writing this extension!

I also bumped into this issue related to how formulas are rendered.

## Example
### Current output
```bash
When rolling two dice, there are a total of \(6 \times 6 = 36\) possible outcomes
```

### Expected output
```bash
When rolling two dice, there are a total of 6 * 6 = 36 possible outcomes
```

## Screenshot
<img width="753" alt="Screenshot 2024-08-20 at 11 11 39" src="https://github.com/user-attachments/assets/5be64420-9156-4bc1-8050-b4f83bf99c5c">


## Actions
I can have a look myself, but it's my first time digging into Raycast Extensions.

> How is the output for the prompt is formated by this extension?

Any guidance from the maintainers is welcome and I can try to dig and implement it.

---

## How-to Reproduce
### ChatGPT Question (full)
```
Compute the probability of rolling a 2 and then a 6 when rolling a pair of dice. Use python code as an example and explain step by step.
```
### ChatGPT Answer (full)

Sure! To compute the probability of rolling a specific outcome with a pair of dice, we can break it down step by step.

### Understanding the Problem

When rolling two dice, there are a total of \(6 \times 6 = 36\) possible outcomes, since each die has 6 faces. We're interested in the specific sequence of rolling a 2 on the first die and a 6 on the second die.

The only combination we're looking for is:
1. The first die shows a 2.
2. The second die shows a 6.

### Steps to Calculate the Probability

1. **Total Outcomes**: As mentioned, the total number of outcomes when rolling two dice is 36.
  
2. **Desired Outcome**: The specific outcome of rolling a 2 and a 6 (in that order) is just one of those outcomes: (2, 6).

3. **Calculating the Probability**: The probability \( P \) of a specific outcome is given by the formula:
   \[
   P(\text{specific outcome}) = \frac{\text{Number of Desired Outcomes}}{\text{Total Outcomes}}
   \]
   Here, the number of desired outcomes is 1 (only (2, 6)), and the total outcomes are 36. Thus:
   \[
   P = \frac{1}{36}
   \]

### Python Code Example

Here's a simple piece of Python code that exemplifies the calculation:

```python
def calculate_probability():
    total_outcomes = 6 * 6  # Total outcomes when rolling two dice
    desired_outcomes = 1     # We want just the outcome (2, 6)
    
    # Calculate the probability
    probability = desired_outcomes / total_outcomes
    
    return probability

# Call the function and print the result
probability_result = calculate_probability()
print(f"The probability of rolling a 2 and then a 6 is: {probability_result:.4f}")
```

### Explanation of the Python Code

1. **Function Definition**: We define a function named `calculate_probability()`.

2. **Total Outcomes Calculation**: Inside the function, we calculate the total outcomes as \(6 \times 6\), which evaluates to 36.

3. **Desired Outcomes**: We set `desired_outcomes` to 1 because there is only one successful combination we want: (2, 6).

4. **Calculating the Probability**: We then calculate the probability by dividing the number of desired outcomes (1) by the total outcomes (36).

5. **Return the Probability**: The function returns the computed probability.

6. **Function Call and Display**: After defining the function, we call it and print the formatted result.

### Output
Running the code will output:
```
The probability of rolling a 2 and then a 6 is: 0.0278
```

This indicates that the probability of rolling a pair of dice and getting a 2 followed by a 6 is approximately 0.0278, or 2.78%.

**Comment by EmrecanKaracayir** [comment]
Why only AI responses get LaTeX support? Why not our requests don't get it? I want to write LaTeX and see the outcome also in the AI chat window.
