### ISSUE TITLE
[Image Modification] optimize images increase the size of the png + degrading quality

### ISSUE THREAD

**Issue by artivilla** [raycast/extensions#13256]
### Extension

https://www.raycast.com/HelloImSteven/sips

### Raycast Version

1.77.3

### macOS Version

 14.5 (23F79)

### Description

Compressed the png and the output was a jpg of 4x the size. Including size of the original and compressed image. Also attaching the original png so you can try it out. `Clipboard -> Save To Downloads` are the only settings I've modified for this plugin.

![icon](https://github.com/raycast/extensions/assets/2120159/736bd827-ac16-415e-a970-885aef7e012d)

![image](https://github.com/raycast/extensions/assets/2120159/cee859d8-efcc-45e5-aea7-1a799f899131)

### Steps To Reproduce

1. Copy logo png image provided under description
2. Run `Optimize Images` on the source image
3. View the difference in file size and degraded quality

### Expected Behaviour

Expect the size of the optimized image to be smaller while maintaining the same quality.

**Comment by SKaplanOfficial** [comment]
The degrading of quality is somewhat expected as it currently uses JPEG optimization and converts the final result to PNG. I know this isn't ideal, so I'm looking into a few different options.

I'd love to use something like [Sharp](https://sharp.pixelplumbing.com) for this, but I can't get it working on my M1 Mac. Most of the other packages I've found on NPM are either unreasonably large (>20MB), have high severity security issues, or simply don't work.

Because of this, I'm thinking of including smaller binaries like [pngout](http://advsys.net/ken/util/pngout.htm) (335 KB & supports PNG, GIF, BMP, and TGA formats). The downside is that it can be quite a bit slower, especially for files >10MB. Do you (or anyone) know of a small, fast, and reliable optimization package/binary that I could use instead?

I'll probably use pngout in the next release as a stop-gap unless there's a better option.

**Comment by artivilla** [comment]
found this in the frontend masters blog. worth a peek. https://github.com/joye61/pic-smaller
