### ISSUE TITLE
[Quick Event] Is this correct?

### ISSUE THREAD

**Issue by Martin-Gonzalez90** [raycast/extensions#13260]
### Extension

https://www.raycast.com/mblode/quick-event

### Raycast Version

1.77.3

### macOS Version

14.5

### Description

I just realized that if I add PM to a 24hs system format it counts an extra day. 
Is not something important, but just wanted to report it.

![image](https://github.com/raycast/extensions/assets/89008098/223a5d9f-0648-4fcc-8b57-ddd8f317abc1)

![image](https://github.com/raycast/extensions/assets/89008098/0ad84a37-e7da-4693-a113-e4020183591d)

### Steps To Reproduce

Just opened the Create Quick Event from the calendar extension.
Typed "Soemthing, August 30 at 16pm"
If you remove PM it uses the correct date

**Comment by MagnusHJensen** [comment]
I guess it makes good sense, since you're mixing the two, and it tries it best by saying okay so at August 30th, 16 (4PM) and then adding PM, makes 16 normally, an invalid value, but it just sees it as that, and adds 4 hours on top of 12PM. Resulting in 4AM.

By the way, this is a limitation of the parser behind (SherlockJS), but this is what I would assume would happen.
