### ISSUE TITLE
[Amazon AWS] Secrets Manager command should have a debounce for keystrokes

### ISSUE THREAD

**Issue by b0lle** [raycast/extensions#13296]
### Extension

https://www.raycast.com/Falcon/aws

### Description

Hey, 

the secrets manager command should have a debounce function to avoid api requests on each keystroke. I find myself in the situation that i regularly got throttling exceptions because of too many requests.
Also it would be nice to add the keywords property to the [list item](https://developers.raycast.com/api-reference/user-interface/list#list.item) by splitting the secret name on -,_,/,|,\= to make search more user friendly

**Comment by jfkisafk** [comment]
It already has the throttle defined here:

https://github.com/raycast/extensions/blob/dedf880749545861a71cb0083030441f4eae5c3e/extensions/amazon-aws/src/secrets.tsx#L24-L25

This should slow down the requests, are you still receiving throttles?

**Comment by b0lle** [comment]
yes I face them regularly. Maybe we can increase the throttling time?

**Comment by jfkisafk** [comment]
Hey @b0lle , since you're a contributor and might have more secrets in your account than I do for testing, can you please try fixing this? I think the problem is coming from the multiple async calls here:

https://github.com/raycast/extensions/blob/d2327f163a4c84b9dd57ef993f0d27474b8776ba/extensions/amazon-aws/src/hooks/use-secrets.ts#L28-L35

Here is the refactoring I would suggest for `useSecrets(string)`:

```typescript
export const useSecrets = (search: string) => {
  const {
    data: secrets,
    error,
    isLoading,
    revalidate,
    pagination,
  } = useCachedPromise(
    async (query: string) => {
        const { SecretList } = await new SecretsManagerClient({}).send(
          new ListSecretsCommand({
            NextToken: cursor,
            MaxResults: 100,
            ...(query.trim().length > 2 && { Filters: [{ Key: "all", Values: [search] }] }),
          }),
        );

        return secretList;
      },
    [search],
    { execute: isReadyToFetch() },
  );
```

The reason being we don't need to paginate the result of an already typeahead supported api call. Plus raycast native pagination makes 2 initial calls to the promise for some reason, instead of just one.

Then, we can make corresponding changes to the command `List` key and metadata (remove resource policy). I think we can add a separate action to display resource policy (as Detail view), just like we do with secret value

https://github.com/raycast/extensions/blob/d2327f163a4c84b9dd57ef993f0d27474b8776ba/extensions/amazon-aws/src/secrets.tsx#L147-L152

That way we can load the resource policy (make the api call) when user triggers the action and not during initial list rendering for all secrets.

**Comment by jfkisafk** [comment]
@raycastbot assign me

**Comment by b0lle** [comment]
thanks, I would have done it but glad you already implemented something
