### ISSUE TITLE
[Jira] Add configurations for default project

### ISSUE THREAD

**Issue by UXnomaan** [raycast/extensions#13391]
### Extension

https://www.raycast.com/raycast/jira

### Description

I'd like to have control over what project is set as default when I create an issue. Being part of a big company means you will have a dozen of projects to select from but for majority of your use, you will need to create an issue in your own team's project. This will help speed up issue creation. 

This will help with search functionality as well. 

### Who will benefit from this feature?

Any one that has more than 1 projects in their jira instance.

**Comment by jfkisafk** [comment]
Hey @UXnomaan , Jira already caches the last project used during issue creation:

https://github.com/raycast/extensions/blob/63ed284e297dbbf9012e384d7829d96b47c9eb24/extensions/jira/src/components/CreateIssueForm.tsx#L146-L148

Also, it caches the last project you select from dropdown in search issues as well:

https://github.com/raycast/extensions/blob/63ed284e297dbbf9012e384d7829d96b47c9eb24/extensions/jira/src/search-issues.tsx#L81

Are these features not working for you? Or do you want a preference that you can configure at the extension level to provide a default projectId, so that creation form and search issue dropdown always start from that project?

**Comment by UXnomaan** [comment]
That works for me, however, I am suggesting a global setting to apply to all of the jira commands that is somewhat permanent as opposed to a cache that can be invalidated.

**Comment by jfkisafk** [comment]
> That works for me, however, I am suggesting a global setting to apply to all of the jira commands that is somewhat permanent as opposed to a cache that can be invalidated.

Thanks for the clarity, so a global preference is what you're looking for. Keep in mind at that level we can't pull all available projects and you'd need to know the `projectId` for your default project you need to input.

**Comment by UXnomaan** [comment]
Yes, I expect this to be somewhere in the extension menu and something you define when you are setting up the command. 
 
![image](https://github.com/raycast/extensions/assets/3068499/c77d404d-2792-4d09-a3fb-2092c5c95217)

**Comment by thomaslombart** [comment]
Hey @UXnomaan, it's unfortunately not possible as preferences are preset (defined statically in the `package.json`). I'll close out this issue to keep the backlog clean 🙂

**Comment by UXnomaan** [comment]
Thanks for the explanation @thomaslombart!
