### ISSUE TITLE
[Things] Option to Disable Automatic Date Parsing in Quick Add

### ISSUE THREAD

**Issue by Jakeroid** [raycast/extensions#13441]
### Extension

https://www.raycast.com/loris/things

### Description

# Feature Request: Option to Disable Automatic Date Parsing in Quick Add

## Current Behavior
The Quick Add feature in Things automatically parses dates and times in task descriptions, moving tasks from the Inbox to specific dates.

## Requested Feature
Add an option to disable automatic date/time parsing in Quick Add.

## Rationale
- Some users prefer to manually organize tasks
- Allows use of date-like text in descriptions without triggering automatic parsing
- Keeps all new tasks in the Inbox for later sorting

## Proposed Implementation
- Add a toggle in Quick Add interface or app settings
- When enabled, Quick Add ignores date/time information in task descriptions
- All tasks added with this option go to the Inbox

## Considerations
- Option to remember toggle state between sessions
- Possible keyboard shortcut for quick toggling

This feature would enhance Things' flexibility, accommodating users who prefer more manual control over task organization.

### Who will benefit from this feature?

- Increased user control over task organization
- Improved flexibility for different task management styles

**Comment by jfkisafk** [comment]
Since this is a `no-view` command, we can only handle the date parsing skip using command preferences. So, we will need to add a new preference for the command, and based on the value, skip the `when` field here and change the corresponding examples:

https://github.com/raycast/extensions/blob/35fe66de9ea6f317a3211540a5313b01b08fa9a0/extensions/things/src/quick-add-todo.tsx#L20-L40

**Comment by jfkisafk** [comment]
@raycastbot assign me

**Comment by Jakeroid** [comment]
Great!

However, words like "today" and "tomorrow" still change the deadline or move the task into the Today folder.

Why could this happen?

**Comment by jfkisafk** [comment]
Hey @Jakeroid, did you disable AI from preferences? If you did and the task is still getting classified into "today" / "tomorrow" list, then we will need to remove the deadline parsing while setting `deadline` field in the request json:

https://github.com/raycast/extensions/blob/af5c29ac6a075a8ef3610c8fc78c42878cedb94b/extensions/things/src/quick-add-todo.tsx#L23-L29

My initial guess based on the examples was that populating the `when` field classified the tasks, but if you confirm, we can reopen this issue and work on the fix.

**Comment by Jakeroid** [comment]
@jfkisafk 

Yes, I have removed the disable AI checkbox, but it still adds tasks for today if I write something like "don't forget to clean tooth today."

It would be great to have an option to "not parse tasks at all" or something similar. Perhaps it's better to add a few checkboxes:

If the user disables AI, then enable two additional checkboxes:
-  Disable deadline parsing
-  Disable Area/Project parsing

I believe there are many users who use their own task management system and many of them would like to avoid any unexpected automation there.

If you want, I could help with the code. Let me know if some help is needed with that.

**Comment by jfkisafk** [comment]
@raycastbot reopen this issue

**Comment by jfkisafk** [comment]
Hello @Jakeroid, given AI parses everything, it would be ambiguous if we supply extra preferences for `Disable deadline parsing` and `Disable project parsing`. Right now even if AI is not used, the request contains `deadline` and `list` (see README). I believe the easier option would be just to remove the aforementioned code (and deadline parsing) when AI is not used. You can open a PR if you want to, otherwise I will get to it EOW.

**Comment by jfkisafk** [comment]
@raycastbot assign to Jakeroid

**Comment by Jakeroid** [comment]
@jfkisafk 

I will make a PR this week, I hope.

**Comment by jfkisafk** [comment]
ok I think @srikirank also reached out, suggesting he will work on it if he finds bandwidth. I can review it.
