### ISSUE TITLE
[Slack] Why the app is not approved in Slack?

### ISSUE THREAD

**Issue by daver182** [raycast/extensions#13448]
### Description

I want to use the Slack app or the Slack Status app, but neither of them appears approved in the Slack directory. That arises a problem in my current company because the admin will not approve the app if it's not approved by Slack.
Is there any reason for this or a workaround to bypass this?

Thanks

**Comment by mathieudutour** [comment]
Seems like this issue is about a specific extension, not the API. Would you mind opening a new issue using the [correct template](https://github.com/raycast/extensions/issues/new?assignees=&labels=extension%2Cbug&projects=&template=extension_bug_report.yml&title=%5BExtension+Name%5D+...) so that the authors of the extension are properly aware of it?
