### ISSUE TITLE
[Gitlab] Todos Menu Bar Item display even if I have no todos

### ISSUE THREAD

**Issue by vincentkoeckerling** [raycast/extensions#13612]
### Extension

https://www.raycast.com/tonka3000/gitlab

### Raycast Version

1.79.1

### macOS Version

13.6.7

### Description

The Todos Menu Bar Item is always visible in the menu bar even though I don't have any active todos. The "Show Always" option in preferences is turned off.

Already tried to deactive/active the menu bar item, disable/enable the menu bar item command and uninstalled/reinstalled the extension.

Settings:
<img width="312" alt="Bildschirmfoto 2024-07-22 um 21 17 31" src="https://github.com/user-attachments/assets/70f6c011-00bb-421a-911a-b2b7209d9841">

Menu Bar Item:
<img width="238" alt="Bildschirmfoto 2024-07-22 um 21 18 00" src="https://github.com/user-attachments/assets/fa8bbad6-9a5c-499e-b3a0-e21f39176a5f">

### Steps To Reproduce

1. Extension connected to Gitlab Account with no active todos
2. Activate "Todos Menu Bar"
3. Uncheck "Show Always"
4. Menu Bar Item is still shown

### Current Behaviour

The Menu Bar Item is shown even if there are no active todos.

### Expected Behaviour

The Menu Bar Item is hidden when there are no active todos and shown when there are.

**Comment by jfkisafk** [comment]
The problem is that `todos` is never `undefined` here, even when there is no todo(s):

https://github.com/raycast/extensions/blob/6f8fed1702841058d9d7f15b90d22f4a123462fe/extensions/gitlab/src/todomenubar.tsx#L50-L54

Instead of checking `!todos`, this should check `!todos.length` as the `todos` list would be empty in case of no todos.
