### ISSUE TITLE
[Music] "Add to Library" doesn't add to Library

### ISSUE THREAD

**Issue by alexschcom** [raycast/extensions#13708]
### Extension

https://www.raycast.com/fedevitaledev/music

### Raycast Version

1.79.1

### macOS Version

14.5

### Description

When playing a song that's not in my Library and I run the "Add to Library" command, it does bring up a toast message saying "Added to Library", but it did in fact not :(

### Steps To Reproduce

1. Play a song in Apple Music that's not in your Library
2. Run "Add to Library"

**Comment by rawnly** [comment]
Hey @alexschcom thanks for reporting, i need your help to debug this. Can you please run in the terminal the following command and post here the output? 

```
osascript -e 'tell application "Music" to get name of source 1'
```

Below a little explanation of how the command "add to library" works:

We use applescript to control the _Music_ application. This for sure has some limitations. The [add to library](https://github.com/raycast/extensions/blob/476d870e62e292ea7269cfac44ad92a67f5869d8/extensions/music/src/util/scripts/current-track.ts#L24) command as you can see in the code tries to add the current track to `source 1` and if it fails tries to retrieve the library name and retry duplicating the track to the playlist `$libraryName`. This happens because in the past the command was just `duplicate current track to library playlist "Library"` but i discovered then that the `Library` is localized so it worked only for OS with language set to EN.

Which version of macOS are you running?

**Comment by alexschcom** [comment]
Hey @rawnly -- the command returns `Library` (I am using my Mac in English). And I'm running macOS 14.5

**Comment by alexschcom** [comment]
Hey @rawnly -- just following up. Any updates on this?

**Comment by rawnly** [comment]
hey @alexschcom can you try running 

```sh
osascript -e 'tell application "Music" to duplicate current track to source 1'

# and then if it fails 

osascript -e 'tell application "Music" to duplicate current track to library playlist "Library"'
```

and see what happens? If this does not fail and does nothing i'll be honest, idk how to help you since seems like for other it's working.

**Comment by rawnly** [comment]
unfortunately we're limited by the api that apple provides to interact with the application. maybe in the future a v2 of the extension could work with the official rest api (with still a lot of limitations)

**Comment by alexschcom** [comment]
Ha! The Raycast command suddenly works... I updated to macOS Sequoia -- maybe that's why?

Thanks for your help anyway!
