### ISSUE TITLE
[Shell History] Squashed ZSH history

### ISSUE THREAD

**Issue by Ernest0-Production** [raycast/extensions#13726]
### Extension

https://www.raycast.com/koinzhang/shell-history

### Raycast Version

1.73.2

### macOS Version

14.4.1

### Description

I use zsh terminal via the built-in terminal and via the terminal in VS Code. 

And the entire history of the teams is reflected in one entry - which seems erroneous.

<img width="862" alt="Снимок экрана 2024-07-28 в 00 40 03" src="https://github.com/user-attachments/assets/b2784c62-0043-4f72-83b2-fdc4a8b22052">

### Steps To Reproduce

1. Open a terminal
2. Enter some command
3. Open a new terminal tab
4. Enter another command
5. Close terminal
6. Open a raycast command

### Current Behaviour

Both commands are in the same entry

### Expected Behaviour

The commands are in different entries

**Comment by j3lte** [comment]
@Ernest0-Production please check the [README](https://www.raycast.com/koinzhang/shell-history) first, here's a note:

---
**Note**

If your Zsh history is not displaying correctly (it is showing as one record), it may be because Zsh history is not saving the timestamp correctly.

1. You can install `oh-my-zsh` to try to solve this problem
2. You can reconfigure the `.zshrc` file to try to fix the problem
   - Check the HIST_STAMPS setting: zsh provides an option called HIST_STAMPS, which controls whether timestamps are saved in the history. You can check your zsh configuration file (e.g. .zshrc) for the HIST_STAMPS setting. Typically, you can ensure that timestamps are logged by adding the following configuration `setopt EXTENDED_HISTORY` to your `.zshrc` file; this option will enable timestamp logging.

**Comment by Ernest0-Production** [comment]
@j3lte Hi!

Thanks, this fixed the problem.

But I don't understand why the timestamp is so important to display the list of commands in history?
I think this field may be optional if EXTENDED_HISTORY is not set

**Comment by koinzhang** [comment]
This has to do with the storage format of zsh_history, which is stored as txt text, and Shell History, which goes by line to read the history record.
It's a bit more complicated here, with two main considerations:
1. most users' zsh_history will be timestamped
2. take into account the multi-line command scenario

<img width="302" alt="image" src="https://github.com/user-attachments/assets/b78cffca-b97d-42a0-bc1f-b37d50434820">

I'm thinking of adding an option or dynamically determining whether zsh_history is timestamped or not.

**Comment by koinzhang** [comment]
Fixed in PR #14715
@raycastbot close this issue
