### ISSUE TITLE
Add the IP2Location.io IP Geolocation API

### ISSUE THREAD

**Issue by ip2location** [raycast/extensions#13779]
### Description

It is good to have an alternative API for getting IP geolocation data. IP2Location.io has a [free API plan](https://www.ip2location.io/pricing) that allows users query up to 30,000 IP addresses per month. If used without an API key, there is a limit of 500 queries per day.

**Comment by mathieudutour** [comment]
Alternative API to what?

**Comment by ip2location** [comment]
As an alternative to ipwho.is as it's always good to have a failover in case your existing API is not responding.

**Comment by mathieudutour** [comment]
what existing API are you talking about?

**Comment by ip2location** [comment]
https://github.com/raycast/extensions/blob/d7dbc9b67006de0d4383f97be8fa921b171268fc/extensions/whois/src/hooks/use-whois-data.ts#L5

**Comment by mathieudutour** [comment]
Seems like this issue is about a specific extension, not the API. Would you mind opening a new issue using the [correct template](https://github.com/raycast/extensions/issues/new?assignees=&labels=extension%2Cbug&projects=&template=extension_bug_report.yml&title=%5BExtension+Name%5D+...) so that the authors of the extension are properly aware of it?
