### ISSUE TITLE
[Toggl Track] Failing to stop time entries

### ISSUE THREAD

**Issue by kikujiro-mms** [raycast/extensions#13800]
### Extension

https://www.raycast.com/franzwilhelm/toggl-track

### Raycast Version

1.80.0

### macOS Version

14.6

### Description

As of today (and so I think the latest update to the extension), the TT extension consistently fails when it tries to stop a running time entry.

### Steps To Reproduce

1. With a timer running,
2. Trigger Raycast
3. Choose Start/Stop Time Entry
4. Choose the running timer at the top of the Raycast window, and hit return to select Stop Time Entry.

### Current Behaviour

Message “Failed to stop time entry” appears. (_Starting_ timers works fine).

### Expected Behaviour

The current timer should stop.

**Comment by lukebars** [comment]
Hi!

I was able to reproduce this behavior. We had two releases in two days, so that might have caused some loopholes. 
Will work on a fix today, sorry for that. In the meantime - the menubar part of this extension seems to be stopping the time entries. I'd suggest to try using that until the fix arrives.

<img width="767" alt="image" src="https://github.com/user-attachments/assets/4fbaa6a3-42b8-49be-ac82-6f18c67e5971">

**Comment by lukebars** [comment]
I've opened a PR for the fix

**Comment by lukebars** [comment]
Fixed in the update ✅
