### ISSUE TITLE
How generate API token for flaticon account

### ISSUE THREAD

**Issue by dariuszpaluch** [raycast/extensions#13814]
### Extension

https://www.raycast.com/bgnfu7re/flaticon

### Raycast Version

1.80.0

### Description

How Can I generate API token to flaticon service?

### Steps To Reproduce

- Generate API token to this extension.

**Comment by kudrykv** [comment]
Err
It appears that Flaticon broke something 🤔
Here is their [support page][1]. In turn, it points to their [API part of the site][2] (almost invisible link in the first sentence: "You can access our API by signing up for an API key"). But that site returns 404. Previously, it allowed to create a token.

Today, if you go to their site, scroll to the bottom and navigate to API (Tools > API), it'll redirect you to another domain. It feels very like they are going to discontinue their API, if didn't already 😞

It may be the case that this plugin should be discontinued if Flaticon API is indeed dead.

I'm hesitant to build the next one for the Freepik (the one, which Flaticon redirects to) because of the pricing.

[1]: https://support.flaticon.com/s/article/Accessing-the-API-FI?language=en_US&Id=ka03V0000008XscQAE
[2]: https://api.flaticon.com/
