### ISSUE TITLE
 [Visual Studio Code] "Open in code" just opens finder window

### ISSUE THREAD

**Issue by jacten** [raycast/extensions#13927]
### Description

When I select a project and click "Open in code" it just opens finder, instead of opening in vscode. 

https://github.com/user-attachments/assets/a590253b-0281-49d9-81fe-ba10d085cf48

### Steps To Reproduce

1. Install vscode extension
2. Choose "Search Recent Projects"
3. Press "enter"

### Current Behaviour

Opens in finder

### Expected Behaviour

Opens in vscode

**Comment by mathieudutour** [comment]
Seems like this issue is about a specific extension, not the API. Would you mind opening a new issue using the [correct template](https://github.com/raycast/extensions/issues/new?assignees=&labels=extension%2Cbug&projects=&template=extension_bug_report.yml&title=%5BExtension+Name%5D+...) so that the authors of the extension are properly aware of it?
