### ISSUE TITLE
[GitHub] Add actions overview

### ISSUE THREAD

**Issue by Bro0f** [raycast/extensions#14132]
### Extension

https://www.raycast.com/raycast/github

### Description

I really like the workflow run view but it gets really overwhelming if you have a lot of GitHub actions in place. 
A nice solution would be to have a list/grid of all available actions in a repository and display their last workflow run result (success, failure, currently running).  
This could replace the current workaround of just displaying the GitHub Action Badges in the repository README.md file.

### Who will benefit from this feature?

Users with a lot of GitHub Actions

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? If yes, here's our [guide on extension contributions](https://developers.raycast.com/basics/contribute-to-an-extension) so that you can open up a pull request. Feel free to contact me here or in the [Slack community](https://raycast.com/community) if you need further help.
