### ISSUE TITLE
[Slack] Add ability to copy links

### ISSUE THREAD

**Issue by pavzagor** [raycast/extensions#14257]
### Extension

https://www.raycast.com/mommertf/slack

### Description

Please allow copying the links to messages, channels, people.

### Who will benefit from this feature?

Everyone who needs to put slack links to task trackers or documentation.

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? If yes, here's our [guide on extension contributions](https://developers.raycast.com/basics/contribute-to-an-extension) so that you can open up a pull request. Feel free to contact me here or in the [Slack community](https://raycast.com/community) if you need further help.
