### ISSUE TITLE
Why not simply search via standard url structure?

### ISSUE THREAD

**Issue by TechRemarker** [raycast/extensions#14315]
### Description

Your readme says, "ChatGPT doesn't provide ability to provide custom search query to the URL, like for perplexity or other search engines https://www.perplexity.ai/search?q=myquery." and that this extension aims to use javascript to similate a person to bypass that limitation. 

But I've never had a problem doing a query via url, just like via google using the standard format, "https://chat.openai.com/?q=" When googling for the url structure the top Google result notes it as well. Wondering if this is an older project from before that feature was added?

### Steps To Reproduce

N/A

### Current Behaviour

N/A

### Expected Behaviour

N/A

**Comment by mathieudutour** [comment]
Seems like this issue is about a specific extension, not the API. Would you mind opening a new issue using the [correct template](https://github.com/raycast/extensions/issues/new?assignees=&labels=extension%2Cbug&projects=&template=extension_bug_report.yml&title=%5BExtension+Name%5D+...) so that the authors of the extension are properly aware of it?
