### ISSUE TITLE
[Claude] Extension stopped working all of a sudden

### ISSUE THREAD

**Issue by diogogpinto** [raycast/extensions#14354]
### Extension

https://www.raycast.com/florisdobber/claude

### Raycast Version

1.82.3

### macOS Version

14.6.1 (23G93)

### Description

The extension was working fine and I was using it with no problem. Suddenly, it stopped working:

- Conversation history disappeared
- Can't ask questions
- Models were deleted and can't create new models

<img width="780" alt="Captura de ecrã 2024-09-06, às 11 49 21" src="https://github.com/user-attachments/assets/af809158-58de-405e-a8c3-6950b90222de">

Cmd + N doesn't work.

<img width="779" alt="Captura de ecrã 2024-09-06, às 11 49 51" src="https://github.com/user-attachments/assets/bc479b2a-846e-4296-9b5b-6040913e81e7">

<img width="778" alt="Captura de ecrã 2024-09-06, às 11 50 04" src="https://github.com/user-attachments/assets/30419df2-67c1-4a36-848d-ea0b7bab900d">

### Steps To Reproduce

Open Claude > Models, Ask Question or Conversations and it's all empty. Can't trace back to where it went wrong.

**Comment by florisdobber** [comment]
Hi @diogogpinto, I cannot reproduce this from a clean install. Can you give me any more information that might help resolve this? I understand that you might have prompts or settings saved, but I am afraid you might have to re-install in order to fix this bug.

**Comment by diogogpinto** [comment]
Hello @florisdobber 

Thank you for the follow up.

I couldn't trace back to any logs or any faulty behaviour (there was none - simple "Ask Question", it started loading then all local history and models disappeared). All I could do was uninstall and install fresh, losing all my local models and conversation history. No big deal, as I had backups of model information from other LLMs.

I'll close this, if anyone else comes across this problem we can come back and I'll try to reproduce the issue.

Thank you!

**Comment by ridjis** [comment]
I didn't have any backup, so all my models are gone.

Also, this happened to me before with ChatGPT extension twice.

After all data is removed, and here are some behavior inconsistencies with Claude extension I've noticed:
- when in "Models", we can't create new one (see first screenshot) because we have no models. Only message is rendered, without any action items.
- even though all data is removed, along with models, on "Ask question" we don't see dropdown for selecting model (understandable), but when I open full text view, there is "Haiku" model in dropdown (actually temp model, fallback in case no models are available).

There is an impossible state — we have no models in local database, but also we can't create model because we have no models ([code](https://github.com/raycast/extensions/blob/14c0c72008fac12005011a254c8fe8e121c5663d/extensions/claude/src/model.tsx#L91-L93)).

My guess is that this might be related to LocalStorage limitation*, but not sure if data reset should happen ever.

> \* The API is not meant to store large amounts of data. For this, use [Node's built-in APIs to write files](https://nodejs.org/en/learn/manipulating-files/writing-files-with-nodejs), e.g. to the extension's [support directory](https://developers.raycast.com/api-reference/environment#environment).

<img width="750" alt="image" src="https://github.com/user-attachments/assets/81c511b9-46f0-488c-b8b2-3b070ac2958c">
<img width="750" alt="image" src="https://github.com/user-attachments/assets/07c4b779-d977-4966-8c84-5525463a2c60">
<img width="750" alt="image" src="https://github.com/user-attachments/assets/9d804699-378e-4918-98ba-af854701d9ee">
