### ISSUE TITLE
[Todoist] Add the Ability to Insert Reminders in Quick Add Tasks Action

### ISSUE THREAD

**Issue by geraldaddey** [raycast/extensions#14422]
### Extension

https://www.raycast.com/doist/todoist

### Description

Add support to use reminders like users would normally do when creating tasks in Todoist. 

Example: !30mb, !30, !Mon, !7pm

### Who will benefit from this feature?

All Pro Users and Family Users.

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? If yes, here's our [guide on extension contributions](https://developers.raycast.com/basics/contribute-to-an-extension) so that you can open up a pull request. Feel free to contact me here or in the [Slack community](https://raycast.com/community) if you need further help.
