### ISSUE TITLE
[Home Assistant] Automations: option to set Primary Action

### ISSUE THREAD

**Issue by robdejonge** [raycast/extensions#14429]
### Extension

https://www.raycast.com/tonka3000/homeassistant

### Description

For automations specifically, but perhaps this could also apply to other entity types, I would like to be able to set the Primary Action to either the current "Turn On/Off" or (to be added) "Trigger". 

### Who will benefit from this feature?

Many, many times I've gone into Automations to trigger one manually. I hit Enter, realize I'm toggling the automation on/off, hit Cmd-Enter or Cmd-K to actually trigger it. It has happened more than once I forget I've now toggled the automation off and it will next time not automatically run! I am certain I am not the only one who experiences this.

### Anything else?

For an example, look at the Raycast "Clipboard History" where for a Primary Action I can select 'Paste to Active App' or 'Copy to clipboard'.

**Comment by rspeicher** [comment]
Personally I think the default action on an automation should be to run it, as you expect. Toggling it seems like the less-often-used action.

I don't think an option for "default action" is a bad idea, but that's a more involved fix.

**Comment by robdejonge** [comment]
I do absolutely agree, the only reason I suggested the default action route is because existing users may have gotten used to this behavior and the default action thing is a common setting for extensions in Raycast. Obviously for me personally, either will be fine 😁

**Comment by tonka3000** [comment]
Hey 👋,

I never run automations manually because they are not intended to run manually (small exception can be during development). I use the turn on/off for automations and I made it the default because it is the only operation which works in all circumstances.
Many automations are broken when the get triggered manully because they skip the triggers, which 99% of all automation have, and this leads to error in the automation.

When you run automations manually regularly, I would highly recommend using a script (which are automations without triggers) and not an automation.

The primary action preference is possible, but it will more and more spam the preference because I can only add it to the whole extension because multiple commands would need the options.

**Comment by robdejonge** [comment]
Hmm. I have thoughts on what you wrote, @tonka3000 , but this is your extension to make decisions on what gets added! 😁
