### ISSUE TITLE
[Bitwarden] Support self-hosted Bitwarden Vault

### ISSUE THREAD

**Issue by aozaki-kuro** [raycast/extensions#1447]
# Extension – [Bitwarden](https://github.com/raycast/extensions/tree/main/extensions/bitwarden)

Author: @pomdtr 

**Describe the feature and the current behavior/state.**

I am using a self-hosted Bitwarden (Vaultwarden actually) but seemed like the extension does not support connecting to the self-hosted vaults.
I successfully logged from the bitwarden-cli but cannot find a way to change the other settings in the extension.

**Who will benefit from this feature?**

A lot of users using self-hosted vaultwarden would benefit from this, there would be no need to install the App anymore!

**Any Other info.**

No.

**Comment by daniel-stoneuk** [comment]
I wonder if #1387 would have broken this for people using a self hosted vault @pomdtr.

@aozaki-kuro how long have you been using the extension for? Did the recent update break this?

Without rolling back #1387 I think we'd have to resolve this by adding a preference that can be used to set a server address and certs environment variable. Instead of adding start-up latency, we could keep track of when this is changed and keep the CLI in sync with Raycast storage.

`bw config server [server-address  | "https://bitwarden.com"]`

`NODE_EXTRA_CA_CERTS: "path/to/certificates.pem"`

We'd probably need to have someone test the branch out with their self hosted server as well.

**Comment by pomdtr** [comment]
We will not rollback #1387, I think it was a considerable improvement to isolate the extension.

I think we could just add an additional command allowing you to interact with the `bw config` command through a form.

I don't want to perform a check each time the extension load the vault items.

**Comment by aozaki-kuro** [comment]
@daniel-stoneuk I am totally new to the extension, fresh install yesterday.
I installed the bitwarden-cli through `pnpm` and successfully logged into my own server. Then I retrieved the API from my own server and filled it into the extension but no luck, it does not work.

**Comment by daniel-stoneuk** [comment]
Thanks @aozaki-kuro, there was a recently merged change that kept the extension's Bitwarden config isolated from the rest of the system. Hopefully there'll be a way to add your server URL soon.

**Comment by pomdtr** [comment]
> Yeah, that was my thinking for keeping the check on the Raycast side of things. Assuming that the [Raycast Storage API](https://developers.raycast.com/api-reference/storage) is fast, the startup could be like this:
> 
> ```ts
> const preferences = ... get preferences ...
> const cliServer = await LocalStorage.getItem<string>("cli-server") || "";
> const preferenceServer = preferences["server"]
> if (preferenceServer != cliServer) {
>     // todo: add logic to reset when preference is empty
>     await api.setServer(preferenceServer)
>     await LocalStorage.setItem<string>("cli-server", preferenceServer)
> )
> // continue ...
> ```
> 
> A form would do the job as well but it might be a barrier for those that want to use a self hosted server.

This works too, it will better integrate with raycast. Do you have time to make a pull request ?

**Comment by daniel-stoneuk** [comment]
Yeah, I can do @pomdtr. Will give it a go sometime today or tomorrow. Cheers.
