### ISSUE TITLE
[GitHub] Have more then the last 50 workflows

### ISSUE THREAD

**Issue by avivv3** [raycast/extensions#14529]
### Extension

https://www.raycast.com/raycast/github

### Description

we have multiple workflows running all the time. this feature is super useful to quickly see if a deployment workflow is done or not. with the volume of workflows we have there's a really short window i can visually search for a workflow and see that it's finished before it's too far gone.

if the amount of recent workflow it searches for was something like 500 instead of 50, the window to search for my workflow would be much larger.

either that, or have the ability to search by  actor:@me for example 

### Who will benefit from this feature?

everyone looking to check the status of their workflow.

this extension is awesome! keep up the good work 👍

### Anything else?

![image](https://github.com/user-attachments/assets/e2b6b2f7-13ef-4b9f-93be-78b7d465f1f1)

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? If yes, here's our [guide on extension contributions](https://developers.raycast.com/basics/contribute-to-an-extension) so that you can open up a pull request. Feel free to contact me here or in the [Slack community](https://raycast.com/community) if you need further help.
