### ISSUE TITLE
[1Password] unvoncenient UX

### ISSUE THREAD

**Issue by pierrebinon** [raycast/extensions#14620]
### Extension

https://www.raycast.com/khasbilegt/1password

### Description

When I open the 1password command, it requires to login (makes sense).
But then after login I am redirected to Raycast home search.
I would like to be redirected to the 1password search.

**Comment by Luk4h** [comment]
Hey @pierrebinon, that happens because you've set a hotkey to open the command. Sadly, Raycast does not open the command again if it was launched using the hotkey. It happens to me as well! 😟 Unfortunately, from what I have searched, trying to fix this issue has not been successful. I still have to log in and then use the hotkey again to open it.
