### ISSUE TITLE
[Gitlab] Do client-side filtering of search results

### ISSUE THREAD

**Issue by meesvandongen** [raycast/extensions#14648]
### Extension

https://www.raycast.com/tonka3000/gitlab

### Description

Doing client-side filtering would probably speed up searching significantly, for example for projects; though I am not sure how feasible it is.

### Who will benefit from this feature?

Anyone using the gitlab extension

**Comment by macbookandrew** [comment]
I suspect it would improve performance for users with access to tens of resources. For users with access to hundreds or thousands of resources, the extension would have to load everything up front and then filter client-side, resulting in significantly slower overall behavior. 🤷🏻‍♂️

**Comment by jessedobbelaere** [comment]
I was using Alfred with the Gitlab extension before using Raycast. It was very snappy to search for a project. In that extension they chose to [build a local cache](https://github.com/lukewaite/alfred-gitlab/blob/master/src/gitlab.py#L59-L65) and refresh it periodically. Searching a project was then always done on the client-side. I see that the Raycast gitlab extension has a [cache.ts](https://github.com/raycast/extensions/blob/main/extensions/gitlab/src/cache.ts) too.

In #14316 I added a project-membership dropdown to only search in projects you are assigned to (instead of all public gitlab projects), so for that use-case it could make sense to keep a local cache and search inside the cache instead of invoking an http call to the Projects API on each search query change... We have 500+ projects; it was way more performant with client-side filtering (alfred) than waiting for http calls to resolve, so I would be happy to see some experiments regarding this 👌

**Comment by macbookandrew** [comment]
Caching would be great!

**Comment by jfkisafk** [comment]
Does loading large number of projects not open this extension to [JS heap memory issues](https://github.com/raycast/extensions/issues/10127#issuecomment-2104485073) for large workspaces? We can perform client-side filtering but keeping all those resources in memory/cache will come with risks (that are currently not present with server-side filtering).

PS: Not shooting down the idea, just indicating that if we release this feature, we might need to do it behind feature flag to not break existing large customers.

**Comment by macbookandrew** [comment]
I recalled some previous discussion about server-side vs. client-side caching: https://github.com/raycast/extensions/pull/10372#issuecomment-1915597316

I believe the “My Groups” and “My Projects” commands do pull all of the groups/projects, cache them, and use client-side filtering; the “Search Groups” and “Search Projects” commands include the search term in the API request, so use server-side filtering.

Unsure about the other “My” vs. “Search“ commands without doing some digging, but @meesvandongen you might get better performance using the “My” commands instead of “Search”?

**Comment by meesvandongen** [comment]
I did some testing and I can see the problem now; getting a single page (100 results) from gitlab.com takes around 5-10 seconds. And I need quite some pages. Building this cache after opening the "My Projects" page takes too long to be useable (in fact I do not get any results at all in the UI).
I compared it with the graphql API and it seems this one takes around 2-3 seconds per page, so this could be an option.

If you combine the graphql API to get the total project count and feed this into the rest api with the offset-based pagination, you can probably get as much as the rate limit allows; in a test I was able to get 1100 projects in 9 seconds, which seems like a fine UX if it is fast after this.

**Comment by alliecatowo** [comment]
I wish this hadn't been closed! 

I was thinking in the extension config, you could select which projects you want to be indexed, or atleast groups. 

I'd imagine it's pretty common to be included in numerous groups for their organizations gitlab. One group may be a general developers group, with a bunch of junk repos, stubs, unrelated internal tools, etc. But the user may be in a more focused group/subgroup, which is where the majority of their current workflow takes place. If you're in a large organization, there may be thousands of projects you have access too, especially if you're in an admin position.

The solution would be relatively simple, the user can configure the gitlab extension to always filter that subgroup or list of repos in its server side requests, and bypass the issues with client side filtering / caching. This could even be a command from within the extension, so you can quickly adjust which projects and groups you're actively working with. 

And if you need to quickly access a project without editing your filter settings, a command + k option could allow a "query all" functionality or something similar. 

I have alot on my plate, but if anyones interested in this feature, I'd be down to collaborate!
