### ISSUE TITLE
[Everhour] Support starting and stopping timer with free text

### ISSUE THREAD

**Issue by RobertCraigie** [raycast/extensions#14649]
### Extension

https://www.raycast.com/farisaziz12/everhour

### Description

It looks like you can currently only start a timer for existing tasks, I'd love to be able to just start a timer with any arbitrary text.

### Anything else?

This is currently supported in the Everhour chrome extension:
<img width="683" alt="Screenshot 2024-09-24 at 17 58 44" src="https://github.com/user-attachments/assets/92f561fb-76ad-46f7-9d8e-a7193e3e9170">

**Comment by xmok** [comment]
The way the extension is currently structured, it's pretty task-dependent but I 100% get the logic behind being able to start a timer with arbitrary text. The issue is though you may be able to start/stop timers without tasks, they will not show up in the extension as it filters out timers w/o tasks.

So there are 2 separate matters:
1) start/stop current timer w/o task (optionally start with a comment)
2) view timers w/o tasks assigned

What we could do for now is create a new command `Current Timer` - this would be a `no-view` command and we could use that to start/stop CURRENT timers. This would solve matter 1️⃣ and we can later on modify the other commands to show timers w/o tasks or something which might be a little more work.

Does that sound like a good approach for now @RobertCraigie?

i.e. to clarify: for now I propose adding a new `Current Timer` command that will simply start/stop and show the current timer which is always ONE according to the API.

**Comment by xmok** [comment]
@raycastbot assign me
