### ISSUE TITLE
[Browser Tabs] Not able to search for Firefox tabs

### ISSUE THREAD

**Issue by qstrnd** [raycast/extensions#14641]
### Extension

https://www.raycast.com/koinzhang/browser-tabs

### Raycast Version

1.83.1

### macOS Version

Sequoia 15.0

### Description

Firefox version 130.0.1 (64-bit)

The extension is supposed to search through all the tabs but I'm able to see only the tabs from Safari

### Steps To Reproduce

1. Open extension
2. See no tabs from Firefox. Searching doesn't give any result as well

**Comment by qstrnd** [comment]
Probably a duplicate of https://github.com/raycast/extensions/issues/11920

But my issue is not related to profile naming (it's `default-release` on `about:profiles`)

**Comment by koinzhang** [comment]
Sorry, the extension can't get Firefox's tabs because Firefox doesn't provide an interface to get all Tabs.

The browsers supported by this extension are indicated on the [README](https://www.raycast.com/koinzhang/browser-tabs#readme) page.

<img width="543" alt="image" src="https://github.com/user-attachments/assets/43dbaeb7-1a50-42ef-8ad9-bb52d6e15ebe">

@raycastbot close as not planned
