### ISSUE TITLE
[Spotify Player] Connect to a Device

### ISSUE THREAD

**Issue by timcastillogill** [raycast/extensions#1479]
# Extension – [Spotify Player](https://github.com/raycast/extensions/tree/317b7f140dfc4a304317e5bde1408221e0777e30/extensions/spotify-player/)
Author: @mattisssa

**Describe the feature and the current behavior/state.**

I would love to be able to choose a connected device - that is the online speakers available on your wifi network to connect to via the `connect to a device` menu. The button to do this via Spotify is located right next to the Spotify Volume rocker.

**Who will benefit with this feature?**

Anyone who uses a connected/smart speaker to listen to music via Spotify.

**Any Other info.**

It looks as if this API endpoint in in Beta but details can be found [HERE](https://developer.spotify.com/documentation/web-api/guides/using-connect-web-api/)

**Comment by mattisssa** [comment]
Hey @andreaselia and @timcastillogill! I just have reached the issue and realised that it wouldn't be possible to implement once my #1766 PR merged because the developer app on the Spotify side doesn't have a proper scope for the feature 🙈 
And their review team is pretty weird about updating these developer apps; it shows to me that I cannot request new scopes for a while.

**Comment by andreaselia** [comment]
Awh, that's unfortunate. I wonder if contacting them, they'd make an exception to the delay between updating the scopes of the app? 😅 

Alternatively, I guess anyone can create one of these developer apps for approval and PR an update to the client ID/scope, alongside this feature, right? Or would you want to avoid anyone having that sort of control over the Spotify Player extensions functionality? 🤔

**Comment by mattisssa** [comment]
>I wonder if contacting them, they'd make an exception to the delay between updating the scopes of the app

I have tried to contact them and ask about it, but they just keep ignoring me, and there was no response from the Spotify team 🤦 

>Alternatively, I guess anyone can create one of these developer apps for approval and PR an update to the client ID/scope, alongside this feature, right

Yes, but it ruins all the advantages of installing the extension and don't worry about anything. Before the update, you had to go to the Spotify developer page, create developer app, update secrets in the Raycast Spotify extension, it's pretty hard.

>Or would you want to avoid anyone having that sort of control over the Spotify Player extensions functionality

If I correctly understand the question, is it about the Spotify's Devices control? Or having another Spotiy extension in the store?

**Comment by andreaselia** [comment]
Ah I see, that sucks that they aren't being responsive 😬 

That's true, I understand, but I mean more so that someone else could create the Spotify app with the extra scopes required, and then put that app token into the extension, but I guess we can wait for your app to be updated (however long that may be).

I mean pretty much as per the above, another can create their own Spotify app and update the extension to use their app token, but then if someone did it and deleted their app, then the extension would stop working, so I guess it has to be from a reliable source (hopefully this makes sense).
