### ISSUE TITLE
[Keyboard Shortcut Sequences] Not authorized to send Apple events to System Events

### ISSUE THREAD

**Issue by 5HT2** [raycast/extensions#14810]
### Extension

https://www.raycast.com/HelloImSteven/keyboard-shortcut-sequences

### Raycast Version

1.83.2

### macOS Version

14.6.1

#### Error:
```
Error: Command failed with exit code 1: osascript -e tell application "Google Chrome"
            tell application "System Events"
                keystroke "64" using [control down, option down, shift down, command down]
            end tell
        end tell 
76:169: execution error: Not authorized to send Apple events to System Events. (-1743)

            tell application "System Events"
                keystroke "64" using [control down, option down, shift down, command down]
            end tell
        end tell 

```

### Steps To Reproduce

1. Create sequence:
```json
{
  "name": "Spotlight",
  "description": "",
  "icon": "magnifying-glass-16",
  "shortcuts": [
    {
      "keystrokes": "64",
      "modifiers": [
        "control down",
        "option down",
        "shift down",
        "command down"
      ]
    }
  ]
}
```

2. Attempt to run sequence from GUI

### Current Behaviour

<img width="750" alt="Screenshot 2024-10-06 at 18 50 22" src="https://github.com/user-attachments/assets/304b87d0-351c-43fb-aab7-03f37cc9527e">

### Expected Behaviour

<img width="600" alt="Screenshot 2024-10-06 at 18 50 33" src="https://github.com/user-attachments/assets/608f0320-e28f-491c-a064-b64082fe49e3">

**Comment by 5HT2** [comment]
This has not been resolved, @SKaplanOfficial if you are not maintaining this extension at all, would you be open to changing over the CODEOWNERS to my account and I would be happy to fix this issue + respond to bug reports for this extension?

**Comment by SKaplanOfficial** [comment]
Responded via email regarding the CODEOWNERs part.

**For others running into the issue with System Events described above:**
Please check whether System Events enabled under System Settings->Privacy & Security->Automation->Raycast. If it's not, please enable it and retry the shortcut sequence. The extension needs this permission in order to simulate keystrokes without requesting permission on an app-by-app basis. I have an in-progress update which provides help dialogs that indicate this more clearly. If that setting is not the problem, please add a comment here or open a new issue. Thanks!
