### ISSUE TITLE
[Migadu] Shortcut to create random identities, similar to Apple's "Hide My Email"

### ISSUE THREAD

**Issue by LBBO** [raycast/extensions#14890]
### Extension

https://www.raycast.com/xmok/migadu

### Description

Apple has a "Hide My Email" feature that will generate a random, unique email that you can use to sign up for random services. Using Migadu's API and Identities, a similar functionality could be implemented without the dependency on Apple.

To this end, it would be useful to have a command that basically just takes the name of the identity you want to create (which would probably end up being the name of the service you're generating the email for) and then creates the identity and copies the new email address to your clipboard. I would suggest a dropdown that allows you to change the mailbox for which the identity is created, but I think it should be pre-populated with a pre-selected default mailbox. It might also be cool to allow for customization of the created identity, i.e. having an input that's prefilled with a random and unique email address.

### Who will benefit from this feature?

Any migadu user who would like to use "Hide My Email", but without depending on Apple.

### Anything else?

I'd be happy to implement this myself! All I need is the go-ahead that this feature would be appreciated. I've started looking into the code and saw that queries are currently handled via vanilla fetch. Would you mind if I migrate them to [TanStack Query](https://tanstack.com/query/latest)? This would remove the need for a manually managed `isLoading` state and enable some useful things in the future. [Other extensions seem to also use this library](https://github.com/search?q=repo:raycast/extensions%20@tanstack/react-query&type=code), so I'm optimistic it won't cause any significant issues.

**Comment by xmok** [comment]
Sounds like a great idea. It's something that's actually in my backlog so I'd definitely appreciate you implementing it.

The [ImprovMX](https://www.raycast.com/ImprovMX/improvmx) extension does something similar in case you need inspiration.

There's no need for TanStack since Raycast Utils has a number of useful [React Hooks](https://developers.raycast.com/utilities/react-hooks). You could wrap the current calls in [useCachedPromise](https://developers.raycast.com/utilities/react-hooks/usecachedpromise) or you could move it all to [useFetch](https://developers.raycast.com/utilities/react-hooks/usefetch); the latter will allow you to remove the `node-fetch` dependency entirely.

Please let me know if you need further guidance.

Assigning the issue to you 🫡.
