### ISSUE TITLE
Does not detect new songs in playlist

### ISSUE THREAD

**Issue by elikyaB** [raycast/extensions#14964]
### Description

Raycast: 1.84.3
MacOS: Sequoia 15.0

### Steps To Reproduce

1. Add new song to existing playlist.
2. Attempt to use Your Library > Command+K on [playlist] > Show Songs > type name of song

### Current Behaviour

Cannot select newly added songs.

### Expected Behaviour

Background sync checks with spotify api when selecting a playlist at least.

**Comment by mathieudutour** [comment]
Seems like this issue is about a specific extension, not the API. Would you mind opening a new issue using the [correct template](https://github.com/raycast/extensions/issues/new?assignees=&labels=extension%2Cbug&projects=&template=extension_bug_report.yml&title=%5BExtension+Name%5D+...) so that the authors of the extension are properly aware of it?
