### ISSUE TITLE
[YouTube Music] ...

### ISSUE THREAD

**Issue by edmarshallio** [raycast/extensions#15056]
### Extension

https://www.raycast.com/danieldbird/youtube-music

### Raycast Version

1.84.3

### macOS Version

15.0 (24A335)

### Description

Youtube music extension does not work, no commands do anything at all. Using Zen Browser a fork of FireFox. 

### Steps To Reproduce

1. On mac Sequioa 15 2. Install extension 3. Link to Zen Browser 4. Try any command

### Current Behaviour

No behaviour at all

### Expected Behaviour

Any command

**Comment by gnosticdev** [comment]
The extension uses a series of AppleScripts to communicate with the browser. So you need to allow JavaScript from AppleEvents in Zen.Not sure where that would be in Zen, but if it has a developer menu I would start there. Otherwise should be able to find in their docs. Jesse Greer(410)953-9525On Oct 23, 2024, at 1:08 PM, raycastbot ***@***.***> wrote:﻿
Thank you for opening this issue!
🔔 @danieldbird @AlexStrNik @zach-fuller @gnosticdev you might want to have a look.

💡 Author and Contributors commands
The author and contributors of danieldbird/youtube-music can trigger bot actions by commenting:

@raycastbot close this issue Closes the issue.
@raycastbot close as not planned Closes the issue as not planned.
@raycastbot rename this issue to "Awesome new title" Renames the issue.
@raycastbot reopen this issue Reopens the issue.
@raycastbot assign me Assigns yourself to the issue.
@raycastbot good first issue Adds the "Good first issue" label to the issue.
@raycastbot keep this issue open Make sure the issue won't go stale and will be kept open by the bot.
