### ISSUE TITLE
[Apple Notes] Add support for quicklinks to specific notes in Apple Notes

### ISSUE THREAD

**Issue by reinerschristopher** [raycast/extensions#15131]
### Extension

https://www.raycast.com/raycast/apple-notes

### Description

Currently:
- Users can add text to notes using the "add text to note" command
- Each time, the target note needs to be manually selected
- No way to create shortcuts/quicklinks to frequently used notes

Requested Feature:
- Ability to create quicklinks that add selected text to a specific pre-defined note
- Example use case: Creating a quicklink "add to braindump" that automatically adds selected text to a note titled "Braindump"

Technical Details:
- Current quicklink format doesn't support note specification:
  `raycast://extensions/raycast/apple-notes/add-text?fallbackText={selection | raw}`
- Need parameter support for targeting specific notes

Use Cases:
- Quick capture of ideas to specific notebooks
- Streamlined workflow for collecting information in designated notes
- Reducing friction in note-taking process

### Who will benefit from this feature?

People using apple notes frequently.

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? If yes, here's our [guide on extension contributions](https://developers.raycast.com/basics/contribute-to-an-extension) so that you can open up a pull request. Feel free to contact me here or in the [Slack community](https://raycast.com/community) if you need further help.
