### ISSUE TITLE
[Browser Bookmarks] Support for Zen Browser

### ISSUE THREAD

**Issue by theherk** [raycast/extensions#15130]
### Extension

https://www.raycast.com/raycast/browser-bookmarks

### Description

Should probably support [Zen Browser](https://zen-browser.app/). I don't think it will be that difficult to mimic the behavior of the forked Firefox implementation.

### Who will benefit from this feature?

Users of the Zen Browser.

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? If yes, here's our [guide on extension contributions](https://developers.raycast.com/basics/contribute-to-an-extension) so that you can open up a pull request. Feel free to contact me here or in the [Slack community](https://raycast.com/community) if you need further help.

**Comment by theherk** [comment]
I may. The zen extension is currently working well, but for posterity I might work on this too.

**Comment by nicoandmee** [comment]
I would also like this.
