### ISSUE TITLE
[Apple Reminders] Weekdays options for recurring reminders

### ISSUE THREAD

**Issue by guspimentel** [raycast/extensions#15180]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

Sometimes I need to create a recurring reminders only for weekdays, but it's not currently possible on the `Create Reminder` command. When I need to do so, I use the Reminders app where it's possible, not only weekdays reoccurrences, but also set hourly, weekends and other options for recurring reminders.

### Who will benefit from this feature?

Everyone

### Anything else?

The current options
![image](https://github.com/user-attachments/assets/50a85af9-cdbb-468e-9f28-2e7002238477)

---

In green 🟢, the options I think it could be added to the extension. In blue 🔵, what already can be done in the extension.

![image](https://github.com/user-attachments/assets/4c260867-d0cc-43f7-8ca4-2bde774d53c7)

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? If yes, here's our [guide on extension contributions](https://developers.raycast.com/basics/contribute-to-an-extension) so that you can open up a pull request. Feel free to contact me here or in the [Slack community](https://raycast.com/community) if you need further help.
