### ISSUE TITLE
Widen search in Lastpass extension

### ISSUE THREAD

**Issue by moseisleydk** [raycast/extensions#15186]
### Description

The Lastpass extension does not search in the username field, that would by appriciated to support, besides name.

Also the URL field was be nice, but I am really missing the "username" search

### Who will benefit from this feature?

Everyone, when switching from the now uselass old native MacOS Client, that does search in "username"

### Anything else?

Also the URL field was be nice, - most fields actually but I am really missing the "username" search

Also the possibiblity to refresh every hour, insted of "always" or "daily"

**Comment by mathieudutour** [comment]
Seems like this issue is about a specific extension, not the API. Would you mind opening a new issue using the [correct template](https://github.com/raycast/extensions/issues/new?assignees=&labels=extension%2Cbug&projects=&template=extension_bug_report.yml&title=%5BExtension+Name%5D+...) so that the authors of the extension are properly aware of it?
