### ISSUE TITLE
[Jira Time Tracking] Filter by Assigned to me

### ISSUE THREAD

**Issue by louisdb03** [raycast/extensions#15238]
### Extension

https://www.raycast.com/niallpaterson/jira-time-tracking

### Description

At the moment when I try using this I get the full list of all Jira tickets from within my organisation. This is massive and I cannot really find my tickets easily.

 Could it be possible to add like a setting to only show tickets assigned to me?

**Comment by haydencbarnes** [comment]
@louisdb03 if we allowed you to set a custom SQL via preferences you could set it yourself to only show tickets assigned to you. Would that work?

**Comment by haydencbarnes** [comment]
@raycastbot assign me

**Comment by louisdb03** [comment]
@haydencbarnes I could try. If I can find the DB schema of Jira somewhere, I'll probably figure it out.

**Comment by haydencbarnes** [comment]
@louisdb03 okay, the basics are here:
https://support.atlassian.com/jira-service-management-cloud/docs/use-advanced-search-with-jira-query-language-jql/

I will work on this at some point this week and get an update out soon

**Comment by haydencbarnes** [comment]
@louisdb03 Since not everyone knows JQL, I just added it as a separate preference, for now, to make it as easy as possible to set. If it is decided/requested, we need to be able to edit the actual JQL, and I can make another PR for this. Sorry, it took me a week longer than expected. Here is the PR: https://github.com/raycast/extensions/pull/15568

**Comment by haydencbarnes** [comment]
@raycastbot close this issue
