### ISSUE TITLE
[Surf Check] option to change units to metric

### ISSUE THREAD

**Issue by droemmelbert** [raycast/extensions#15451]
### Extension

https://www.raycast.com/john_alexander/surf-check

### Description

It would be awesome if we could add an option to change measurements to metric (temperature in °C, wave height in m, wind in km/h or m/s etc)

Maybe these options could also be mixed and matched. 

I would also be happy to help with coding myself

**Comment by johnalxndr** [comment]
@raycastbot assign to me

**Comment by johnalxndr** [comment]
@droemmelbert makes sense. thanks for flagging.  should have this up next week

**Comment by johnalxndr** [comment]
@raycastbot assign me

**Comment by johnalxndr** [comment]
@droemmelbert this just went up. let me know what you think!

**Comment by droemmelbert** [comment]
![CleanShot 2024-12-02 at 18 02 04](https://github.com/user-attachments/assets/bce6d3a4-c9e5-4286-896e-345734df9c5b)

Thanks for your work! Couple of things seem off here:

1. Current wave height not calculated correctly
2. Water Temperature not calculated correctly
3. Tide height not calculated correctly
4. Tide Time is off by 1 hour in this example.

My guess where these issues come from:
1.-3. I am guessing that depending on where the api request is sent from, Surfline automatically changes units to match the countries preference (API request from the US -> wave height in ft, API request from Europe -> wave height in m).
4. My API request is sent from a different time zone which probably needs to be considered when calculating the tide times.

Happy to answer questions as they arise!

**Comment by johnalxndr** [comment]
for the wave height discrepancy, can you check your Surfline settings to see if you have 'traditional' height checked? Im able to replicate an issue if traditional is selected. looks like the default response from the api cal im using returns it in "Face height" so that could the be problem. 

![CleanShot 2024-12-06 at 12 53 26@2x](https://github.com/user-attachments/assets/2e408b31-0902-4b7c-9f8a-010d04cf88bc)

I've got some ideas after looking into other accessible api endpoints that allow unit params but with no official api docs it's a bit of trial and error. might take me some time. 

but feel free to contribute if you'd like!
