### ISSUE TITLE
[Linear] ... Add "Copy URL" to options after successful issue creation

### ISSUE THREAD

**Issue by clintmiller** [raycast/extensions#15490]
### Extension

https://www.raycast.com/linear/linear

### Description

It would be helpful to add a 3rd option to the set of actions you can take after creating a Linear issue. Currently, you can
 - Open Issue (Cmd+Shift+O)
 - Copy Issue ID (Cmd+Shift+C)

I would like to add "Copy Issue URL" (Cmd+Shift+U ?) to the list of options.

**Comment by jfkisafk** [comment]
Toasts only support two actions (Primary and Secondary), so we cannot add more actions. Fortunately, if you find yourself just copying issue URL instead of ID, please change the preferences for "Create Issue" to change the secondary toast action:

![Screenshot 2024-11-28 at 5 15 29 PM](https://github.com/user-attachments/assets/4da4d5b5-fc94-4f7c-a371-885354581a07)

You will then be able to use _Cmd + Shift + C_ to copy issue URL directly. Closing this issue as it has already been addressed.

**Comment by jfkisafk** [comment]
@raycastbot close this issue
