### ISSUE TITLE
Custom Search Engine in Extension Settings

### ISSUE THREAD

**Issue by uzairansaruzi** [raycast/extensions#15512]
### Description

When using the 'Open New Little Arc Window", there are only a few select search engines to pick from. I personally use Brave and know many people that use search engines, not in the predefined list. It would be awesome to be able to use custom search engine queries here.

![SCR-20241124-nyxe](https://github.com/user-attachments/assets/bce8db82-57b6-49e6-a38e-bc23b3bb97f8)

**Comment by mathieudutour** [comment]
Seems like this issue is about a specific extension, not the API. Would you mind opening a new issue using the [correct template](https://github.com/raycast/extensions/issues/new?assignees=&labels=extension%2Cbug&projects=&template=extension_bug_report.yml&title=%5BExtension+Name%5D+...) so that the authors of the extension are properly aware of it?
