### ISSUE TITLE
Lastpass 2FA support 

### ISSUE THREAD

**Issue by csolje** [raycast/extensions#15601]
### Description

In the extensions description it is stated the due to lastpass-cli does not support 2FA the lastpass extension does not support it also, 
but I have downloaded the lastpass-cli and it supports 2FA really good now and I would like for this extension to support it too

### Who will benefit from this feature?

Everyone who wishes to use Lastpass with 2FA and it makes this extension more future proof and will live up to the roadmap of lastpass.

**Comment by mathieudutour** [comment]
Seems like this issue is about a specific extension, not the API. Would you mind opening a new issue using the [correct template](https://github.com/raycast/extensions/issues/new?assignees=&labels=extension%2Cbug&projects=&template=extension_bug_report.yml&title=%5BExtension+Name%5D+...) so that the authors of the extension are properly aware of it?
