### ISSUE TITLE
getSelectedText function changes clipboard

### ISSUE THREAD

**Issue by aleksey925** [raycast/extensions#15756]
### Description

Good afternoon, I encountered an unpleasant bug when calling getSelectedText that changes the content of the clipboard. This is clearly noticeable if you try to receive user data for processing in the extension either through text selection or through the clipboard.

Simple extension that can help reproduce this bug https://github.com/aleksey925/raycast-get-selected-text-bug.

### Steps To Reproduce

1. Copy any text to clipboard.
2. Open any file in sublime text or pycharm.
3. Move the cursor to any empty line or place the cursor near any text.
4. Open raycast and run extension.
5. Paste anywhere in the content of the clipboard; there will be an empty line instead of your content or any text that was next to the cursor in the line.

### Current Behaviour

Call of the getSelectedText function changes the content of the clipboard.

### Expected Behaviour

Clipboard content doesn't change.

**Comment by LitoMore** [comment]
I can reproduce the bug with the `Selected Text to Say` command of https://raycast.com/litomore/say.

**Comment by aleksey925** [comment]
Did you try to reproduce it with extension that i made as example?

**Comment by mathieudutour** [comment]
Yeah the heuristic of the `getSelectedText` is to try to use accessibilities APIs but if it can't, it'll try to send a copy command to get the selection. We found that some apps don't behave nicely and we have workaround that with the clipboard :/ 

Not much we can do here...

**Comment by abed-daloopa** [comment]
>  it'll try to send a copy command to get the selection

@mathieudutour Do you add a delay after sending the `cmd+c` command before reading the clipboard?

From my experiments (just trial and error), I found that approximately 200 ms is needed after the command executes before reading the clipboard content. Otherwise, you risk reading the wrong clipboard entry, the one that existed before the command executed.

It's obvious this is happening and is affecting a lot of people. See https://github.com/raycast/extensions/issues/18289

Could the `getSelectedText` API perhaps accept a `delay (ms)` option? 

Please consider this, as `getSelectedText` currently is kinda broken.
