### ISSUE TITLE
[Ollama AI] Highlight Changes

### ISSUE THREAD

**Issue by martindisley** [raycast/extensions#15826]
### Extension

https://www.raycast.com/massimiliano_pasquini/raycast-ollama

### Description

Raycast AI's 'Fix Spelling and Grammar' is probably my most used AI command. I would love to run this locally instead of sending all my unfinished text to the cloud and I was hoping that the Ollama extension would be a direct replacement for this. However, it was immediately apparent how crucial 'highlight changes' is to the utility of Raycast's version. It would be brilliant if 'highlight changes' could be implemented in Ollama.

### Who will benefit from this feature?

Anyone who would like to use a local model for minor text editing.

**Comment by MassimilianoPasquini97** [comment]
Hi @martindisley,
All predefined commands are quite generic, designed to work well enough with most available models. This was necessary because the extension provide full control over the model.

If you need a specific "Fix Spelling and Grammar" tailored on your needs, you can use the "Create Custom Command" command where you can create you custom command where you can chose your prompt.

**Comment by MassimilianoPasquini97** [comment]
@raycastbot assign me

**Comment by MassimilianoPasquini97** [comment]
@raycastbot close this issue
