### ISSUE TITLE
[Toothpick] Make it easier to differentiate connected devices

### ISSUE THREAD

**Issue by felixludwig1** [raycast/extensions#1590]
# Extension – [Toothpick](https://github.com/raycast/extensions/tree/e01d203db555e65ec3ee2d1c62e679a756f3d06b/extensions/toothpick/)
Author: @briankosw

Hey there, nice extension! Exactly what I was looking for!

The only problem for me is, that I'm having a hard time differentiating the connected devices, as the icons are all looking the same and the colour-difference is somewhat low. Could be way easier to spot them with different icons, brighter colors or something. Maybe a text aligned to the right saying "connected"? 
Also it would make sense to show the connected devices on the top, like when you open the Bluetooth Menu from the Control Center!

Thanks in advance! :) 

![Screenshot 2022-05-04 at 18 10 46](https://user-images.githubusercontent.com/97047348/166724310-c5b49dc5-5e16-43e7-a531-d9442e395734.png)

**Comment by briankosw** [comment]
Hey @felixludwig1, glad you're enjoying the extension! I think you're right on both points, so I'll create a PR soon to address both points.

**Comment by briankosw** [comment]
Hi @felixludwig1, I've changed the icons so that the icon for the connected devices is brighter and the icons were enlarged. The improvements definitely help me better distinguish the two statuses, but let me know how you feel.

This is the previous version:
![_on](https://user-images.githubusercontent.com/10988056/167868651-6ff9343a-3976-4d1a-85a8-92bf28736a14.png)

This is the new version:
![on](https://user-images.githubusercontent.com/10988056/167868727-aa82411a-b696-4c42-9812-80598d5283a2.png)

**Comment by felixludwig1** [comment]
Hey, thanks for reaching out for my feedback!

I like the direction where this is going, but would definitely combine this
with some other changes, like ordering, grouping and additional labels.

What do you say to this quick idea?
Felix
