### ISSUE TITLE
switch windows of current application

### ISSUE THREAD

**Issue by dima-m711** [raycast/extensions#1688]
# Extension – Navigation -> Switch Windows

I would like to request a feature for this existing internal extension for switching windows, adding another command that will allow switching between only windows that belong to the currently focused application.

**Describe the feature and the current behavior/state.**
Should act exactly the same as the current Switch Window command, but the list will filter all windows except for windows that belong to the current focused application

**Who will benefit from this feature?**
Quick switching between the same type of app

**Any Other info.**
should act similar command + ~ of OSX.

**Comment by cmenginnz** [comment]
@dima-m711   This feature must be the first one on my wish list. I need to switch between multiple windows of the current application hundreds of times every day. This feature definitely will make my life better. 

Alternatively, instead of adding a new command, it may be easier to place the windows of the current application at the top of the windows list.

**Comment by CanRau** [comment]
Would also love that 🙌🏼 

Pinging you @peduarte as I found couple of closed issues because the @raycastbot couldn't identify built-in extensions 😬 But maybe you'd expect feedback for built-ins in Slack and/or elsewhere?

Also `Switch Windows` is pretty slow maybe some form of caching could help or could be improved?
