### ISSUE TITLE
[Twitter] ...Schedule tweet

### ISSUE THREAD

**Issue by mkandan** [raycast/extensions#1726]
# Extension – [Twitter](https://github.com/raycast/extensions/tree/c3b6c2ff6eef5f9026337d975820079b03274ec1/extensions/twitter/)
Author: @tonka3000 

Schedule tweet using https://developer.twitter.com/en/docs/twitter-ads-api/creatives/guides/scheduled-tweets-guide

**Describe the feature and the current behavior/state.**
Right below the character (out of 280) box, include the option to schedule a tweet for later posting.

**Who will benefit with this feature?**
Power users. A lot of raycast users are already productivity users/enthusiasts. We don't like spending more time than we have to on twitter. A lot of them (like myself) like to schedule tweets so we can minimize time on Twitter.

**Any Other info.**
Love all that you do Michael! Great stuff :)

**Comment by tonka3000** [comment]
@mkandan , that is a great idea.

It seems that the feature would is a good fit for the v2 version of my Twitter extension (still a draft #1629, based on the v2 API Version of Twitter, not v1), because I think that I need login with Twitter (OAuth) to be able to use that, which is not available in v1. Twitter mention that the ad API will only be granted for one API key per company, so getting #1629 before impl. that feature seems to be the way to go.

Do you have experience with the endpoint you mentioned? Especially with the auth part?
