### ISSUE TITLE
[heroku] Adding logs

### ISSUE THREAD

**Issue by frbuccoliero** [raycast/extensions#1801]
Hi! I'm new to Raycast. It's great!
I would like to suggest a little feature to add to the "Heroku" plugin, I would like to quickly check the logs for my apps. Is this possible? Thanks a lot :)

**Comment by mattisssa** [comment]
Hey! Since it doesn't related to the API, I'll close the issue. Can I please ask you to open a new one but with [the right template](https://github.com/raycast/extensions/issues/new?assignees=&labels=extension%2C+feature+request&template=extension_feature_request.md&title=)? 

To avoid filling the data about the extension it could be easier to create templates through the feedback actions that you can find in a root search or in the store for the extension 😉 

![CleanShot 2022-06-09 at 23 33 54@2x](https://user-images.githubusercontent.com/15333662/172956429-20b2c5fc-e0b5-468b-b8ff-68cd63c6637b.png)
![CleanShot 2022-06-09 at 23 34 05@2x](https://user-images.githubusercontent.com/15333662/172956473-2027744a-f411-4362-8184-f3cdb0bf91f7.png)
