### ISSUE TITLE
[Google Drive] ... 

### ISSUE THREAD

**Issue by Anshuljkt** [raycast/extensions#1855]
# Extension – [Google Drive](https://github.com/raycast/extensions/tree/1655e5205d460085b88656682dd9ce9f099c928c/extensions/google-drive/)
Author: @vishaltelangre

## Description
Google Drive folder search broken, always crashes when attempting to access search results.

## Error:
```
Error: ENOENT: no such file or directory, stat  '....REDACTED..../Insurance May 2022-1.jpg'

statSync:node:fs:1536:3
Nl:index.js:6:10098
processTicksAndRejections:task_queues:96:5
```

## Steps To Reproduce

1. Search for a file, attempt to look through results...
2. ends up broken

### Raycast version
Version: 1.35.2

**Comment by vishaltelangre** [comment]
@Anshuljkt Thanks a lot for the report. But unfortunately, I am unable to reproduce this error. If you are running this extension from the [source](https://github.com/raycast/extensions/tree/1655e5205d460085b88656682dd9ce9f099c928c/extensions/google-drive/), can you please post the exact backtrace from the terminal since it is not clear where exactly it is crashing from the error above? BTW, if you're on Slack, ping me so we can debug + fix it further. Thanks!
