### ISSUE TITLE
[File Manager] ... Copy and Move Files

### ISSUE THREAD

**Issue by spsisys** [raycast/extensions#1990]
# Extension – [File Manager](https://github.com/raycast/extensions/tree/738baf4329423ed4ec1d1dcf78451a175db42ecd/extensions/file-manager/)
Author:

**Describe the feature and the current behavior/state.**

**Who will benefit with this feature?**

**Any Other info.**

**Comment by koinzhang** [comment]
Hi @spsisys. Given that the developers have said he will not update this extension (because he thinks the built-in File Search can already replace this extension), you can try the [Common Directory](https://github.com/koinzhang/common-directory) extension, one of the commands is Send File to Directory.
Also unfortunately, due to API limitations, any extensions for moving and copying files now cannot pass the official review, so the full version of Common Directory can only be installed locally.
