### ISSUE TITLE
[Clockify] Invalid API key error

### ISSUE THREAD

**Issue by honzapav** [raycast/extensions#2173]
# Extension – [Clockify](https://github.com/raycast/extensions/tree/baa9c7891b5876e62d9af4453d73498f6655bf07/extensions/clockify/)
Author: @isma

## Description
Hi I am getting problem with Clockify Raycast extension – even though I set up the API key multiple times, I still got an error.

![Screenshot 2022-07-03 at 13 19 44](https://user-images.githubusercontent.com/9762266/177037168-c0194ee2-e405-4942-9418-a16ca2d3b5ec.png)

### Raycast version
1.37.1

**Comment by GWillmann** [comment]
This can happen if your API was generated a long time ago because its format has changed. Try regenerating it, it worked for me.

**Comment by honzapav** [comment]
@GWillmann hello, thank you! This works for me! 👏

**Comment by Joren-Thijs-KasparSolutions** [comment]
For anyone alse running into this. I got this Error because I selected the EU zone instead of just the global one.
The different zones point to different url's in the code. And it seems they don't share authentication.  See https://github.com/raycast/extensions/blob/1591d98210aed469e4f1316e7d697fbf45494004/extensions/clockify/src/utils.ts#L6-L21
