### ISSUE TITLE
[Unicode Symbols Search] find super script with number input

### ISSUE THREAD

**Issue by lukasoppermann** [raycast/extensions#2240]
# Extension – [Unicode Symbols Search](https://github.com/raycast/extensions/tree/d18a6e43408d105a3ed7a17b6693fca19ea75ea3/extensions/unicode-symbols/)
Author: @mmazzarolo

I would love to be able to get a superscript number by entering something like `super 9` -> ⁹

**Describe the feature and the current behavior/state.**
Currently it does not find the superscript item when I enter `super 9`. I have to type `super nine`.

It would be easier to use if it could just work with both, the numeric (9) value and the word (9).
Same should work for subscript.

**Who will benefit with this feature?**
Anybody using this to get super script numbers or subscript.

**Comment by danielsequeira** [comment]
@FezVrasta FYI

**Comment by danielsequeira** [comment]
@mmazzarolo fyi

**Comment by lukasoppermann** [comment]
Hey @mmazzarolo @danielsequeira I think all that is required is to add the number to the name in the dataset json file: https://github.com/raycast/extensions/blob/d18a6e43408d105a3ed7a17b6693fca19ea75ea3/extensions/unicode-symbols/assets/dataset.json#L4803

Happy to send a PR if it will be merged.

**Comment by lukasoppermann** [comment]
That is even better. How would we go about adding this though?

**Comment by mmazzarolo** [comment]
> @mmazzarolo That is even better. How would we go about adding this though?

OK, I started writing something and then I changed my mind 😬 

## Easiest way to implement this

- In the [`generate-dataset.ts`](https://github.com/raycast/extensions/blob/main/extensions/unicode-symbols/scripts/generate-dataset.ts) script, add a something something like `const charCodeToAliases = {"8313": ["superscript 9"]}`. This will be the list of aliases we want to apply to the final dataset. I think it might even be better to define it in its own json file. 
- Update [`mapCharacterToDatasetItem`](https://github.com/raycast/extensions/blob/dcce8fde80a4b1b87d0d5794679a18f32402d1ea/extensions/unicode-symbols/scripts/generate-dataset.ts#L75-L77) to also add the `aliases` to the output (if any). 
- In the [`src/dataset-manager.ts`](https://github.com/raycast/extensions/blob/dcce8fde80a4b1b87d0d5794679a18f32402d1ea/extensions/unicode-symbols/src/dataset-manager.ts#L26), update the Fuse search to also search in `aliases` (just add it to the `key` array). 

I think this is the easiest (and most performant) way to implement this. 

Drawback of this approach:
- Adding an alias requires re-running the [`generate-dataset.ts`](https://github.com/raycast/extensions/blob/main/extensions/unicode-symbols/scripts/generate-dataset.ts) script. 
- It would be cool if users could add their own alias for a character as a preference, but I think it might be a bit hard to do with the current setup. 

Let me know if it makes sense!

## Previous idea (just for historical context):

It's been a while since I worked on this extension, but if I recall correctly the idea I had around character aliasing was:
- Create a new [`/src/default-aliases.json`](https://github.com/raycast/extensions/tree/main/extensions/unicode-symbols/assets) file that maps characters to custom aliases. Given your example, it would look something like: `{"8313": ["superscript 9"]}`. People can submit PR to update this file. 
- It would also be nice to allow setting your own alises through preferences. 
- In [`dataset-manager.ts`, right after we get the filtered results from Fuse](https://github.com/raycast/extensions/blob/main/extensions/unicode-symbols/src/dataset-manager.ts#L53), append the result of the same search query but done directly on the aliases. 

Reason about some of the decisions above:
- We could also merge the aliases with the dataset values using the [`generate-dataset.ts`](https://github.com/raycast/extensions/blob/main/extensions/unicode-symbols/scripts/generate-dataset.ts) script. While more "elegant", I think this is less ergonomic because it requires running that script every time we add new aliases to the repo. 
- There might be a way to use Fuse to also handle the aliases search as well (instead of doing that search manually like I suggested), but we need to ensure we don't low the performance → **AT THIS POINT I REALIZED THAT IT DOESN'T SEEM TO BE POSSIBLE TO GRAB CHARS BY ALIASES WITH THIS SETUP UNLESS WE FILTER THE ENTIRE DATASET WITHOUT USING FUZE. /STOP-SCREAMING**

**Comment by Sheraff** [comment]
I might have time to work on this next weekend. Would it be possible to add `generate-dataset` to the `build` script so that the fact that "it requires running that script every time we add new aliases to the repo" doesn't become a pain point? I think merging aliases is the only way for this command to remain performant.

**Comment by mmazzarolo** [comment]
@Sheraff I think so? I *think* I did find some issues doing that in the past but I don't remember what it was... and things might have changed now 👍
