### ISSUE TITLE
[Numi] mention of 'Alfred' in Numi extension error

### ISSUE THREAD

**Issue by jackmsvaughan** [raycast/extensions#2310]
# Extension – [Numi](https://github.com/raycast/extensions/tree/083f164cc1a663d23b78ead032ede7df0a508737/extensions/numi/)
Author:

## Description

Hey there, looks like you've got an error here related to Alfred, not Raycast. https://share.cleanshot.com/FwTI4t

<img width="886" alt="CleanShot 2022-07-20 at 08 13 26@2x" src="https://user-images.githubusercontent.com/50674127/179920292-308a78bb-cf23-48c4-863a-fb35d45d9465.png">

## Steps To Reproduce

1. I opened Numi
2. I installed your extension
3. I triggered your extension and got this warning

**Comment by haackt** [comment]
This error message is intentional as one has to toggle **"Activate Alfred Integration"** (at the bottom of the screenshot) in Numi before being able to use this extension.

<img width="416" alt="Screenshot 2022-09-04 at 13 05 32" src="https://user-images.githubusercontent.com/53407297/188310164-7dd4c9b9-0569-4aa2-8f02-23496856c212.png">

This is also mentioned in the extension's README.md:

<img width="812" alt="Bildschirmfoto 2022-09-04 um 13 07 49" src="https://user-images.githubusercontent.com/53407297/188310250-b7d2c5bb-c06a-49c2-8ef7-982f15528663.png">
