### ISSUE TITLE
[Stock Lookup] ...

### ISSUE THREAD

**Issue by mattouzalem** [raycast/extensions#2326]
# Extension – [Stock Lookup](https://github.com/raycast/extensions/tree/9b983d94c0b978af16dcbfaa2b6f9402ed9f1562/extensions/stock-lookup/)
Author: @jones-sam

<!--
Hey,
Just tried your extension, that's nice!
I have a suggestion for the link in Google Finance ⇒ how about using this link (`https://www.google.com/finance/quote/{Query}`) that directly redirects to Google Finance, instead of being redirected to Google Search?
Let me know your thoughts!
Cheers ✌️

**Comment by mattouzalem** [comment]
Hey,
I have a suggestion for the link to redirect to Google Finance, how about using this one instead of the link to Google Search: `https://www.google.com/finance/quote/{Query}`?

**Comment by jones-sam** [comment]
I switched the url to `https://www.google.com/finance/quote/{Query}` but the site gives this message:

<img width="1943" alt="image" src="https://user-images.githubusercontent.com/45644425/180267109-eeea55f5-5514-4388-ab7e-e5363ef8a7a2.png">

This is because it requires the market in which the stock is trading like so:

<img width="1943" alt="image" src="https://user-images.githubusercontent.com/45644425/180267286-da5d2d0d-349a-4106-90ef-19d423dcde50.png">

But currently the alphavantage api does not return this information, (at least not the endpoint currently in use), so changes to the api implementation will have to be made. We could potentially use yahoo finance api or something similar if need be

**Comment by mattouzalem** [comment]
Ah good point indeed, I didn't know Google Finance required the market where the stock is listed. In that case, I think your initial way of handling it with the search on Google stock may be the best way to make it work.
Sorry for the useless issue then 🤪
