### ISSUE TITLE
Not compatible with pnpm

### ISSUE THREAD

**Issue by sxzz** [raycast/extensions#2384]
Raycast version: `1.38.2`

## Description

When I use `pnpm` as my project package manager, and run `ray develop`

```
/path/raycast-extension/node_modules/.bin/../@raycast/api/bin/ray: line 18: /path/raycast-extension/node_modules/.pnpm/@raycast+api@1.38.2/node_modules/@raycast/api/arm64/ray: No such file or directory
```

As you can see, `bin` folder is missing.

## Steps To Reproduce

1. Clone the [project](https://github.com/open-jike/raycast-extension)
2. `pnpm i` && `pnpm run dev`

## The current behavior

Emit an error.

## The expected behavior

Run normally (correct path: `/path/raycast-extension/node_modules/.pnpm/@raycast+api@1.38.2/node_modules/@raycast/api/bin/arm64/ray`)

## Additional 

Currently, Raycast store only supports `npm` as the package manager. IMHO, as Raycast is a modern project, `pnpm` or `yarn` is much much faster than `npm`. Also, some projects can't use `npm` in some cases.

**Comment by agenordebriat** [comment]
Ran into the same issue. However `yarn` works perfectly fine for me as an alternative to `npm` for now.

**Comment by grzegorzkrukowski** [comment]
Hey

It seems that issue is related to multiple symlinks being used on the path.

In our latest API [v1.39.1](https://www.npmjs.com/package/@raycast/api/v/1.39.1) we refactored the `ray` script completely due to moving binaries from NPM itself and it should also resolve the problem you are experiencing with `pnpm`.

Can you try it out on mentioned version and close this issue if it's resolved?
