### ISSUE TITLE
isLoading is true when usePromise's and onFetch's execute is set to false

### ISSUE THREAD

**Issue by pindab0ter** [raycast/extensions#2410]
When using `usePromise` or `useFetch` (and possibly other methods?) and setting `execute: false` in the options, `isLoading` is true. It shouldn't be, because it isn't loading anything.

Raycast version: 1.38.2

## Steps To Reproduce

1. Open a command
2. It shows that it's loading, even though it isn't

[Example repo](https://github.com/pindab0ter/raycast-showcase-isloading-bug)

## The current behavior
`isLoading` is true when defining `useFetch` or `usePromise` with `execute: false` specified.

## The expected behavior
`isLoading` should be false because it is not in fact loading.

**Comment by mathieudutour** [comment]
`{isLoading: true}` is the initial state of the hook, regardless of the value of `execute`.

This is on purpose because of the following case:

let's say you have 2 useFetch and the second depends on the results of the first one. So you set execute: firstData to only fetch the second when you have the results of the first. That means that you would have the following flow:
1. isLoading1: true; execute2: false; isLoading2: false
2. fetch1 finished
3. isLoading1: false; execute2: true; isLoading2: false
4. on the next render: isLoading1: false; execute2: true; isLoading2: true

on step 3, you can potentially have a flicker - and that's bad...

**Comment by mathieudutour** [comment]
Alright I actually found a way to make it work nicely. `isLoading` will be `false` when `options.execute` is false starting from `@raycast/utils@1.5.0`!

**Comment by pindab0ter** [comment]
Awesome!
