### ISSUE TITLE
[Linear] Copy ID and Title in one hotkey

### ISSUE THREAD

**Issue by dmastylo** [raycast/extensions#2427]
# Extension – [Linear](https://github.com/raycast/extensions/tree/0aea27a6d2b3bf0f75d8ba2a972004e462c5400f/extensions/linear/)
Author: @thomaslombart

**Describe the feature and the current behavior/state.**
When I track what I've worked on during the day in my other applications, I like to have the ID and the Title (so I have context on what it means) of the linear issue I worked on. I have to do several keystrokes to do this as there are just separate copy actions for ID and title but not together.

EXAMPLE ACTION: Copy ID and Title
OUTPUT:  STE-749 Fix bug on position input component

**Who will benefit with this feature?**
Anyone who wants more context than the ID or just title alone

**Any Other info.**

**Comment by thomaslombart** [comment]
Thanks for the feedback. Right now, the extension has the same copy actions as Linear. 

This copy action seems specific to your workflow and I'm afraid adding it would bloat the actions. I'm thinking instead of something more customizable: a preference on which you can define a template of what to copy (e.g `{ISSUE_ID} {ISSUE_TITLE}`).

Then we could add an option (called "Custom copy" or something similar) so that other users could define their preferred format, regardless of their workflow. What do you think?

**Comment by dmastylo** [comment]
Love that idea!
