### ISSUE TITLE
Find in Dash isn't working for react docs

### ISSUE THREAD

**Issue by hadjev** [raycast/extensions#2452]
# Extension – [Title](https://github.com/raycast/extensions/tree/main/extensions/*)

Author: @RSO 

## Description
Find in Dash command isn't working for react (HTML, CSS, JS etc. are working correct. Only react isn't)

## Steps To Reproduce

1. Find in Dash
2. react
3. Search in React field remains empty

## The current behavior
There are no results for a search in react docs

## The expected behavior
There should be results 

### Raycast version

Version: 1.38.2

**Comment by RSO** [comment]
The issue here is that `` returns `pluginKeyword = javascript` for the `react` docset, which makes us believe that we should do `javascript:` in the search instead of `react:`. If you look at what's in the defaults:

```
                {
            blocksOnlineResources = 1;
            dashIndexFilePath = "reactjs.org/docs/hello-world.html";
            docsetBundle = react;
            docsetName = React;
            docsetPath = "/Users/remon/Library/Application Support/Dash/DocSets/React/React.docset";
            docsetSQLPath = "/Users/remon/Library/Application Support/Dash/DocSets/React/React.docset/Contents/Resources/docSet.dsidx";
            isDash = 1;
            isEnabled = 1;
            isFTSUnsupported = 0;
            isJavaScriptEnabled = 1;
            parseFamily = dashtoc2;
            platform = react;
            pluginKeyword = javascript;
            version = 1;
        }
```

There's two fields that have `react` as the value (which is what the search keyword should be): `platform` and `docsetBundle`. The problem is that if I look at other docsets that I have installed, both `platform` and `docsetBundle` aren't correct values to put as the keyword 😕 .

A potential fix for you (not ideal, since it's a fix on your side instead of in the code) is to manually set the keyword for the React bundle to `react` here:

![CleanShot 2022-09-12 at 16 24 49@2x](https://user-images.githubusercontent.com/139663/189679507-f15896a8-c77f-46b5-a697-49d3e2179a78.png)

You just have to double click on the `react:` bit and press return! When I do this, the defaults for this docset change to:

```
                {
            blocksOnlineResources = 1;
            dashIndexFilePath = "reactjs.org/docs/hello-world.html";
            docsetBundle = react;
            docsetName = React;
            docsetPath = "/Users/remon/Library/Application Support/Dash/DocSets/React/React.docset";
            docsetSQLPath = "/Users/remon/Library/Application Support/Dash/DocSets/React/React.docset/Contents/Resources/docSet.dsidx";
            isDash = 1;
            isEnabled = 1;
            isFTSUnsupported = 0;
            isJavaScriptEnabled = 1;
            isProfileEnabled = 1;
            keyword = "react:";
            parseFamily = dashtoc2;
            platform = react;
            playURLChecked = 1;
            pluginKeyword = javascript;
            shouldUseImage = 0;
            version = 1;
        }
```

As you can see it now has `keyword = "react:"`. After applying this fix I can now successfully search through the React codebase:

<img width="1000" alt="dash 2022-09-12 at 16 26 50" src="https://user-images.githubusercontent.com/139663/189679790-bdf7e7cd-b3b3-4fa3-89e4-fb5bbf3096da.png">
