### ISSUE TITLE
[JetBrains Toolbox Recent Projects] ...

### ISSUE THREAD

**Issue by ddavid-son** [raycast/extensions#2499]
# Extension – [JetBrains Toolbox Recent Projects](https://github.com/raycast/extensions/tree/c614a2dfc24aad9174e55bacc6053238781d77a7/extensions/jetbrains/)
Author: @gdsmith

## Description

Nothing happens when trying to open a project - 
I have the toolbox installer and this bug happens with both WebStorm and Rider(didn't try on other JB product)

I use the 13 inch m1 matchbook pro running the latest version of the OS, WebStorm and Rider 

## Steps To Reproduce

1. enter to the jet brain command
2. type name of a project 
3. press enter

## The current behavior
Raycast closes and a rat angular popup in the bottom of the screen stating "opening <name-of-project>" and nothing else

## The expected behavior
opening the project

### Raycast version
Version: 1.38.3

**Comment by alihazemfarouk** [comment]
I'm having the same issue with PyCharm

**Comment by NewbieDong** [comment]
I'm having the same issue with IntelliJ IDEA

**Comment by NewbieDong** [comment]
I solved this problem, you can try to enter` idea yourProjectName` on the command line, if it doesn't open, it's issue of the idea command, not the plugin.

**Comment by NewbieDong** [comment]
I am a developer using IDEA, I solved this problem.

you can try to enter `[idea yourProjectName](https://www.jetbrains.com/help/idea/opening-files-from-command-line.html)` on the command line, if it doesn't open, it's issue of the idea command, not the plugin.

**Solved step:**
1. Open Jetbrains Toolbox
2. Type `command + ,`  go to setting page
3. Generate shell scripts in /usr/local/bin/
4. Check if there is a script named **idea** (your dev tool script name)

**Comment by NewbieDong** [comment]
I am a developer using IDEA, I solved this problem.

you can try to enter `idea yourProjectName`([link](https://www.jetbrains.com/help/idea/opening-files-from-command-line.html)) on the command line, if it doesn't open, it's issue of the idea command, not the plugin.

Solved step:

Open Jetbrains Toolbox
Type command + , go to setting page
Generate shell scripts in /usr/local/bin/
Check if there is a script named idea (your dev tool script name)

**Comment by NewbieDong** [comment]
I am a developer using IDEA, I solved this problem.

you can try to enter idea yourProjectName([link](https://www.jetbrains.com/help/idea/opening-files-from-command-line.html)) on the command line, if it doesn't open, it's issue of the idea command, not the plugin.

**Solved step:**

1. Open Jetbrains Toolbox
2. Type command + , go to setting page
3. Generate shell scripts in /usr/local/bin/
4. Check if there is a script named idea (your dev tool script name)

**Comment by NewbieDong** [comment]
I am a developer using IDEA, I solved this problem.

you can try to enter `idea yourProjectName`([about command link](https://www.jetbrains.com/help/idea/opening-files-from-command-line.html)) on the command line, if it doesn't open, it's issue of the idea command, not the plugin.

Solved step:

1. Open Jetbrains Toolbox
2. Type command + , go to setting page
3. Generate shell scripts in /usr/local/bin/
4. Check if there is a script named idea (your dev tool script name)

**Comment by ParzivalExe** [comment]
> 3. Generate shell scripts in /usr/local/bin/

That is the secret to this problem (at least in my experience), as by default JetBrains Toolbox now creates the Scripts in `/Users/lasse/Library/Application Support/JetBrains/Toolbox/scripts` on MacOS which (at least in my experience) doesn't work with the Extension even if you change to Script-Path inside it's Settings.

Also you need to manually change the `Shell scripts location` in the Toolbox-Settings from the old one to `/usr/local/bin` since at least for me there was no way to select this path through the Finder-Window that opens when clicking `Change...`. 

Also from my experience, if you have a new Computer (as I have) the folders `local/bin` might not even exist yet (for me only `/usr/bin/` existed which is protected and can therefore not be used) so you might need to first create the necessary folders before changing the `Shell scripts location`

The last tip I can give is that even though `/usr/local/bin` might be written grayed-out in the settings of the Raycast-Extension you actually do need to write it there. If you simply leave the `Shell scripts location`-Field of the Extension-Settings empty it will also not work.

Well, that's all I have found about this issue and that I had to do to fix it for myself. Now that it is fixed I absolutely love it since I don't even have to keep the Toolbox open all the time in the background because the scripts automatically open the appropriate IDEs without needing the Toolbox.
