### ISSUE TITLE
[Dash] Pandas docs are unable to be searched, incorrect doc keyword inputted into Dash (`python:` vs `pandas:`)

### ISSUE THREAD

**Issue by paw-lu** [raycast/extensions#2691]
# Extension – [Dash](https://github.com/raycast/extensions/tree/cf7485961c3c4394da7e87b8477aa28f9aadfe1c/extensions/dash/)
Author: @RSO @sxn

## Description

Searching for pandas docs does not work. For some reason, the Raycast extension inputs the `python:` prefix into Dash instead of `pandas:`. This works as expected on other docsets—like Flask. Additionally pandas docs on Dash work as expected on other plugins—like Alfred.

## Steps To Reproduce

1. Launch `Find in Dash`
2. Select `pandas` as docset
3. Attempt to search for any reference under `pandas`

Recording demonstrating a docset that works as expected (`Flask`) vs one that does not work as expected (`pandas`).

https://user-images.githubusercontent.com/30049606/186968691-2a7ce594-c373-4bec-bdba-d5279483ab27.mp4

## The current behavior

`pandas` doc does not successfully look up any references, and inputs the wrong doc prefix into Dash.

## The expected behavior

Selecting `pandas` as a docset inputs the `pandas:` search prefix into Dash, and allows for access to the docset references.

### Raycast version

1.39.1

---

Thank you so much for providing this extension!

**Comment by paw-lu** [comment]
Same problem with `Python 3` docset. It inputs `python:` as the prefix, when I think it should be `python3:`.

**Comment by RSO** [comment]
Hey there! Sorry for getting back so late. I was enjoying the sun for a bit on holiday.

I just posted a comment on an issue that I think is related and that I think might help you as well: https://github.com/raycast/extensions/issues/2452#issuecomment-1243825227. As I said, I'm not very confident in changing the code that decides what prefix to use since I'm pretty sure I changed it to the current implementation to fix issues that were the same as the ones reported here. The problem with the data format returned by Dash in the `defaults read` is that it has a lot of similar-looking fields that aren't exactly what we think they are 😢 

Either way, I hope my proposed fix helps unblock you in the meantime!

**Comment by paw-lu** [comment]
> Sorry for getting back so late. I was enjoying the sun for a bit on holiday.

Absolutely nothing to be sorry about. Hope you enjoyed your time off!

> The problem with the data format returned by Dash in the `defaults read` is that it has a lot of similar-looking fields that aren't exactly what we think they are

I admitedly have not read through it yet, but the Alfred app does work as expected. While the workflow isn't open sourced, @Kapeli lays out the high level logic of the workflow in this issue:

https://github.com/Kapeli/Dash-Alfred-Workflow/issues/26#issuecomment-1068502270

**Comment by RSO** [comment]
Thanks for CC'ing me on that issue! Hopefully we can figure out the right way of prefixing that works all the times!

**Comment by Kapeli** [comment]
@RSO I think the best way to fix it would be for me to make Dash update the `keyword` so you'll always get a keyword for all docsets when you're reading the defaults. I'll do this in the next Dash update.

**Comment by paw-lu** [comment]
Just caught up on this thread. This is so great now. Thanks you so much @RSO and @Kapeli!
