### ISSUE TITLE
[Bear] Search query should be tokenized

### ISSUE THREAD

**Issue by jrk** [raycast/extensions#2710]
# Extension – [Bear](https://github.com/raycast/extensions/tree/main/extensions/bear)

Author: @hmarr @lucaschultz

**Describe the feature and the current behavior/state.**
Bear note search currently treats the entire query string as a single token. Coming from most modern search interfaces (including Bear's own search), this is surprising and limiting behavior, as it prevents searching for things based on multiple tokens which occur independently, or not necessarily in the same order.

The search should be tokenized according to common practice (e.g., with support for `"quoted strings"` where a longer substring should be treated as a single token).

(There is currently a workaround where one can explicitly search for `foo%bar`, relying on the SQL wildcard being passed directly to the underlying SQLite query, but this is likely not expected or discoverable for most users.)

**Comment by jrk** [comment]
I should clarify: even the wildcard workaround isn't a full tokenized search, as it still constrains the order of the tokens.

**Comment by hmarr** [comment]
Yeah this occasionally bugs me too. Unfortunately it's not trivial to solve. I haven't put the time into improving it yet because I'm mostly searching by title, so I don't find it a huge problem day to day.

Anyway, I did have a quick think about this when I was originally building the extension, and here are a few options I came up with.

### Use the sqlite [FTS5](https://www.sqlite.org/fts5.html) module

This builds full text search right into sqlite, so on the surface is the most straightforward option available to us.

However, the Bear sqlite database doesn't have a full text search table already, so we'd need to create it. So far we've been strict about avoiding any writes to the Bear sqlite database. The worst thing this extension could do is lose someone's notes by corrupting the database. Reading the database is unlikely to cause any harm, but as soon as we start modifying the database we're in uncharted territory.

To work around this, we could periodically copy the database to another place in the filesystem, and create the search table there. Periodically recreating the search table from scratch might not be great for performance, but I'd want to try it out before ruling it out.

Additionally, the sqlite WASM library we're using (sql.js) doesn't appear to come with a distribution that bundles the FTS5 module, but it does look like other extensions (craftdocs, ensk-is) have found a distribution that does include the module.

### Build our own index

Alternatively we could extract all the notes from the database, and load them into our own search index, perhaps using something like [tinysearch](https://github.com/tinysearch/tinysearch) or [stork](https://github.com/jameslittle230/stork). The sqlite database does include modification dates, so we could probably use them to keep the index up to date incrementally.

**Comment by jrk** [comment]
Indeed, I went down a similar mental rabbit hole after posting this, reaching similar conclusions.

I strongly agree that the Bear database should be treated as strictly read-only, but the one thing I wondered was whether a SQLite `ATTACH` to the Bear DB would be sufficient to allow managing a custom, writable index database that still works with the live Bear DB as read-only.

For realistically-sized Bear databases, though, I suspect that a pure standalone index (tinysearch, stork, etc.) should be far more than enough. (I say this even as someone with megabytes of text across thousands of notes.)
