### ISSUE TITLE
[Notion] Configuration which property show in raycast

### ISSUE THREAD

**Issue by van556** [raycast/extensions#2727]
# Extension – [Notion](https://github.com/raycast/extensions/tree/8ea3c6f9563bf73663218d2ead8c32e683ef7b34/extensions/notion/)
Author:

**Describe the feature and the current behavior/state.**

The current state is raycast will show all properties,even furmula.It confuse me.

When I create a database page through raycast,I want to pursue efficiency.So I want to configuration which property will show in raycast.

**Who will benefit with this feature?**

**Any Other info.**

**Comment by gupta-anmol** [comment]
To add to this, it would be great if we could set the order in which the database properties should appear. It's a pain to press tab multiple times to skip through irrelevant properties until you reach the one you want to fill. It kind of hampers the usefulness of this extension to make quick entries in the database. Great extension otherwise!
