### ISSUE TITLE
[Confluence Search] Can't get search to work

### ISSUE THREAD

**Issue by megaroeny** [raycast/extensions#2728]
# Extension – [Confluence Search](https://github.com/raycast/extensions/tree/c5d7bc5776f040c7f4b42184e9f11ab42f155d88/extensions/confluence-search/)
Author: @daviddkkim

## Description
I'm pretty sure I set up the config correctly. I'm not getting any errors. But when using the extension and I start to search, it always shows no results. Any known issues? Thanks!
![Screen Shot 2022-08-30 at 11 54 14 AM](https://user-images.githubusercontent.com/1559447/187485302-d5136b89-6495-468c-97d6-66f605a4ef3f.png)

![Kapture 2022-08-30 at 12 08 54](https://user-images.githubusercontent.com/1559447/187486904-58961ed4-1365-42f7-b430-1e757a7053ab.gif)

## Steps To Reproduce

1. Configure Cloud account
2. Add [company name].atlassian.net to `Domain` field
3. Add rest of the fields
4. Start extension command
5. You'll immediately see "No results" message even before searching 

## The current behavior
"No results" is always shown

## The expected behavior
Results should be appearing, due to no errors of configuration.

### Raycast version
Version: 1.39.1

**Comment by megaroeny** [comment]
@mikeozornin also tagging you since I saw you mentioned in the source code.

**Comment by mikeozornin** [comment]
> @mikeozornin also tagging you since I saw you mentioned in the source code.

I just created a test cloud confluence instance and checked everything.
I used the following settings:
Server: ```raycast-test-wiki.atlassian.net```
Username: my atlassian email ```login@gmail.com```
API Key: previously created API key.

I got extension worked, maybe it's depending on the environment, so let's try to troubleshoot.

Do you use email as username?

**Comment by megaroeny** [comment]
> Do you use email as username?

Yes, it's my work email.

**Comment by mikeozornin** [comment]
That's not very good. I I don't really understand how to troubleshoot your issue. You made correct preferences (as I think).

As soon I will be able to reproduce it, I could run a local version of the raycast confluence extension and debug it.

Maybe you can run a rest query and check what's going on?

Here are parameters:
URL:
```https://{{confluence-domain}}/wiki/rest/api/search?cql=title~"test*"&expand=content.version```

Headers:
```Authorization``` with value: ```Basis {{auth string}}```
```auth string``` is ```email:token``` encoded as base64.

Something like
```Authorization``` ```Basic bWlrZS5vem9ybmluQGdtYWlsLmNvbTpNanRoeFRoanJGQUhE123asdagfgdkYxNTg=```

Here are my query in HTTPie.
<img width="1442" alt="image" src="https://user-images.githubusercontent.com/1744928/187805898-c7e1107e-1c88-4c8c-bdaa-4648c7280a2a.png">

Result could help to understand what's going on there.

**Comment by megaroeny** [comment]
> That's not very good. I I don't really understand how to troubleshoot your issue. You made correct preferences (as I think).
> 
> As soon I will be able to reproduce it, I could run a local version of the raycast confluence extension and debug it.
> 
> Maybe you can run a rest query and check what's going on?
> 
> Here are parameters: URL: `https://{{confluence-domain}}/wiki/rest/api/search?cql=title~"test*"&expand=content.version`

Sorry I'm not a developer. Do I enter this URL into my browser? If so I got this message:

`{"message":"Current user not permitted to use Confluence","statusCode":403}`

**Comment by mikeozornin** [comment]
No, you need to run it via any postman-like app for debugging web apps.

I'm very sorry, but I don't understand how to troubleshoot and to fix your issue. Maybe extension author could help (but they is not very active, as I could see).

**Comment by megaroeny** [comment]
@mikeozornin no worries at all. Appreciate the help. Yeah I was hoping that author would respond. ☹️

**Comment by andy2mrqz** [comment]
Just wanted to mention that I also had an issue similar to this, but in my case when I went to "Configure Command" in Raycast I noticed my email was missing (perhaps I hadn't seen it in the setup form).  After adding it, I saw results correctly.

So it sounds like my issue was different from @megaroeny's, since it looks like they had their email present.  Just wanted to note this for people that may find this issue.

(Also, following @mikeozornin's steps with Postman helped me see that my API token did work, although I went to "Authorization" > "Basic" and filled in username (work email) and password (API token) to get it to work)

**Comment by megaroeny** [comment]
@andy2mrqz is the API token a password?? I used the generated API token from my Atlassian profile. Thanks for chiming in too!

**Comment by andy2mrqz** [comment]
@megaroeny Ah my bad for not being very clear - I put the generated API token in the password field. It sounds like you are using the correct API token.

It sounds like the best troubleshooting step would be to try the Postman route that was mentioned before (they have an online client). Even not being a developer, it is pretty discoverable. The screenshot tells you most of what you need, I would just suggest using the Authorization tab and selecting Basic Auth instead of using the Headers tab.

If it doesn't work there too, it would indicate that it's probably not an issue with the Raycast extension. But if it does, that would be good to know for troubleshooting.

Hope that helps if you're still trying to get it to work 🙏

**Comment by megaroeny** [comment]
@andy2mrqz would you mind pointing me to a link for the online client you mentioned? Would appreciate it. Thank you!

**Comment by andy2mrqz** [comment]
@megaroeny postman.com, it requires a free login for the web version, or you can download the app

**Comment by megaroeny** [comment]
I'm SO DUMB! 😹 I was missing an `a` in my email domain 🤦🏼‍♂️ 🤦🏼‍♂️ 🤦🏼‍♂️ 

Fixed the typo and all good. I ended up testing out the request in Postman when I noticed the typo in the results. Closing this issue haha!
