### ISSUE TITLE
[Kill Process] Always lists `syspolicyd` as high CPU usage

### ISSUE THREAD

**Issue by joepio** [raycast/extensions#2864]
# Extension – [Kill Process](https://github.com/raycast/extensions/tree/161ef683e135825a8fef68699742aca55ebca9ff/extensions/kill-process/)
Author: @rolandleth 

## Description

The `kill process` tool has an impact on the running processes, making the CPU load metrics not representative of the actual CPU load.

The `syspolicyd` process checks if other processes have the correct permissions. This is probably executed when the `kill process` tool accesses the currently running processes, leading to a high CPU usage of `syspolicyd` whenever `kill process` is opened. This leads users (at least, led me) to believe that the process is eating up loads of CPU power, and may have gone rogue, sending the user into a dark spiral of non-solutions.

## Steps To Reproduce

1. Open `kill process`
2. See `syspolicyd` at the top, most often at 70 to 100% load

<img width="833" alt="Screenshot 2022-09-11 at 11 11 48" src="https://user-images.githubusercontent.com/2183313/189520036-f301f26b-5af3-4b87-a096-cb4d66b73cae.png">

## The current behavior

`syspolicyd` has a high load, while in activity monitor / htop / whatever, the load for `syspolicyd` is about 0 - 10%.

## The expected behavior

- `syspolicyd` has a normal CPU load (maybe because the CPU load calculation in the background is performed in a different way)
- `syspoicyd` does not appear in the list, at all, as the numbers tend to be skewed up. This could be done with a hard-coded blacklist of processes that the user should (probably) not kill. 
- the list updates (although updating the ordering will introduce usability issues, we could still update the values, if that's possible)

### Raycast version

1.39.3

**Comment by rolandleth** [comment]
Running the command from terminal doesn't show it either, so what I assume is that it's part of Raycast's processes, just like `node` is also found in the list, but running this from the terminal doesn't show it.

As you can see in the image, `syspolicyd` _is_ caught by Activity Monitor, but the polling interval can not be customized in there, and it simply catches it too late.

<img width="1286" alt="2022-10-10 at 01 45 38" src="https://user-images.githubusercontent.com/1858700/194849077-349db81a-af08-4948-a10b-58bd0181a223.png">

As you also noted, refreshing brings the values back down to normal levels (for node and WindowsServer too), so I'd suppose it's something related to the start of the extension.

I think having a list of to-be-ignored processes is a good way to solve this, but I wouldn't hardcode it, I would create a preference with a default value of "syspolicyd,WindowsServer". On the other hand, these values should probably be ignored only on first render, after reloading they should also be included, because they _might_ go rogue and ignoring them completely would hide any issues.

[Or maybe we can trigger a refresh automatically, 0.2seconds after the initial load.]: I tried this and doing a reload after 1 second does the trick, but it's not ideal. 

Weird part? If I _don't_ fetch processes at start, but after 1 second, `syspolicyd` is still there, so maybe it's not the extension itself? I've no idea what could be, because the first time `fetchProcesses` is called (no matter how soon or late after the extension loaded), it always shows `syspolicyd`, but subsequent calls do not.

Any help from the Raycast team on this?

**Comment by joepio** [comment]
> Weird part? If I don't fetch processes at start, but after 1 second, syspolicyd is still there, so maybe it's not the extension itself? I've no idea what could be, because the first time fetchProcesses is called (no matter how soon or late after the extension loaded), it always shows syspolicyd, but subsequent calls do not.

What I think is going on, is `syspolicyd` is checking if Raycast is allowed to `exec`. The first time this is asked of the OS, we see high intensity usage for a short time. After that, the response is cached (the process is temporarily whitelisted by macOS), so we see almost no CPU usage.
