### ISSUE TITLE
[Google Cloud Platform Search] Large list of projects 

### ISSUE THREAD

**Issue by davizucon** [raycast/extensions#2891]
# Extension – [Google Cloud Platform Search](https://github.com/raycast/extensions/tree/409131618bc22b05050a311375e24d4634915742/extensions/google-cloud-platform-search/)
Author: @klaa97

## Description
Trying to list GCP projects, command line working fine.

## Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

__node_internal_captureLargerStackTrace:errors:464:5
NodeError:errors:371:5
Worker.[kOnExit]:worker:279:26
Worker.<computed>.onexit:worker:201:20
```

## Steps To Reproduce

1. Open raycast
2. Select "Search Projects" from Google Cloud Platform Search
3. Wait a few secs and crash 

## The current behavior
"Something went wrong"

## The expected behavior
List GCP projects

### Raycast version
Version: 1.39.3

**Comment by klaa97** [comment]
Ciao! Thank you for the bug report!

I am not currently able to work on this for the ~next month, but I have an idea if you wanna dive in the code. Note that I think the problem is your list is huge, and pagination may not be the solution (but could be a part of it).

The real problem could be the size itself of the list, which with pagination or without could still grow. So, following this issue and the related solution https://github.com/raycast/extensions/issues/1523 , a possible idea may be to use SQLite to index the project identifiers instead of plain JS objects.

**Comment by davizucon** [comment]
Yeah, It's a good approach, make a local cache using SQLite can handle huge list. If so, may need to add some function to refresh. I'll take a look. Thanks.

**Comment by shotarok** [comment]
I also faced this issue today. It'd be great if we could implement the SQLIte approach!
