### ISSUE TITLE
[Obsidian] Order results by relevance

### ISSUE THREAD

**Issue by gui-costa** [raycast/extensions#3030]
# Extension – [Obsidian](https://github.com/raycast/extensions/tree/e2c19dd992e84f89ce5ef011a7ed2b323b47bff0/extensions/obsidian/)
Author: @marcjulianschwarz

Order note search results by relevance (e.g. to start with, it could be as simple as how much the title matches with the searched term).

**Describe the feature and the current behavior/state.**
Example of current behavior: in a search for "MPJ", a note titled "MPJ" exists but you have to scroll through results to find it.
![image](https://user-images.githubusercontent.com/67469232/192336940-93ecb5a7-9eb3-48b0-ac49-d50d7a8f7a4f.png)

**Who will benefit with this feature?**
All users who have many notes and use search feature

**Comment by marcjulianschwarz** [comment]
Hi @gui-costa,

this should of course already be working.

Do you habe *Full Content Search* enabled in the settings? If yes, then the content of every note will be searched and the filtered results will be displayed in mostly alphabetical order.
Try turning off *Full Content Search* and see if that helped.

**Comment by gui-costa** [comment]
I do, that's the issue. I also value the feature to be able to find content inside the notes quickly.

Isn't there a way to, even so, keep the notes sorted by relevance vs the title somehow? 

I understand this is not pertinent to relevant content inside the note, but since you're going with alphabetical order anyway, this would only improve the experience from where it stands.

**Comment by gui-costa** [comment]
By the way, thank you so much for sharing your work with the rest of us!

**Comment by marcjulianschwarz** [comment]
Glad that was the issue and not something else.

I agree that the sorting has to be adjusted (with content search enabled). That's why I have a "Better Fuzzy Search" draft on the roadmap for the extension. [See Roadmap](https://github.com/users/marcjulianschwarz/projects/1/views/1)

However I am really busy with university exams right now, so probably won't be able to work on this for the next few weeks.

Of course every contribution to this project will be appreciated!
