### ISSUE TITLE
[Timers] ...

### ISSUE THREAD

**Issue by niel-bowerman** [raycast/extensions#3043]
# Extension – [Timers](https://github.com/raycast/extensions/tree/d370a046747bdbac6385282a4c16b4b24dfb2b61/extensions/timers/)
Author:

**Describe the feature and the current behavior/state.**
Currently timer options increase in multiples of 5 mins.  

**Who will benefit with this feature?**
Several other timers, e.g. Nag Timer, have a 2 minute timer as a default option, so I assume it's popular (though I don't have data for this)

**Any Other info.**
David Allen's GTD methodology suggests doing tasks if they take <2 mins.  I religiously set a 2 minute timer when I start doing a task immediately instead of adding it to my ask management system.  This makes sure I don't get lost in the task.  

You could always add a 2 minute option, see how much use it gets, and drop it if no-one except me is using it!

**Comment by ThatNerdSquared** [comment]
Hi @niel-bowerman - thanks for using Timers, and thanks for the suggestion! I will consider adding a 2 minute default option - it seems useful, but I also don't want to clutter the defaults too much. I will note that, as far as I know, there's no way for me to determine which options get more use because we don't have any sort of Raycast-supported analytics.

In the meantime, have you tried creating a custom preset for 2 minutes? This would allow you to easily start the 2 minute timer as needed.
<img width="862" alt="Screen Shot 2022-10-03 at 21 06 58" src="https://user-images.githubusercontent.com/72814106/193732056-5202b1c9-99e6-4278-ac76-c6191159d71a.png">
<img width="156" alt="Screen Shot 2022-10-03 at 21 07 10" src="https://user-images.githubusercontent.com/72814106/193732097-303fb8ad-38e8-45ef-91e4-55ce8213f588.png">

**Comment by ThatNerdSquared** [comment]
I've added the 2 minute preset in #3999.

**Comment by niel-bowerman** [comment]
Amazing, thank you!

Cheers,

Niel

--
Niel Bowerman | +44 7912 614 541 | nielbowerman.com
