### ISSUE TITLE
[iTranslate] not translate 

### ISSUE THREAD

**Issue by UtopiaEH** [raycast/extensions#3076]
# Extension – [iTranslate](https://github.com/raycast/extensions/tree/1ceb73cae548d777df140b209b6d771752de081a/extensions/itranslate/)
Author:

## Description
A few days ago ITranslate stopped to translate

![shoot_30_09_14_23](https://user-images.githubusercontent.com/25262913/193259772-947edd1a-e98f-4aba-9f4a-fe6a8f312056.png)

**Comment by 404J** [comment]
@UtopiaEH Hi, the default is the free Google translation, which is really not very stable. I just tried it, it could work.
<img width="746" alt="CleanShot 2022-10-01 at 19 43 50@2x" src="https://user-images.githubusercontent.com/35960860/193408299-65b52e9a-2b8a-474a-b0d2-69751ec8c464.png">


You can check this configuration, whether it is "com"
<img width="309" alt="CleanShot 2022-10-01 at 19 54 13@2x" src="https://user-images.githubusercontent.com/35960860/193408348-21558374-9ddc-465b-8b61-f0aa6b7271cb.png">

Free Google Translate by default isn't perfect. It crashes a lot. I will look for a better replacement later. BTW, You can spend some time to apply for some translation services, and they often provide free quotas, so that the translation function will be much stable。

- [Google Could Translation](https://cloud.google.com/translate)
- [Deepl](https://www.deepl.com/pro-api?cta=header-pro-api)
- [Microsoft Azure](https://docs.microsoft.com/en-us/azure/cognitive-services/translator/quickstart-translator?tabs=csharp)
- [Youdao](https://ai.youdao.com)
- [Baidu](https://fanyi-api.baidu.com)
- [Tencent](https://fanyi.qq.com/translateapi)
- [Aliyun](https://www.alibabacloud.com/product/machine-translation)

**Comment by UtopiaEH** [comment]
> @UtopiaEH Hi, the default is the free Google translation, which is really not very stable. I just tried it, it could work. <img alt="CleanShot 2022-10-01 at 19 43 50@2x" width="746" src="https://user-images.githubusercontent.com/35960860/193408299-65b52e9a-2b8a-474a-b0d2-69751ec8c464.png">
> 
> You can check this configuration, you should set it to "com" if you are not in mainland China <img alt="CleanShot 2022-10-01 at 19 54 13@2x" width="309" src="https://user-images.githubusercontent.com/35960860/193408348-21558374-9ddc-465b-8b61-f0aa6b7271cb.png">
> 
> Free Google Translate by default isn't perfect. It crashes a lot. I will look for a better replacement later. BTW, You can spend some time to apply for some translation services, and they often provide free quotas, so that the translation function will be much stable。
> 
> * [Google Could Translation](https://cloud.google.com/translate)
> * [Deepl](https://www.deepl.com/pro-api?cta=header-pro-api)
> * [Microsoft Azure](https://docs.microsoft.com/en-us/azure/cognitive-services/translator/quickstart-translator?tabs=csharp)
> * [Youdao](https://ai.youdao.com)
> * [Baidu](https://fanyi-api.baidu.com)
> * [Tencent](https://fanyi.qq.com/translateapi)
> * [Aliyun](https://www.alibabacloud.com/product/machine-translation)

![ufc-205-thank-you-gif-by-ufc](https://user-images.githubusercontent.com/25262913/193412723-a166758c-2cb0-4f2d-9a06-81c448705595.gif)

**Comment by 404J** [comment]
@UtopiaEH Is it working right now?😅

**Comment by UtopiaEH** [comment]
> @UtopiaEH Is it working right now?😅

yeap i changed to com and I don't noticed some issues

**Comment by 404J** [comment]
> 
nice～～ In the next version I will make `com` as the default value. Have a good day

**Comment by UtopiaEH** [comment]
> > 
> 
> nice～～ In the next version I will make `com` as the default value. Have a good day

thx you,  by the way very useful extensions to improve your dictionary have a good week I will subscribe to you new feature :D

**Comment by 404J** [comment]
> > nice～～ In the next version I will make `com` as the default value. Have a good day
> 
> thx you, by the way very useful extensions to improve your dictionary have a good week I will subscribe to you new feature :D

Dictionary is a good suggestion, but for now, iTranslate's goal is to do a good job of translating. Maybe in the future I'll add a Commond to iTranslate for the dictionary feature🤔
In the Raycast Store, [Easy Dictionary](https://www.raycast.com/isfeng/easydict) is a good extension of the dictionary, you can try it

**Comment by tisfeng** [comment]
It seems that cn can no longer be used because Google Translate has closed the China site.  [Google疑似关闭了Google翻译的中国站点](https://www.solidot.org/story?sid=72923)

However, since Raycast does not support system proxy by default, com does not work for Chinese users either. 

Maybe you need to make your extension support system proxy in order to allow Chinese users to continue using Google Translate 😓

**Comment by 404J** [comment]
@tisfeng Thx, Let me try.
