### ISSUE TITLE
[YouTrack] YouTrack global search field directly from RayCast

### ISSUE THREAD

**Issue by Canis1Majoris** [raycast/extensions#3156]
# Extension – [YouTrack](https://github.com/raycast/extensions/tree/cca2a7ffcbd70f7d665a93c9ac2da188b0b4f9a9/extensions/youtrack/)
Author: [tiulpin](https://www.raycast.com/tiulpin)

Global search field directly from RayCast with autocomplete like: Stat -> Status:, Ver -> Verified, etc. Or search by keywords from all YouTrack's projects

**Describe the feature and the current behavior/state.**
Global search request field which available on /youtrack/issues directly from RayCast
Right now you need to hardcode search query in settings to get list of issues and you can search by keywords only from that list.

**Who will benefit with this feature?**
PMs or POs who need to control and navigate bunch of issues from various projects

**Any Other info.**

**Comment by Canis1Majoris** [comment]
:(

**Comment by TyceHerrman** [comment]
This is still relevant afaik. Browse Issues still fetches only the configured Query up to the Issues limit, and typing in Raycast only filters those fetched results rather than querying YouTrack.

Making non-empty search text query YouTrack would support broad ad hoc searches, while an empty search could retain the configured default view. The issue limit would cap each server response rather than the entire searchable set.

@skoch13 @tiulpin I’m interested in working on implementing this - and if that's good by you can we reopen this?

**Comment by skoch13** [comment]
@TyceHerrman The extension is not actively maintained on my end, but I have no objections to adding anything relevant to it, so feel free.
