### ISSUE TITLE
[JetBrains Toolbox Recent Projects] Make Fleet available in IDE list

### ISSUE THREAD

**Issue by alejgarciarodriguez** [raycast/extensions#3345]
# Extension– [JetBrains Toolbox Recent Projects](https://github.com/raycast/extensions/tree/main/extensions/*)

Author: @gdsmith @adrienbaron @dima-m711

**Describe the feature and the current behavior/state.**

Currently Fleet is not listed in "All Toolbox Search". It is possible to make it appear here even it is still in public preview?

<img width="429" alt="image" src="https://user-images.githubusercontent.com/16359911/198599538-ae1bbc1c-1de0-49d9-9656-5ee258c804ee.png">
<img width="277" alt="image" src="https://user-images.githubusercontent.com/16359911/198599692-138d8e41-20d5-4b2a-a48c-0e500bb18962.png">

**Who will benefit from this feature?**

All people who are testing Fleet

**Any Other info.**

**Comment by gdsmith** [comment]
JB has done something different with project history for this one, the projects are not even showing in the official JB Toolbox list. The extension code is picking up the app correctly, it's just not finding any history because it's not where it is for the other apps. Will definitely keep an eye on this, but I'm cautious to invest too much time, especially while this is still in preview as some of the things – like how it's storing project history – may be subject to change. It's possible it may end up just working without any changes required as the history json file is there, it's just not got any history in it.

**Comment by gdsmith** [comment]
@alejgarciarodriguez I opened an issue here: https://youtrack.jetbrains.com/issue/TBX-8546/Fleet-Projects-Are-Not-Shown-in-Toolboxs-Projects-List if you want to +1

**Comment by alejgarciarodriguez** [comment]
Thanks @gdsmith!

**Comment by gdsmith** [comment]
It's an open issue, awaiting upstream fixes 🤷
