### ISSUE TITLE
[Keyboard Layout Switcher] Auto switch when only 2 options

### ISSUE THREAD

**Issue by agusluques** [raycast/extensions#3397]
# Extension – [Keyboard Layout Switcher](https://github.com/raycast/extensions/tree/28d400f1c7f4bcb23e56e87ad472208df996e6ed/extensions/keyboard-layout-switcher/)
Author: @lucaschultz 

## Current State
When calling the command, a list of layouts appears and the user needs to go through each one and select the wanted one.

## New Feature
It would be awesome that if there are only 2 possible options, the command will select the other one automatically. Just like default Mac shortcuts does. (see photo)
![image](https://user-images.githubusercontent.com/12550839/199776061-3e33c841-2bfb-4454-abe0-e19398221d7f.png)

Or at least, it'd great if the non-selected one appears first.

**Comment by lucaschultz** [comment]
Thanks for the suggestion. Generally both are doable. However, toggling if two are available is a bit weird, because the command would behave entirely different depending on the amount of available layouts without providing any explanation. 

The better solution for _toggling_ might be to add an additional command which toggles through the available layouts.

Would you be interested in contributing yourself?

**Comment by agusluques** [comment]
> Thanks for the suggestion. Generally both are doable. However, toggling if two are available is a bit weird, because the command would behave entirely different depending on the amount of available layouts without providing any explanation.
> 
> The better solution for _toggling_ might be to add an additional command which toggles through the available layouts.
> 
> Would you be interested in contributing yourself?

Sure, I'll create a [Toggle Keyboard Layout]
