### ISSUE TITLE
[Night Light] `Change Night Shift Color Temperature` command does not work

### ISSUE THREAD

**Issue by hrvstr** [raycast/extensions#3414]
# Extension – [Night Light](https://github.com/raycast/extensions/tree/f13c0b4a5be51c905ac3f994b416897671ea3f8c/extensions/night-light/)
Author: @devmoath 

## Description

When trying to change the color temperature with this Raycast extension nothing happens. Switching and toggling Night Shift does work. Setting the temperature directly with the `nightlight` package in the terminal works, too.

## Steps To Reproduce

1. Set the color temperature to `0` manually via `nightlight temp 0` in the terminal
2. Run Raycast command `Change Night Shift Color Temperature`
3. Set the value to `100` and press `Enter` - Nothing happens
4. Set the color temperature to `100` manually via `nightlight temp 0` in the terminal - Temperature changes

## The current behavior
The color temperature does not change.

## The expected behavior
The color temperature does change.

### Raycast version
Raycast v1.42.2
Extension v1
Nightlight v0.3.0

**Comment by pernielsentikaer** [comment]
@devmoath do you have time to check this?

**Comment by devmoath** [comment]
@pernielsentikaer yeah sure.

Hi @hrvstr, I followed the steps you provided and the command is working as expected.

NOTE: this command `Change Night Shift Color Temperature` will just change the temp color without activate the night shift. at least this is the implementation in the mean time.

**Comment by hrvstr** [comment]
Hey @devmoath,

Thanks for the reply. I just did some more testing and found out that it is a different problem. I didn't realize that I can't confirm the new temperature value by just hitting `ENTER`. I have to press `CMD` + `ENTER`. Then it is working as expected. I am not sure if this is intentional or not but it kind of confused me as it is not really a "secondary action" like in other parts of Raycast where this key combo is used.

**Comment by devmoath** [comment]
@hrvstr yeah you are correct, I will see if I can change that

**Comment by devmoath** [comment]
Hi @pernielsentikaer, I'm reading the docs to make the submit form uses `ENTER` instead of `CMD` + `ENTER`, but I did not find anything related to that. 

also I'm searching for example from other extensions and I find out this, The create issue command from [GitHub Beta](https://www.raycast.com/raycast/github-beta) shows one button in the store screenshots but when downloaded its still uses `CMD` + `ENTER` for the form submission (see images bellow).

My question: is this possible to do ? if so please direct me to it please.

![github-1](https://user-images.githubusercontent.com/28797003/202270062-5e2990e1-74b0-414a-8171-a6a078adc3b9.png)
![CleanShot 2565-11-16 at 21 54 02](https://user-images.githubusercontent.com/28797003/202270070-5edab1e5-653e-44c0-bb15-3a173f640a8f.png)

**Comment by pernielsentikaer** [comment]
It's because on the first screenshot you'll see the old native extension for GitHub, the new one on the second screenshot is the open-sourced one - everything in Raycast uses ⌘+enter
