### ISSUE TITLE
Add action to allow users to clear the support directory of an extension

### ISSUE THREAD

**Issue by tonka3000** [raycast/extensions#3816]
When some content of the support directory of an extension get corrupted a user has no way to clear the support directory via the UI. If the corrupted data throw an exception, the user is stuck on the error screen (see #3801 ).

## The user has 2 options here

- Uninstall and install the extension

  Downside: The preferences of an extension get completely removed and everything need to get configured again, which can be very frustrating.

- Find the folder on the disk and remove it

  Downside: This requires some specific skills and is not doable by anybody.

## Proposal

Add an action that the user can delete the support directory of an extension. One place could be in the action menu of an command or the preferences menu of an extension like it is done with the logout button when an extension use OAuth.

This action would also be helpful for extension development as well.

**Comment by fe9lix** [comment]
I'm not sure whether adding such an action for end users would actually be helpful since a lot of users probably wouldn't know when to use this action or what it means to clear the support directory. Ideally, an extension would internally handle the error and "auto-recover". In the specific case you're mentioning, is there a way to catch this error in the extension itself?

**Comment by tonka3000** [comment]
> In the specific case you're mentioning, is there a way to catch this error in the extension itself?

I add some fixes in #3810 but I can not really do this for every variable. I need to check every variable.

Try/Catch around my component does not work in all cases because a component don't get e.g. a title so raycast throw the error and not the node process.

Maybe it could be an option to add the clear support directory to the error screen action.
![CleanShot 2022-12-08 at 12 33 56](https://user-images.githubusercontent.com/3163807/206436530-1b80be5e-4224-4c34-bbe0-ec258d220273.png)

I can change the prefix of my cache keys in my extension, so that my old cache get invalid and that would work but if there is a bug in it I have no really good way to recover. Any ideas?

**Comment by fe9lix** [comment]
In the case you show above (missing title), this is still an error in the extension where the component with its type information expects a required title but the extension provides a null value at runtime. An action that lets users clear the support directory does not appear intuitive to me and doesn't really seem to solve the root cause. This should be handled as much as possible in the extension through catching the error or providing fallback values.

I guess there is some place in the code where values that are going to be provided to required view component properties are stored (be it from an API response, the Cache, or something else). The fact that those properties are required is the invariant/API contract, so the client code (the extension) needs to ensure to satisfy this. This could be some sort of model that you check whether all values are provided as they should and if not, provide fallback values. If fallback values don't make sense either, there might be a real unrecoverable error that should then be surfaced to the user (e.g. through a Toast).

**Comment by tonka3000** [comment]
Released in 1.54.0
