### ISSUE TITLE
useSQL throws error code 14

### ISSUE THREAD

**Issue by crisboarna** [raycast/extensions#3853]
`useSQL` fails with error code 14 when trying to open Firefox `places.sqlite` file.

Raycast version: 1.44.0

## Description
When trying to open a SQLite file, it errors out with error code 14.

## Steps To Reproduce
Minimum reproducible command:

```javascript
import { List, showToast, Toast } from "@raycast/api";
import { Topic } from "./useStories";
import { useState } from "react";
import { useSQL } from "@raycast/utils";

export default function Command() {
  const [topic, setTopic] = useState<Topic | null>(null);
  // const [items, isLoading, error] = useStories(topic);
  const {} = useSQL(
    "/Users/cris/Library/Application Support/Firefox/Profiles/ctpx2o7a.default-release/places.sqlite",
    "SELECT\n" +
      "            id, url, title,\n" +
      "            datetime(last_visit_date / 1000000 + (strftime('%s', '1601-01-01')), 'unixepoch', 'localtime')\n" +
      "          FROM moz_places"
  );
  return <List></List>;
}
```

## The current behavior
It errors out with error code 14.
## The expected behavior
I should get a list of entries from Firefox history file.

Note that using WASM SQL approach as implemented in [3791](https://github.com/raycast/extensions/pull/3791) works.

<img width="757" alt="CleanShot 2022-12-10 at 20 39 56@2x" src="https://user-images.githubusercontent.com/12763781/206870440-ac731ebe-3b45-4422-bb9b-48d9d79b8d8f.png">
<img width="980" alt="CleanShot 2022-12-10 at 20 40 16@2x" src="https://user-images.githubusercontent.com/12763781/206870453-5873b079-18df-479f-b222-e5b185418359.png">

**Comment by mathieudutour** [comment]
`useSQL` and `sql.js` have very different approach. 

`sql.js` loads the entire database in memory and then query it. It means that if the database becomes to big, your extension will crash (and it's also a lot slower). It also means that you won't get the updated results if they change while your extension is running.

On the other hand, `useSQL` works on the database directly. It does mean that depending on how the database is used by the application, it will be blocked (because you can only have one process accessing the database at the same time).

So I wouldn't say that it is _expected_ that accessing an SQL database work if they don't implement WAL.

That being said, I implemented a workaround in the new version of the utils to make a copy of the database if we get an error 14 (and then query it). So it's pretty much the same as what sql.js does (with the addition of not loading it all in memory)

**Comment by crisboarna** [comment]
Hi @mathieudutour, 

I still get the same error even on the latest `1.4.12`, same code snippet as above.

<img width="745" alt="CleanShot 2022-12-12 at 15 31 16@2x" src="https://user-images.githubusercontent.com/12763781/207057250-064080c7-dc31-454a-bbd6-3d815832a56f.png">

<img width="952" alt="CleanShot 2022-12-12 at 15 33 01@2x" src="https://user-images.githubusercontent.com/12763781/207057571-9c7d76b0-3657-49ce-bc34-330118f24db1.png">

**Comment by mathieudutour** [comment]
Could you try to run `sqlite3 --json --readonly "/Users/cris/Library/Application Support/Firefox/Profiles/ctpx2o7a.default-release/places.sqlite" "SELECT id from moz_places"` when Firefox is opened? And when it's closed?

**Comment by crisboarna** [comment]
Hi @mathieudutour ,

When it is closed, I get a `14`, when it is open I get a `5`.

**Comment by crisboarna** [comment]
Hi @mathieudutour ,

`1.4.13` indeed remediates the sqlite3 error, thank you.
