### ISSUE TITLE
[Kill Process] Adding more details about homonym processes like Activity Monitor

### ISSUE THREAD

**Issue by Sulfyderz** [raycast/extensions#3913]
### Extension

https://www.raycast.com/rolandleth/kill-process

### Description

When I search "QuickLook" with your extension, I have 3 processes with the same name: QuickLookUIService.

Compared to Activity Monitor, I don't have any more precision about them. In Activity Monitor I have some information in parenthesis: 

- 'Finder';
- 'Open and Save Panel Service (Safari)';
-  'Open and Save Panel Service (com.apple.Safari.SandboxBroker (Safari))'.

Could you add these precisions?

### Who will benefit from this feature?

Everyone.

### Anything else?

Thank you for your work and your nice extension.

**Comment by rolandleth** [comment]
Hey! 

From the extension's settings you can configure it to display the process id and/or its path:
<img width="1112" alt="Screenshot 2022-12-31 at 12 15 26" src="https://user-images.githubusercontent.com/1858700/210132992-046ea3f5-92b3-4b8e-9ff0-f2354a8d2b94.png">

An from the extension's actions you can already copy its path:
<img width="862" alt="Screenshot 2022-12-31 at 12 16 25" src="https://user-images.githubusercontent.com/1858700/210133018-bac5b55f-49c2-456a-91f5-ec6c76909440.png">

There's not much else that can be added, because it appears that this is all the info `ps` offers.

**Comment by Sulfyderz** [comment]
Hello @rolandleth,

Thank you for your answer and your time.

Arf, I get it. I hoped to have more details about the processes like in Activity Monitor app.

**Comment by rolandleth** [comment]
Not sure what parenthesis you mean, `ps` doesn't output something like that.

**Comment by mathieudutour** [comment]
yeah, I'm talking about what Activity Monitor displays: in `Open and Save Panel Service (Safari)`, `Safari` is the parent process

**Comment by Sulfyderz** [comment]
Yeah, it would be great to have the parent folder in parenthesis whenever there are homonyms.

**Comment by rolandleth** [comment]
Yes, but the `ps` command I'm using for this script doesn't offer that kind of info, that's what I meant [here](https://github.com/raycast/extensions/issues/3913#issuecomment-1368195997). You can run `ps` from your terminal and see what info it offers and if you can find a way to display anything extra useful, I'd be open to having a look to implement it.

**Comment by mathieudutour** [comment]
I believe you can get the pid of the parent process for every process, then if you have a map of pid -> name, you should be able to get the name of the parent process? Not sure

**Comment by Sulfyderz** [comment]
> Yes, but the `ps` command I'm using for this extension doesn't offer that kind of info, that's what I meant [here](https://github.com/raycast/extensions/issues/3913#issuecomment-1368195997). You can run `ps` from your terminal and see what info it offers and if you can find a way to display anything extra useful, I'd be open to having a look to implement it.
> 
> > Yeah, it would be great to have the parent folder in parenthesis whenever there are homonyms.
> 
> You can already display paths for this, just that it shows the full path, not just the parent folder.

My bad, I meant parent process.

**Comment by rolandleth** [comment]
> I believe you can get the pid of the parent process for every process, then if you have a map of pid -> name, you should be able to get the name of the parent process? Not sure

> My bad, I meant the parent process.

Never tinkered with this more than tweaking the `ps` output to my needs, but if you find a way to do this, we could add a new setting for the extension, [Show parent process]. More than happy to make the extension more useful. Also very open to Pull Requests, since time isn't my ally on this, at this point.
