### ISSUE TITLE
[Linear] Add comment to issue from anywhere

### ISSUE THREAD

**Issue by coffenbacher** [raycast/extensions#4006]
### Extension

https://www.raycast.com/raycast/linear

### Description

I'd like to be able to highlight text and trigger Raycast to add a comment to a Linear issue from anywhere. 

So for example, if someone sends me a message in Slack or on Gmail about an open issue, I could just highlight it and do:

Raycast -> Linear: Add Comment To Issue -> (search for issue to add it to) -> (option to edit text, default highlighted text)

### Who will benefit from this feature?

I think this would be powerful for any users of Linear that use the comments feature to post updates to Issues. In my company we use this feature frequently to post updates from emails, share relevant URLs, or important discussion points from Slack so that they can all be found in Linear.

### Anything else?

An alternative would be a way to link a particular Gmail thread to a Linear issue such that every email in the thread comes as a new comment. That was my original thought, but I think it might be more difficult to do and in some ways less powerful.

**Comment by thomaspaulmann** [comment]
That's actually a cool idea. It could use a dropdown to search the issues and put the highlighted text into a text area below.

**Comment by thomaspaulmann** [comment]
@thomaslombart how do you feel about this? Any thoughts on how to best integrate it UX-wise?

**Comment by thomaspaulmann** [comment]
@coffenbacher I wonder if a similar command would be handy to use the selected text as a description in an issue.

**Comment by mathieudutour** [comment]
given you have to search for the issue, wouldn't it be enough to add an action to add a comment?

The flow would be:
- open "Search Issues"
- find your issue
- press the keyboard shortcut to add a comment
- A form gets pre-populated with the selected text

It does add a step from:
- open "Add comment to issue"
- A form gets pre-populated with the selected text
- find your issue

but it feels a bit more "integrated" to me 🤔

**Comment by coffenbacher** [comment]
@mathieudutour I actually didn't realize how powerful the Search Issues action is - it looks like I can already add a comment from there? That's cool! Definitely better than my current workflow. 

The following might not be exact but is kind of how I am thinking about it now? This is a workflow I do _all the time_ so saving even a single step feels really good. So just a highlight to pre-populate would be a great addition I think. 

Without Raycast:

- copy text
- open Linear using Raycast
- open Linear search
- find your issue
- press the keyboard shortcut to add a comment
- paste text
- edit

With Raycast - Search Issues (current)

- copy text
- open "Search Issues"
- find your issue
- press the keyboard shortcut to add a comment ( shift+option+command+n - this is a little gnarly but I guess I can get used to it 😅)
- paste text
- edit

With Raycast - Search issues (highlight text to prepopulate proposed improvement)

- open "Search Issues"
- find your issue
- press the keyboard shortcut to add a comment
- A form gets pre-populated with the selected text

With Raycast - Add Comment (dedicated flow proposed improvement)

- open "Add Comment to issue"
- A form gets pre-populated with the selected text
- find your issue

**Comment by mathieudutour** [comment]
For sure we could pre-populate the comment field yes, that sounds like a good improvement 👍

**Comment by thomaslombart** [comment]
I agree with @mathieudutour, going through the search issues command seems like a better solution. Generally speaking, I think it's better to have actions on list items than the other way around (`Search Issues > Action (comment, assign to, etc.) > Perform the action` instead of `Action > Search Issues > Perform the action`). 

That being said, this feature request sounds like a perfect use-case for a no-view command with command arguments such as `Create Issue for Myself`. The command would have two arguments: the issue key + the comment. That may be not the best UX since it's not possible to dynamically retrieve all the issues on command arguments but if you happen to know the issue key, it may be even quicker for your use case.

![CleanShot 2022-12-23 at 09 50 13@2x](https://user-images.githubusercontent.com/16003285/209304304-0b7a6bc1-e6b3-42ba-84ff-cbfc0a73a5e7.png)

Otherwise, populating the selected text on the comment form may be a good idea as well. I'm just wondering if this wouldn't require setting a preference for that. Let's say I don't want the form to get populated when adding a new comment, then I'll have to remove the text from the text area which can be annoying.

**Comment by coffenbacher** [comment]
Slick prototype! 😍 At first I was thinking that I'm unlikely to know the issue key off the top of my head, but then I realized that in most of the contexts I'd want to be quick adding a comment, there will be a link to the Linear issue or mention of the issue key. Usually it's from an email or Slack thread in my case. So that might actually be pretty viable / slick. 

As for pre-populating the text, I agree that might be annoying if unwanted, I guess it depends on how often people do commands with text highlighted unintentionally? In my case (and I think most people's) it's essentially never, but there are surely some people that do.

**Comment by thomaslombart** [comment]
The best would be to be able to have some sort of typeahead search on the issue key command argument but it's not possible at the moment and this sounds like a complex feature to implement (since command arguments are defined statically in `package.json`). (by the way, @thomaspaulmann, adding such a feature would be awesome. This would feel like quick links on steroids!)

> I guess it depends on how often people do commands with text highlighted unintentionally?

I honestly have no idea about the data behind that. It sounds like a good improvement but at the same time, I could see it being annoying in certain use cases. That's the problem with these kinds of tools/extensions. They're so flexible that users have lots of workflows (with some strange edge cases sometimes), so we have sometimes to be careful not to break their ways of working 😄

What do you think of the quick-add solution? Should we implement it?

**Comment by coffenbacher** [comment]
Typeahead version of your mockup would be the dream! Combined with selecting text to pre-populate the comment content, that would be about as slick as adding comments to an issue could possible be. And probably something that would be widely used I have to guess.

I would use the quick-add solution as it is, but I worry a little bit that it's narrowly fit to my particular use case and I don't want to waste your guys' time. Same with pre-populating Add Comment text on the Search Issues -> Add Comment flow - it would save me some time, but I'm not sure if it's compelling enough to spend your time on.

**Comment by thomaslombart** [comment]
This use case could benefit others. Quick-adding a comment to a Linear issue from Raycast seems like a nice feature. As far as it looks, it's OK for me to build it. However, I'm on vacation right now, so I'll get back to that in two weeks 😊

**Comment by coffenbacher** [comment]
Sweet! Thanks @thomaslombart , just tried it out, thanks!
