### ISSUE TITLE
[Extension Feature Request] Snippet Folders

### ISSUE THREAD

**Issue by edgarasben** [raycast/extensions#403]
Currently Snippets are organised on one level folder. It would be great if I could organise Snippets into folders, similar way that Alfred is doing it.

![image](https://user-images.githubusercontent.com/725324/142763591-f86b5c1e-5d8b-4423-9e24-6abc45d4f1ee.png)

**Comment by edgarasben** [comment]
Also, Alfred has a separate keyboard shortcut to open this snippet library.

**Comment by LeeBuckle** [comment]
+1

**Comment by davidleininger** [comment]
I won't be able to leave Alfred until there are snippet folders.

**Comment by lucaschultz** [comment]
+1

**Comment by thomaspaulmann** [comment]
This is planned and we'll start working on it soon. I'll close this issue because the feature request isn't related to an extension built with our API. The snippet extension is native and core part of Raycast. Keep an eye on our changelog and Twitter to see when we ship the folders. Thanks for reporting it!
