### ISSUE TITLE
[Raindrop] ...

### ISSUE THREAD

**Issue by KillDozerX2** [raycast/extensions#4043]
### Extension

https://www.raycast.com/lardissone/raindrop-io

### Description

Add command to create a new raindrop directly from Raycast. I've completely stopped using the app or the extension in favour of raycast, however I still have to open raindrop everytime I want to add a new bookmark

### Who will benefit from this feature?

People that use raindrop extensively to collect their bookmarks

**Comment by lardissone** [comment]
@KillDozerX2 thanks for your suggestion, it's something in my TODO list. I'm still considering this because it requires some background tasks when creating a new bookmark,ie: I need to get the list of tags, collections, etc, to be able to display those in the form.
Anyway I'll continue thinking and working on this.

**Comment by KillDozerX2** [comment]
Thanks, good to know someone’s thinking about it

**Comment by lardissone** [comment]
I'll put this on hold because the [TagPicker](https://developers.raycast.com/api-reference/user-interface/form#form.tagpicker) component doesn't let you create tags. I hope Raycast add support to this anytime soon otherwise you can only create bookmarks with existing tags.
