### ISSUE TITLE
[Toothpick] Device support form

### ISSUE THREAD

**Issue by natikgadzhi** [raycast/extensions#4081]
# Extension – [Toothpick](https://github.com/raycast/extensions/tree/d228408bdb2e9155158cc8ff175d0c79d6188141/extensions/toothpick/)

Hope this helps ;) 

**Device brand and model**

Sony WH-1000XM4

**Device data**
```
{
	"WH-1000XM4": {
		"device_address": "14:3F:A6:BC:78:F4",
		"device_firmwareVersion": "2.5.0",
		"device_minorType": "Headset",
		"device_productID": "0x0D58",
		"device_services": "0x800019 < HFP AVRCP A2DP ACL >",
		"device_vendorID": "0x054C",
		"device_connected": "true"
	}
}
```

It seemed to be recognized out of the box, but no fancy features like battery levels etc. Happy to help further if you need to debug anything, @VladCuciureanu.

**Comment by VladCuciureanu** [comment]
Hey! Thanks for this submission. So, this device is mapped in the latest version but to explain the current situation a bit...

The BlueTooth api we have access to is kinda limited.
Some devices share battery levels along with the rest of the device's metadata, in which case we display them.
Otherwise, if the device sends the battery level via other methods, we have no current way to fetch them.
Sadly, for WH-1000XM4, the case is the latter.

I have a companion app planned, kind of like a bridge that would give this extension access to more functionalities, like fetching battery levels, toggling ANC, etc. But for now it's just that. A plan.

Either way, any submission is helpful and appreciated. Have a nice day! 🌻

**Comment by natikgadzhi** [comment]
If I remember ble correctly, you’ll have to actually go talk to a service advertised in the metadata over ble, right?

**Comment by VladCuciureanu** [comment]
> If I remember ble correctly, you’ll have to actually go talk to a service advertised in the metadata over ble, right?
> 
> 

Yep. Something like that
