### ISSUE TITLE
[GitLab] Fuzzy Search for Projects

### ISSUE THREAD

**Issue by TribuneX** [raycast/extensions#4175]
### Extension

https://www.raycast.com/tonka3000/gitlab

### Description

Finding projects with the current search implementation of the [Gitlab extension](https://www.raycast.com/tonka3000/gitlab) requires to be precise in entering the projects names.
E.g. projects api-specification cannot be found with writing spec api. It would be awesome to have a fuzzy search feature for finding projects. Compared to e.g. https://github.com/lukewaite/alfred-gitlab where its easy to do fuzzy search. Although, I think the search itself is provided by Alfred instead of the plugin.

### Who will benefit from this feature?

Every extension user

**Comment by TribuneX** [comment]
I could also try to contribute here if you point me to some code sections where to look at for extending the search.

**Comment by tonka3000** [comment]
Hi @TribuneX ,

Which command did you use? It depends on the command if there is fuzzy search in place (fuzzy is done through fuse.js).

e.g. `My Projects` or `My Starred Project` use fuzzy search. Most commands which can be prefetched use local fuzzy search. All others, like `Search Project` using the GitLab API search directly because I can not prefetch millions of projects before and AFAIK GitLab API has no fuzzy search in there API.

Example:
![CleanShot 2023-01-07 at 18 16 58@2x](https://user-images.githubusercontent.com/3163807/211162649-30b69236-8b24-4131-8387-5068fc696712.png)

I can expose the fuse.js threshold as preference. Right now it is `0.2`. When I use a higher number I got very imprecise matches. You can play around with it when you change values [here](https://github.com/raycast/extensions/blob/8bc9f1664a7a1b183de14da21a75f841200b6eb0/extensions/gitlab/src/gitlabapi.ts#L796)

**Comment by leeoniya** [comment]
some (better) alternatives to Fuse: https://github.com/leeoniya/uFuzzy#a-biased-appraisal-of-similar-work

**Comment by TribuneX** [comment]
I am mostly using the `My Starred Projects` search. Although I also miss the cache behavior of the linked Alfred plugin, which was able to do fuzzy search on cached project lists. 
I‘ll try to change the options to see how this affects the search.
As a result I would like to be able to find projects like `api-specification` also by entering `spec api`.

**Comment by TribuneX** [comment]
I still wonder daily why certain projects to not appear 😢. 
@tonka3000 How can I change the threshold in my current setup to see if it helps?
