### ISSUE TITLE
[Urban Dictionary Search] ...Automatic submission of search results is too fast

### ISSUE THREAD

**Issue by jovidalao** [raycast/extensions#4194]
### Extension

https://www.raycast.com/Sheraff/urban-dictionary

### Description

Automatic submission of search results is too fast, When entering text, it will be submit immediately.

**Comment by Sheraff** [comment]
@jovidalao could you explain a little more what you mean? Maybe a video screen grab?

PS: I have stopped using raycast because I found it too slow and not ergonomic compared to Alfred. But if this issue is easy to fix I can still take a look.

**Comment by sannidhyaroy** [comment]
I've noticed this too... Tried to reinstall the extension but it's still the same.

@Sheraff I think this video will explain it better

https://user-images.githubusercontent.com/58990408/211273388-9b9e7251-dbc5-4400-8dc3-d6d00fa5ba59.mov

As an example, I tried searching for `plants`. You can notice that when I type this fast, it would display the search results and then clear the input word. Now, when I try typing it slowly, I won't be able to type the entire word before it clears out the input.

### The issue is it shouldn't clear the input word even after showing the search results.

**Comment by Sheraff** [comment]
This seems like a change from Raycast since it didn't behave like this when I developed this extension. There is probably a fix to be done, but I don't think I'm going to be the one doing it.

**Comment by jovidalao** [comment]
> @jovidalao could you explain a little more what you mean? Maybe a video screen grab?
> 
> PS: I have stopped using raycast because I found it too slow and not ergonomic compared to Alfred. But if this issue is easy to fix I can still take a look.

https://user-images.githubusercontent.com/46136368/211694831-60121f5e-94f0-4395-a01e-8d95ed4fccef.mp4


Thank you for your reply, this is a screen recording. I try to query LOL
