### ISSUE TITLE
[Vivaldi] Allow user to select profile

### ISSUE THREAD

**Issue by TwisterMc** [raycast/extensions#4210]
### Extension

https://www.raycast.com/crisboarna/vivaldi

### Description

When I setup the Raycast extension, it appears to only be pulling information from the first profile. I'd like to be able to choose what profile it pulls information from.

### Who will benefit from this feature?

Any user with multiple profiles in Vivaldi.

**Comment by crisboarna** [comment]
Hi @TwisterMc 

In order to shed some light on the issue and perhaps discover a solution through crowdsourcing, please refer to this [comment](https://github.com/raycast/extensions/issues/4287#issuecomment-1399221312)

In essence as mentioned there, searching through profiles is possible, opening your selection in specific profile is not.
