### ISSUE TITLE
[API Feature Request] Dropdown Item - support for numeric values

### ISSUE THREAD

**Issue by Padamdam** [raycast/extensions#4249]
### Description

Dropdown items should support numeric values (ex: customer ID) and not only string values.

This would remove the need to parse the value to numeric.

**Comment by mathieudutour** [comment]
Thank you for opening this feature request! However, that's not something we will implement for the following reason: returning a string or a number would force you to cast the value every time. 

If I have an dropdown that only deals with strings (like 95% of the time), I would then need to make sure to parse the value into a string otherwise TypeScript will complain. It's not possible (or very very hard) to know at build time what type of value you pass to the dropdown items and so we would have to have a generic `string | number` value type which will increase the boilerplate for everybody (even in your numeric values case!)
