### ISSUE TITLE
[Google Chrome] Enabled to choose profile

### ISSUE THREAD

**Issue by Cat1007** [raycast/extensions#4287]
### Extension

https://www.raycast.com/Codely/google-chrome

### Description

when I have two chrome window using two sperate profiles, one for docs and the other for debug.
new tabs alaways open on debug window and other features like search will be operated in debug profile.
I want to choose or have a default setting to specify the default profile

**Comment by crisboarna** [comment]
Hi @Cat1007,
Unfortunately due to the incomplete implementation of AppleScript support in [Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=174117) makes it impossible to provide a way to select the profile in which a tab is to be open.

At most what can be done is to add a search bar accessory to specify which profile to search in for bookmarks/history, but the opening of a new tab cannot be controlled, it will happen randomly in the top most window of Chrome at the time of the command being run.

I still see value in having the ability to search through profiles nevertheless, so I'll look at adding that, knowing that some entries will need a copy paste into desired profile(ex: logged in only on the development profile into Github)

Best that can be done unless somebody completes support for Chromium AppleScript support 🤷
