### ISSUE TITLE
[API Bug] Form.DatePicker and Form.Dropdown cannot be reset

### ISSUE THREAD

**Issue by loris** [raycast/extensions#443]
Raycast version: v1.25.7

## Description

Both Form.DatePicker and Form.Dropdown should reset to their initial state if we change back their `value` prop to `undefined`, but it is not working as expected

## Steps To Reproduce

1. Use this simple test form code:

```
export default function TestForm() {
  const [date, setDate] = useState();

  return (
    <Form>
      <Form.DatePicker
        id="date"
        title="Date"
        value={date}
        onChange={(val) => {
          setDate(val);
          setTimeout(() => setDate(undefined), 2000);
        }}
      />
    </Form>
  );
}
```
2. Render it and change the Date input to any value

## The current behavior

The input will keep displaying the first selected value

## The expected behavior

it should reset (ie, "No Date") after 2 seconds

**Comment by fe9lix** [comment]
Hey @loris, I'll close this issue since the standard React behavior is actually that setting the value back to `undefined` would turn this into an uncontrolled component again (so it would act as if value was not defined at all). This is still not working currently but it's a different type of bug. If you want to reset a value, you can use null, empty string or whatever other value represents a "none item" or default value in your case.
