### ISSUE TITLE
[ray.so] Title and Code provided in action not available in Result

### ISSUE THREAD

**Issue by andre-s-sousa** [raycast/extensions#4432]
### Extension

https://www.raycast.com/garrett/ray-so

### Description

Provided input to action "Create Image from Code":
![image](https://user-images.githubusercontent.com/65219481/214558152-23162e44-0687-45d3-be43-0ef42965e790.png)

Generated page:
![image](https://user-images.githubusercontent.com/65219481/214558246-08fd95b0-ff4e-4acd-9ce6-3b76b6aa63c5.png)

Generated URL:
https://ray.so/?theme=candy&background=true&darkMode=true&spacing=16&title=Test&code=aW50ZXJmYWNlIFVzZXIgewogIG5hbWU6IHN0cmluZzsKICBpZDogbnVtYmVyOwp9&language=auto

### Steps To Reproduce

1. Run create image from code
2. Fill title
3. Fill code
4. Execute action

### Current Behaviour

Default ray.so page is shown with random code snipped

### Expected Behaviour

Ray.so page contains provided code with provided title.

**Comment by andre-s-sousa** [comment]
Just as a quick comment, not 100% sure if a new issue should be opened, the title is not being escaped as a string with "", so it's not inserted into the generated page
https://ray.so/#theme=candy&background=true&darkMode=true&spacing=16&title=Test&code=aW50ZXJmYWNlIFVzZXIgewpuYW1lOiBzdHJpbmc7CmlkOiBudW1iZXI7Cn0&language=auto
VS
https://ray.so/#theme=candy&background=true&darkMode=true&spacing=16&title="Test"&code=aW50ZXJmYWNlIFVzZXIgewpuYW1lOiBzdHJpbmc7CmlkOiBudW1iZXI7Cn0&language=auto

**Comment by RSO** [comment]
Thanks for catching that! I just pushed a fix for this.

--- original message ---
On January 25, 2023 at 9:15 PM GMT+1 ***@***.*** wrote:



Just as a quick comment, not 100% sure if a new issue should be opened, the title is not being escaped as a string with "", so it's not inserted into the generated page

https://ray.so/#theme=candy&background=true&darkMode=true&spacing=16&title=Test&code=aW50ZXJmYWNlIFVzZXIgewpuYW1lOiBzdHJpbmc7CmlkOiBudW1iZXI7Cn0&language=auto

VS

https://ray.so/#theme=candy&background=true&darkMode=true&spacing=16&title="Test"&code=aW50ZXJmYWNlIFVzZXIgewpuYW1lOiBzdHJpbmc7CmlkOiBudW1iZXI7Cn0&language=auto

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you modified the open/close state.Message ID: ***@***.***>
--- end of original message ---
