### ISSUE TITLE
[Toothpick] Device Support Form

### ISSUE THREAD

**Issue by DJP1981** [raycast/extensions#4442]
### Extension

https://www.raycast.com/briankosw/toothpick

### Description

<b>Oneplus 9 Prol</b>
Replace this line with your device's brand name and model

<b>{"OnePlus 9 Pro":{"device_address":"D0:49:7C:C5:FD:3F","device_firmwareVersion":"20.3.6","device_minorType":"MobilePhone","device_productID":"0x1200","device_rssi":"-37","device_services":"0x900000 < GATT ACL >","device_vendorID":"0x001D","device_connected":"true"}}</b>
Replace this line with the copied data

### Who will benefit from this feature?

Eu

**Comment by VladCuciureanu** [comment]
I haven't mapped phones before since I don't find them a priority (most people only have one so no need for a custom icon and they don't send the battery percentage via BT so no battery level meter either). 
But I'm curious... What feature are you requesting? What do you wish to accomplish by using Toothpick with your phone?

**Comment by VladCuciureanu** [comment]
@raycastbot close this issue
