### ISSUE TITLE
[Music] ... missing music control icons

### ISSUE THREAD

**Issue by waterstone15** [raycast/extensions#4466]
### Extension

https://www.raycast.com/fedevitaledev/music

### Description

When a music control command is used the toast notification is showing a 'question-box' icon instead of the expected music control icon.

### Steps To Reproduce

Unsure how to reproduce. I've uninstalled and reinstalled both the Music add on and Raycast itself.

I'm on Raycast version 1.46.1

### Current Behaviour

Incorrect music control icons.

### Expected Behaviour

Correct music control icons.

**Comment by peterdev22** [comment]
Try downloading Apple's SF Symbols [here](https://developer.apple.com/sf-symbols/), then it should start displaying the icons.

I think these icons need to be replaced (or removed) since I wasn't aware of SF Symbols not being in MacOS's system files. - I'll look into Raycast's symbols and see if they can be displayed in HUD notifications.

**Comment by waterstone15** [comment]
This did the trick, thanks!

**Comment by peterdev22** [comment]
@Rawnly I looked through the documentation and there's nothing about adding Raycast symbols to HUD notifications. Only for lists and actions.

I've seen an extension with symbols in the HUD, the clipboard history extension, but I don't think it's an actual extension since it's built into the app - so it's not in this repository.
![image](https://user-images.githubusercontent.com/95014170/215301487-6eda4723-15f2-4593-ad94-785d77f54993.png)

**Comment by Rawnly** [comment]
@peterdev22 if we can find a way to check if the icon can be rendered (eg by checking SF Symbols installation) we could render icons conditionally

**Comment by Rawnly** [comment]
It can be done via: 

```osascript
tell application "Finder" to get displayed name of application file id "com.apple.sfsymbols"'
```

**Comment by Rawnly** [comment]
@raycastbot close this issue
