### ISSUE TITLE
[Extension Feature Request] Todoist should show Nested Tasks

### ISSUE THREAD

**Issue by SmashMineGame** [raycast/extensions#449]
# Extension – [Todoist](https://github.com/raycast/extensions/tree/main/extensions/todoist)
Author: @thomaslombart

**Describe the feature and the current behavior/state.**
Nested Tasks are all listed in line as if they were all of the highest level. The nested ones should be indented and put in the correct position so that it makes sense visually.

**Who will benefit with this feature?**
Anyone that uses the nested tasks feature in Todoist. I think it might also be called subtasks.

**Comment by thomaslombart** [comment]
Indeed, subtasks are not supported at the moment because I haven't found an easy way of retrieving subtasks from the [Todoist REST API](https://developer.todoist.com/rest/v1/#overview). I'll let you know in this issue if I find a way of doing it!

**Comment by SmashMineGame** [comment]
Each task has a `parent_id` property which is empty if the task is top level. It's a bit roundabout but it could be used. 

For the today and upcoming views, maybe a "see sub-tasks" action can be added to the menu and it would look that the project that the main task is from and display all the tasks in that project who have the correct parent_id value. 

For the project views, maybe you could insert any task that has a parent_id into the correct position with the indentation after all the top-level tasks are added.

What are your thoughts?

**Comment by thomaslombart** [comment]
Yeah, I could see a "see sub-tasks" action.

However, it's not possible for now to indent a list item as of today with the Raycast API. So, if a task is at the root level and does have subtasks, don't show subtasks and instead show an accessory icon that indicates it has subtasks (something like a right chevron could do it). 
There would be a problem, however: the accessory icon is used to indicate if a task is recurring. It wouldn't be possible to indicate if a task is both recurring **and** has subtasks.

**Comment by SmashMineGame** [comment]
A see subtasks action would be nice. I think that the indicator isn't necessary, and maybe can be added later if raycast gives more options what can be added to a List Item.

**Comment by thomaslombart** [comment]
Let's go for that then. I'll work on it this weekend.

**Comment by thomaslombart** [comment]
Update on this task's status: the REST API makes it tedious to retrieve the subtasks associated with a task simply because there are no parameters associated with the [GET tasks endpoint](https://developer.todoist.com/rest/v1/#get-active-tasks). It's not possible to use a filter for that either.

There are two things to do here:
1. Include an action panel item "See sub-tasks" if a task does have subtasks
2. Show the subtasks in a list view

For the first one, I don't see any other options than fetching **all** of the tasks in order to see which task is associated with a certain parent ID. This is a deal-breaker for me since one can have a lot of tasks and the call can be quite long.

For the second one, the only solution I've seen is to fetch the tasks by using a "subtasks" filter. But once again, we're fetching all subtasks instead of the dedicated subtasks of a certain task.

So, I don't see how to support nested tasks. In the meantime, I hid the nested tasks in the project view to have a clearer view and see only your root tasks just like in Todoist: https://github.com/raycast/extensions/pull/527

Let me know if you have other ideas, otherwise, I'd suggest closing this issue or putting it in a frozen state waiting for improvements from the API.

**Comment by utkarshk384** [comment]
What is the status of this feature?

**Comment by thomaslombart** [comment]
After checking with a Todoist's team member, adding this feature would imply a significant revamp of the extension since the extension would need to retrieve the entire tasks list on load (shifting from the [REST API](https://developer.todoist.com/rest/v1/#overview) to the [Sync API](https://developer.todoist.com/sync/v9/#overview)). This also has some drawbacks to the maintainability of the extension since the TypeScript client used to interact with Todoist would be useless.

If someone wants to work on it, please do. But it's unlikely I'll work on it in the next weeks.
