### ISSUE TITLE
[Extension Feature Request] Emoji fuzzy search + keywords

### ISSUE THREAD

**Issue by patrick91** [raycast/extensions#451]
# Extension – [Emoji](https://github.com/raycast/extensions/tree/main/extensions/emoji)

Author: @FezVrasta

**Describe the feature and the current behavior/state.**
It would be nice to fuzzy search emoji based on their name and some keywords. I've done a POC
and it seems to work quite well for my usecase. 

<img width="787" alt="image" src="https://user-images.githubusercontent.com/667029/144118415-18a2047b-9a37-45fb-9aeb-94b4efd09158.png">

(this is done with fuse.js for fuzzy search and emojilib to get keywords)

**Who will benefit with this feature?**

Me :D and all people that don't remember emojis are called

**Any Other info.**

I'm happy to send a PR if that's ok 😊

**Comment by FezVrasta** [comment]
That'd be a great addition! It was in my todo list so it'd be great if you sent a PR to add it

**Comment by timonbimon** [comment]
Would be amazing if this could stay open 😇

**Comment by lucaschultz** [comment]
Yup this sounds awesome 💪

**Comment by timonbimon** [comment]
@patrick91 did you ever get the chance to send that MR you talked about? I know I'm kind of free-riding here, but this is the last thing that's stopping me from switching from Alfred that's why I regularly come back here to check if the "find emojis with alternative names "has been added (without it it's just impossible to use in my opinion)  😬

**Comment by FezVrasta** [comment]
I used the emojilib

**Comment by timonbimon** [comment]
It works like a charm. Thank you so much @FezVrasta 🚀 Time to switch to Raycast. 😇
