### ISSUE TITLE
[Toothpick] Device Support Form

### ISSUE THREAD

**Issue by adamarbour** [raycast/extensions#4621]
### Extension

https://www.raycast.com/briankosw/toothpick

### Description

<b>Device brand and model</b>
Beats Flex

<b>Device data</b>
{"Beats Flex":{"device_address":"74:8F:3C:0B:73:25","device_firmwareVersion":"3.7.2","device_minorType":"Headphones","device_productID":"0x2010","device_rssi":"-61","device_serialNumber":"FL6GMGHSQ1HL","device_services":"0x880019 < HFP AVRCP A2DP AACP ACL >","device_vendorID":"0x004C","device_connected":"true"}}

**Comment by maximuscode** [comment]
I wanted to raise an issue for Bose Headphones and even Magic Mouse 2, then realised that I haven't checked permissions from my side. So after going to "System Settings >> Privacy & Security >> Bluetooth" and adding Raycast as a trusted app the problem was resolved. Leaving it here just in case. Peace!

P.S.
@briankosw  / @VladCuciureanu GREAT EXTENSION, BLESS UP  🤍👏🏻

**Comment by VladCuciureanu** [comment]
@maximuscode Glad you like the extension! Thanks for sharing the solution

@adamarbour Hey! While I do appreciate your submission, this device is mapped already.
Given the fact that there's no extra info added I'll close this ticket.

@raycastbot close this issue
