### ISSUE TITLE
[Spotify Controls] ... Add command to dislike song and skip to the next song

### ISSUE THREAD

**Issue by tomershukhman** [raycast/extensions#4671]
### Extension

https://www.raycast.com/thomas/spotify-controls

### Description

Hi,
It would be great if there was an option to dislike a song and skip at once,
Usually when I dislike a song I skip, so one action isted of two would be nice.

**Comment by thomaspaulmann** [comment]
Maybe instead of another command, this could be an preference on the "Next Track" command? Or maybe better on the "Like Current Song" and when it dislikes it, you can have the preference to go to the next track. The latter command is not part of the Spotify Controls extension but the [Spotify Player](https://www.raycast.com/mattisssa/spotify-player) one. Do you want to contribute to it?
