### ISSUE TITLE
[Google Workspace] ...

### ISSUE THREAD

**Issue by JhonnyAxe** [raycast/extensions#4685]
### Extension

https://www.raycast.com/raycast/google-workspace

### Description

Hi! Every time I try to activate the extension I receive this:
![CleanShot 2023-02-09 at 11 44 45](https://user-images.githubusercontent.com/84262172/217761502-0951f006-87fc-4d23-a1b6-3eb123931b4c.png)

I tried to upgrade and reinstall the extension but it didn't change the thing...
https://dsh.re/0995c

**Comment by thomaslombart** [comment]
Hey there! Yes, it's expected 😊

Google Workspace was previously an extension native to Raycast, but it's been rebuilt and open-sourced for a few months. You can install it in the store (https://www.raycast.com/raycast/google-workspace)

**Comment by JhonnyAxe** [comment]
I install from the official store and it's the sameOn 9 Feb 2023, at 12:02, Thomas Lombart ***@***.***> wrote:﻿
Hey there! Yes, it's expected 😊
Google Workspace was previously an extension native to Raycast, but it's been rebuilt and open-sourced for a few months. You can install it in the store (https://www.raycast.com/raycast/google-workspace)

**Comment by thomaslombart** [comment]
Are you running the latest Raycast version? (should be 1.47.3)

**Comment by thomaslombart** [comment]
After checking that with the team, there's indeed a bug on our end. When searching for something in Raycast's root search, you get a list of [fallback commands](https://manual.raycast.com/fallback-commands) if it can't find anything relevant.

When searching for `{Query}` in your example, you're getting a fallback command from the native Google Workspace extension, not the one you installed. That's where the bug is: we shouldn't show fallback commands for deprecated extensions 😬

Here's the list of steps to fix it:
1. Open the `Manage Fallback Commands`
2. Search for `Search Google Drive Files` and disable it (through the `Disable Fallback Command`)
3. Install the `Google Workspace` extension from the store
4. Add the `Search Google Drive Files` as a fallback command

And you should be good to go 😊

We'll fix it on our end, so this doesn't happen again in the future.

**Comment by JhonnyAxe** [comment]
The latest one, yes

Best regards,
Pavel

**Comment by JhonnyAxe** [comment]
Got it, thanks!

Best regards,
Pavel
