### ISSUE TITLE
[Toothpick] Device Support Form

### ISSUE THREAD

**Issue by kiranjd** [raycast/extensions#4707]
### Extension

https://www.raycast.com/briankosw/toothpick

### Description

<b>Device brand and model</b>
JBL TUNE 130NC

<b>Device data</b>
{"JBL TUNE130NC TWS":{"device_address":"28:6F:40:05:01:17","device_minorType":"Headset","device_services":"0x800019 < HFP AVRCP A2DP ACL >","device_connected":"true"}}

### Who will benefit from this feature?

Users of JBL headphones

### Anything else?

https://www.amazon.in/JBL-130NC-Active-Cancellation-Earbuds/dp/B09HGW9V7D/ref=sr_1_1_sspa?adgrpid=67891045401&ext_vrnc=hi&gclid=CjwKCAiA0JKfBhBIEiwAPhZXDzRkneXwoEcldKqCQCAGnOB23Lh9a157cW_JrVtghSKX3nqWA5U-MRoCv-oQAvD_BwE&hvadid=398054182492&hvdev=c&hvlocphy=9062134&hvnetw=g&hvqmt=e&hvrand=5384535848385203301&hvtargid=kwd-1416629574671&hydadcr=18849_1972034&keywords=jbl+tune+130nc&qid=1675979561&sr=8-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1

**Comment by VladCuciureanu** [comment]
Hey! While I do appreciate your submission, the device data is missing a vendor id and a product id. This is the first time I see this happen and my intuition says that there's nothing we can do since this device doesn't send that info over BT. For now, since I don't have that data, there's no way for me to map it. Sorry ☹️

Since that there's not much we can do, I'll close this issue.
@raycastbot close this issue
