### ISSUE TITLE
[Open Path] First open is successful, second open is not

### ISSUE THREAD

**Issue by HerrNiklasRaab** [raycast/extensions#4783]
### Extension

https://www.raycast.com/koinzhang/open-path

### Description

https://www.loom.com/share/da59026e290e42a6b78b227588615884

**Comment by koinzhang** [comment]
Hi @HerrNiklasRaab. Watching your video I probably understand what you mean, but this is not an extension problem, it should be considered a Raycast problem. Because when you reopen the Raycast interface, the text that is selected is the text in the Raycast input box, so you use Open Path again here will recognize `Open`.
I can make a simple improvement by clearing the content of the input box after using Open Path again, hope this can help you!

**Comment by HerrNiklasRaab** [comment]
Hey @koinzhang, thx for the quick response. Now I understand, not sure if this makes a difference. I guess this then can be closed :D
