### ISSUE TITLE
[Hue] Too many requests

### ISSUE THREAD

**Issue by astrit** [raycast/extensions#4929]
### Extension

https://www.raycast.com/pindab0ter/hue

### Description

Even tho I managed to connect successfully after a while it throws this error, it usually work only the first time 

<img width="760" alt="CleanShot 2023-02-23 at 11 34 31@2x" src="https://user-images.githubusercontent.com/2398447/220883384-9c9f97ac-3ae1-498b-b6bb-0ddde9f0b33d.png">

@pindab0ter 

### Steps To Reproduce

1. Open Raycast
2. Open one of the commands ( Control Groups, Lights, Set Scene )

**Comment by pindab0ter** [comment]
Hey, this is something that I noticed, too. I currently don't have the time to look into this.

Some things to note, though. The library that is used to interface with Hue does (should) honor rate limiting.

Something that I can think of that could possibly be an issue is multiple calls because a view is rendered multiple times when it should only be rendered once.

If anyone is willing to look into this, that'd be great!

**Comment by pindab0ter** [comment]
I've made some improvements in #5647 that hopefully result in the 429 error not happening unwarranted any more.

Please let me know if you still experience the issue after you've tried the update once it is available.
