### ISSUE TITLE
[Extension Feature Request] Add missing key symbols

### ISSUE THREAD

**Issue by donovanroubos** [raycast/extensions#500]
# Extension – [Unicode Symbols](https://github.com/raycast/extensions/tree/main/extensions/unicode-symbols/)

Author: @mmazzarolo

**Describe the feature and the current behavior/state.**
Currently the list of symbols is quite good! But it seems like I'm missing some key symbols like:
- `⇪` capslock
- `⇧` shift
- `⌃` control
- `⌥` option (alt, alternative)
- `` apple symbol 1
- `⌘` command (open apple) 2
- `⏎` return
- `⌫` back
- `⇤` tab back
- `⇥` tab forward
- etc

**Who will benefit with this feature?**
Anyone who will be using key symbols to explain shortcuts to others.

**Any Other info.**
_Previously I've used Alfred in combination with [Symbols](https://github.com/bevesce/unicode-symbols-search) workflow._

**Comment by mmazzarolo** [comment]
@donovanroubos I like this proposal. Do you know [the Unicode blocks](https://en.wikipedia.org/wiki/Unicode_block) these symbols are in?

**Comment by zepfietje** [comment]
> _Previously I've used Alfred in combination with [Symbols](https://github.com/bevesce/unicode-symbols-search) workflow._

Thanks for opening this issue @donovanroubos! I actually thought about it this week.

> Do you know [the Unicode blocks](https://en.wikipedia.org/wiki/Unicode_block) these symbols are in?

@mmazzarolo some of them seem to be in "[Miscellaneous Technical](https://en.wikipedia.org/wiki/Miscellaneous_Technical)".

**Comment by mmazzarolo** [comment]
Thanks, @zepfietje !
At this point, I'm wondering if it would be worth it to add a section of Unicode characters manually so that we can add common symbols without having to add the entire block. 

Some pro/cons I can think about are:

Cons:
- It would be an "exception" to the common rule/patterns
- We would need to come up with descriptions for the characters (and as a rule of thumb us the original description by looking for the characters in the official Unicode list)

Pros:
- Adding new symbols would be as easy as sending a PR

**Comment by zepfietje** [comment]
Hmm not sure. Just adding the entire block would make sense maybe, but then you'd probably still like to alias the symbols if you want to find them easily.

**Comment by mmazzarolo** [comment]
The thing is, the more blocks we add, the more the list will slow down. Additionally, the more items we have on the list, the more we'll add uninteresting items that worsen the search results. 
(I'm saying this because I don't see all the symbols mentioned in the issue description in that block, so I assume we'd have to add multiple blocks 🤔)

**Comment by zepfietje** [comment]
Yeah I agree only adding symbols upon request is probably the best idea then.

**Comment by donovanroubos** [comment]
> Yeah I agree only adding symbols upon request is probably the best idea then.

Slowing down the process seems not very desirable. Adding requested symbols by PRs should be fine by me! 😄

**Comment by donovanroubos** [comment]
Just curious, wat is the current status of this issue? @mmazzarolo

**Comment by mmazzarolo** [comment]
@donovanroubos open? 😬 
I haven't had a chance to work on it, I'm a bit busy, PRs are very welcome though!

**Comment by donovanroubos** [comment]
> @donovanroubos open? 😬 I haven't had a chance to work on it, I'm a bit busy, PRs are very welcome though!

Aah gotcha, I was just curious on how the progress was managed. But I fully understand you all are busy with (other) stuff ;)

**Comment by megaroeny** [comment]
Would this be able to be looked at again? I'd love to have these technical symbols added to the emoji search possibly.
