### ISSUE TITLE
[Asana] New tasks assignee is broken and should be default

### ISSUE THREAD

**Issue by alper** [raycast/extensions#5008]
### Extension

https://www.raycast.com/raycast/asana

### Description

I can't find the assignee to set for a task I create in Asana with Raycast.

This is a critical feature that seems to be buggy.
![CleanShot 2023-02-27 at 11 48 29@2x](https://user-images.githubusercontent.com/72429/221544277-19b20ede-e1ab-4b79-acd1-ca4ec7de0a99.png)

Moreover for a quick entry such as this having to set the assignee every time is kinda annoying so it should default to the logged in person (or be a setting, or be sticky).

### Steps To Reproduce

See screenshot.

**Comment by thomaslombart** [comment]
That's weird. Do you have any results in the `Assignee` field? Are there a lot of users in your workspace? Have you searched with your name instead of your username?

It's unassigned by default because the extension can also be used by other users, such as product managers who want to assign tasks to others. It can also quickly report a bug to a backlog without knowing who will tackle it. Note that the field is supposed to remember the value once creating the task, so you should be fine afterward.
