### ISSUE TITLE
[Extension Bug] Todoist Doesn't Separate Overdue and Today Tasks in Today View

### ISSUE THREAD

**Issue by SmashMineGame** [raycast/extensions#502]
# Extension – [Todoist](https://github.com/raycast/extensions/tree/main/extensions/todoist)
Author: @thomaslombart

**Describe the bug and the current behavior/state.**
I have both overdue and today tasks, however the app just shows all of the tasks together without separating the two groups. This works properly in Upcoming View.

**Comment by thomaslombart** [comment]
The overdue tasks are handled in both today and upcoming views. Where do you get the bug?

**Comment by SmashMineGame** [comment]
When I look at my Today tasks view, all of the task shown are in an “overdue” section, even though most of them should be in another section called “today”. I was explaining that the upcoming tasks view does not have this problem.

**Comment by thomaslombart** [comment]
I'm not sure I get what you mean. As of today, the upcoming and today views show tasks in an "overdue" section if the due date is before today. I can't reproduce with my local setup.

Can you maybe share a screenshot?

**Comment by lukthony** [comment]
@thomaslombart Hate to risk reviving this unnecessarily, but this is an active bug/oversight. When you open today's tasks, it makes it seem like all the tasks due today are overdue. They are not overdue. They are just due today. It seems this extension mistakes "today" with "overdue" and "today" with "tomorrow". The tasks in the "upcoming" view under "tomorrow"(in todoist) are labeled "today". It's like the extension is a day off.

Here's a screenshot:
<img width="748" alt="Screen Shot 2022-01-31 at 7 09 59 PM" src="https://user-images.githubusercontent.com/65358837/151898888-42cd4870-07b4-40c2-a341-d13f411753d8.png">
The tasks in this screenshot are not overdue—they're due today. Listing them as overdue is incorrect.

Furthermore, here's a screenshot of the "upcoming" view:
<img width="758" alt="Screen Shot 2022-01-31 at 7 18 16 PM" src="https://user-images.githubusercontent.com/65358837/151899361-4abce1ad-8720-4740-9617-581c80d4a345.png">
The tasks listed under "today" here aren't today's tasks—they're due tomorrow. Listing them as today's tasks is incorrect. 

Further days of the week are also incorrect. My Tuesday tasks are labeled today, my Wednesday tasks are labeled tomorrow, and so on. (This was written on a monday).

**Comment by thomaslombart** [comment]
@lukthony My gut feeling is that there must be something's wrong with timezones. Would you mind sharing what's your timezone so that I make a few tests?

**Comment by lukthony** [comment]
@thomaslombart that's a good idea. I'm in CST, central standard time. (UTC-6)

**Comment by thomaslombart** [comment]
After some investigations, it seems timezones are indeed the root cause of the problem. I can't promise I'll get a fix in the next few days since I'm busy with other work right now, but I'll try to get it done in the next few weeks.

**Comment by thomaslombart** [comment]
@lukthony Have you switched between timezones recently? For example, did you enter some tasks in Todoist, traveled somewhere, and saw these tasks in Raycast?

I think that's the root cause of the issue. According to [Todoist REST API](https://developer.todoist.com/rest/v1/#tasks), the date is a _"Date in format YYYY-MM-DD corrected to user's timezone."_

So, there shouldn't be an issue if you stay within the same time zone. But if you create a task, say at 10 PM, and switch to a timezone that is 4 hours in advance (2 AM), the task will still be considered as a task from yesterday on the API's side while it should be a task due today.

Not sure of that yet, but according to some tests, that seems to be the problem.

**Comment by lukthony** [comment]
@thomaslombart That's interesting, but unfortunately I haven't switched time zones at all recently. Been lingering here in CST for a long time now. Further, I've added more tasks since I first saw the problem, and it persists regardless.

**Comment by thomaslombart** [comment]
Thanks for the answer. The problem must come from somewhere else then. My other guess is that I'm making comparisons using the `Date` constructor which returns the date to UTC time, but since Todoist returns tasks to the user's corrected timezones, there can be some mismatches. Working with timezones is always tricky 😅

**Comment by thomaslombart** [comment]
@lukthony I worked a bit on the extension this morning. I found a fix that hopefully will fix timezone issues: https://github.com/raycast/extensions/pull/952.

**Comment by lukthony** [comment]
Works like a charm on my end! Tasks all have correct dates, as far as I can tell. Thanks for everything :]
