### ISSUE TITLE
Unable to link Raycast Pocket Extension to existing Pocket Account

### ISSUE THREAD

**Issue by martinbliss** [raycast/extensions#5022]
### Description

Having followed the instructions on this page https://github.com/raycast/extensions/blob/a71cc275b353e1cbfbc01b59fe4ae5f022fbf792/extensions/pocket/README.md I am not able to get my Pocket extension for Raycast to link with my Pocket account. 

I receive a 503 when POSTing to https://getpocket.com/v3/oauth/authorize with my consumer key and access code. This may be an actual bug/problem with Pocket's internal systems, or it could be this documentation requires an update to use a different URL or step to complete the OAuth flow. In any event, I think an update to the cited README is in order.

I would submit a PR instead of an issue, except I'm hoping Victor (the README Author) is able to figure out the issue in 5 minutes and come up with a better update than just "Sorry - your mileage may vary when wishing to use this Raycast extension."

**Comment by thomaslombart** [comment]
cc @vimtor

**Comment by vimtor** [comment]
Hi @martinbliss!

There is a PR (#2991) with a bunch of improvements that is currently on hold for this same issue. I tried to figure out what is happening but it seems like Pocket change something since the first time I wrote the instruction. I've tried to use Raycast OAuth API but Pocket uses a modified version and I couldn't get it to work. I would love if you could try to see if you can get it to work since I no longer use Pocket myself.

If not I may take a look in a week or so.

Thank you :)

**Comment by paulpet** [comment]
I am hitting the same issue.
