### ISSUE TITLE
[Keyboard Layout Switcher] An option to assign Hotkey to a specific Keyboard Layout (language)

### ISSUE THREAD

**Issue by shalomma** [raycast/extensions#5064]
### Extension

https://www.raycast.com/lucaschultz/input-switcher

### Description

An option to assign Hotkey to a specific Keyboard Layout (language).
It could be tremendously useful to enable switching to a certain layout with a designated hotkey.

### Who will benefit from this feature?

Users that have more than one layouts.
In many cases, a MacOS user is not aware of the current layout. As it only appears in the toolbar which is not always visible.
Therefore, just toggling between layouts, is not always the most efficient way to choose the desired layout.

**Comment by lucaschultz** [comment]
Hey @shalomma, have you checked out the new toggle feature @agusluques added in #5122? It's a really handy way to cycle through all your layouts with just a single hotkey! 

Unfortunately, I don't think it's possible to do what you're suggesting. Since you can only assign hotkeys to commands, the extension would need a command for each of your layouts. I'm not sure if it's possible to add commands to an extension dynamically, but @pernielsentikaer might know something I don't.

The only other option would be to add _favorite_ commands and let the user decide which layout they should trigger. If you're feeling up for a challenge, why not give it a go?

**Comment by pernielsentikaer** [comment]
There is no way to add commands dynamically as it is now, no 😞
