### ISSUE TITLE
[iMessage 2FA] Change "search last days for 2FA" to "search last hours/minutes for 2FA"

### ISSUE THREAD

**Issue by smelskiy** [raycast/extensions#5095]
### Description

I would prefer to view messages only from the last hour instead of seeing all of them throughout the day. Moreover, it would be helpful to determine if I have received a 2FA message.

To address this, my proposed solution is to create two fields in the configuration settings:

"How many": this will be an input field where a user can enter a number
"What": this field will offer options such as "minutes," "hours," or "days."

### Who will benefit from this feature?

Many users.

**Comment by mathieudutour** [comment]
Could you open an extension issue instead of an api issue? [raycast/extensions/issues/new?assignees=&labels=extension%2Cbug&template=extension_bug_report.yml&title=%5BExtension+Name%5D+](https://github.com/raycast/extensions/issues/new?assignees=&labels=extension%2Cbug&template=extension_bug_report.yml&title=%5BExtension+Name%5D+)...
