### ISSUE TITLE
[Unsplash] Change desktop background on all monitors

### ISSUE THREAD

**Issue by jackmsvaughan** [raycast/extensions#5116]
### Extension

https://www.raycast.com/eggsy/unsplash

### Description

This is an awesome extension. Use it daily. But it only ever affects one desktop. It should change all desktops or have options for this.

**Comment by eggsy** [comment]
I'll see what I can do!

**Comment by eggsy** [comment]
Hey @jackmsvaughan,

Thank you for the issue, I'd like to point out that the feature you requested already exists under extension settings which you can find by simply pressing `Cmd` + `Option` + `,` while hovering any of the commands from Unsplash; then you'll simply scroll down through the list on the right and find the option "Apply Wallpaper To"... Changing that setting to "Every Desktop" should help you get what you want!

<img width="303" alt="image" src="https://user-images.githubusercontent.com/13917975/222698030-6b0a50cf-f59f-467f-aa24-86f685087193.png">

Let me know if there's anything else, and please react/respond so I can close the issue! I'm not sure if the setting works since I don't have a second monitor installed, this will help me fix it if it wasn't working! Thanks.

**Comment by yug2005** [comment]
Perhaps there can be two separate commands for setting wallpaper to current desktop and every desktop? That could be useful and simple to integrate.

**Comment by eggsy** [comment]
That's a really great idea @yug2005! I'm working on a huge update right now, I will add a separate action to set on each display and remove that setting there 🤞
