### ISSUE TITLE
[Extension Feature Request] Notion – Disable time in date element

### ISSUE THREAD

**Issue by es183923** [raycast/extensions#545]
# Extension – Notion
Store link: https://www.raycast.com/HenriChabrand/notion
GitHub link: https://github.com/raycast/extensions/tree/main/extensions/notion
Author: @HenriChabrand

**Describe the feature and the current behavior/state.**
I'd like the option to *disable* time from showing in the date element. Currently, it puts in the time of an event, even though I don't directly specify.

Example:
If I were to input `Wednesday, December 29, 2021` as the date, It would show `December 29, 2021 5:00 PM (UTC)` as the date on Notion, but I only want `December 29, 2021`.

raycast selection: 
![Raycast selection](https://user-images.githubusercontent.com/72744903/146622994-5d197082-7614-4d5e-8d09-d7905d534574.png)
result on notion: 
![result on notion](https://user-images.githubusercontent.com/72744903/146623029-9312e564-0354-4600-a866-18e8a1dc33a0.png)

One solution could be to add preferences setting, `Add time to Date elements`, as a checkbox.

**Who will benefit with this feature?**
Anyone who uses Notion and uses the Date element, but doesn't want the time to show.

**Any Other info.**
none.

**Comment by HenriChabrand** [comment]
Hello @es183923 👋 

The issue is that the `DatePicker` don't take in consideration the user timezone.

It does in the interface, but not in the value.

As an example – here is what `Today` looks like in the interface:
<img width="444" alt="Screenshot 2021-12-18 at 08 50 46" src="https://user-images.githubusercontent.com/18643714/146636935-41f9b460-30e7-47b6-b3cf-73bc4d631978.png">
And here is the value returned:
<img width="352" alt="Screenshot 2021-12-18 at 08 51 36" src="https://user-images.githubusercontent.com/18643714/146636941-5a99744f-4f0c-4388-8d39-dc712ee5a65b.png">
The value don't take into account my timezone.
It is set to T13:00:00 where it should be T00:00:00.

And actually, if the UI shows only the date – the value should be also only a date so `2021-12-18`.

**Comment by es183923** [comment]
Then, could you make a preference for time zone, and will automatically convert the date to the right timezone?

eg: if the input is shown as `Saturday 18 December 2021`, the code receives `2021-12-18T13:00:00.000Z`, and this value would then be converted so that the input actually is of the right time zone, to `2021-12-18T00:00:00.000Z`

**Comment by HenriChabrand** [comment]
Yes that's an idea – in the meantime the DatePicker gets an update.

I'll try to push this beginning of the year.

**Comment by fe9lix** [comment]
fyi: with the upcoming API release, it will be possible to set the date element to a "date only" mode.
