### ISSUE TITLE
[OneNote] stopped working

### ISSUE THREAD

**Issue by g4challenge** [raycast/extensions#5530]
### Extension

https://www.raycast.com/alewandowski/onenote

#### Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:393:5
[kOnExit]:worker:277:26
Worker.<computed>.onexit:worker:199:20
```

### Steps To Reproduce

1. in the raycast main window
2. run search notes
3. error happens either right away - or within trying to open in OneNote

**Comment by brycerton** [comment]
@alewandows - any thoughts or updates on this? I am experiencing the same error now. I can still search for all notes and pull them up, but I can no longer open any deeplinks into the OneNote app.

Search dialog:
![image](https://github.com/raycast/extensions/assets/1308141/9db827de-2f75-468d-a0ac-8af40e3d8471)

After trying to open a note:
![image](https://github.com/raycast/extensions/assets/1308141/3e6688bb-f57d-46f9-8fee-45eacc7238b1)

**Comment by thomaslombart** [comment]
Hey @g4challenge @brycerton, we've fixed a performance issue in the 1.54.0 release that should make this type of bugs less likely to appear. Do you still have the error?

**Comment by didjit86** [comment]
Hi, I'm having the issue too and 1.55.1 did not resolve it. Still get the "Something went wrong" when clicking "Open in Onenote". Error below.

Error: missing expected parameter: value

process.processImmediate:timers:476:21

**Comment by iDarkHusky** [comment]
Hi,

Same issue for me on Raycast 1.57.1: "Something went wrong" after pressing Enter or clicking on "Open in OneNote".

![CleanShot 2023-08-24 at 12 49 31](https://github.com/raycast/extensions/assets/22275955/72841cdc-79a2-42d9-8737-cfb7b36628d7)
![CleanShot 2023-08-24 at 13 02 17](https://github.com/raycast/extensions/assets/22275955/ddbfe51b-8bc8-4141-85eb-66da388f2bb5)

```
Error: missing expected parameter: value

process.processImmediate:timers:476:21
```

It's most likely due to a change of behavior of OneNote application when opening a note, and now the arguments passed by the extension aren't working anymore (looks like a parameter is missing).
