### ISSUE TITLE
[AirPods Noise Control] User configurable mode cycle

### ISSUE THREAD

**Issue by khasbilegt** [raycast/extensions#5649]
### Extension

https://www.raycast.com/chrahe/airpods-noise-control

### Description

The default one can be still Transparency <-> Noice Cancelling, but it would be awesome if the user could override the default combination to something else like Off <-> Transparency.

### Who will benefit from this feature?

Anyone who doesn't use the Noice Cancelling mode that much, but use Off <-> Transparency combination often and people who wanna save up some battery but change into Transparency mode when it's really necessary.

**Comment by chrahe** [comment]
Yeah that should be fairly straightforward to add to the script, I can get to that later this week. 🙂

**Comment by chrahe** [comment]
I'm so sorry, life got in the way and I forgot about this issue entirely. Will get around to it now!

**Comment by chrahe** [comment]
Unfortunately the release of macOS Sonoma beta and Adaptive mode made it a bit more difficult to work with the sound menu again, since Apple changed the order of noise control modes around. I built an implementation where you just provide the index of the NC mode you're looking for. There's a PR for it now, so hopefully it should be available soon.
