### ISSUE TITLE
[1Password] ...Cannot Install/Get Working

### ISSUE THREAD

**Issue by jeisaacs** [raycast/extensions#5780]
### Extension

https://www.raycast.com/khasbilegt/1password

### Description

Try as I might, I cannot seem to get 1Password in Raycast working.

I have installed the CLI, which I have verified as being installed using  `op -version` - the version returned is 2.16.1

When I run `op signin` I get `Output of 'op signin' is meant to be executed by your terminal. Please run 'eval $(op signin)'. You can use the '-f' flag to override this warning.`

When I try activate the extension working I get an error - which I've copied below
![2023-04-05_08-40-08](https://user-images.githubusercontent.com/24828392/230014352-b9b2bdb3-28a0-437a-929d-76dbf25ea720.png)

Command failed: /usr/local/bin/op signin --account OFH4OV34IBB6TJTKVAIGG5WZSQ
Enter the password for emailaddress@emailaddress.com at my.1password.com: [ERROR] 2023/04/05 08:38:07 operation not supported on socket

Please help

**Comment by Sillium** [comment]
I have the same problem.

**Comment by Mporsi** [comment]
Have you followed the installation guide to the CLI? 
Specifically asked the 1pass app to connect to the CLI. See the installation guide [here](https://developer.1password.com/docs/cli/get-started/#install):

**Comment by Sillium** [comment]
Yes, I did. For me, the problem is a little bit strange. I have two MacBooks, one MacBook Air M1 and one MacBook Pro M1. On the Pro, the 1Password Raycast extension works. On the Air, it doesn't. Both MacBooks have the 1Password CLI tool installed and use the same 1Password account of course.

I can do
`op signin --account my.1password.com`
successfully on the MB Air and the MB Pro.

If I try
`op signin --account 39A<redacted by me>E97`
this fails on both MacBooks with the same error message:
`[ERROR] 2023/05/24 21:36:16 found no accounts for filter "39A<redacted by me>E97"`

The error log of the 1Password Raycast extension is only shown on the MB Air:
`Command failed: /usr/local/bin/op signin --account DF8<redacted by me>FB3
[ERROR] 2023/05/24 21:40:16 found no accounts for filter "DF8<redacted by me>FB3"
`
and shows a different account id on every try, so for example
`Command failed: /usr/local/bin/op signin --account C74<redacted by me>6DA
[ERROR] 2023/05/24 21:40:48 found no accounts for filter "C74<redacted by me>6DA"
`
after the next "Sign In" attempt in Raycast.

**Comment by pernielsentikaer** [comment]
Where is `op` installed? Type `which op` in a terminal 🙂

**Comment by Sillium** [comment]
On both Macs it's installed in the same location:
```
❯ which op
/usr/local/bin/op
```

`op` itself can also be found without problems, there's never a `command not found` message or similar.

I want to reiterate that the log message given by the 1Password Raycast extension upon trying to sign in on my MB Air always contains a new/different UUID for the `--account` parameter of `op signin` on every try.

![2023-05-25_08-32-12](https://github.com/raycast/extensions/assets/8177259/fb512c94-f22f-4cb2-912b-fd966a87790f)

![2023-05-25_08-32-46](https://github.com/raycast/extensions/assets/8177259/d8aa5986-e477-467f-86ea-2d3a1b48dc58)

**Comment by Sillium** [comment]
For the sake of completeness: The extension's configuration is unchanged and has `/usr/local/bin/op` configured as 1Password's CLI path. As I said, the command is executed, it's just that the account ID given via `--account` parameter seems to be random or at least wrong.

<img width="1205" alt="image" src="https://github.com/raycast/extensions/assets/8177259/694501b9-0df8-4ba0-9a0b-5f97f37cf81d">

**Comment by Mporsi** [comment]
It still looks a bit like you have not actually connected the 1Password desktop app with the cli. This is needed. 
From the installation guide:
![image](https://github.com/raycast/extensions/assets/9087564/c9622b78-c5e0-4380-9fe4-9db2b0c43d1d)

**Comment by Sillium** [comment]
<img width="970" alt="image" src="https://github.com/raycast/extensions/assets/8177259/8afed52e-c167-4a00-852b-a7b3c0307499">

**Comment by Sillium** [comment]
I also tried unchecking the "Connect with 1Password CLI" setting, restarting 1Password and then checking the box again but that didn't change anything.

**Comment by csatwood** [comment]
I have the same issue, I've tried uninstalling the 1Password CLI completely and installed via the homebrew suggested install and the Cask path 1Password provides as well. I can login via Terminal but when it tries to authorize in the extension I get the same "socket" error.

**Comment by zeitchef** [comment]
I'm having exactly the same issue.

**Comment by Sillium** [comment]
The problem still exists, that's why I'd like to keep this issue open. :) I'd be glad to assist in finding the problem if someone has the resources to look at this.

**Comment by p-ackland** [comment]
I had the same issue and started digging through the extension code. I noticed the extension uses the `whoami` 1Password CLI command which when running 

```shell
/usr/local/bin/op whoami --format json
``` 

1Password would return 

```
Command failed: /usr/local/bin/op whoami --format=json
[ERROR] 2023/10/28 19:47:32 unknown command "whoami" for "op"
```
Checked the 1Password CLI docs and that command does indeed exist. Turns out I had an old version of 1Password CLI installed (v2.0.0) even after a fresh install of 1Password 8. After installing the latest version (v2.22.0), the `whoami` command is available and the extension now works 🎉
