### ISSUE TITLE
[Change Scroll Direction] ...

### ISSUE THREAD

**Issue by alexrqs** [raycast/extensions#5795]
### Extension

https://www.raycast.com/gregoralbrecht/change-scroll-direction

### Description

has to be triggered twice to actually get it to work, sometimes goes as far as I have to open the trackpad/mouse tab from the os in order for the extension to work

### Steps To Reproduce

OSX Ventura 
![Screenshot 2023-04-05 at 4 40 26 PM](https://user-images.githubusercontent.com/1099589/230218179-3361b520-c88f-4db9-8307-84d47e369dc0.png)

### Current Behaviour

after triggering the scroll extension, it opens the preferences and then attempts to go to trackpad or mouse, and stops, so it has to be executed twice or three times.

### Expected Behaviour

it will execute the scroll direction change after one attempt

**Comment by emilshr** [comment]
Hey @alexrqs 
Is this happening every time you run the extension?

**Comment by dschibster** [comment]
As I see that this issue is open, and I can't quite identify it's the same issue, I wanted to hop on here to say that for me, even having the mouse menu open leads to a toast message saying "Couldn't change Scroll direction"

<img width="258" alt="image" src="https://user-images.githubusercontent.com/34553908/233565517-5017a4b9-b6d9-4d7f-a6e3-62aaf81990ed.png">

Maybe it's the same issue.

Using a 14" M1 Pro MBP on Ventura.
