### ISSUE TITLE
[Pomodoro Timer] Menu bar timer is not smooth

### ISSUE THREAD

**Issue by jahirfiquitiva** [raycast/extensions#6038]
### Extension

https://www.raycast.com/asubbotin/pomodoro

### Description

The menu bar does not update every second, and so it looks like the timer has been stuck/frozen.

https://user-images.githubusercontent.com/10360816/233106042-5b0ba8ac-cd1e-4fed-a7c0-6ccf5a8ea8df.mp4

### Steps To Reproduce

Start a timer in menu bar with Pomodoro Timer

### Current Behaviour

The menu bar does not update every second, and so it looks like the timer has been stuck/frozen.

### Expected Behaviour

The timer should be updated every second.

**Comment by AshConnolly** [comment]
Thanks for this great extension! 😄 

I found this behaviour too, but wondered if it was intentional to stop having the ui 'flickering' in the corner as the seconds change. If this does get resolved and the seconds do get updated every second. Could we add an option so that the seconds only get updated at say 30 second intervals. Might be a nicer UX, particularly on a smaller screen.

**Comment by pernielsentikaer** [comment]
At the moment it's a limitation in the API since it's only possible to update every 10 seconds and everytime you clock on it, we might change this in the future but for now it's the only thing possible
