### ISSUE TITLE
[GitHub Trending] ...

### ISSUE THREAD

**Issue by macOSWk** [raycast/extensions#6052]
### Extension

https://www.raycast.com/mikqi/github-trending

### Description

I cannot load any content using github-trending

**Comment by peelar** [comment]
I am not the author of the extension, but I investigated it out of curiosity. From what I see, the extension depends on a npm package called [`trending-github`](https://www.npmjs.com/package/trending-github) which scrapes the content of the GitHub trending page (as there is no public API for it). I suspect the semantics of the page have changed and now the scraping is not accurate, thus a lot of `undefined`s and errors.

This is, unfortunately, inscribed in scraping and will happen again. For now, you have to wait on the authors of the `trending-github` to update their library.

**Comment by mikqi** [comment]
Thank you for bringing this issue. After investigating the problem, the extension was previously dependent on the ﻿[trending-github](https://www.npmjs.com/package/trending-github) package, which caused issues due to changes in the GitHub trending page semantics. To address this, I removed the dependency and added a scraper directly into the code. This change will make it easier to update the scraper if the GitHub trending page semantics change in the future. 

Thank you once again for reporting this issue.
