### ISSUE TITLE
[Unsplash] ...

### ISSUE THREAD

**Issue by albertkinng** [raycast/extensions#6175]
### Extension

https://www.raycast.com/eggsy/unsplash

### Description

Even if I'm registered to the website it give me the "The redirect uri included is not valid." error

### Steps To Reproduce

Install extension
verifying account
error

**Comment by priyanshuppal** [comment]
im having the same problem. it was working fine until 4 days ago. afterwards i get the same error

**Comment by eggsy** [comment]
Go to extensions store page and check the installation steps, you need to configure it for your own app.

**Comment by dennysdl** [comment]
same problem here. It worked before. Since a few days ago it asks me to login to my Unsplash account when I search for an image. But when I click on "Sign in with Unsplash" the website that opens up says "The redirect uri included is not valid."

Could it have something to do with this Unsplash guideline? https://help.unsplash.com/en/articles/2511257-guideline-replicating-unsplash

**Comment by eggsy** [comment]
@dennysdl @priyanshuppal please follow these steps 

<img width="677" alt="image" src="https://user-images.githubusercontent.com/13917975/234964561-d52d84f9-7e58-48a0-8e67-4c6e0a093fdb.png">

**Comment by albertkinng** [comment]
> @dennysdl @priyanshuppal please follow these steps
> 
> <img alt="image" width="677" src="https://user-images.githubusercontent.com/13917975/234964561-d52d84f9-7e58-48a0-8e67-4c6e0a093fdb.png">

Is this on the Raycast app or in Unsplash website?

**Comment by eggsy** [comment]
> Is this on the Raycast app or in Unsplash website?

Sorry, that’s in your Unsplash application’s settings.

**Comment by dennysdl** [comment]
@eggsy  thanks! worked.

**Comment by eggsy** [comment]
@raycastbot close this issue
