### ISSUE TITLE
[Spotify Beta] Quick Actions are too nested to efficiently use them

### ISSUE THREAD

**Issue by baiirun** [raycast/extensions#6194]
### Extension

https://www.raycast.com/mattisssa/spotify-beta

### Description

Quick Actions are too nested. Right now to quickly perform an action you have to access the nested Quick Actions menu. For example, if I want to play, pause, or skip songs, I have to perform multiple steps.

1. Open Raycast
2. Type "Quick Actions" (or some subset of it)
3. Select Quick Actions
4. Type "Pause," "Play," etc.
5. Select the action

Ideally the Quick Actions are root actions instead of being nested. This would cut down on a lot of extra typing and nesting. this is how the original Spotify Commands extension works.

### Who will benefit from this feature?

Anybody using the Quick Actions.

**Comment by andreaselia** [comment]
This is resolved in #6204

**Comment by peduarte** [comment]
Done https://github.com/raycast/extensions/pull/6204

**Comment by dgfl-gh** [comment]
I strongly believe the previous way was better overall. You could setup a quicklink with the action to have it in root search, or  you could keep it nested.
Now, you're forced to have it clutter up root search if you want to assign a hotkey to it; I'll never hit "Previous" from root search, since I have a hotkey linked to it, but I will always have the command cluttering my options.

To be clear, before I didn't have the commands in my root search since I had an external software open the command deeplink.

**Comment by peduarte** [comment]
But you can only enable the ones you want. There's no need to clutter your root search. And keep it mind that Raycast uses fuzzy search + a ranking system for the results. So if you have something enabled that you rarely use, it will almost never show up there — unless it matches your search term obviously

**Comment by peduarte** [comment]
Overall I understand that some people prefer the old approach. I kind of did too. But the vast majority didnt like it, so it's hard to please everyone. Having both approached seems extra confusing to me
