### ISSUE TITLE
[Bing Wallpaper] Set wallpaper fails

### ISSUE THREAD

**Issue by subscribe88** [raycast/extensions#6278]
### Extension

https://www.raycast.com/koinzhang/bing-wallpaper

### Description

When selecting the wallpaper, the desktop paper will not change instead it reverts to one of the default apple desktop wallpaper.

### Steps To Reproduce

OSX Version 13.4 Beta (22F5037d)
through raycast bing command, when set wallpaper is being selected, the desktop wall paper will reset to one of the default apple desktop or remain unchange it is already one of the default wallpaper. 

### Expected Behaviour

The set wallpaper should load the selected Bing wallpaper as the desktop wallpaper

**Comment by koinzhang** [comment]
Hi @subscribe88. First of all, thank you for using Bing Wallpaper.
I use the extension on the official system normally, maybe because there is a bug in the beta system or the beta system has modified the script for setting desktop wallpaper, this problem needs to be confirmed after 13.4 becomes official.
If you still encounter this problem on the official system, please feel free to contact me.
