### ISSUE TITLE
[Image Modification] Selection handling error when image copied to Clipboard 

### ISSUE THREAD

**Issue by 0xOsprey** [raycast/extensions#6373]
### Extension

https://www.raycast.com/HelloImSteven/sips

### Description

If an image is copied in the clipboard, the commands run without error, but do not produce the intended modification. Reproduced across all commands within the extension.

### Steps To Reproduce

1. Copy an image to clipboard
2. Run any command
3. Extension/command presents "success" message in the toast detail
4. Pasted image is the same and unmodified

### Current Behaviour

All commands provide a "success" message when an image is copied. But no modifications occur to the image in the clipboard.

### Expected Behaviour

Assuming this should either error as an "invalid selection" (need to select in file manager instead of having image in clipboard) or it should copy the new image given the selected command.

**Comment by SKaplanOfficial** [comment]
Hi, I'm not able to recreate this — if I copy an image and ensure no files are selected, I get the proper `No Images Selected` toast. Is it possible you have the image still selected in Finder when doing this? If so, you should see the modifications in the file itself, not the clipboard. Otherwise, would you mind sharing a short screen recording so I can see what's going on? Thanks!
