### ISSUE TITLE
[Readwise to Tana] ...

### ISSUE THREAD

**Issue by ricky-on-git** [raycast/extensions#6650]
### Extension

https://www.raycast.com/believer/readwise-to-tana

### Description

I press enter to copy all my highlights from Readwise but when I paste them into Tana is paste this:
%%tana%%

Individual highlights it works perfectly, but for all highlights it doesnt.

### Steps To Reproduce

1. Run extension
2. Select book
3. Press "enter" to copy all highlights
4. Paste on Tana
5. get "%%tana%%"

### Expected Behaviour

I expect to paste all the highlights.

**Comment by ricky-on-git** [comment]
I have attached a screen recording of what is happening. 
The weird thing is that for a single highlight, it works.

https://github.com/raycast/extensions/assets/4391175/67e44b53-5d90-4a4a-be31-9bb6b87c5f2d

**Comment by believer** [comment]
Thank you, that's helpful! I'll have a look at it next week.

**Comment by ricky-on-git** [comment]
No updates on this?

**Comment by believer** [comment]
@ricky-on-git I believe the problem is that the template is initially empty. Did you update it when you began? You can do this by pressing `cmd + enter` or `cmd + k` and selecting “Update template” from the list view with all the sources. If you open this and save, you should start getting notes.

I'll add a fix that sets the initial template with some data though.
