### ISSUE TITLE
[Figma File Search] Quicklook error report

### ISSUE THREAD

**Issue by Qiaoya123456** [raycast/extensions#6724]
### Extension

https://www.raycast.com/michaelschultz/figma-files-raycast-extension

### Description

Reason: Code: 2 (Unhandled Extension Rejection)
Domain: commands
Time: 18:11:06.903

### Steps To Reproduce

Menu bar exclamation mark icon, no response to reload

**Comment by GLaDO8** [comment]
This error is the same as the one mentioned in this issue https://github.com/raycast/extensions/issues/3889

It is a `ENOTFOUND` error, screenshot below. Happens when either fetch URL is wrong or connectivity issues. I'm investigating this. 

Till then, I've seen deactivating and Reactivating the menu bar command works sometimes. 

<img width="1141" alt="CleanShot 2023-05-22 at 18 34 35@2x" src="https://github.com/raycast/extensions/assets/22849100/09040629-e842-49a0-bc6e-f6faeed1811f">
