### ISSUE TITLE
[Incognito Clone] ...

### ISSUE THREAD

**Issue by nukesean** [raycast/extensions#6743]
### Extension

https://www.raycast.com/kgrhartlage/incognito-clone

### Description

It does not work for me at all. In both Chrome and Brave, I get the error, "Cloning tab failed." Using the ⇧⌘N shortcut directly opens a new incognito window as expected, so there is no conflict. I'm currently using an Intel iMac running Ventura 13.3.1.

### Steps To Reproduce

1. Use either command.
2. Watch it fail.

### Current Behaviour

It fails to clone the tab.

### Expected Behaviour

It should clone the tab.

**Comment by kgrhartlage** [comment]
I'm sorry to hear it's not working for you. In the case of Chrome the extension does not simulate key strokes, so that cannot be the problem.

Can you run the following in Script Editor (Applications > Utilities > Script Editor):

```applescript
tell application "Google Chrome"
	activate
	delay 1
	if (count every tab of front window) > 0 then
		set theURL to URL of active tab of front window
		make new window with properties {mode:"incognito"}
		set URL of active tab of front window to theURL
	end if
end tell
````

This is more or less the [same code that the extension executes](https://github.com/raycast/extensions/blob/9935ca0d32bcee3b784c75b3aa219d237317363e/extensions/incognito-clone/src/utils.ts#L16-L23).

It should look something like this:

<details>
<summary>screenshot</summary>

<img width="812" alt="CleanShot 2023-05-24 at 07 13 14@2x" src="https://github.com/raycast/extensions/assets/42832087/d4fc38c8-e340-4d8d-84d7-afa53b038e49">

</details>

Click the "Play" button and let me know what the output looks like. 🙏

**Comment by nukesean** [comment]
I confirmed that this AppleScript does work correctly in both Brave Browser and Chrome.

**Comment by LonnyX** [comment]
> I'm sorry to hear it's not working for you. In the case of Chrome the extension does not simulate key strokes, so that cannot be the problem.
> 
> Can you run the following in Script Editor (Applications > Utilities > Script Editor):
> 
> ```applescript
> tell application "Google Chrome"
> 	activate
> 	delay 1
> 	if (count every tab of front window) > 0 then
> 		set theURL to URL of active tab of front window
> 		make new window with properties {mode:"incognito"}
> 		set URL of active tab of front window to theURL
> 	end if
> end tell
> ```
> 
> This is more or less the [same code that the extension executes](https://github.com/raycast/extensions/blob/9935ca0d32bcee3b784c75b3aa219d237317363e/extensions/incognito-clone/src/utils.ts#L16-L23).
> 
> It should look something like this:
> 
> screenshot
> Click the "Play" button and let me know what the output looks like. 🙏

I just wanted to let you know that this extension is still not working even if the script above does works fine.
I have tried in Chrome and Safari but it always give the same error "Cloning tab failed"

**Comment by kgrhartlage** [comment]
I would love to help, but I'm not sure how to resolve this because it's working fine on my end. I'm also not knowledgable enough about AppleScript to be aware of nuances or pitfalls in this context.

<details><summary>screen recording</summary>
<p>

https://github.com/raycast/extensions/assets/42832087/fa96faeb-44db-4788-9ff3-7d5ee0289a83

</p>
</details>
