### ISSUE TITLE
[Amazon AWS] Run configured scripts for any of your AWS profiles

### ISSUE THREAD

**Issue by jijo-nl** [raycast/extensions#6766]
### Extension

https://www.raycast.com/Falcon/aws

### Description

Run configured scripts for any of your AWS profiles - Only listing default profiles. As I have 5 profiles available in .aws/credentials

### Steps To Reproduce

Run configured scripts for any of your AWS profiles command is only showing one profile as default, and I have other profiles available in .aws/credentials file and I really want to switch between to work across multiple accounts.

**Comment by JonathanWbn** [comment]
Do you have a dropdown that shows up on the top right? If so, what does it show?

**Comment by jijo-nl** [comment]
No it;s not showing any other dropdown.


[cid:c0c494a5-1648-43c2-99d6-b7f03b1d2026]


Thanks & Regards,
Jijo Alexander


On Thu, May 25, 2023 at 17:41:28, Jonathan Wieben ***@***.******@***.***>> wrote:

Do you have a dropdown that shows up on the top right? If so, what does it show?

**Comment by frese** [comment]
Try move your profiles to `.aws/config` see if this helps ?

**Comment by jijo-nl** [comment]
Even after copied the credentials file to .aws/config the same issue.

[cid:f48165bd-1ede-4cbc-955b-87416af5bca4]


Thanks & Regards,
Jijo Alexander


On Fri, May 26, 2023 at 11:53:04, Jijo Alexander ***@***.******@***.***>> wrote:
aws/config

Moved to .aws/config location and reinstall the extension, For first running the profile script command what needs to be added here as profile

/bin/zsh -l -c "assume -c <profile>"

Thanks & Regards,
Jijo Alexander


On Thu, May 25, 2023 at 20:17:26, Allan Frese ***@***.******@***.***>> wrote:

Try move your profiles to .aws/config see if this helps ?

**Comment by jijo-nl** [comment]
can I get some help here??

**Comment by frese** [comment]
Hi Jijo

I'm not sure how to help you, but I can try.
In the Amazon AWS extension the command "Run profile script" is a bit different from the other commands. This will NOT have a dropdown in upper right corner, but should just list all the profiles you have. Choosing one of them, you can execute a script for that profile.
Every other command SHOULD show a dropdown with the profiles and will work with the selected profile.

If you cant see you profiles in either the dropdown or in the list of "run profile script" you must have something wrong with your profiles. Can you use them with standard aws-cli tools ?

Also, beware that the default script for "run profile script" - "/bin/zsh -l -c "assume" -c <profile>" requires granted.dev assume installed and configured previously. Otherwise you can write you own "script" to execute for a profile.

Hope this helps.
-Allan

**Comment by arash-cid** [comment]
How does this suppose to work ?
It is not working .....

How should we put our command/template in place ??

`/bin/zsh -l -c "assume -c <profile>"`

Didn't work .. what is `assume` here anyway ?
