### ISSUE TITLE
[Jira] (PNG) Images embedded into issues are not shown

### ISSUE THREAD

**Issue by jo-te** [raycast/extensions#6973]
### Extension

https://www.raycast.com/raycast/jira

### Description

Image attachments which are embedded into the description of an issue are not rendered properly.
Instead Raycast renders this:
<img width="476" alt="'Failed to load image' instead of correct image" src="https://github.com/raycast/extensions/assets/49439343/ee52886f-3cc1-424d-8740-90c55a2ba7fd">
Inside the attachments area the small preview works fine.
The attached images in my case are PNG files.

### Steps To Reproduce

View an issue with an embedded PNG image. Instead of the image you see "Failed to load image".

### Current Behaviour

Embedded (PNG) images are not loaded or rendered properly inside of the description of an issue.

### Expected Behaviour

Embedded (PNG) images are shown properly as preview inside of the description of an issue.

**Comment by thomaslombart** [comment]
This is happening because Jira returns an API URL to call instead of an actual image URL when (e.g `![](/rest/api/3/attachment/content/10029)`) an image is used in the body description.

To fix it, we'd probably need to catch these URLs thanks to a regex (something like this `/^!\[\]\(/rest/api/3/attachment/content/\d+\)/`), [fetch the content](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-attachments/#api-group-issue-attachments), and replace the image with the result. Would you like to work on it?

**Comment by FezVrasta** [comment]
not stale
