### ISSUE TITLE
[Summarize YouTube Videos with AI] ...

### ISSUE THREAD

**Issue by MichaelZahn** [raycast/extensions#7035]
### Extension

https://www.raycast.com/iKasch/summarize-youtube-video-with-ai

### Description

Hi there,

sadly the Extension won't run for me. I immediatly get an error when selecting "raycastai" after installing. I use Raycast Pro of course.

This is the error i get:

TypeError: Cannot read properties of undefined (reading 'trim')

Ure:summarizeVideo.tsx:23:26
_r:index.js:6:2490
    at ray-navigation-stack
Do:index.js:6:2088

### Steps To Reproduce

1. Install the Extension
2. choose "RaycastAI"
- crash

**Comment by iKasch** [comment]
@MichaelZahn Thanks for the report! I tried to reproduce this but could not get it to "break" 😄  
Do you get the error without even pasting a youtube link? Seems like you tried, can you give me an example maybe?

Otherwise, I'd ask you to remove and install the extension again, maybe there were some hiccups during installation. I also heard one person say that they could not get the extension to run when installing through the website instead of the in-app store.

Let me know if I can help some more, I would love to get it to work on your machine.

**Comment by MichaelZahn** [comment]
Hello there,

thanks for your support. I reinstalled it through the store and now it worked. Might really be a problem with the Webinstallation. Works great now!

Mit freundlichen Grüßen,
Michael Zahn


Projekt Design | Karl-Heinz von Lackum
Auf der Beune 48 | D-64839 Münster
Tel.:
+49 (0)6071 36135
Fax:
+49 (0)6071 36143
E-Mail:
***@***.***
Domain:
www.projekt-design.com

RECHTSHINWEIS | Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder
diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die
unbefugte Weitergabe dieser Mail ist nicht gestattet.
Am 11. Juni 2023, 19:09 +0200 schrieb Kim ***@***.***>:

**Comment by iKasch** [comment]
@raycastbot close this issue
