### ISSUE TITLE
[Flaticon — Search Icons] ... Advanced Search

### ISSUE THREAD

**Issue by qlery49** [raycast/extensions#7266]
### Extension

https://www.raycast.com/bgnfu7re/flaticon

### Description

Could you implement these two search filter types maybe?

<img width="291" alt="CleanShot 2023-06-25 at 01 42 50@2x" src="https://github.com/raycast/extensions/assets/127060121/0e7fd6db-9f90-4e36-9c83-c1c545e6d17b">
<img width="219" alt="CleanShot 2023-06-25 at 01 42 46@2x" src="https://github.com/raycast/extensions/assets/127060121/f360071a-c98b-47c1-bc11-3184ccf12a31">

### Who will benefit from this feature?

everyone

**Comment by kudrykv** [comment]
Hi, @qlery49!

So the issue here is that Raycast doesn't provide good methods for multidimensional filtering. A top-right dropdown that you can find in some other extensions isn't suitable, as I can't override it with custom mechanics.

A workaround I see is to add magic words into the search query itself. Something like,
```
sunny icon color:black shape:fill
           ^^^^^^^^^^^ ^^^^^^^^^^
           these kind of magic words
```

But it looks cumbersome, and you actually need to know somehow that these exist and what are their possible values.

I don't know what else we could do here.
