### ISSUE TITLE
[Git Repos] Allow setting local path for multiple machines

### ISSUE THREAD

**Issue by dewinterjack** [raycast/extensions#7289]
### Extension

https://www.raycast.com/moored/git-repos

### Description

I have cloud sync however my code location is different on each machine so when I change the setting on one machine it breaks the extension on another.

### Steps To Reproduce

1. Set projects path on machine A.
2. Cloud sync
3. Use extension on machine B with different projects path.

### Current Behaviour

Path not found

### Expected Behaviour

Setting that is not synced for path.

**Comment by danielsequeira** [comment]
Hi @dewinterjack,

This is a current limitation with the Cloud Sync feature, since at the moment and by default we sync Extensions and their settings, unless they are “secure” settings, such as passwords and API keys, which are not synced.

Our plan is to allow users to select/unselect exactly what they want to sync, like it happens with icloud for example.

Also since this is not really an extension related feature, but rather a Raycast app one I will close this issue.
