### ISSUE TITLE
[Raycast Wallpaper] Suggestions (Loading Time and Wallpaper exclusions) 

### ISSUE THREAD

**Issue by NicolasVaillant** [raycast/extensions#7396]
### Extension

https://www.raycast.com/koinzhang/raycast-wallpaper

### Description

I have two suggestions:
> When I run `Set Raycast Wallpaper`, it takes a few seconds to load all the pictures. It's really annoying to have to wait for a preview.

→ Maybe you could work with lighter pictures instead of the large 6K pictures (it seems you are taking the official wallpaper pictures).

> I really love the `Auto Switch Raycast Wallpaper`, but I would really appreciate having the ability to exclude a wallpaper from the auto switch list.

→ You could let users set pictures as an exclusion and create something like a sub-list.

**Comment by koinzhang** [comment]
Hi @NicolasVaillant.
For problem one, the current extension has been optimized. When you enter the extension, the cached pictures will be loaded first (the first time you enter the extension, you need to download the cache, and it will take a long time), so that you can quickly load the pictures
For question two, I will consider submitting a PR to update

**Comment by koinzhang** [comment]
Hi @NicolasVaillant.
It is recommended to use the Grid layout. The problem of image loading delay does exist in the List layout.
Also I submitted a PR #8007 to add a new action for Set Raycast Wallpaper: Exclude From Auto Switch

@raycastbot close this issue
