### ISSUE TITLE
Easy Dictionary: Add the ability to set multiple target languges or switch between them

### ISSUE THREAD

**Issue by herrsilen** [raycast/extensions#7403]
### Extension

https://www.raycast.com/isfeng/easydict

### Description

Today, you set two languages in the extension, and the extension figures out itself which target language you want for the translations.

I'm often switching between languages, which means that I'm sometimes interested in translations in a third or fourth language.

It would be great to be able to set multiple language and possibly having different commandos for them.

### Who will benefit from this feature?

Everyone who handles more than two languages.

**Comment by tisfeng** [comment]
@herrsilen  You can turn on the `Show Select Target Language` option on the Settings page so that you can manually select the translation target language.

The ability to switch between multiple languages is a bit too complex for a Raycast extension, and is not supported by UI operations.

>  set multiple language and possibly having different commandos for them.

<img width="810" alt="image" src="https://github.com/raycast/extensions/assets/25194972/79a94a72-8813-4ede-af5c-18c80953dce6">

**Comment by tisfeng** [comment]
@raycastbot close this issue
