### ISSUE TITLE
[Jisho] Not working anymore due to Axios/Node-fetch banned from API

### ISSUE THREAD

**Issue by mmtftr** [raycast/extensions#7432]
### Extension

https://www.raycast.com/dmacdermott/jisho

### Description

The extension has stopped working for some time now.

<img width="901" alt="image" src="https://github.com/raycast/extensions/assets/13402668/1ea96c7a-a86b-4da4-bea2-4173f9343b20">

It seems axios/node-fetch was banned for "scraping". I've tested on my end and changing User-Agent fixes the issue for the extension. However, I'd like to discuss some steps so that the extension doesn't cause too much noise for the Jisho servers. To that end, I think it might be useful to use custom throttling with higher delay and a local cache for repeat searches.

@dmacdermott let me know your thoughts here.

### Steps To Reproduce

1. Use the extension normally to search a word

### Current Behaviour

No requests work

### Expected Behaviour

Requests return proper responses

**Comment by evkaw** [comment]
Same issue here!! How would I go about changing the "User Agent"? Sorry if this is a stupid question, just not good at this sort of stuff

**Comment by Lisenish** [comment]
@mmtftr Do you need help with fixing this? 
Sorry, I'm a permanent user and a bit struggling now because of this. IMHO it's ok just to update UA to `Raycast v.XX` or something. 
If proper debounce is added I don't think it should cause any troubles to Jisho servers since it probably would be similar to if you just used their website
