### ISSUE TITLE
[Tailwind CSS] Allow searching by HEX, and allow searching for the closest color

### ISSUE THREAD

**Issue by alessandro-newzoo** [raycast/extensions#7455]
### Extension

https://www.raycast.com/vimtor/tailwindcss

### Description

Hello again! :) 

I was thinking there are two features that would make working with Figma (and similar) files a lot smoother:

1. Allow searching the colors by HEX value and not only by name, as it's often needed when receiving the designs from the designer to cross-reference the color they've used. Indeed the designer should specify this in the Figma file, but they don't always do that 🤷 
2. similarly to point 1, sometimes the nasty designers might use colors that are not in your library at all, so you might want to find the closest one you've got. I understand this might be a tad complicated on your end, but it's worth asking :D

In regards to point 2, there is an extension that does exactly that, if you need some "inspiration":

https://github.com/raycast/extensions/tree/ca6c5a724f2ec924793ea3fd90d5df3592ea7b6e/extensions/convert/

<img width="788" alt="image" src="https://github.com/raycast/extensions/assets/47320294/9f347cbb-636d-4758-af49-a54be9e249db">

Also please do note these are just suggestions and I'm in no way expecting you to work on these!
Thanks a lot, and have a great day ahead!

Alessandro

**Comment by vimtor** [comment]
Great idea @alessandro-newzoo!

I will try to implement point 1 this week.

Regarding point 2, a similar issue once popped #4968 a while ago but I did not understand the use case so I discarded it. Now that you have explained it, it makes more sense, but I'm still wondering how to communicate this to the user effectively. Maybe this could happen automatically? Perhaps a separate command? I'm not sure if this is something people will expect, or if it will seem like a bug when they search for a color and others pop up. Since I will have to implement the custom search and replace the Raycast one, I would like to be sure that doing something like this makes sense.

**Comment by alessandro-newzoo** [comment]
Hi @vimtor, thank you for looking into this!

Since, in theory, inputting a HEX value in the search box should return only *up to* one Tailwind color's name, this would leave you with a lot of real estate that could host a row to display the closest color(s), especially if there is no color for the provided HEX value:


![image](https://github.com/raycast/extensions/assets/47320294/43374232-077c-4f9f-8a34-9a7754d05a1d)

And probably the most likely scenario in which this would be useful would be when no colors are found at all:

![image](https://github.com/raycast/extensions/assets/47320294/14d2f7bc-6700-48d8-8607-6e92e4bdd5b1)

So yeah to answer your question, I think it would make sense to avoid creating a separate command.
What do you think?

**Comment by vimtor** [comment]
Hi @alessandro-newzoo!

I've been experimenting and I'm sure I'll add the ability to search by hex value. I don't know why I didn't include it when I built the extension.

I've also tried searching for distance, but I found an edge case that could ruin the whole endeavour. As you can see in the video below, when you search by a specific color, other colors appear too, since they are nearby. Additionally, the search experience is a bit janky, as fewer colors appear as the user types until they hit 3 characters (a valid hex), when other colors suddenly pop up.

https://github.com/raycast/extensions/assets/36263538/ddcafd9f-b847-4d86-9254-6aa2810aa3cc

If you want, you can find the code in my fork branch `tailwindcss` if you want to include it in your own fork.

**Comment by alessandro-newzoo** [comment]
@vimtor wow this is beautiful (and so is your wallpaper :D)!

I see what you mean, additionally, someone who doesn't know about this new behavior might get confused when seeing additional colors popping up. 
Unfortunately I don't know what can be done with Raycast's API, but if it's possible, then maybe separating exact matches from similar matches might help _(make exact matches bold? or add a vertical separator between exact and similar?)_, as well as adding a message somewhere at the top to notify the user when zero exact matches were found.

That being said, I just tried your branch, and it works fine at times, but it's acting weird with most colors for which an exact match exists.
Examples you can use to reproduce are `#dbeafe`, or `#fecaca`:

https://github.com/raycast/extensions/assets/47320294/61932574-b512-4aa4-bb44-005ed7e0c12a

As you can see, the color I searched for is buried deep into the other ones.
I'm not sure what's causing this, but perhaps, avoiding to show similar colors when an exact match is found, could prevent most of these issues from happening?

**Comment by vimtor** [comment]
After considering it, I will keep things simple and add the HEX to the color search. I don't want to complicate things too much for such a niche use case. I will also consider creating a separate extension, `Color Palettes`, for doing both this and what you mentioned in your other issue.

Thank you for the suggestions and sorry for not bringing them to life. I hope the code from my branch serves you well.

@raycastbot close this issue

**Comment by alessandro-newzoo** [comment]
hi @vimtor , I understand don't worry, if anything thank you so much for spending all this time on this!
