### ISSUE TITLE
[Mozilla Firefox] Support specifying path to firefox

### ISSUE THREAD

**Issue by nicoandmee** [raycast/extensions#7507]
### Extension

https://www.raycast.com/crisboarna/mozilla-firefox

### Description

I use firefox developer edition instead of the regular firefox. It would be great to allow the user to specify a custom path to the app, so as to allow for different flavors of ff.	

### Who will benefit from this feature?

cool developers who use developer edition ;)

**Comment by jaybhanushali3195** [comment]
+1 facing the same issue.

**Comment by jaybhanushali3195** [comment]
Getting this error when trying to search bookmarks
<img width="730" alt="16 July Sunday at 06 PM@2x" src="https://github.com/raycast/extensions/assets/36804441/6f9f6f54-b4d5-4167-9733-37a241b63279">

**Comment by KieranHunt** [comment]
I'm also running into this. I'm on Firefox ESR.

<details>

<summary>Screenshots</summary>

![CleanShot 2023-07-28 at 08 21 34@2x](https://github.com/raycast/extensions/assets/4106917/f960e2f9-3b10-42c0-962a-f8f6ca5f3a77)

![CleanShot 2023-07-28 at 08 22 40@2x](https://github.com/raycast/extensions/assets/4106917/75a31ba5-b701-48e9-a00d-ee5d2abf821e)

</details>

I think the bug is on the [line where a profile is selected](https://github.com/raycast/extensions/blob/67e51c199612850d775276671a0c98e8710f24e9/extensions/mozilla-firefox/src/util/index.ts#L14C10-L15C1).

```javascript
const path = require("path"); 
const fs = require("fs"); 

const userDirectoryPath = path.join(process.env.HOME, "Library", "Application Support", "Firefox", "Profiles"); 

const profiles = fs.readdirSync(userDirectoryPath);
const profileName = profiles.filter((profile) => profile.endsWith(".default-release"))[0];

console.log(profileName);
console.log(profiles)

const historyDbPath = path.join(userDirectoryPath, profileName, "places.sqlite");
```

Which logs 

```
undefined
[ '35mqecyd.default', '5d5aw3cy.default-esr' ]
node:internal/validators:162
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:162:11)
    at Object.join (node:path:1175:7)
    at Object.<anonymous> (/Users/hunkiera/Downloads/raycast-ff-bug.js:12:28)
    at Module._compile (node:internal/modules/cjs/loader:1255:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1309:10)
    at Module.load (node:internal/modules/cjs/loader:1113:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v20.2.0
```

I can think of a few options forward:
1. Raycast just picks a profile (chaotic neutral)
1. Make the profile configurable in Raycast (lawful good)
1. Merge the bookmarks from all profiles together and dedupe (neutral)

Option 3 seems like good low-effort solution that lets us move to option 2 later.

**Comment by kud** [comment]
Yeah I've got the same issue with Firefox Nightly.

```
TypeError: The "path" argument must be of type string. Received undefined

O6:new-tab.js:95:342
Ir:index.js:9:2490
    at ray-navigation-stack
Mo:index.js:9:2088
```

**Comment by KieranHunt** [comment]
Pinging to mark this issue as not stale.

**Comment by KieranHunt** [comment]
Pinging to mark this issue as not stale.

**Comment by kud** [comment]
How come, @KieranHunt ?

**Comment by KieranHunt** [comment]
D'you no longer have this issue, @kud ? 

Running the Firefox extension returns this for me:

![CleanShot 2023-12-13 at 14 34 40](https://github.com/raycast/extensions/assets/4106917/7b0d79b3-489d-485c-afd4-d8f6838bf450)

(I'm typing this from my installed Firefox...)

**Comment by kud** [comment]
Which Firefox you've got? Stable? Developer? Nightly?
