### ISSUE TITLE
[Google Translate] ...

### ISSUE THREAD

**Issue by vitali-melamud-lmnd** [raycast/extensions#7561]
### Extension

https://www.raycast.com/gebeto/translate

#### Error:
```
TypeError: Cannot read properties of undefined (reading 'code')

Q3:translate-form.tsx:10:56

---
 7: import { LanguagesManagerList } from "./LanguagesManager"

### Steps To Reproduce

Just start the exception

### Current Behaviour

_No response_

### Expected Behaviour

_No response_

**Comment by gebeto** [comment]
This issue was fixed in yesterday release, it is also related to autodetect issue

Related to https://github.com/raycast/extensions/pull/7864
Especially to this line of code: https://github.com/raycast/extensions/pull/7864/files#diff-2e313e032b365e1a7d7cdf7759752e6bf26498384734a90fa569de2358e34a4dR41

@pernielsentikaer can you please also close this issue?
