### ISSUE TITLE
[Script Commands Store – Find and manage your Raycast Script Commands] ...

### ISSUE THREAD

**Issue by LanikSJ** [raycast/extensions#7581]
### Extension

https://www.raycast.com/tholanda/script-commands

#### Error:
```
Command id unknown
```

### Steps To Reproduce

1. Install Script Command Store extension
2. Search for Amphetamine
3. Install "Start Default Session" and "End Session" script commands
4. Both commands remain as "installed" in "Script Command Store" 

### Current Behaviour

Both commands remain as "installed" in "Script Command Store" 

### Expected Behaviour

Both commands should be uninstalled in Script Command Store

**Comment by LanikSJ** [comment]
I've been able to reproduce it consistently.

1. Install script command of your choosing
2. Uninstall said script command
3. Open Script Command Store extension
4. Observe said command from step 1 still installed

There's no option to reinstall / install.  Only option is to uninstall, which throws the error:
```
Command id unknown
```
I also see errors about Raycast API. 

Unfortunately I can't do a screen recording (this is a work machine and very restricted as far as installed software 🙁).

**Comment by unnamedd** [comment]
Yes, there are tons of things to fix in the store. I haven't had a lot of free time to work on them recently, so things just got old and they didn't get fixed. Since the last time I submitted the extension to the Store, Raycast has deprecated some APIs that I was making use of. This means that it isn't odd to me that you are seeing those errors from the Raycast API.

The good thing is that because of your report and another one I recently received, I have decided to invest a bit of time to fix those problems. Soon, I should submit an update fixing them all. I cannot promise when since I have my work schedule quite full. However, as soon as I submit it and it gets accepted, I will mention this issue here.

In any case, thank you for engaging here to report the problem.
