### ISSUE TITLE
[Browser Bookmarks] Extension should open bookmarks with their corresponding browser

### ISSUE THREAD

**Issue by CoXier** [raycast/extensions#7684]
### Extension

https://www.raycast.com/raycast/browser-bookmarks

### Description

Thanks for providing this awesome extension.

I usually use two browsers: Chrome for work and Safari for personal usage.

However, I've noticed that the extension always opens bookmarks using the system's default browser, even when some bookmarks are from another browser.

In my opinion, if a bookmark, let's say A, is from Safari, the extension should open it using Safari.

### Steps To Reproduce

1. Install two browsers such as chrome and safari.
2. Open this extension

**Comment by thomaslombart** [comment]
That makes sense! We could add a preference so that users have the choice between:
- Open the bookmark in the browser where the bookmark has been saved in
- Open the bookmark in the default browser.


Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the [Slack community](http://raycastcommunity.slack.com/) if you need further help.

**Comment by CoXier** [comment]
> That makes sense! We could add a preference so that users have the choice between:
> 
> * Open the bookmark in the browser where the bookmark has been saved in
> * Open the bookmark in the default browser.
> 
> Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the [Slack community](http://raycastcommunity.slack.com/) if you need further help.

Yes, it's my pleasure to make it work for me and someone else. I want to get some help from you:

1. How to know where the bookmark comes from?
2. How can I use specific browser to open the selected bookmark?
3. How to run this extension and debug it ？

**Comment by thomaslombart** [comment]
Here's our guide about contributing to extensions: [Contribute to an extension](https://developers.raycast.com/basics/contribute-to-an-extension)

**Comment by thomaslombart** [comment]
Shipped!
