### ISSUE TITLE
[Google Translate] ...

### ISSUE THREAD

**Issue by lenseffect** [raycast/extensions#7793]
### Extension

https://www.raycast.com/gebeto/translate

### Description

Hello and thanks for your work. I am curious, can we have an expanded view of translated text? Because sometimes the translated word is new to me, but on Google Translate when I expand "More translations" then I have a logical meaning behind the translated word/text.

Now we have only the first one. See example:
![translation_raycast](https://github.com/raycast/extensions/assets/68323173/ec7a9ce8-a066-4f7f-b0a9-854f76d812e5)

Here the screenshot from GTranslate with expanded "More translations":

![translation](https://github.com/raycast/extensions/assets/68323173/f3be4619-d49a-408d-9499-08e78cbe6074)

Thanks

### Who will benefit from this feature?

I guess everyone.

### Anything else?

Thanks again for the work!

Regards

**Comment by gebeto** [comment]
Unfortunately I can not do it in my extension, because free api do not return any additional translations

But Raycast released native Translator yesterday, and it looks like they can add this because they are using paid api, also they are using native code so they can build some native custom UI for it, so it will looks better

<img width="1000" alt="Raycast 2023-08-10 at 14 51 14" src="https://github.com/raycast/extensions/assets/13422799/2b490ea1-6436-4f9f-bc3c-5bb6cea86b93">
