### ISSUE TITLE
[timers] add ability to manage stopwatch in the menu bar

### ISSUE THREAD

**Issue by ad2969** [raycast/extensions#7809]
### Extension

https://www.raycast.com/ThatNerd/timers

### Description

https://github.com/raycast/extensions/blame/8929f23d165777b188816cf354b241422042b0b3/extensions/timers/src/stopwatchMenuBar.tsx#L45-L48

Any opposition to adding buttons that stop/remove the stopwatch in the menu bar?

Something like this:
<img width="250" alt="Screenshot 2023-08-05 at 2 58 56 PM" src="https://github.com/raycast/extensions/assets/44561376/24d7b300-4f14-400b-979b-5349f7b712b5">

Can contribute if this is a good idea

### Who will benefit from this feature?

Helps especially if only using one stopwatch/timer at a time - so that one can remove the stopwatch (or stopwatches) through the menu bar without typing any more words than needed

An alternative is to have a different view for if only one stopwatch is running.

### Anything else?

Tagging @ThatNerdSquared for opinion!

**Comment by ThatNerdSquared** [comment]
Hey @ad2969 - thanks for the suggestion! I've actually been thinking about this lately as well.

It's not possible to add another icon to the MenuBarExtra item like your image shows, but we could turn each stopwatch into a submenu with pause/stop sub-items. I can add it sometime tonight if that seems like a good idea.

**Comment by ThatNerdSquared** [comment]
Downside of this implementation is that to avoid the submenu being impossible to use, I have to change the refresh rate to every 3 seconds instead of every 1 (if the MenuBarExtra refreshes every 1 second, it resets the user selection faster than you can click anything)

**Comment by ad2969** [comment]
@ThatNerdSquared Thanks for taking a look! I haven't tested out the most recent changes you made to adding functionality to the menu bar but I assume it works! Although, I feel that having the stopwatch update every second instead of every 3 may be a deal breaker for some ppl looking for timer functionality.

I was able to take a quick peek at the extension's source code too. Just a quick Q, is there a reason you ended up using files to keep track of existing timers/stopwatches? (instead of something like `useCachedState` [from the API](https://developers.raycast.com/utilities/react-hooks/usecachedstate) --> i'm not sure if this does exactly what I think it does though)

**Comment by ThatNerdSquared** [comment]
I've now changed the menu to look like this:
![Screenshot 2023-08-10 at 22 21 30](https://github.com/raycast/extensions/assets/72814106/3a48ffdd-b465-44c5-8ca4-a315cf082efe)
Instead of using submenus, I've just created another section for deleting stopwatches. This is a little repetitive, but it has the upside of still allowing a 1-second update inverval. I've also fixed up some of the wording in the menu bar (you start to notice little improvements when you use your own extension daily, lol).

> Just a quick Q, is there a reason you ended up using files to keep track of existing timers/stopwatches?
@ad2969 I use files to keep track of existing timers because timers really rely on [this external bash command](). Essentially I craft a command that runs after the timer is done, no matter what. However, users can stop a timer before the countdown is finished, so the command needs a way to double-check the timer still exists before it starts firing off any notifications, sound effects, etc.
So the workaround was to check for the existence of the timer file - this doesn't work with Raycast's Storage APIs because those rely on an encrypted database (which can't be accessed from an external bash command IIRC). As for stopwatches - those could theoretically use Raycast Storage, but I'm used to reading/writing to JSON anyway, and I wanted to keep it consistent with timers.
