### ISSUE TITLE
[Craft] ...

### ISSUE THREAD

**Issue by manfrombar** [raycast/extensions#7891]
### Extension

https://www.raycast.com/bgnfu7re/craftdocs

### Description

I would like to set up the space name where Raycast is looking for daily page or block search.

**Comment by kudrykv** [comment]
@manfrombar do you mean manually naming a Space within the extension?

**Comment by manfrombar** [comment]
Yes. I mean naming the Space where I want to open the Daily Page within the extension.
Thanks

**Comment by kudrykv** [comment]
So that we are on the same page:

I don't know Space names, whether there is one or many. All I have is Space UUID (e.g., `3bc8cacd-b4e5-49ad-9a07-c6677ce9437c`). For example, I know this UUID is your primary Space, and others are secondaries, but I don't know their names.

Now, I can give you a way to name UUID within the extension itself manually. After that, it will be easy to implement a Space selector for daily pages.

This puts a burden on you as a user to match UUID with your space name. Although it's a one-time operation per Space, it still will be tricky.

Does it sound good to you?

**Comment by kudrykv** [comment]
From my side as an extension, I would try to help you. I would pull some recent data / whatever I can access from the space, so that would give you a hint of how to name a space.

Okay then. Now all I need is to implement this.

**Comment by sfkmk** [comment]
This is being implemented in PR #19976 + I will add a way to determine which space is which in the README
