### ISSUE TITLE
[Raindrop.io] ...

### ISSUE THREAD

**Issue by dikaio** [raycast/extensions#8029]
### Extension

https://www.raycast.com/lardissone/raindrop-io

### Description

Hi guys. Thanks for creating this extension, really love it.

There's one feature that I haven't been able to find and that's creating new tags within Raycast, only select existing tags.

Also I'm not sure if this is a bug but after you "command enter" it creates the bookmark but leaves raycast open to create another bookmark. I think a better ux here might be to close out the app, currently, esc the window is what I've been doing.

### Who will benefit from this feature?

Likely everyone.

### Anything else?

Thank you!

**Comment by lardissone** [comment]
@dikaio hi, thanks for your comments.

Yes, I'm aware that you can't create new tags at the moment. But since we depend on the auto complete component, it only let you access pre-existing values. I've asked Raycast support to allow creation feature.

Thanks for your suggestion about closing Raycast after saving a bookmark, I agree that it's a better UI. I think it's the default since other extensions does the same, like Reminders.

Thanks.
