### ISSUE TITLE
[Bitwarden Vault] ... enable unlock with apple fingerprint ID as opposed to Master Password

### ISSUE THREAD

**Issue by ariccb** [raycast/extensions#8075]
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Description

Just enabling the apple fingerprint ID to unlock would save loads of effort, and allow me to set a much shorter vault lock timer to be more secure.

### Who will benefit from this feature?

everyone with a mac with a fingerprint Id

**Comment by jomifepe** [comment]
Hello, thank you for the suggestion. It's not the first time someone has opened an issue requesting biometric authentication, and here's why it's not a thing yet:

- **Difficulty** - Raycast doesn't provide an easy way of prompting the user for fingerprint via its APIs, so you're on your own there, most likely developing native Swift code. I'm already experimenting with this.
- **Resources** - Extensions [don't have access to the macOS keychain](https://developers.raycast.com/basics/prepare-an-extension-for-store#keychain-access), due to security concerns. I'm not very experienced in macOS development or biometric authentication, but I believe this would be needed to implement it
- **Security** and **Maintainability**. I always try to rely on official Bitwarden and Raycast APIs, avoiding implementing these mechanisms just for this extension, in order to reduce failure points or introduce vulnerabilities.

That said, it's still something I would very much like to have and I will keep investigating it, but it's not easy and I don't think there's a single extension with it 🙂

**Comment by ariccb** [comment]
Thanks for the in depth response! That does sound like a complicated process, and I'd understand if it doesn't get implemented, still hoping you can find a way though!


On August 26, 2023 at 3:56 PM, José Pereira ***@***.******@***.***>) wrote:
Hello, thank you for the suggestion.
It's not the first time someone has opened an issue requesting biometric authentication, and here's why it's not a thing yet:

  *
Difficulty - Raycast doesn't provide an easy way of prompting the user for fingerprint via its APIs, so you're on your own there, most likely developing native Swift code. I'm already experimenting with this.
  *
Resources - Extensions don't have access to the macOS keychain<https://developers.raycast.com/basics/prepare-an-extension-for-store#keychain-access>, due to security concerns. I'm not very experienced in macOS development or biometric authentication, but I believe this would be needed to implement it
  *
Security and Maintainability. I always try to rely on official Bitwarden and Raycast APIs, avoiding implementing these mechanisms just for this extension, in order to reduce failure points or introduce vulnerabilities.

That said, it's still something I would very much like to have and I will keep investigating it, but it's not easy and I don't think there's a single extension with it 🙂

**Comment by loky-lp** [comment]
(@jomifepe hoping the ping doesn't bother you)
Wouldn't be possible to use the bridge with the native application if present?

I haven't got the time yet to check how browser extension does it, but you have an option there to ask access to the native application.
This way:
- the security is handled directly by the native application, we only need to copy the browser extension implementation;
- we don't need raycast to implement APIs to talk to the platform's keychain, it's handled by the bw app.

I'd like to implement this myself in the coming weeks, do you see this as a viable path? Have you already tried and stumbled on some blockers?

**Comment by Xytronix** [comment]
@jomifepe would you look into it?

**Comment by loky-lp** [comment]
@Xytronix I've looked into it but didn't enough time to plan an implementation.

It seems that the extension communicates with the client app through the [chrome.runtime](https://developer.chrome.com/docs/extensions/reference/api/runtime) interface, reaching at the `com.8bit.bitwarden` (the desktop app identifier).

The browser extension then sets up an encrypted IPC bridge handling the key exchange, then the bridge is used to get the keys needed to decript the whole vault.
All the communication is handled by this class:
https://github.com/bitwarden/clients/blob/95100b6f239c033cda677ffece75e44a07ac1e0b/apps/browser/src/background/nativeMessaging.background.ts#L74

The unlock method that gets the keys from the desktop app:
https://github.com/bitwarden/clients/blob/95100b6f239c033cda677ffece75e44a07ac1e0b/apps/browser/src/key-management/biometrics/background-browser-biometrics.service.ts#L91-L120

This implementation is non trivial, as would require the raycast extension to:
- Handle the raw unencrypted vault
- Handle the IPC messages and ensure the secure message exchange (and i think raycast doesn't even support native messaging)
- Implement and stay up to date with any change in the vault encryption logic

making the raycast extension basically a full blown bitwarden client.

Perhaps this is something that the bitwarden team should consider implementing, show some love in the [community forum](https://community.bitwarden.com/t/official-raycast-extension/65476)

**Comment by jomifepe** [comment]
@loky-lp Thanks for looking into this, that's quite insightful! I haven’t been able to dive deep myself and have been pushing it back because of the complexity and maintainability concerns mentioned. I’d like the feature in the extension, but it isn’t a priority. If it’s ever added, I’d strongly prefer a Raycast API that allows protecting the extension itself with biometric authentication - that would significantly reduce complexity and long‑term maintenance cost.

That said, I’m open to investigations and contributions on this topic, so thank you again.
