### ISSUE TITLE
[Flutter Documentation Search] ...

### ISSUE THREAD

**Issue by GroovinChip** [raycast/extensions#8134]
### Extension

https://www.raycast.com/MattisBrizard/flutter-documentation-search

#### Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:399:5
[kOnExit]:worker:287:26
Worker.<computed>.onexit:worker:209:20
```

### Steps To Reproduce

1. Open the Flutter Documentation Search extension
2. Start typing "Offstage"

### Current Behaviour

The extension fails

### Expected Behaviour

The extension should bring up search results

**Comment by MattisBrizard** [comment]
Hey @thomaslombart, I saw your answer on [similar issue].(https://github.com/raycast/extensions/issues/7013#issuecomment-1586810373)

It seems that the issue is still there. Do I have to do something by my side to fix this ?

**Comment by thomaslombart** [comment]
The issue still persists if you're dealing with a super-long list (think hundreds and hundreds of thousands of items). How many results do you get when typing "offstage" in the extension?

**Comment by MattisBrizard** [comment]
I set a limit of 10 items to show in the list, but I'm iterating through a very big JSON file (32MB)

**Comment by thomaslombart** [comment]
Maybe the JSON file is too large to iterate over? Is "offstage" the only query for which it fails?

**Comment by MattisBrizard** [comment]
It looks like every query is failing now. It was not the case when I released the extension, the JSON documentation file must have increased in size.

I did the same logic as done by https://api.flutter.dev/
Load the JSON documentation file and iterate over the documentation nodes for the query with scoring for each node, sort it, and return the first 10 elements. 

Every node is everything we can find in the documentation (class, property, method, etc.), that's why there is a large number of elements in the array.

The JSON file is downloaded the first time and then is cached to avoid fetching it every time. The cache has a time to live, retrieved in the response headers.

Sadly there isn't any search API that I could use to avoid downloading the JSON file.

**Comment by thomaslombart** [comment]
Did the documentation suddenly grow in size recently? One solution you could try is to stream the JSON file and reconstruct a JSON object with only the data you need. The Brew extension does just that [here](https://github.com/raycast/extensions/blob/8eb89dc1a50a6f4e643c3a77283653086303ec11/extensions/brew/src/utils.ts#L126).
