### ISSUE TITLE
[Jira] Does it support JQL?

### ISSUE THREAD

**Issue by jzhang-brex** [raycast/extensions#8190]
### Extension

https://www.raycast.com/raycast/jira

### Description

Does this plugin support the JIRA query language (JQL)

**Comment by thomaslombart** [comment]
While JQL is used to actually search for issues under the hood, you can't type in custom JQL queries because we're escaping the search text to find if an issue matches a certain text or a project. [It looks like so under the hood](https://github.com/raycast/extensions/blob/main/extensions/jira/src/search-issues.tsx#L39):

```tsx
const { issues, isLoading, mutate } = useIssues(`(text ~ "${escapedQuery}" OR project = "${escapedQuery}" ${issueKeyQuery}) ORDER BY updated DESC`, { keepPreviousData: true });
```
