### ISSUE TITLE
Unsplash authorize does not work

### ISSUE THREAD

**Issue by simonecampora** [raycast/extensions#8241]
### Description

following the guide on the readme, lands in a spot where the first autorize fail (Unplash says that "Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method." 

### Steps To Reproduce

Just follow the readme and land in the same spot. 

### Current Behaviour

Error on unsplash page

### Expected Behaviour

autorhize succeeds and extensions start to work.

**Comment by simonecampora** [comment]
Ok, I found the issue, when copying from Unsplash the client ID had an extra space and with no easy way to replace the clientID, that created an extra + symbol after the clientID in the request that went to Authorize. We should sanitise the client and secret keys to avoid leading/trailing spaces to avoid people getting stuck.

**Comment by mathieudutour** [comment]
Could you create an extension specific issue https://github.com/raycast/extensions/issues/new?assignees=&labels=extension%2Cbug&projects=&template=extension_bug_report.yml&title=%5BExtension+Name%5D+... instead of a generic "api" one? This will make sure that the authors of the extensions are aware of it
