### ISSUE TITLE
[Notion] Search pages with page content, not just page title

### ISSUE THREAD

**Issue by cgillett** [raycast/extensions#8397]
### Extension

https://www.raycast.com/notion/notion

### Description

Notion's in-app search function searches page content, not just page titles. They Raycast Notion Search command would be more powerful if it did too.

**Comment by thomaslombart** [comment]
Thanks for the feature request. Unfortunately, [Notion's API search](https://developers.notion.com/reference/post-search) doesn't provide this option. In an effort to keep the backlog clean, I'll close this issue as won't fix since the issue lies on Notion's end. It may be worth to ask that in their [Slack community](https://notiondevs.slack.com/join/shared_invite/zt-20b5996xv-DzJdLiympy6jP0GGzu3AMg#/shared-invite/email).

**Comment by thomaslombart** [comment]
Thanks for the feature request. Unfortunately, [Notion's API search](https://developers.notion.com/reference/post-search) doesn't provide this option. In an effort to keep the backlog clean, I'll close this issue as won't fix since the issue lies on Notion's end. It may be worth to ask that in their [Slack community](https://notiondevs.slack.com/join/shared_invite/zt-20b5996xv-DzJdLiympy6jP0GGzu3AMg#/shared-invite/email).
