### ISSUE TITLE
GitLab extension to fetch the repos proactively

### ISSUE THREAD

**Issue by karakanb** [raycast/extensions#842]
# Extension – [GitLab](https://github.com/raycast/extensions/tree/main/extensions/gitlab)
Author: @tonka3000 

Currently, when I list my projects using the GitLab extension, the extension makes a request when I attempt to do that, which means I have to wait until the API responds, and it is usually slow. In my day-to-day usage, I really want to be able to use this extension to quickly jump to my repo, but sometimes it is even slower than actually going to GitLab UI and searching there.

**Describe the feature and the current behavior/state.**
I think the GitLab extension should fetch the repositories in the background, just like the GitHub extension does. I can search my GitHub repos very quickly, but not for GitLab.

**Who will benefit with this feature?**
All the users of GitLab extension, in my opinion.

**Comment by tonka3000** [comment]
Hi @karakanb ,

thanks for reaching out to me. 

>  In my day-to-day usage, I really want to be able to use this extension to quickly jump to my repo, but sometimes it is even slower than actually going to GitLab UI and searching there.

Can you describe this in more detail. The GitLab extension already using a SWR cache, so only the first call should take longer.

How often do you open raycast to get to your GitLab repo? Only a few times?

The cache right now fetching all projects in the beginning, so it can be locally searched afterwards (this is what you see when you mention that the GitLab webui is faster, because it loads only the first page of results and the extension fetch all in the beginning). After the first call the projects will update will happen in the background (when you open the command, there are no background service in raycast right now) and searched should be fast, more or less like the GitHub extension.

## Cache
The cache itself will refetch in the background when the local data is older than `5` minutes and the cache is invalid after `24` hours. Invalid mean that the extension refetch all new and not in the background. The `24` hours is also a moving time-window, so when you open the projects command often enough the cache should not be invalid. Maybe `24` hours is to short for your actual use case.

So I can make this settings user editable, so that you can increase the invalidation time, so that e.g. your get invalid after  7 days or so. What do you think, would that match your daily usage pattern?

**Comment by karakanb** [comment]
Hey, thanks a lot for the details. My usage is usually 1-2 times a day, and somedays many times a day when I focus on some of those repos.

I have been guessing that there was a cache like that because I noticed that when I loaded it up afterward it loads quickly. I think the repo information is something that changes rarely in the majority of the cases, so I have two ideas:
- Make the cache configurable, as you said.
  - At least making it a longer period could work by default.
  - Also, I think refreshing this every 5 mins is too often anyway, right? maybe if that was also configurable or if I had the ability to trigger a refresh manually, I could very well live with an hourly or a few hours of refresh interval.
- Make the list show stale data even when it is refreshing the cache.
  - This would still allow a fluid user experience while serving up-to-date information.
  - I think Raycast does something like this while serving the store page, so I presume the ability to do that is there.

Thanks for looking into this.
