### ISSUE TITLE
[Jira] Ability to comment on an issue

### ISSUE THREAD

**Issue by qbunt** [raycast/extensions#8483]
### Extension

https://www.raycast.com/raycast/jira

### Description

I would love the ability to comment on an issue (or even view them) from Raycast. You are very quickly pushed into the web UI in order to grab comments or add a new comment.

There's clearly complexity with this feature due to the way Jira handles @mentions and similar, but simply the ability to comment on an issue quickly would be next level.	

### Who will benefit from this feature?

Anyone who has to comment on jira tickets frequently

**Comment by igor9silva** [comment]
Jira Slack bot has that so it's achievable.

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the [Slack community](http://raycastcommunity.slack.com/) if you need further help.

Note that opening up a PR and having it merged will earn you some credits as we want to reward contributions. You’ll then be able to exchange them in a swag store that we’ll launch soon!

**Comment by thomaslombart** [comment]
Hey @qbunt, someone kindly added support for comments over [here](https://github.com/raycast/extensions/pull/8671), so I'm closing out this issue 🙌
