### ISSUE TITLE
[Browser Bookmarks] Support Firefox Developer edition

### ISSUE THREAD

**Issue by LiamW** [raycast/extensions#8520]
### Extension

https://www.raycast.com/raycast/browser-bookmarks

### Description

I was just upgraded to the new version. I use Firefox developer edition and this isn't supported, while Firefox is. 

### Who will benefit from this feature?

I know firefox isn't huge userbase, but a lot of devs do use it and probably use the the dev version. It would also be a simple fix.

**Comment by JuanG970** [comment]
It appears to have native support to Firefox Developer Edition, since they user the same profiles file according to this:

https://support.mozilla.org/en-US/questions/1072750

So, to use the bookmarks, you need to choose the "dev" profile using `⌘` + `⇧` + `F` 

<img width="760" alt="SCR-20231001-pgmd" src="https://github.com/raycast/extensions/assets/36969954/21f8f925-0ebe-4418-bbab-43f3b4cd0187">

I wonder if this should be explicit on the README file.

**Comment by JuanG970** [comment]
I see, I think I have an idea for a fix, can you confirm that the bookmarks are on the same path:
1. On your Firefox, type `about:profiles` on the navigation bar and hit enter
2. Lookup for the root directory of one of the profiles and confirm that it is located in `/Users/<YOUR_USERNAME>/Library/Application Support/Firefox/Profiles`
<img width="1995" alt="SCR-20231002-llpw" src="https://github.com/raycast/extensions/assets/36969954/5d6d4917-7972-459f-a6d5-38e96f8219af">

**Comment by LiamW** [comment]
Here's mine:

<img width="753" alt="Screenshot 2023-10-03 at 9 54 55 AM" src="https://github.com/raycast/extensions/assets/2015237/642df5e3-9b1b-41dc-9137-223283e11118">

**Comment by JuanG970** [comment]
Got it, I will write the fix tomorrow
