### ISSUE TITLE
[Asana] Create a task from template

### ISSUE THREAD

**Issue by M1straL** [raycast/extensions#8561]
### Extension

https://www.raycast.com/raycast/asana

### Description

There are the templates in Asana which create tasks or bugs with preinstalled fields.
It will be great if I can choose in raycast extension template from dropdown list and when it applied all fields was preinstalled.

Thank you.

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the [Slack community](http://raycastcommunity.slack.com/) if you need further help.

Note that opening up a PR and having it merged will earn you some credits as we want to reward contributions. You’ll then be able to exchange them in a swag store that we’ll launch soon!
