### ISSUE TITLE
[Asana] Seeing my tasks fail after updating sections

### ISSUE THREAD

**Issue by unmultimedio** [raycast/extensions#8707]
### Extension

https://www.raycast.com/raycast/asana

#### Error:
```
TypeError: Cannot read properties of null (reading 'gid')

W7e:my-tasks.tsx:12:53

---
 9: import { useMe } from "./hooks/useMe"
```

### Steps To Reproduce

1. Connect asana
2. See my tasks
3. Go to the Asana site, rename or delete some section
4. Go back to raycast, refresh

### Current Behaviour

It crashes:

<img width="862" alt="Screenshot 2023-10-06 at 17 04 29" src="https://github.com/raycast/extensions/assets/4431392/a8e34358-25e6-4b78-b6a1-4c174e26c351">

If I clear my local storage it's fixed.

### Expected Behaviour

It shows my tasks with in the updated sections

**Comment by thomaslombart** [comment]
Thanks for flagging this issue. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the [Slack community](http://raycastcommunity.slack.com/) if you need further help.

Note that opening up a PR and having it merged will earn you some credits as we want to reward contributions. You’ll then be able to exchange them in a swag store that we’ll launch soon!
