### ISSUE TITLE
[Notion] Show/Hide Properties - Relation fields can be selected, but are not displayed.

### ISSUE THREAD

**Issue by christianmagill** [raycast/extensions#8717]
### Extension

https://www.raycast.com/notion/notion

### Description

When you Navigate to a database, choosing to show relation based poprties is not reflected in List or Kanban views.

### Steps To Reproduce

1. Create a database with a relation property.
2. Navigate to database and choose to show that relation property.
3. View items with missing relation property.

**Comment by thomaslombart** [comment]
Thanks for flagging this issue. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the [Slack community](http://raycastcommunity.slack.com/) if you need further help.

Note that opening up a PR and having it merged will earn you some credits as we want to reward contributions. You’ll then be able to exchange them in a swag store that we’ll launch soon!

**Comment by christianmagill** [comment]
@thomaslombart What would you say is the best place to get started learning the React side of things? My JavaScript skills are more based on what I've needed for marketing sites. I've experimented with Vue a tiny bit.

**Comment by thomaslombart** [comment]
I don't know, to be honest. It's been a long time since I learned React so not sure what's relevant as of today. I heard some good things about [The Joy of React](https://www.joyofreact.com) but that's pricey. Otherwise, I guess that the [React docs](https://react.dev/learn) are a good starting point since they've been revamped lately.
