### ISSUE TITLE
[Bitwarden Vault] Bitwarden new secret manager access

### ISSUE THREAD

**Issue by tahsinature** [raycast/extensions#8731]
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Description

I am a huge fan of Bitwarden and this Raycast extension.
Bitwarden recently introduced their secret manager. It would be nicer to have access to secrets so that we don't have to manage 2 different things to manage passwords and secrets.

### Who will benefit from this feature?

Developers

**Comment by jomifepe** [comment]
Hey. To be honest, I still don't have that feature on Bitwarden, it seems pretty new, and it probably hasn't been rolled out to my region. It might be something worth implementing, I'm not too sure if the CLI will keep up, and I'm 100% dependent on that, so that might be a blocker. But I'll see what can be done, once I'm able to play around with it.

**Comment by tahsinature** [comment]
Awesome. Seems like there is a new CLI and SDK for that.
https://bitwarden.com/help/secrets-manager-cli/
