### ISSUE TITLE
[Home Assistant] Direct entity action link

### ISSUE THREAD

**Issue by lanwen** [raycast/extensions#8742]
### Extension

https://www.raycast.com/tonka3000/homeassistant

### Description

I have quite a few lights which I toggle constantly and would be nice to have that as a hotkey assigned. I didn't find a way to communicate any arguments to the `lights` command via deep link, however, if that's possible in general, would be nice and sufficient to have that in the readme.

### Who will benefit from this feature?

Users who action on a specific entity often

**Comment by tonka3000** [comment]
Hi @lanwen ,

Right now there is no deeplink support, but I already thought about that. It is a little bit tricky to implement because I need to assume state of an entity which can fail in some cases and I'm still not sure how to implement them safely.

Right now the closest you can get are the menu bar commands.
In your case the light menu bar command can be the best fit.  You will see all your lights by default, but you can set filters in the command preferences to only show the light you want.
If you wanna mix entity types you can also checkout the entity menu bar command.

Of course, the menu bar command can not be aliased or can get a shortcut, but it is a handy way to access your lights faster.

Greetings
Michael

**Comment by Samywamy10** [comment]
+1 would love this.

I think even if the entities are subject to change (e.g. could be unavailable, not the right state etc.) a best guess would be good. I have lights, fans and other switches which I often toggle - I don't need to know the state, just need to issue the toggle command. If it fails you could send a toast or something.
