### ISSUE TITLE
[Remove Paywall] Get URL from active browser tab

### ISSUE THREAD

**Issue by grafst** [raycast/extensions#8748]
### Extension

https://www.raycast.com/tegola/remove-paywall

### Description

When I call the extension without an url it should use the url from the active browser tab.

### Who will benefit from this feature?

lazy people who don't want to copy and paste the url.

### Anything else?

Extracting the url of the current page should be possible. For example, see this https://www.raycast.com/koinzhang/copy-path.

Thank you very much for your work on this great extension 🙏.

**Comment by tegola** [comment]
Hey @grafst,
this was initially a must-have for me, but I scrapped it because the implementation wasn't trivial and there was the question of where to open the un-paywalled URL (e.g. I've copied it in Firefox but my default browser is Chrome): Raycast doesn't actually offer any API for getting the current URL or to open an URL in a different browser.

I still plan to add the functionality later, as I'm working on another feature at the moment. I'm open to contributions though.

As a workaround, you can just hit `⌘+L` in the current browser to select the URL in the address bar, then invoke the "Remove Paywall" command in Raycast to use the selected text as the input URL.
