### ISSUE TITLE
[Browser Bookmarks] Support Pulse Browser Alpha

### ISSUE THREAD

**Issue by notmudge** [raycast/extensions#8760]
### Extension

https://www.raycast.com/raycast/browser-bookmarks

### Description

Support Pulse Browser Alpha

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the [Slack community](http://raycastcommunity.slack.com/) if you need further help.

Note that opening up a PR and having it merged will earn you some credits as we want to reward contributions. You’ll then be able to exchange them in a swag store that we’ll launch soon!
