### ISSUE TITLE
[Wi-Fi] Menu bar icon does not update immediately when toggling wi-fi

### ISSUE THREAD

**Issue by xilopaint** [raycast/extensions#8781]
### Extension

https://www.raycast.com/koinzhang/wi-fi

### Description

Self-explanatory title.

### Steps To Reproduce

Click on `Toggle Wi-Fi` on menu bar command.

### Current Behaviour

Icon does not update immediately. 

### Expected Behaviour

Icon should update immediately.

**Comment by louishuyng** [comment]
Did you fix that yourself, @xilopaint? If not, let me take a quick look at it.

**Comment by xilopaint** [comment]
@louishuyng no, I didn't investigate it.

**Comment by koinzhang** [comment]
Hi @xilopaint @louishuyng. Thanks for the issue. Fix this issue in PR #10217

**Comment by koinzhang** [comment]
@raycastbot close this issue

**Comment by xilopaint** [comment]
<img width="257" alt="Screenshot 2024-01-19 at 20 39 41" src="https://github.com/raycast/extensions/assets/11052366/7fc9769c-6861-484b-8aa7-ea2d3c6664ab">

@koinzhang @pernielsentikaer PR #10217 didn't fix the issue. The menu bar icon is not immediately updated when I click on "Toggle Wi-Fi" that you can see in the image above. This issue should be reopened.

**Comment by xilopaint** [comment]
<img width="257" alt="Screenshot 2024-01-19 at 20 39 41" src="https://github.com/raycast/extensions/assets/11052366/7fc9769c-6861-484b-8aa7-ea2d3c6664ab">

@koinzhang @pernielsentikaer PR #10217 didn't fix the issue. The menu bar icon is not immediately updated when I click on "Toggle Wi-Fi" that you can see in the image above.

@raycastbot reopen this issue

**Comment by koinzhang** [comment]
@xilopaint It looks as if I overlooked this Toggle Wi-Fi path, I'll patch in a PR to fix this

**Comment by koinzhang** [comment]
@xilopaint Unfortunately, I've tried to use various methods to update the menu bar icon in a timely manner, but they all failed, and the issue can remain open, but there will be no new updates anytime soon.
For now I suggest you manually click once on the menu bar to update the icon after clicking Toggle Wi-Fi on the menu bar

@pernielsentikaer Here is the issue I am having:
I tried using launchCommand to run the Wi-Fi Signal command to update the menu bar icon when I clicked on the action in the menu bar, but it didn't take effect (I'm not sure if this is expected)
I also tried to use useState(`const [refresh, setRefresh] = useState<number>(0);`) to update the hook function as a way to refresh the icons, but that didn't work either, this works fine with normal commands, but not with this menu command, I'm not sure if it's because he's a menu bar command or if it's because I'm using exeSync

Also I'm experiencing console not being able to print logs, which makes debugging the extension difficult, do you have a solution for this?

If you understand why or have a good suggestion, feel free to suggest it!

**Comment by xilopaint** [comment]
@koinzhang a similar issue was reported in https://github.com/raycast/extensions/issues/7727 and fixed in https://github.com/raycast/extensions/pull/8261. Hope it can be useful.

**Comment by koinzhang** [comment]
Hi @xilopaint. In the PR #10561 , I fixed this problem in a clever way, but there are still some minor problems. Welcome to experience and give feedback after the PR is merged.

There are currently 2 problems
1. Toggle Wifi in the menu bar command uses deeplink, so a pop-up window will pop up for the first time.
2. When Wifi is turned off, after clicking Toggle Wifi in the menu bar command, the menu bar icon will change three times because the menu bar command is actually called three times.

**Comment by xilopaint** [comment]
> There are currently 2 problems
> 
> 1. Toggle Wifi in the menu bar command uses deeplink, so a pop-up window will pop up for the first time.
> 2. When Wifi is turned off, after clicking Toggle Wifi in the menu bar command, the menu bar icon will change three times because the menu bar command is actually called three times.

@koinzhang Now that the PR has been merged, should I close this issue or keep it open due to these two problems?
