### ISSUE TITLE
[Trello] ...

### ISSUE THREAD

**Issue by ignsanjeev121** [raycast/extensions#8789]
### Extension

https://www.raycast.com/ChrisChinchilla/trello

### Description

set default options in todo as for someone who will have to create todo and have mutiple users, it's frustrating to keep selecting same options multiple time for multiple todos, 99% of the time the following option stays the same for me

Assign to me

Select a board

Select a list from that board

### Who will benefit from this feature?

most of trello raycast user who use todo often

**Comment by ChrisChinchilla** [comment]
@ignsanjeev121 I have had some similar ideas to this, so yes, will add it to the todo list!

**Comment by ChrisChinchilla** [comment]
@raycastbot or @pernielsentikaer Can you assign me? That's how I tend to find issues later :)

**Comment by ChrisChinchilla** [comment]
@ignsanjeev121 I am looking at this, but trying to figure out the UX…

**Comment by ChrisChinchilla** [comment]
So, after some discussion with the Raycast team, this isn't actually possible right now. As to get it to work, I'd have to call Trello APIs to populate extension settings and that's not possible right now with Raycast. I am slowly adding other options to settings that at least filter what you will see, so that's one option for now.

**Comment by ChrisChinchilla** [comment]
@raycastbot close

**Comment by ignsanjeev121** [comment]
Thanks Chris for the update great to know you're working on it
