### ISSUE TITLE
[Zotero] Add an open pdf action.

### ISSUE THREAD

**Issue by wooogler** [raycast/extensions#892]
# Extension – [Zotero](https://github.com/raycast/extensions/tree/main/extensions/zotero)

Author: @sadanand-singh 

**Describe the feature and the current behavior/state.**
Can you add an action to open pdf file directly?
Thank you for creating zotero and notion extensions! They are really helpful to research!

**Who will benefit from this feature?**
Zotero users

**Any Other info.**
https://forums.zotero.org/discussion/86980/quickly-create-a-open-pdf-link
This link may help.

**Comment by sadanand-singh** [comment]
Thanks @wooogler! I had thought about adding that, but the issue is that for open-pdf links we would need the item key of the pdf not the actual parent reference. I was not able to find a way to find the item key of the pdf from the API. See the last comment in the above forum. If you are able to find a way to get this, please let me know, I would be happy to implement this quickly.

**Comment by sadanand-singh** [comment]
@wooogler Thanks for the suggestion. I have found a way to implement this. See PR #956.
