### ISSUE TITLE
[Port Manager] not working at all under sonoma

### ISSUE THREAD

**Issue by jrapp2** [raycast/extensions#8948]
### Extension

https://www.raycast.com/lucaschultz/port-manager

#### Error:
```
Error: Command failed: /usr/bin/sudo /bin/ps -p 0 -o comm=


ChildProcess.exithandler:node:child_process:422:12
ChildProcess.emit:node:events:517:28
ChildProcess.emit:node:domain:489:12
```

### Steps To Reproduce

I am using Sonoma.
Just using the "List open Ports" command (or starting the menu bar variant) results in the error message above.
In the UI, the following screen is shown: 
<img width="526" alt="image" src="https://github.com/raycast/extensions/assets/136393255/bd7bafdd-06a4-41d7-87c7-67463eeebf87">

### Current Behaviour

Error message, nothing is working.

### Expected Behaviour

A list of open ports.

**Comment by lucaschultz** [comment]
Hey @jrapp2 and potentially @samdenty, sorry for the long response time. For me, the extension works on Sonoma without any issues. It seems you are using the sudo option (see the [extension description](https://www.raycast.com/lucaschultz/port-manager)) which only works when your user is set up to [use sudo without a password](https://osxdaily.com/2014/02/06/add-user-sudoers-file-mac/). Could you have a look at the extension preferences, uncheck the "Use Sudo" option, and try again?

Even if I'm right and this is indeed the issue, you should still not get an error screen. Instead, you should receive a message explaining that you need to deactivate the sudo mode.

<img width="886" alt="Bildschirmfoto 2023-11-17 um 18 56 31" src="https://github.com/raycast/extensions/assets/45899273/b758ea5a-5e1b-4133-8029-01ee80468ab0">

I might remove the sudo mode in a future update because it is a pretty niche feature, and I don't think many users are using it. @pernielsentikaer, what do you think?

**Comment by samdenty** [comment]
i didn't change any settings but it now works. Strange

I also didn't enable sudo mode in settings, i just installed it fresh out the box
