### ISSUE TITLE
[GitHub Stars] Can't find the Stars

### ISSUE THREAD

**Issue by 0x0-00** [raycast/extensions#8986]
### Extension

https://www.raycast.com/mrmartineau/search-github-stars

### Description

There is no error in the network or username, but it keeps showing user does not exist.

### Steps To Reproduce

1.Setting the user name
2.Shortcut Search

**Comment by mrmartineau** [comment]
@0x0-00 Which username are you adding to the extension's settings? If I use yours, I am able to see your stars: 
<img width="1263" alt="image" src="https://github.com/raycast/extensions/assets/64883/12fc7d97-f07f-474b-820b-401da63aca58">

Double-check the extension settings and let us know if the bug is still present.

**Comment by 0x0-00** [comment]
There are no errors in the username, and occasionally the query succeeds, but in most cases the query fails while the request is being processed. Can we wait a little longer?
