### ISSUE TITLE
[Notion] Selecting a browser to open pages

### ISSUE THREAD

**Issue by Harosatchi** [raycast/extensions#9005]
### Extension

https://www.raycast.com/notion/notion

### Description

Add the ability to open pages in the browser of your choice (in addition to default browser). Specifically interested in Arc (and specifically Little Arc).

Now there are only two options - the app and the default browser. And if there is no app, then both options lead to the default browser.

### Who will benefit from this feature?

All users

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the [Slack community](http://raycastcommunity.slack.com/) if you need further help.

Note that opening up a PR and having it merged will earn you some credits as we want to reward contributions. You’ll then be able to exchange them in a swag store that we’ll launch soon!
