### ISSUE TITLE
[Linear] Ability to paste image / screenshot when creating a new issue

### ISSUE THREAD

**Issue by tristanadlington** [raycast/extensions#9072]
### Extension

https://www.raycast.com/linear/linear

### Description

When creating a new Linear ticket via Raycast I would like to be able to paste an image into the description. Most people use screenshot tools (Cleanshot) to capture and copy a screenshot to their clipboard. Ideally I would then be able to paste this into the ticket I am creating. Saving the file and then selecting is too slow and hard to do without reaching for the mouse.

**Comment by thomaslombart** [comment]
It's not possible to do so with a textarea field. However, note you can use the `Attachment` field like shown in the screenshot:

![CleanShot 2023-11-03 at 12 37 41@2x](https://github.com/raycast/extensions/assets/16003285/3f3cba95-51e1-4c34-9801-f45fdbee01b4)

**Comment by tristanadlington** [comment]
Yes that makes sense. What I'm requesting is the ability to paste in a screenshot / image to the ticket I'm creating. Whether thats in a rich text field or separate input I don't necessarily mind. I just don't want to have to save a screenshot to my laptop and then find it using the current 'add file' flow you have. I just want to press CMD+V to paste it into the ticket (like I do in Linear).

**Comment by thomaslombart** [comment]
So, we've reviewed this feature request, and while we see its value, it's not something we'll be doing anytime soon. This is mostly because pasting an image into a form field (as done on Linear or GitHub) would mean uploading these images somewhere, which comes with its own set of challenges. As saving an image into files is relatively low effort, this makes this feature request too costly. Thanks for your understanding! 🙌
