### ISSUE TITLE
[Apple Reminders] Menu Bar Reminders

### ISSUE THREAD

**Issue by crym** [raycast/extensions#9086]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

The "My Reminders" command is able to filter reminders on a certain list. 
The Menu Bar Reminders displays reminders for all lists. This includes "past due" reminders from all lists. 
I would like to be able to select which list(s) to display reminders from. The list selection could be made in the settings in the same way the "View" is configured.

### Who will benefit from this feature?

Everyone who uses different lists for different purposes. Separate work/personal reminders etc.

**Comment by tmwrnr** [comment]
Hi @thomaslombart,

I am interested in working on this! Currently, I have a few potential solutions in mind:

## Solutions

### 1. Preferences

One option is to save the name of the list in the command preferences. Then, only display reminders from the selected list. However, this approach is prone to errors due to user input. The preference can only be a `textfield`, and the list name can change without notice.

### 2. Shared State

We could utilize the cached state of the `my-reminders.tsx` command. If I make changes to the list there, it would also reflect in the menu bar. The drawback here is that you can select a list (e.g., `today`) that is already in the preferences.

### 3. Cached State

Similar to `my-reminders.tsx`, we could add a cached state with the list ID. The list can be modified in the command bar using a submenu. The submenu would list all available lists for selection.

# Conclusion

Personally, I prefer solution 3. It eliminates the need to access command preferences and prevents the user from entering an incorrect list name. Additionally, it allows for displaying different lists in the command bar and the My Reminders command. What do you think is the best option?

**Comment by thomaslombart** [comment]
Solution 3 is indeed a great compromise, as you did with the PR.
