### ISSUE TITLE
[Google Workspace] Add ability to create Google Doc / Sheet in specific Shared G Drive Folder

### ISSUE THREAD

**Issue by dan-thatch** [raycast/extensions#9112]
### Extension

https://www.raycast.com/raycast/google-workspace

### Description

G Suite does not allow us to change the default drive or folder for creating new docs or sheets, which makes it a pain for permissions when trying to spin up new docs quickly and share with the rest of the team. It'd be nice if this extension would allow us to specific a specific shared G Drive and Folder so we could circumvent this G Suite limitation.

### Who will benefit from this feature?

Employees from any company that struggle with creating docs quickly and ensuring that folks have the correct permissions to edit, comment, etc.

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the [Slack community](http://raycastcommunity.slack.com/) if you need further help.

Note that opening up a PR and having it merged will earn you some credits as we want to reward contributions. You’ll then be able to exchange them in a swag store that we’ll launch soon!
