### ISSUE TITLE
[obsidian] search note cannot search some file created by excalidraw

### ISSUE THREAD

**Issue by t427794322** [raycast/extensions#9141]
### Extension

https://www.raycast.com/KevinBatdorf/obsidian

### Description

cmd search note cannot search some file created by excalidraw, for examples: "学习新知识.excalidraw.md"

### Steps To Reproduce

1.  getinto obsidian search note 
2. type: "学习新知识.excalidraw.md", there is no result, but I have created it

### Current Behaviour

there is no result 

### Expected Behaviour

display the the right results

**Comment by KevinBatdorf** [comment]
If you search the title of the note instead of the file name, does it show up?

Alternatively, if you enable "search content" int he preferences it will search the title too. 

![284080422-017ca286-47bd-4082-b4af-f01cfffe213b](https://github.com/raycast/extensions/assets/1478421/03d2afb2-ece4-4696-84d5-181b11c06722)

Does that work?
