### ISSUE TITLE
[Visual Studio Code] Cannot read properties of undefined (reading 'publisherId')

### ISSUE THREAD

**Issue by ashchen738** [raycast/extensions#9160]
### Extension

https://www.raycast.com/thomas/visual-studio-code

### Description

Doesn't show installed extensions. Shows error, saying Cannot read properties of undefined (reading 'publisherId'). VS Code is installed.

### Steps To Reproduce

Install VS Code extension
Open "Show installed extension" command
See error

### Current Behaviour

Shows nothing and has error

### Expected Behaviour

Should display installed extensions

**Comment by erics118** [comment]
To debug, could I get a bit more information?
- Do you use VSCode, or some similar variant, eg Cursor, VSCodium?
-  It could be that one of the extensions has a broken manifest. Could you provide a list of all your installed extensions? You can do this with:
```sh
code --list-extensions
```
- Do you have any extensions installed via a different means than the VSCode extension marketplace?

**Comment by tonka3000** [comment]
@erics118

There is a high chance that @ashchen738 has a local installed extension which does not contain a `metadata` field (this get injected from the "install via store") and therefore there is no `publisherId`.

The fix should be straight forward. Make `metadata` optional (`e.metadata?.publisherId` instead of `e.metadata.publisherId`)  [here](https://github.com/raycast/extensions/blob/0cee84c2d60433969934376eaf9044ef552f6749/extensions/visual-studio-code-recent-projects/src/lib/vscode.ts#L160) and [here](https://github.com/raycast/extensions/blob/0cee84c2d60433969934376eaf9044ef552f6749/extensions/visual-studio-code-recent-projects/src/lib/vscode.ts#L161C13-L161C13).
Also mark [metadata](https://github.com/raycast/extensions/blob/0cee84c2d60433969934376eaf9044ef552f6749/extensions/visual-studio-code-recent-projects/src/lib/vscode.ts#L12) as nullable as well as [here](https://github.com/raycast/extensions/blob/0cee84c2d60433969934376eaf9044ef552f6749/extensions/visual-studio-code-recent-projects/src/lib/vscode.ts#L29) and [here](https://github.com/raycast/extensions/blob/0cee84c2d60433969934376eaf9044ef552f6749/extensions/visual-studio-code-recent-projects/src/lib/vscode.ts#L30C3-L30C3).

It seems that I forget that only store based extension have these fields when I impl. that feature.

**Comment by tonka3000** [comment]
@ashchen738 I made a fix for the issue (#9888). Maybe you can check if it fix your issue.
