### ISSUE TITLE
[Music] "Play Library Album" plays wrong album.

### ISSUE THREAD

**Issue by christianmagill** [raycast/extensions#9208]
### Extension

https://www.raycast.com/fedevitaledev/music

### Description

I've run into an album where selecting the album triggers the playing of a different album. This happens to the same album regardless of the search.

### Steps To Reproduce

I'm not sure what would be most helpful here, but the album in question is Quality by Talib Kweli. The album that plays when Quality by Talib Kweli is selected is Quality Control by Jurassic 5. What's interesting is this happens whether I search by referencing the album title, or the artist name.

**Comment by darmijo15** [comment]
I just experienced this bug.

I have two "Albums" in my Library:
- "Demonstration - EP" by Big Boy
- "Demo" - Fury 

Whenever I use "Play Library Album" to search and play "Demo" by Fury, it plays Demonstration - EP.

I deleted Demonstration - EP and added "Demo - Single" by Fleshwater. When I try to play Demo by Fury, it plays Fleshwater instead.

I think the issue is the command is searching for the first instance of "Demo" in my albums and playing "Demonstration" because that's the first string it catches.

**Comment by rawnly** [comment]
> I think the issue is the command is searching for the first instance of "Demo" in my albums and playing "Demonstration" because that's the first string it catches.

https://github.com/raycast/extensions/blob/ca9591bce9ebaec1386fd03a6162f020e5da489f/extensions/music/src/util/scripts/albums.ts#L60-L77

Maybe by changing the part `whose albums contains ${album}` to `whose album is ${album}` could fix this. Unfortunately there's no official supported command to play an album so it's error prone in this way.
