### ISSUE TITLE
[Toggle Audio Input (microphone)] ...

### ISSUE THREAD

**Issue by jackkerhere** [raycast/extensions#9342]
### Extension

https://www.raycast.com/Quentin23Soleil/mute-microphone

### Description

Hello, I'm a big fan of this extension you've made! I was wondering if you could help me with something to make the menu bar icon more noticeable. I would like to request the menubar icon be boxed up in Red (muted) and Green (unmuted) similar to the new icon on Mac OS Sonoma (refer to image below).

![Xnip2023-11-21_15-31-19](https://github.com/raycast/extensions/assets/54267080/fadf0cbc-24c6-42f9-9a46-18708c632002)

I'm no coder but I tried going through this page (https://developers.raycast.com/api-reference/user-interface/icons-and-images#image.imagelike) but was not able to change it myself.. really would appreciate it if you could teach me how to do so!

### Who will benefit from this feature?

only me really..

### Anything else?

thank you very much for your contribution!

**Comment by parkeraddison** [comment]
Hey I felt this was lacking too, since I rely on the color to help me quickly tell if my mic is hot. Fortunately you can edit the extension code locally to achieve this. Here are the steps:

1. Find the extension source code, for me this was at _"~/.config/raycast/extensions/c9ece8c4-784f-48e9-8a7a-7b67ffae12e8/mute-menu-bar.js"_ 
	```shell
	find ~/.config/raycast/extensions/ -name "mute-menu-bar.js"
	```

2. Open the file, find the span of code responsible for the icons, and change it to use your desired `tintColor`:
	```diff
	- c=u==0?r.Icon.MicrophoneDisabled:r.Icon.Microphone
	+ c=u==0?{source:r.Icon.MicrophoneDisabled, tintColor:r.Color.Red}:{source:r.Icon.Microphone, tintColor:r.Color.Green}
	```
    Then save the file! It'll use the new value the next time you toggle the mute.

You can use any colors as explained in the Raycast Colors docs: https://developers.raycast.com/api-reference/user-interface/colors#color. I figured out how to do this through the Raycast Icons & Images docs: https://developers.raycast.com/api-reference/user-interface/icons-and-images#properties

## Going beyond
Ideally we can use command preferences to allow users to choose their desired colors for the enabled and disabled icons, without needing to dive into the source code.

Some docs to make this happen:
- https://developers.raycast.com/information/manifest#preference-properties
- https://developers.raycast.com/api-reference/preferences

**Comment by iamyeizi** [comment]
@parkeraddison thank you so much!

**Comment by iamyeizi** [comment]
@raycastbot close this issue
