### ISSUE TITLE
[Notion] Open page in browser or app when searching pages

### ISSUE THREAD

**Issue by Yakitrak** [raycast/extensions#9361]
### Extension

https://www.raycast.com/notion/notion

### Description

Currently we can configure the default settings to open a page in browser or app from the extension settings but this applies to everything. It would be helpful to use the actions menu when searching a page and chose to open in app/browser specifically for that interaction.

### Who will benefit from this feature?

Any user who wants to have more control on where certain pages are opened

### Anything else?

I am happy to add a PR for functionality if you agree - would appreciate any guidance.

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the [Slack community](http://raycastcommunity.slack.com/) if you need further help.

Note that opening up a PR and having it merged will earn you some credits as we want to reward contributions. You’ll then be able to exchange them in a swag store that we’ll launch soon!

**Comment by Yakitrak** [comment]
@thomaslombart thank you for the reply! Yes I'll be happy to work on it. Haven't looked into the extensions code too much but I have a rough idea how it would work - but any advice on best approach or things to keep in mind would be appreciated.

**Comment by Yakitrak** [comment]
@thomaslombart I've created a quick PR for this: https://github.com/raycast/extensions/pull/9411
