### ISSUE TITLE
[Apple Reminders] Ability to Assign a Reminder to a List when using the Quick Reminder

### ISSUE THREAD

**Issue by csatwood** [raycast/extensions#9374]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

When entering a Quick Reminder it would be nice to enter the list name you want it to be added to via a "#" (a la Todoist or InstaRemind) to be able to drop a reminder into the right context.

### Who will benefit from this feature?

Everyone using Quick Reminders that wants to add the reminder to a specific list at the time of creation.

**Comment by thomaslombart** [comment]
You can already specify the list name so that the AI understands which list to pick. For example, `Fix a bug in Raycast` will add the reminder `Fix a bug` to the `Raycast` list. It's possible the AI doesn't properly pick up the list name, so in this case, you can literally add the word `list` to the reminder (e.g `Fix a bug in Raycast list`).
