### ISSUE TITLE
[Browser Bookmarks] Request support for Vivaldi Snapshot

### ISSUE THREAD

**Issue by QuantumRoseinAmethystVase** [raycast/extensions#9409]
### Extension

https://www.raycast.com/raycast/browser-bookmarks

### Description

I noticed that Vivaldi is among the supported browsers for Browser Bookmarks, but as a niche browser, Vivaldi has a long update cycle. Therefore, choosing Vivaldi Snapshot is another option. However, Browser Bookmarks is not compatible with Vivaldi Snapshot, even if I change the app's name. It would be great if bookmarks that support Vivaldi Snapshot could be available.

### Who will benefit from this feature?

All users using Vivaldi Snapshot.

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the [Slack community](http://raycastcommunity.slack.com/) if you need further help.

Note that opening up a PR and having it merged will earn you some credits as we want to reward contributions. You’ll then be able to exchange them in a swag store that we’ll launch soon!

**Comment by QuantumRoseinAmethystVase** [comment]
> Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the [Slack community](http://raycastcommunity.slack.com/) if you need further help.
> 
> Note that opening up a PR and having it merged will earn you some credits as we want to reward contributions. You’ll then be able to exchange them in a swag store that we’ll launch soon!

It's okay if it's within my power. What can I do?

**Comment by thomaslombart** [comment]
Some users have made contributions similar to the one you're requesting before. You can take a look at theirs to get some inspiration: https://github.com/raycast/extensions/pulls?q=label%3A%22extension%3A+browser-bookmarks%22+is%3Aclosed+is%3Apr
