### ISSUE TITLE
[Coffee] The Caffeinate/Decaffeinate command creates zombie processes

### ISSUE THREAD

**Issue by faultables** [raycast/extensions#9410]
### Extension

https://www.raycast.com/mooxl/coffee

### Description

I use this extension very often (big thanks for making it!) and just noticed that every time I run `caffeinate` and `decaffeinate`, it creates a zombie process with "Raycast Helper (Extensions)" as the parent process.

![CleanShot 2023-11-25 at 00 50 47@2x](https://github.com/raycast/extensions/assets/6561394/fa0c5f65-913b-42a8-8958-0900724dea7e)

I don't know exactly who is responsible for this issue (the extension developer? the extension API itself?) and the workaround is of course by killing the "Raycast Helper (Extensions)" process which is most likely harmless.

### Steps To Reproduce

1. Install the [Coffee](https://www.raycast.com/mooxl/coffee) extension
2. Launch Raycast, select "Caffeinate"

### Current Behaviour

The coffee command is executed, works as intended (prevent mac from sleeping) and the `<defunct>` process will appear (`ps -ef | grep defunct`)

### Expected Behaviour

No defunct processes are created

**Comment by pernielsentikaer** [comment]
Do you have a clue what the might be @erics118

**Comment by erics118** [comment]
I have no clue why the process is kept hanging. I tried a few things to attempt to fix it, including adding a `&` or a `&; disown` to the end of the `(start|end)Caffeinate`, which didn't seem to change anything.

**Comment by faultables** [comment]
After playing around for a while if we use `execSync` instead of async `exec`, the problem seems to go away?

![CleanShot 2023-11-26 at 14 28 34](https://github.com/raycast/extensions/assets/6561394/17462037-7199-4e80-86cc-72c91874c112)

The patches:

```diff --git a/extensions/coffee/src/utils.ts b/extensions/coffee/src/utils.ts
index 7018c7f..394aca1 100644
--- a/extensions/coffee/src/utils.ts
+++ b/extensions/coffee/src/utils.ts
@@ -1,5 +1,5 @@
 import { getPreferenceValues, launchCommand, LaunchType, showHUD } from "@raycast/api";
-import { exec } from "node:child_process";
+import { execSync } from "node:child_process";
 
 function preventArguments(args?: string | undefined) {
   const preferences = getPreferenceValues<Preferences>();
@@ -42,7 +42,7 @@ export async function stopCaffeinate(updateMenubar = true, hudMessage?: string)
     await showHUD(hudMessage);
   }
 
-  return exec("/usr/bin/killall caffeinate");
+  return await execSync("/usr/bin/killall caffeinate || true");
 }
 
 export async function startCaffeinate(updateMenubar = true, hudMessage?: string, args?: string | undefined) {
@@ -60,5 +60,5 @@ export async function startCaffeinate(updateMenubar = true, hudMessage?: string,
     await showHUD(hudMessage);
   }
 
-  return exec(`/usr/bin/caffeinate ${preventArguments(args)}`);
+  return await execSync(`/usr/bin/caffeinate ${preventArguments(args)} || true`);
 }
```

Are there any side effects when using `execSync` in the Raycast API?

**Comment by neumannjan** [comment]
+1, also observing this issue

**Comment by pernielsentikaer** [comment]
Are any of you up for a PR? Otherwise I can do it when I have time

**Comment by erics118** [comment]
I've created a PR that implemented the suggested code changes.

**Comment by ShikChen** [comment]
**Note for Future Readers Encountering Zombie Processes with Raycast Extensions and Menu Bar Commands:**

If you're experiencing zombie subprocesses when using asynchronous execution in your Raycast extensions, the issue might be related to improper handling of component unmounting. To resolve this, ensure you're correctly wiring an `AbortSignal` with the cleanup function in `useEffect()`.

**Potential Cause:**

This could happen due to multiple component renders, possibly triggered by React's Strict Mode. Strict Mode intentionally mounts and unmounts components twice to help catch side effects (though it's unclear if this applies in Raycast since it's not open source, to my knowledge).

When the first component instance finishes its asynchronous task and updates `isLoading` in `MenuBarExtra` to `false`, it may unmount all instances and stop the JavaScript environment. If a second instance still has an active asynchronous subprocess, that process can become orphaned when the component unmounts, leading to a zombie subprocess.

**Comment by sladg** [comment]
Hey! I'm seeing `<defunct>` processes from last month.

When a MacBook runs for a couple of days, it becomes unusable (programs randomly fail, processes won't open as resources deplete).

It's coming from the `Raycast Helper (Extensions)` process. I've tried disabling a bunch of extensions (in case it's caused by a 3rd party), but I wasn't able to pinpoint it further.


Any suggestions?

**Comment by arthur-fontaine** [comment]
For a few weeks now I have the same <defunct> processes created and it makes my MacBook unstable too (`fork failed resource temporarily unavailable`).

I have the caffeinate extension installed, I haven't tried to disable it yet.

@sladg is it possible for you to share a list of your installed extensions? Maybe we can find the common extension that makes our both Mac crash after a few days on.

**Comment by sladg** [comment]
> For a few weeks now I have the same processes created and it makes my MacBook unstable too (`fork failed resource temporarily unavailable`).
> 
> I have the caffeinate extension installed, I haven't tried to disable it yet.
> 
> @sladg is it possible for you to share a list of your installed extensions? Maybe we can find the common extension that makes our both Mac crash after a few days on.
> 
> **EDIT**
> 
> After investigating, I found that those zombie processes were created by [Connect to VPN](https://www.raycast.com/rasmusbe/connect-to-vpn) extension every 30 seconds. It matches with a change made last month [989f3ec#diff-291e4da920717a0f856d10b8a6d0d2b79a1caf7376c8bc8c34b736af7992002bR28](https://github.com/raycast/extensions/commit/989f3ec7e74a3e5400b5f1d6f899aa2df231287f#diff-291e4da920717a0f856d10b8a6d0d2b79a1caf7376c8bc8c34b736af7992002bR28).
> 
> I will open a new issue.

Great find! I uninstalled offending extension - https://www.raycast.com/rasmusbe/connect-to-vpn and it seems to be fixed now!
