### ISSUE TITLE
[Apple Reminders] Today facet not displaying all of the tasks scheduled for today

### ISSUE THREAD

**Issue by bdielman** [raycast/extensions#9507]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

When using the extension and viewing Today it only shows maybe one or two of my reminders scheduled for today. Changing the due date, restarting Raycast and Reminder, moving the tasks into different lists… Nothing seems to work

### Steps To Reproduce

1. Latest MacOS (14.1.2)
2. Open up Raycast and choose 'My Reminders'
3. Use `CMD`+`P` to choose the 'Today' list

### Current Behaviour

Opening 'My Reminders' and switching to 'Today' I only see a few of the reminders I have due. When I change the facet to 'Scheduled' I see all of the reminders due today

### Expected Behaviour

I expect the 'Today' list in the extension to reflect what I see in Apple Reminders

**Comment by thomaslombart** [comment]
Looks like a timezone issue? What's your timezone and at which time did you check that?

**Comment by bdielman** [comment]
Can't remember the time I checked, but this could definitely be timezone related as I've had similar issues with the Asana extension. I notice I don't see this issue with the Todoist extension, but I could test it out as the day winds down. Currently EST

**Comment by thomaslombart** [comment]
All right, I'll take a look at that.

**Comment by bjork24** [comment]
This also seems to happen when adding a reminder via Siri. If you say "Siri, remind me to mow the yard tomorrow" the reminder will be set with a date only, no time. The Raycast reminder facet seems to ignore reminders that don't have a default time associated with them.

**Comment by lucasnad27** [comment]
I'm also experiencing a similar issue. And I don't believe it has anything to do with timezones, but perhaps the "time" piece that @bjork24 mentioned above. Over the past couple of weeks, it seems that the "My Reminders" feature, when filtered to "Today" is almost always missing most of my reminders. Only took a couple of tasks not getting done because I wasn't aware of them before I removed this from my workflow🤣 I'd love to add it back if I could get the two "Today" views consistent. I've tried quitting the Raycast and Reminders app, and I still can't get them in sync. Screenshot below to show the problem.

![image](https://github.com/raycast/extensions/assets/2490636/b2d80f15-f5b7-4be4-b854-3b3789274e26)

If it's helpful, I'm happy to try and come up with steps to reproduce.

**Comment by xilopaint** [comment]
I hope it can be fixed soon. The extension is unusable.

**Comment by bdielman** [comment]
@thomaslombart Thanks! Seems to be working for me 🥳

**Comment by lucasnad27** [comment]
So far, so good. thanks @thomaslombart !!
