### ISSUE TITLE
[Jira] Unable to select workspace

### ISSUE THREAD

**Issue by TWHarr** [raycast/extensions#9548]
### Extension

https://www.raycast.com/raycast/jira

### Description

My Atlassian account is connected to two different workspaces, A and B. I was initially only in workspace A, and was able to use the Jira extension as expected. I have moved internally, and was assigned to a new project with workspace B. When i log out of the jira extension and reconnect it, selecting workspace B on the login page, I still only see data from workspace A. 

### Steps To Reproduce

1. Create two separate Jira workspaces (A and B). Invite a user to workspace A only. 
2. Connect the Jira extension as normal. 
3. Invite the user to workspace B as well. 
4. Log out of the Raycast Jira extension. 
5. Reestablish the connection, and select workspace B from the dropdown. 

### Current Behaviour

I continue to see projects and data from Workspace A.

### Expected Behaviour

I see projects and data from Workspace B in Raycast.

**Comment by thomaslombart** [comment]
Could you uninstall and reinstall the extension, and let me know if it works for you?

**Comment by stigkj** [comment]
Hi, I have the same issue. I have tried now to logout and then uninstalling & reinstalling, but it is still not working after logging in again.

Would it be [here](https://github.com/raycast/extensions/blob/main/extensions/jira/src/helpers/withJiraCredentials.tsx#L39) you choose the workspace? I have not debugged this, but maybe the workspace I choose is not always the first one?

**Comment by thomaslombart** [comment]
So, to be clear, when you say "workspace", do you mean, another Jira site (as in you were using `https://foo.atlassian.net` and now `https://bar.atlassian.net`)? If so, then it may be related to what @stigkj noticed. Could you [fork the extension](https://developers.raycast.com/basics/contribute-to-an-extension#get-source-code) and let me know if you see multiples sites if you add a `console.log` right after retrieving the sites?

**Comment by esthor** [comment]
I have the same issue and @stigkj's identification of the single line is precisely the issue.

Currently, I pulled the repo and running it locally with hardcoded `site = sites[1]` because I exactly want the second site for my specific multi-Jira setup....

I'd love to PR, but I don't have bandwidth tonight...I'm thinking "site selection" should have:
- Must Have: If request comes back with more than 1 element in the array of sites, the user should be prompted to select which one
- Very God to Have: If a user has selected a site frommultiple, we should persist (and update) the list of sites so a user can easily switch (without logout -> login -> select site). Probably in the extension config, because a command may take up too much space for a rarely needed config change?

(lol, look at me basically defining a Jira ticket for this...so meta 🙄 )

**Comment by esthor** [comment]
Ok, I lied. I did have some bandwidth. I *think* this is working, but I need to test on another Jira instance tomorrow to be more confident.
