### ISSUE TITLE
[iMessage 2FA] ...

### ISSUE THREAD

**Issue by msneves13** [raycast/extensions#9570]
### Extension

https://www.raycast.com/yuercl/imessage-2fa

### Description

when I receive the code, the extension takes a long time to display the code.

### Steps To Reproduce

1 - send a sms code to your phone
2 - check on your phone that you received the code
3 - open the extension 

### Current Behaviour

does not display the code when received

### Expected Behaviour

display the code instantly or a few seconds after receiving it

**Comment by samdenty** [comment]
same issue not working

**Comment by yuercl** [comment]
It's depending on how fast iCloud synchronizes iMessage, 2FA can only read the content after iMessage synced. Hope to help.

**Comment by ariktatishev** [comment]
Same issue here

**Comment by garyhtou** [comment]
This seems to have been resolved for me! I'm not sure what fixed it

**Comment by yuercl** [comment]
> Same issue here

This is a phenomenon https://github.com/raycast/extensions/issues/10113#issuecomment-1928511204. And do you think it is caused by iMessage synchronization?

**Comment by navtoj** [comment]
If the message is showing in the `Messages.app` but not in the extension then maybe it's an issue with the **sql query not filtering the message** since it's being checked every second.
https://github.com/raycast/extensions/blob/e815950fc123da16c68757d5b3686dd2456075be/extensions/imessage-2fa/src/index.tsx#L8
https://github.com/raycast/extensions/blob/e815950fc123da16c68757d5b3686dd2456075be/extensions/imessage-2fa/src/messages.ts#L59

**Comment by bcometa** [comment]
FYI: 2FA is working perfectly for me now (I use it daily).

**Comment by samdenty** [comment]
I had to follow https://discussions.apple.com/thread/252335837?sortBy=best
