### ISSUE TITLE
Converting Image to WEBP Error

### ISSUE THREAD

**Issue by kevindesign22** [raycast/extensions#9615]
### Description

When I try to convert an image to WEBP I get the following error:

Command failed: /Users/kevinbhagat/.config/raycast/extensions/7c158f0e-b70b-4922-8a1b-5c8a9ccb55d6/assets/webp/cwebp "/Users/kevinbhagat/Desktop/Screenshot 2023-12-08 at 9.58.40 AM.png" -o "/Users/kevinbhagat/Desktop/Screenshot 2023-12-08 at 9.58.40 AM.webp"
/bin/sh: /Users/kevinbhagat/.config/raycast/extensions/7c158f0e-b70b-4922-8a1b-5c8a9ccb55d6/assets/webp/cwebp: Bad CPU type in executable

**Comment by mathieudutour** [comment]
Seems like this issue is about a specific extension, not the API. Would you mind opening a new issue using the [correct template](https://github.com/raycast/extensions/issues/new?assignees=&labels=extension%2Cbug&projects=&template=extension_bug_report.yml&title=%5BExtension+Name%5D+...) so that the authors of the extension are properly aware of it?
