### ISSUE TITLE
[Wikipedia] Add Fuzzy Search for Page Searches

### ISSUE THREAD

**Issue by medio4** [raycast/extensions#9702]
### Extension

https://www.raycast.com/vimtor/wikipedia

### Description

Currently, searching for pages requires the _exact_ title of the page you're looking for.
If fuzzy search was implemented, it would be quite a bit easier to get to where you're looking for.

**Comment by vimtor** [comment]
Thanks for the suggestion!

The current search has fuzzy search built-in:

![CleanShot 2023-12-16 at 10 56 51@2x](https://github.com/raycast/extensions/assets/36263538/1a815f8d-9728-4040-b1df-e844392d0e5b)

Could you please share some examples so that I can test them with the other search algorithms?
