### ISSUE TITLE
Folder moved and folder path updated, but scripts cannot be found

### ISSUE THREAD

**Issue by thomastardy** [raycast/extensions#978]
# Extension – [Script Commands Store – Find and manage your Raycast Script Commands](https://github.com/raycast/extensions/tree/de047f2e9ad02d2c79a526f2291f64f74aca05b6/extensions/script-commands/)
Author: @unnamedd

## Description
I moved the folder the extension is installing the script command into.
Then I updated the folder path of this extension and added the new folder to the script commands extensions.
But the script command don't show up.
But the extension thinks the script commands are installed. And when I try to uninstall a script command, it fails because some file cannot be found (points to the old folder).

## Steps To Reproduce

1. Install extension
2. Install any script command
3. Move the folder
4. Reconfigure the folder

## The current behavior
I cannot us the installed script commands and cannot deinstall them.

## The expected behavior
I need kind of a reindex of the folder.

### Raycast version
Version: 1.29.0

**Comment by unnamedd** [comment]
Hello @thomastardy,
unfortunately, this is something I didn't foresee might happen when I develop the extension, there are a couple of things that can be done to solve the problem, but they had to be done manually until I create an automated folder migration.

For now, the best thing you can do to solve the problem is restore to the original path the Script Commands folder and the index should get back to normal.

Please, reach me out on Slack if you prefer to discuss more about it. 
My username there is: tholanda.

**Comment by thomastardy** [comment]
Hi @unnamedd 
Thanks for your quick response!
Can you list the things I have to do manually. I would very much like to do this.

**Comment by unnamedd** [comment]
@thomastardy sorry for the not so quick answer, but definitely today isn't being a good day for all of us, however I will prepare some steps for you soon. I will try to find you on Slack, but for now, please be patient.
