### ISSUE TITLE
[World Clock] Daylight savings starting and ending impacting the times in the menubar

### ISSUE THREAD

**Issue by aprice42** [raycast/extensions#9789]
### Extension

https://www.raycast.com/koinzhang/world-clock

### Description

Related to #5798 

I experienced this issue last spring, just after daylight savings started. After time in my area moved an hour forward, all of the favorite times in my world clock menu bar were an hour behind.

Now after Daylight savings time ended, and time in my area moved an hour backward, all of the favorite menu bar times are an hour ahead. 

I haven't looked at the code, but I am betting that there is nothing taking time changes into consideration to update the saved favorites?

### Steps To Reproduce

1. Enable the menu bar feature of the plugin
2. Add some timezones as favorites (I have: NY, Chicago, LA, UTC)
3. Simulate a daylight savings event (time moves one hour ahead or backward)
4. Note that the favorites added above now do not reflect the correct times

**Comment by koinzhang** [comment]
Hi @aprice42. In the third part of the reproduction steps, I don't quite understand how it works, so I can't reproduce it.

**Comment by aprice42** [comment]
@koinzhang I am not totally sure the best way to do that since my experience was an actual Daylight savings event and the time on my mac changed automatically. I am guessing if you disable the automatic time setting on your mac and set it to an hour earlier or later it would reproduce the issue.

**Comment by kngtani** [comment]
I think the issue is that when you star a timezone, for example America/Los_Angeles during which this timezone was in DST, it stays in DST even when the actual timezone transitioned to Standard Time.  
My starred timezone that have DST (America/Los_Angeles, America/New_York, etc) were still showing the time in DST even today, until I unstarred them and then re-starred them again which is now showing the correct Standard Hours for the timezone. This workaround is a bit of pain as the alias gets cleared when you unstar a timezone.
It'll be great if this issue can be solved soon - it's a great extension I use frequently.

**Comment by koinzhang** [comment]
keep active
