### ISSUE TITLE
[Notion] another endpoint access denied error on fresh raycast install

### ISSUE THREAD

**Issue by jacobnollette** [raycast/extensions#9813]
### Extension

https://www.raycast.com/notion/notion

### Description

First and foremost, ray cast isn't in the notion connection store anymore; alter, I created a connection key, it can't connect or come up with relevant data.

### Steps To Reproduce

1) install notion plugin
2) create notion connection key
3) add notion key to raycase plugin
4) trigger raycast notion extension and let it rip

### Current Behaviour

access denied; this error shows once

### Expected Behaviour

popular notion search or notion compose with relevant information

**Comment by jacobnollette** [comment]
I suspect the issue is that Raycast is no longer in the notion integration store

**Comment by jacobnollette** [comment]
we back from holiday break - any update on weather this can get jumpstarted back into the notion app store?

**Comment by thomaslombart** [comment]
I don't think it has ever been in the Notion store. Could you send a recording? Do you maybe have more error logs to share?

**Comment by jacobnollette** [comment]
The raycast documentation states to add the integration in notion as well.

**Comment by vardecab** [comment]
I happen to have the same problem. Just installed Notion through Raycast and cannot connect. 

That's how it's set up in Notion (I copy-pasted secret to Raycast): 
<img width="978" alt="image" src="https://github.com/raycast/extensions/assets/6877391/2cd3a16f-78f3-4e22-bd49-5216aac74d8f">

<img width="726" alt="image" src="https://github.com/raycast/extensions/assets/6877391/9f2d2b8c-60ce-40ee-9b93-46003f912f0b">


<br>
And that's what Raycast returns: 
<img width="788" alt="image" src="https://github.com/raycast/extensions/assets/6877391/98766987-29b6-4445-a59e-a1954c6ab34c">

PS, that instruction is no longer up-to-date as the layout in Notion has changed.

<img width="498" alt="image" src="https://github.com/raycast/extensions/assets/6877391/d8696f28-4bdb-4590-bcb1-ad9187316d87">

PS2, looks like placeholder for secret in Raycast is 28 chars but if you copy secret from Notion it's 50 chars. Not sure if relevant here.

**Comment by thomaslombart** [comment]
So, I took a deeper look at that and the issue is… you manually have to give permissions to every page as it's explained [here](https://developers.notion.com/docs/authorization).

![CleanShot 2024-02-26 at 15 46 54@2x](https://github.com/raycast/extensions/assets/16003285/4c94abd0-caf3-47d5-b92a-ca0586f34ec7)

Here's how you do it [from another page](https://www.notion.so/help/add-and-manage-connections-with-the-api#add-connections-to-pages).

![CleanShot 2024-02-26 at 15 52 00@2x](https://github.com/raycast/extensions/assets/16003285/513fe2b0-4ed4-4abd-80d7-a343ea1bf65f)

It is quite annoying, but if you want to use the secret token, that seems to be the only way. Since granting access to a page provides access to all its children, a workaround could be to place all your pages under a "master" page and connect the latter.

I'll update the extension's docs to clarify this.
