### ISSUE TITLE
[raindrop] search became case sensitive and does not search in tags

### ISSUE THREAD

**Issue by tmnd1991** [raycast/extensions#9829]
### Description

Since a week or so, I'm not getting proper results out of raindrop. I guess something has changed with case-sensitivity and ability to search by tag too

**Comment by japanese-goblinn** [comment]
Based on what you described, it seems that this is not an extension problem. Just a few days ago, I received this message in my inbox.
<img width="552" alt="image" src="https://github.com/raycast/extensions/assets/33631005/38755e49-6e6c-464d-91d1-705ef1472010">

**Comment by mathieudutour** [comment]
Seems like this issue is about a specific extension, not the API. Would you mind opening a new issue using the [correct template](https://github.com/raycast/extensions/issues/new?assignees=&labels=extension%2Cbug&projects=&template=extension_bug_report.yml&title=%5BExtension+Name%5D+...) so that the authors of the extension are properly aware of it?
