### ISSUE TITLE
[Spotify Player] volume behavior on other devices

### ISSUE THREAD

**Issue by Laaarge** [raycast/extensions#9896]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

Volume edits do not work on another (android) device.
This may be a limitation of the API / android app (haven't tested on 2 MacOs devices) ?
When changing volume (with any command) 

### Steps To Reproduce

1. play music from another device (android 11 in my case)
2. use raycast to change the volume

### Current Behaviour

you get the "No active device" message when trying to change the volume on another device, and it doesn't do anything on the target device

### Expected Behaviour

changing volume on the target device

**Comment by peduarte** [comment]
This is expected, because the Spotify mobile apps (both on Android and iOS) dont have playback volume, they only rely on the device's volume, and that cannot be controlled by the Spotify API, because it's at the system level. 

The Volume commands only work for devices that support playback volume, like the Spotify App on desktop, web player, or with smart speakers. 

We could however improve the UX here by either renaming the command name to "Set Playback Volume to *" or by providing a more helpful error message

![(ಠ ›ಠ) — @peduarte — nrIn42mR004103@2x](https://github.com/raycast/extensions/assets/372831/8d12afd4-0407-4817-bcc0-b5a68123171e)

**Comment by zebapy** [comment]
@peduarte was the 'set playback volume' command removed entirely?
