### ISSUE TITLE
Forge: Shortcut to access sites without server layer

### ISSUE THREAD

**Issue by Gitsack** [raycast/extensions#991]
# Extension – [Laravel Forge](https://github.com/raycast/extensions/tree/main/extensions/laravel-forge)
Author: @KevinBatdorf

Currently, the way to access sites via the Laravel Forge extension is to select the server on which the site is hosted to be able to apply actions on the respective site. While this is very useful for browsing and managing servers, a way to access sites directly would be very helpful in some scenarios.

This would be a function similar to the filter of the "Sites" nav entry on [Forge](htps://forge.laravel.com)

![CleanShot 2022-02-25 at 12 40 48](https://user-images.githubusercontent.com/22915882/155709411-25fbc9c5-700d-49aa-a994-684f68645f76.png)

Specifically, this would be useful for:

1. Accessing the site information on Laravel Forge in the browser by being able to quickly call the respective link from raycast
2. More quickly managing sites using the provided site actions, avoiding the extra layer of servers in between.

Therefore, it would be most beneficial to have the option to search for servers and sites with separate calls (which could be configured to certain aliases fitting to user needs).

I'm interested in hearing your opinion about this @KevinBatdorf or if this would be useful to others, as well.

Btw: Thanks for the great extension! :)

**Comment by Gitsack** [comment]
Hey, yeah I can imagine 😁  - no worries!

Yes, what I would imagine is a direct way to search for sites, separate from the way that is now already integrated where you can search for servers.

So I guess it would be really useful to have a separate command like `forge site` or something similar where you can query the list of sites directly and act on these results.

**Comment by KevinBatdorf** [comment]
I'll look at it this week. I think even just adding the site data to the existing search would be useful. I'll take a look at what the API sends back for sites.

**Comment by KevinBatdorf** [comment]
I have a PR on the repo I use to develop this extension. It essentially adds the sites as keywords to the server list so you can search the site names, then press to get to the server. It doesn't bypass the server though because I think having the relationship of server -> site there is meaningful. 

I still think it's a much better experience this way. If you want to try it out here's the PR (no worries though!). I'll use it myself for the next few days and open a PR after.

https://github.com/KevinBatdorf/laravel-forge-raycast/pull/10
