### ISSUE TITLE
[Todoist] Change colour of menu bar icon

### ISSUE THREAD

**Issue by jaklan** [raycast/extensions#9925]
### Extension

https://www.raycast.com/doist/todoist

### Description

In the dark mode, most applications use #E6E6E6 / #E5E5E5 for their icons in the menu bar instead of pure #FFFFFF - I'm not a specialist here, but it looks like ~90% opacity which leads to such effect. As Todoist icon is a big white square, its pretty distracting - and that's the only reason I had to disable it.

<img width="521" alt="image" src="https://github.com/raycast/extensions/assets/24907857/34cd4710-1c3f-4600-9dfa-ad0744507714">

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the [Slack community](http://raycastcommunity.slack.com/) if you need further help.

Note that opening up a PR and having it merged will earn you some credits as we want to reward contributions. You’ll then be able to exchange them in a swag store that we’ll launch soon!

**Comment by Princeyadav05** [comment]
@thomaslombart Hi, I would love to give it a try. :)

**Comment by Princeyadav05** [comment]
@thomaslombart I was able to find the menu bar command and the icon used for light and dark mode.

<img width="596" alt="image" src="https://github.com/raycast/extensions/assets/22894003/ec1996b1-96f8-475b-a794-13e0f830f03c">

Should I just create a new icon from the raycast icon maker and replace the dark icon? Or is there any other way like using react/code to do so?

**Comment by thomaslombart** [comment]
No need to use the icon maker. You can just tweak the icon's color using the `tintColor` property: https://developers.raycast.com/api-reference/user-interface/icons-and-images#image.imagelike.

**Comment by Princeyadav05** [comment]
> No need to use the icon maker. You can just tweak the icon's color using the `tintColor` property: https://developers.raycast.com/api-reference/user-interface/icons-and-images#image.imagelike.

Sure. Will do this tonight. Thanks for the help.

**Comment by Princeyadav05** [comment]
@thomaslombart has raised a PR fixing the issue. Have a look at it.
