### ISSUE TITLE
[Jira] Filter search seems to be searching individual letters in order rather than words

### ISSUE THREAD

**Issue by Ziggoto** [raycast/extensions#9987]
### Extension

https://www.raycast.com/raycast/jira

### Description

I was searching for a user called Caio, and one of the results had nothing to do with him. 

And then I realised the Jira card had the word "creation". "Creation" has all the letters of the word "Caio" in the same order.

**C**re**a**t**io**n. (Bold parts: C, a, io)

I think the search would be more powerful if it was searching for words rather than individual letters.

Another example:

Fabio (my name) matches with the sentence "Create metrics **f**or tr**a**cking the success rate of **b**us**i**ness fl**o**ws"

### Steps To Reproduce

1. Having a Jira story with the word "creation"
2. Search for "Caio"

### Current Behaviour

"Caio" does match with "creation"

### Expected Behaviour

"Caio" shouldn't match with "creation"

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the [Slack community](http://raycastcommunity.slack.com/) if you need further help.

Note that opening up a PR and having it merged will earn you some credits as we want to reward contributions. You’ll then be able to exchange them in a swag store that we’ll launch soon!
